### PR TITLE
Fix JS Ptr factory namespace regression

### PR DESCRIPTION
**Pull request by Shubh3155**
This PR fixes a regression in the JS bindings generator where factory methods
returning Ptr<T> were not correctly namespace-qualified.

The fix restores unconditional namespace qualification when '::' is missing
and ensures the type substitution loop always runs.

Verified locally with:
make gen_opencv_js_source

### CODE REVIEW

**Comment by vrabaud** [comment]
It's actually that one you need to fix: https://github.com/opencv/opencv/blob/dc52acc7d1310f5fbd2a0f60db06f767a4698bcf/modules/js/generator/embindgen.py#L721

I do not understand the copilot comment fully but it seems valid and works for me. @Shubh3155 , please use it if you think it is valid

**Comment by asmorkalov** [comment]
@vrabaud I just compared opencv+opencv_contrib before and after patch and do not see any changes in generated code. What is the failed case for the PR?

**Comment by vrabaud** [comment]
This PR fixes this: https://github.com/opencv/opencv/issues/28130 SYou should see a difference in that code

**Comment by asmorkalov** [comment]
Hm, ximgproc is disabled in my build as depends on imgcodecs. I try to hack the dependency and check again.

**Comment by Shubh3155** [comment]
@vrabaud ive updated the code with the copilot one. can you check that.

**Comment by asmorkalov** [comment]
PR to make imgcodecs dependency optional in ximgproc: https://github.com/opencv/opencv_contrib/pull/4054

**Comment by asmorkalov** [comment]
Looks like the patch does not solve the issue:
```
[100%] Building CXX object modules/js/CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o
cd /mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js && /usr/bin/ccache /mnt/Projects/Projects/emsdk/upstream/emscripten/em++ -D_USE_MATH_DEFINES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS @CMakeFiles/opencv_js.dir/includes_CXX.rsp -s SINGLE_FILE=1 -s USE_PTHREADS=0 -s EXPORTED_FUNCTIONS="['_malloc', '_free']"   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagnostics-show-option -Qunused-arguments -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG -std=c++11  -Wno-missing-prototypes -MD -MT modules/js/CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o -MF CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o.d -o CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o -c /mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js_bindings_generator/gen/bindings.cpp
em++: warning: linker setting ignored during compilation: 'SINGLE_FILE' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'EXPORTED_FUNCTIONS' [-Wunused-command-line-argument]
/mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js_bindings_generator/gen/bindings.cpp:5808:42: error: unknown type name 'EdgeDrawing'; did you mean 'cv::ximgproc::EdgeDrawing'?
 5808 |         .constructor(select_overload<Ptr<EdgeDrawing>()>(&cv::ximgproc::createEdgeDrawing))
      |                                          ^~~~~~~~~~~
      |                                          cv::ximgproc::EdgeDrawing
/mnt/Projects/Projects/opencv_contrib/modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp:21:20: note: 'cv::ximgproc::EdgeDrawing' declared here
   21 | class CV_EXPORTS_W EdgeDrawing : public Algorithm
      |                    ^
1 error generated.
```

**Comment by asmorkalov** [comment]
@Shubh3155 Friendly reminder. I'm working on 4.13.0 release that should happen this year. Please harry up to be there.

**Comment by Shubh3155** [comment]
@asmorkalov Thanks for the reminder.

I removed the '::' check and now always resolve Ptr<T> via self.classes
(with fallback to the enclosing class). Rebuilt gen_opencv_js_source
locally — please PTAL.

**Comment by asmorkalov** [comment]
The issue is still there.

```
[100%] Building CXX object modules/js/CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o
cd /mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js && /usr/bin/ccache /mnt/Projects/Projects/emsdk/upstream/emscripten/em++ -D_USE_MATH_DEFINES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS @CMakeFiles/opencv_js.dir/includes_CXX.rsp -s SINGLE_FILE=1 -s USE_PTHREADS=0 -s EXPORTED_FUNCTIONS="['_malloc', '_free']"   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagnostics-show-option -Qunused-arguments -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG -std=c++11  -Wno-missing-prototypes -MD -MT modules/js/CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o -MF CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o.d -o CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o -c /mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js_bindings_generator/gen/bindings.cpp
em++: warning: linker setting ignored during compilation: 'SINGLE_FILE' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'EXPORTED_FUNCTIONS' [-Wunused-command-line-argument]
/mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js_bindings_generator/gen/bindings.cpp:5808:42: error: unknown type name 'EdgeDrawing'; did you mean 'cv::ximgproc::EdgeDrawing'?
 5808 |         .constructor(select_overload<Ptr<EdgeDrawing>()>(&cv::ximgproc::createEdgeDrawing))
      |                                          ^~~~~~~~~~~
      |                                          cv::ximgproc::EdgeDrawing
/mnt/Projects/Projects/opencv_contrib/modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp:21:20: note: 'cv::ximgproc::EdgeDrawing' declared here
   21 | class CV_EXPORTS_W EdgeDrawing : public Algorithm
      |                    ^
1 error generated.
make[3]: *** [modules/js/CMakeFiles/opencv_js.dir/build.make:77: modules/js/CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o] Error 1
make[3]: Leaving directory '/mnt/Projects/Projects/opencv_contrib-build-js-patch/js'
make[2]: *** [CMakeFiles/Makefile2:4062: modules/js/CMakeFiles/opencv_js.dir/all] Error 2
make[2]: Leaving directory '/mnt/Projects/Projects/opencv_contrib-build-js-patch/js'
make[1]: *** [CMakeFiles/Makefile2:4095: modules/js/CMakeFiles/opencv.js.dir/rule] Error 2
make[1]: Leaving directory '/mnt/Projects/Projects/opencv_contrib-build-js-patch/js'
make: *** [Makefile:797: opencv.js] Error 2
Traceback (most recent call last):
  File "/mnt/Projects/Projects/opencv_contrib-build-js-patch/../opencv/platforms/js/build_js.py", line 312, in <module>
    builder.build_opencvjs()
  File "/mnt/Projects/Projects/opencv_contrib-build-js-patch/../opencv/platforms/js/build_js.py", line 213, in build_opencvjs
    execute(["make", "-j", str(multiprocessing.cpu_count()), "opencv.js"])
  File "/mnt/Projects/Projects/opencv_contrib-build-js-patch/../opencv/platforms/js/build_js.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
Fail: Child returned: 2
emcmake: error: 'python3 ../opencv/platforms/js/build_js.py js --build_test --extra_modules /mnt/Projects/Projects/opencv_contrib/modules/ -DCMAKE_TOOLCHAIN_FILE=/mnt/Projects/Projects/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/mnt/Projects/Projects/emsdk/node/20.18.0_64bit/bin/node' failed (returned 1)
```

**Comment by Shubh3155** [comment]
@asmorkalov can you check again pls ive done some changes and if it still dont resolve can you help me out if possible? thx.

**Comment by asmorkalov** [comment]
Still the same issue.

**Comment by Shubh3155** [comment]
@asmorkalov 
Screenshot 2025-12-19 at 8 16 45 PM
ive made some changes again and in my terminal its not showing Ptr<EdgeDrawing now and getting cv::ximgproc::EdgeDrawing so can you check it too. thx,

**Comment by asmorkalov** [comment]
cv::ximgproc::EdgeDrawing is part of contrib module. I made a patch there to unblock it for JS bindings: https://github.com/opencv/opencv_contrib/pull/4054

**Comment by Shubh3155** [comment]
Thanks for clarifying!
I understand this part depends on opencv_contrib and your PR there.
My local generator output no longer produces Ptr<EdgeDrawing> unqualified.
Happy to adjust anything further if needed.

**Comment by Shubh3155** [comment]
@asmorkalov Windows CI failure seems unrelated to the JS ptr namespace change.
Linux/macOS pass cleanly.
Looks like a Windows workflow / infra issue (checkout/action resolution).
Please let me know if you want me to adjust anything on my side.

**Comment by asmorkalov** [comment]
The original issue is still there.

**Comment by asmorkalov** [comment]
```
[100%] Building CXX object modules/js/CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o
cd /mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js && /usr/bin/ccache /mnt/Projects/Projects/emsdk/upstream/emscripten/em++ -D_USE_MATH_DEFINES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS @CMakeFiles/opencv_js.dir/includes_CXX.rsp -s SINGLE_FILE=1 -s USE_PTHREADS=0 -s EXPORTED_FUNCTIONS="['_malloc', '_free']"   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagnostics-show-option -Qunused-arguments -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG -std=c++11  -Wno-missing-prototypes -MD -MT modules/js/CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o -MF CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o.d -o CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o -c /mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js_bindings_generator/gen/bindings.cpp
em++: warning: linker setting ignored during compilation: 'SINGLE_FILE' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'EXPORTED_FUNCTIONS' [-Wunused-command-line-argument]
/mnt/Projects/Projects/opencv_contrib-build-js-patch/js/modules/js_bindings_generator/gen/bindings.cpp:5808:42: error: unknown type name 'EdgeDrawing'; did you mean 'cv::ximgproc::EdgeDrawing'?
 5808 |         .constructor(select_overload<Ptr<EdgeDrawing>()>(&cv::ximgproc::createEdgeDrawing))
      |                                          ^~~~~~~~~~~
      |                                          cv::ximgproc::EdgeDrawing
/mnt/Projects/Projects/opencv_contrib/modules/ximgproc/include/opencv2/ximgproc/edge_drawing.hpp:21:20: note: 'cv::ximgproc::EdgeDrawing' declared here
   21 | class CV_EXPORTS_W EdgeDrawing : public Algorithm
      |                    ^
1 error generated.
make[3]: *** [modules/js/CMakeFiles/opencv_js.dir/build.make:77: modules/js/CMakeFiles/opencv_js.dir/__/js_bindings_generator/gen/bindings.cpp.o] Error 1
make[3]: Leaving directory '/mnt/Projects/Projects/opencv_contrib-build-js-patch/js'
make[2]: *** [CMakeFiles/Makefile2:4062: modules/js/CMakeFiles/opencv_js.dir/all] Error 2
make[2]: Leaving directory '/mnt/Projects/Projects/opencv_contrib-build-js-patch/js'
make[1]: *** [CMakeFiles/Makefile2:4095: modules/js/CMakeFiles/opencv.js.dir/rule] Error 2
make[1]: Leaving directory '/mnt/Projects/Projects/opencv_contrib-build-js-patch/js'
make: *** [Makefile:797: opencv.js] Error 2
Traceback (most recent call last):
  File "/mnt/Projects/Projects/opencv_contrib-build-js-patch/../opencv/platforms/js/build_js.py", line 312, in <module>
    builder.build_opencvjs()
  File "/mnt/Projects/Projects/opencv_contrib-build-js-patch/../opencv/platforms/js/build_js.py", line 213, in build_opencvjs
    execute(["make", "-j", str(multiprocessing.cpu_count()), "opencv.js"])
  File "/mnt/Projects/Projects/opencv_contrib-build-js-patch/../opencv/platforms/js/build_js.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
Fail: Child returned: 2
emcmake: error: 'python3 ../opencv/platforms/js/build_js.py js --build_test --extra_modules /mnt/Projects/Projects/opencv_contrib/modules/ -DCMAKE_TOOLCHAIN_FILE=/mnt/Projects/Projects/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/mnt/Projects/Projects/emsdk/node/20.18.0_64bit/bin/node' failed (returned 1)
```

**Comment by Shubh3155** [comment]
@alankarkotwal The failing job is a Windows self-hosted runner infrastructure error
("lost communication with the server").

All Linux, macOS, Android, iOS, and JS-related builds pass.
This failure appears unrelated to the JS Ptr namespace change.

I suggest re-running the Windows job.
Happy to adjust if you see a code-level issue.

**Comment by vrabaud** [comment]
@asmorkalov , did you really mean to close this PR ?

**Comment by asmorkalov** [comment]
It does not solve the issue. I've tried several iterations and gave up. See build issue above.
