### ISSUE TITLE
Problem with quantized models in cv2.dnn.readNetFromTensorflow

### ISSUE THREAD

**Issue by bileki** [opencv/opencv#14472]
##### System information (version)
- OpenCV => 4.0 / 3.4
- Operating System / Platform => Ubuntu 16.04 / Raspbian
- Tensorflow 1.13 

##### Detailed description

I'm trying to run a FasterRCNN_Resnet101 model on a Raspberry Pi 3. I have a trained model for detecting bottles and it works fine on my PC with GPU running Ubuntu 16.04.

Directly through the tensorflow I can not load my model because there is a lack of memory, so I tested with `cv2.dnn.readNetFromTensorflow` and worked perfectly for frozen_inference_graph.pb, with the graph.pbtxt file generated with tf_text_graph_faster_rcnn.py, taking 140s per image.

However, when trying to generate the graph.pbtxt of the quantized model, in order to verify if the inference would be faster than with the original model, I did not succeed, generating the error 

> File "tf_text_graph_faster_rcnn.py", line 91, in createFasterRCNNGraph assert(graph_def.node[0].op == 'Placeholder') AssertionError

Imagining that the problem was specific to my model, I looked for some example that was quantized and with the correct files (frozen_inference_graph.pb and graph.pbtxt) and found these files in [Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)

Testing the `cv2.dnn.readNetFromTensorflow('tflite_graph.pb', 'tflite_graph.pbtxt')` for all quantized examples, I noticed the same error: 

> cv2.error: OpenCV(4.0.0) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:616: error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'addConstNodes'

Which leads me to believe that there is some problem in reading graphs quantized/optimized by bazel.

I wonder if this is a bug or feature in development.

##### Steps to reproduce

-Download any quantized model from [Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), like:

- ssd_mobilenet_v1_quantized_coco
- ssd_mobilenet_v1_0.75_depth_quantized_coco
- ssd_mobilenet_v2_quantized_coco

-Run:

`model = cv2.dnn.readNetFromTensorflow('tflite_graph.pb', 'tflite_graph.pbtxt')`

-Get the error:

> cv2.error: OpenCV(4.0.0) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:616: error: (-215:Assertion failed) const_layers.insert(std::make_pair(name, li)).second in function 'addConstNodes'

**Comment by dkurt** [comment]
@bileki, Thanks! Currently OpenCV doesn't support quantized networks execution (already mentioned in https://github.com/opencv/opencv/issues/14360). There are different approaches to improve efficiency: Use specific hardware (Movidius Sticks) or try to compile DLDT (the same acceleration library which is used for NCSs) for AARCH64 with OpenCV (see https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend). Please note that the second way is not tested but there are experiments: https://github.com/opencv/dldt/pull/87. In this way you'll need to switch from Raspbian which is 32bit to some 64bit OS: [Debian for Raspberry Pi](https://wiki.debian.org/RaspberryPi3) or [Yocto](http://git.yoctoproject.org/cgit/cgit.cgi/meta-raspberrypi/about/).

**Comment by bileki** [comment]
@dkurt Thank you for the answer! I will close this issue.

**Comment by mohaghighat** [comment]
@dkurt : I see this issue was about 3 years ago. I wonder if OpenCV supports quantized networks execution now?
