### PR TITLE
videoio: fix C4576 build error with older ffmpeg versions

### LINKED ISSUE #28875: OpenCV 4.13.0 fails to build with FFMPEG version 4.4.4
### System Information

c++ OpenCV version: 4.13.0 Operating System / Platform: Windows 11 Compiler & compiler version: Ninja-MSVC 19.44.35219

### Detailed description

Build of OpenCV fails with the below error code when ffmpeg/4.4.4 is already built on this system.

Build works fine with later versions on FFMPEG (e.g. ffmpeg/7.1.3). Likely just need to update the required minimum version of ffmpeg in conancenter to one that is C++17 compatible.

```cap_ffmpeg_impl.hpp (534) error C4576: a parenthesized type followed by an initializer list is a non-standard explicity type conversion syntax```

### Steps to reproduce

Example conanfile. Note that ffmpeg/4.4.4 was previously built on this computer for OpenCV 4.10
```
from conan import ConanFile
from conan.tools.cmake import cmake_layout
from conan.tools.cmake import CMakeDeps
from conan.tools.cmake import CMakeToolchain

class TestProgram(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    name = "TestProgram"
    version = "4.41"

    def requirements(self):
        self.requires("opencv/4.13.0")
        # self.requires("ffmpeg/7.1.3") # required to build opencv as opencv's requirements aren't strict enough
        generators = "CMakeDeps", "CMakeToolchain"

    def build_requirements(self):
        pass

    def layout(self):
        cmake_layout(self)

    def generate(self):
        cmake = CMakeDeps(self)
        cmake.generate()
        toolchain = CMakeToolchain(self)
        toolchain.generate()

```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by Teddy-Yangjiale**
Fixes #28875

### Description
This PR fixes a build failure (`error C4576`) that occurs when building the `videoio` module with older FFmpeg versions (e.g., 4.4.4) using MSVC under strict C++17 mode.

**Root Cause:**
In older FFmpeg headers, the `AV_TIME_BASE_Q` macro is defined using a C99 compound literal `(AVRational){1, AV_TIME_BASE}`. This syntax is non-standard in C++ and is strictly rejected by MSVC when `/std:c++17` is enabled.

**Solution:**
Replaced the `AV_TIME_BASE_Q` macro with FFmpeg's standard `av_make_q(1, AV_TIME_BASE)` function. This resolves the C4576 compiler error and ensures modern C++ compatibility. 

*(Note: `av_make_q` is already smoothly polyfilled in `cap_ffmpeg_impl.hpp` for extremely old FFmpeg versions, making this a highly safe, consistent, and zero-overhead replacement.)*
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/videoio/src/cap_ffmpeg_impl.hpp [hunk 1]
```diff
@@ -526,15 +526,18 @@ inline static std::string _opencv_ffmpeg_get_error_string(int error_code)
 
 static inline int64_t to_avtb(int64_t ts, AVRational tb)
 {
-    return av_rescale_q(ts, tb, AV_TIME_BASE_Q);
```
Comment (asmorkalov) [inline modules/videoio/src/cap_ffmpeg_impl.hpp:529]: Please move the comment to the PR description. No need to store it in the code.

File: modules/videoio/src/cap_ffmpeg_impl.hpp [hunk 2]
```diff
@@ -526,15 +526,18 @@ inline static std::string _opencv_ffmpeg_get_error_string(int error_code)
...
+    // Replace AV_TIME_BASE_Q with av_make_q(1, AV_TIME_BASE) to fix 
+    // MSVC C4576 error caused by C99 compound literal in strict C++17 mode
+    return av_rescale_q(ts, tb, av_make_q(1, AV_TIME_BASE));
 }
 
 static inline int64_t from_avtb(int64_t ts_avtb, AVRational tb)
 {
-    return av_rescale_q(ts_avtb, AV_TIME_BASE_Q, tb);
```
Comment (asmorkalov) [inline modules/videoio/src/cap_ffmpeg_impl.hpp:534]: The same.

File: modules/videoio/src/cap_ffmpeg_impl.hpp (hunk 1 above)
Comment (Teddy-Yangjiale) [reply modules/videoio/src/cap_ffmpeg_impl.hpp:529]: "Done! The explanatory comments have been removed from the code as requested.

**Review by asmorkalov — APPROVED** [review]
