### ISSUE TITLE
OpenCV: Cannot infere model TopFormer: (-215:Assertion failed) poolingType == PSROI || src.size[1] == dst.size[1] in function 'cv::dnn::PoolingLayerImpl::PoolingInvoker::run'

### ISSUE THREAD

**Issue by ukoehler** [opencv/opencv#23142]
### System Information

OpenCV => Python opencv-python-rolling-4.7.0.68
Operating System / Platform Windows 10 64 bit
Python =>3.10.4

### Detailed description

I converted a TopFormer model from PaddleSeg to ONNX (https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/configs/topformer), but cannot infere images with it using OpenCV

### Steps to reproduce

```
input_size = [512, 512]
mean = [127, 127, 127]
input_scale = 1 / 127
model = cv2.dnn.readNet(model_path)
image_blob = cv2.dnn.blobFromImage(image, input_scale, input_size, mean, swapRB=False)
model.setInput(image_blob)
result = model.forward().squeeze()
```
error message:
```
Traceback (most recent call last):
  File "d:\Local\devel\Python\OpenCV\dnn_segmentation_paddle_topformer_ade\inference.py", line 161, in <module>
    label_image, color_image, prob_image, ind, duration = infereImage(image_path, model, duration)
  File "d:\Local\devel\Python\OpenCV\dnn_segmentation_paddle_topformer_ade\inference.py", line 64, in infereImage
    result = model.forward().squeeze()
cv2.error: OpenCV(4.7.0-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\pooling_layer.cpp:756: error: (-215:Assertion failed) poolingType == PSROI || src.size[1] == dst.size[1] in function 'cv::dnn::PoolingLayerImpl::PoolingInvoker::run'
```

Find the ONNX file here: https://drive.google.com/file/d/1OoW8rQgoN2isyM5YCWZ0irxhDMKmZorA/view?usp=sharing

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by ukoehler** [comment]
Surprisingly works with version opencv-python-rolling-4.8.0.20230624

Note to self: Local\devel\Python\OpenCV\dnn_segmentation_paddle_rtformer_ade\inference.py
