### ISSUE TITLE
brew install opencv3: error: '_mm_cvtph_ps' was not declared in this scope

### ISSUE THREAD

**Issue by timotheecour** [opencv/opencv#7985]
```
In file included from /tmp/opencv3-20170108-6620-1uhrnfh/modules/core/include/opencv2/core/hal/intrin.hpp:293:0,
                 from /tmp/opencv3-20170108-6620-1uhrnfh/modules/core/src/precomp.hpp:84,
                 from /tmp/opencv3-20170108-6620-1uhrnfh/modules/core/src/hal_internal.hpp:48,
                 from /tmp/opencv3-20170108-6620-1uhrnfh/modules/core/src/hal_internal.cpp:45:
/tmp/opencv3-20170108-6620-1uhrnfh/modules/core/include/opencv2/core/hal/intrin_sse.hpp: In function 'cv::v_float32x4 cv::v_cvt_f32(const cv::v_float16x4&)':
/tmp/opencv3-20170108-6620-1uhrnfh/modules/core/include/opencv2/core/hal/intrin_sse.hpp:1721:42: error: '_mm_cvtph_ps' was not declared in this scope
     return v_float32x4(_mm_cvtph_ps(a.val));
```

full logs: https://gist.github.com/d752621eff5844eee4cc47ff5e9147cf

It's a regression, it was working fine with opencv 3.1

Related issues:
https://github.com/Homebrew/homebrew-science/issues/4825
https://github.com/Homebrew/homebrew-science/issues/4788
http://answers.opencv.org/question/72675/opencv3-build-failing-with-linuxbrew/
escalating here for help

**Comment by alalek** [comment]
Confirmed by using of `-march=native` gcc option with `ENABLE_AVX=OFF` flag (which adds `-mno-avx` and other options which broke `-march=native` behavior).

**Comment by karandeepdps** [comment]
Which version of brew you are on.

Do

```
sudo chown -R $(whoami) /usr/local
brew update
```

 and try again.

**Comment by timotheecour** [comment]
I am using linuxbrew on linux. Homebrew works on osx. Its the latest
version (brew auto updates)

**Comment by timotheecour** [comment]
PS: the brew gistlogs mentioned above has all the context.

**Comment by victor1234** [comment]
I've added `#include <x86intrin.h>` to the top of `intrin_sse.hpp` but get error: 
```
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/immintrin.h:81:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/x86intrin.h:48,
                 from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin_sse.hpp:50,
                 from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:293,
                 from /home/victor/development/opencv/modules/core/src/precomp.hpp:84,
                 from /home/victor/development/opencv/modules/core/src/convert.cpp:44:
/usr/lib/gcc/x86_64-linux-gnu/6/include/f16cintrin.h: In function ‘cv::v_float32x4 cv::v_cvt_f32(const cv::v_float16x4&)’:
/usr/lib/gcc/x86_64-linux-gnu/6/include/f16cintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128 _mm_cvtph_ps(__m128
i)’: target specific option mismatch
 _mm_cvtph_ps (__m128i __A)
 ^~~~~~~~~~~~
In file included from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:293:0,
                 from /home/victor/development/opencv/modules/core/src/precomp.hpp:84,
                 from /home/victor/development/opencv/modules/core/src/convert.cpp:44:
/home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin_sse.hpp:1721:12: note: called from here
     return v_float32x4(_mm_cvtph_ps(a.val));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/immintrin.h:81:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/x86intrin.h:48,
                 from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin_sse.hpp:50,
                 from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:293,
                 from /home/victor/development/opencv/modules/core/src/precomp.hpp:84,
                 from /home/victor/development/opencv/modules/core/src/convert.cpp:44:
/usr/lib/gcc/x86_64-linux-gnu/6/include/f16cintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128 _mm_cvtph_ps(__m128i)’: target specific option mismatch
 _mm_cvtph_ps (__m128i __A)
 ^~~~~~~~~~~~
In file included from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:293:0,
                 from /home/victor/development/opencv/modules/core/src/precomp.hpp:84,
                 from /home/victor/development/opencv/modules/core/src/convert.cpp:44:
/home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin_sse.hpp:1721:12: note: called from here
     return v_float32x4(_mm_cvtph_ps(a.val));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/immintrin.h:81:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/x86intrin.h:48,
                 from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin_sse.hpp:50,
                 from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:293,
                 from /home/victor/development/opencv/modules/core/src/precomp.hpp:84,
                 from /home/victor/development/opencv/modules/core/src/convert.cpp:44:
/usr/lib/gcc/x86_64-linux-gnu/6/include/f16cintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128 _mm_cvtph_ps(__m128i)’: target specific option mismatch
 _mm_cvtph_ps (__m128i __A)
 ^~~~~~~~~~~~
In file included from /home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:293:0,
                 from /home/victor/development/opencv/modules/core/src/precomp.hpp:84,
                 from /home/victor/development/opencv/modules/core/src/convert.cpp:44:
/home/victor/development/opencv/modules/core/include/opencv2/core/hal/intrin_sse.hpp:1721:12: note: called from here
     return v_float32x4(_mm_cvtph_ps(a.val));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tomoaki0705** [comment]
Seems curious.
The gist log says [FP16 feature is available](https://gist.github.com/anonymous/d752621eff5844eee4cc47ff5e9147cf#file-01-cmake-L200)

```
-- FP16: Compiler support is available
```

When the cmake tries fp16 option, [it should have ```AVX``` enabled](https://github.com/opencv/opencv/blob/master/cmake/OpenCVCompilerOptions.cmake#L376)

```
elseif((X86 OR X86_64) AND NOT MSVC AND ENABLE_AVX)
```

so in your case, cmake [should show ](https://github.com/opencv/opencv/blob/master/cmake/OpenCVCompilerOptions.cmake#L388)

```
-- FP16: Feature disabled
```

so some how, on cmake stage, your compiler managed to use ```_mm_cvtph_ps``` instruction but not at compile stage. Hmmmm, curious.


just one more thing to say is that it seems [you have two versions of gcc installed on your computer.](https://gist.github.com/anonymous/d752621eff5844eee4cc47ff5e9147cf#file-00-config-out-L24-L26)
```
OS gcc: 5.4.0
Linuxbrew glibc: N/A
Linuxbrew gcc: 5.3.0
```

I hope this could be a clue, but otherwise, it's just curious......

**Comment by archenroot** [comment]
Facing same error, I am on Gentoo system and have multiple gcc installed on my system:
```
ares opencv # gcc-config -l
 [1] x86_64-pc-linux-gnu-4.8.5
 [2] x86_64-pc-linux-gnu-4.9.4
 [3] x86_64-pc-linux-gnu-5.4.0 *
 [4] x86_64-pc-linux-gnu-6.2.0
```

But that shouldn't be a problem, the switch is proven to work fine.

**Comment by iMichka** [comment]
I could reproduce the error too on ubuntu 16.10. Testing with the latest commit from the master branch works though. The `'_mm_cvtph_ps' was not declared in this scope` errors is fixed with latest master. Could it be possible to get a new release tag?

**Comment by alalek** [comment]
#7462 has better support for external CXXFLAGS .
