### ISSUE TITLE
mingw32-make failed

### ISSUE THREAD

**Issue by MiChongGET** [opencv/opencv#12444]
I had used the version of 3.4.2 or 3.4.3,when I used the windows powershell and mingw32-make would error,please see the picture,the libjpeg-turbo is error.

**Comment by alalek** [comment]
There is no official MinGW support.
Feel free to prepare patch yourself and provide PR. It would be accepted if it doesn't break other configurations.

You can switch back from libjpeg-turbo to legacy libjpeg via CMake `BUILD_JPEG_TURBO_DISABLE=1` option.

BTW,
Don't make screenshots with text information.
It blocks searching for similar reports.

**Comment by MiChongGET** [comment]
Thank you!

**Comment by pi-null-mezon** [comment]
@MiChongGET, actually it is possible to compile opencv 3.4.3 by mingw32 (i have used 5.3.2 for the instance). Follow this [guide](http://pavelk.ru/kompilyaciya-opencv-2-4-6-v-windows-dlya-qt-5-1). It is little bit old but works even for opencv 3.4.3

**Comment by MiChongGET** [comment]
@pi-null-mezon Your means is that the version of mingw32 is not right or I need use other tools?

**Comment by pi-null-mezon** [comment]
@MiChongGET I meant that Opencv 3.4.3 can be build on Windows7 by mingw32-make v4.1 (with g++ v5.3.0)

**Comment by MiChongGET** [comment]
@pi-null-mezon May be I use the windows10.

**Comment by pi-null-mezon** [comment]
In Windows 10 Opencv 3.4.3 successfully builds by mingw too

**Comment by MiChongGET** [comment]
@pi-null-mezon Ok, I try again

**Comment by MiChongGET** [comment]
@pi-null-mezon 
So detailed! Amazing,Thank you very much! More recently I begin to student Opencv ,so much things I don't know, nowday I use Vscode to code by C++ that because of the VS is so big. But the enviroment of opencv makes me cry ,it bothers me several days. I hope to figure out as quickly as possible. (All in all, still Python is so esay ,not as hardly as it)

**Comment by MiChongGET** [comment]
@pi-null-mezon Wrong again!
error :
D:\Ai\OPENCV\opencv3.4.3\sources\3rdparty\libjpeg-turbo\src\jmemmgr.c: In function 'realize_virt_arrays':
D:\Ai\OPENCV\opencv3.4.3\sources\3rdparty\libjpeg-turbo\src\jmemmgr.c:662:11: error: 'SIZE_MAX' undeclared (first use in this function)
       if (SIZE_MAX - maximum_space < new_space)
           ^~~~~~~~
D:\Ai\OPENCV\opencv3.4.3\sources\3rdparty\libjpeg-turbo\src\jmemmgr.c:662:11: note: each undeclared identifier is reported only once for each function it appears in
3rdparty\libjpeg-turbo\CMakeFiles\libjpeg-turbo.dir\build.make:1162: recipe for target '3rdparty/libjpeg-turbo/CMakeFiles/libjpeg-turbo.dir/src/jmemmgr.c.obj' failed
mingw32-make[2]: *** [3rdparty/libjpeg-turbo/CMakeFiles/libjpeg-turbo.dir/src/jmemmgr.c.obj] Error 1
CMakeFiles\Makefile2:380: recipe for target '3rdparty/libjpeg-turbo/CMakeFiles/libjpeg-turbo.dir/all' failed
mingw32-make[1]: *** [3rdparty/libjpeg-turbo/CMakeFiles/libjpeg-turbo.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....

**Comment by vivkv** [comment]
@MiChongGET  I am getting the same error while building OpenCV,  I am on Windows 10 (64 bit) with gcc (tdm-1) 5.1.0. What did you do to make this error go away, can you please tell me ?

**Comment by MiChongGET** [comment]
@vivkv I use the version of mingw is 5.3.0,try use it!

**Comment by Ranarox** [comment]
If someone else stumbled over this thread and still cant fix it, try to uncomment these three lines in the source code of the `jmemmrg.c` file and just include`stdint.h`. Worked for me with 
opencv v.3.4.3
mingw32 v.6.3
cmake v.3.14.1

```
// #ifndef _WIN32
#include <stdint.h>
//#endif
//#include <limits.h>
```
