### PR TITLE
remove Eclipse relicts in Android sample

### PR DESCRIPTION
**Pull request by hannesa2**
It removes more Eclipse relicts used by previous Android samples. With recent Gradle sample they are pointless

### CODE REVIEW

**Comment by alalek** [comment]
> samples/java/eclipse/HelloCV

This is not Android stuff.
Eclipse IDE is not dead.

---

> android_test

Android tests are not ported on Gradle yet.

---

BTW, Nightly Android pack builds are broken (since Jan 4, perhaps by #16222): http://pullrequest.opencv.org/buildbot/builders/master_pack-android

**Comment by hannesa2** [comment]
> samples/java/eclipse/HelloCV

> android_test

@alalek you are right, I reverted these files 👍 

> BTW, Nightly Android pack builds are broken (since Jan 4, perhaps by #16222): http://pullrequest.opencv.org/buildbot/builders/master_pack-android

I did a look, but unfortunately I don't understand the issue

```
Constructing Javadoc information...
/build/master_pack-android/build/OpenCV-android-sdk/sdk/java/src/org/opencv/android/CameraGLSurfaceView.java:3: error: cannot find symbol
import org.opencv.R;
                 ^
  symbol:   class R
  location: package org.opencv
/build/master_pack-android/build/OpenCV-android-sdk/sdk/java/src/org/opencv/android/CameraBridgeViewBase.java:5: error: cannot find symbol
import org.opencv.BuildConfig;
                 ^
  symbol:   class BuildConfig
  location: package org.opencv
/build/master_pack-android/build/OpenCV-android-sdk/sdk/java/src/org/opencv/android/CameraBridgeViewBase.java:6: error: cannot find symbol
import org.opencv.R;
                 ^
```

and this

```
Generating /build/master_pack-android/build/OpenCV-android-sdk/sdk/java/javadoc/org/opencv/android/OpenCVLoader.html...
error: cannot find symbol

  symbol:   variable BuildConfig
  location: class OpenCVLoader
```
Maybe you have a hint or know how to get rid of it ? My knowledge about Javadoc is just rudimentary

**Comment by asmorkalov** [comment]
".R" is Java class generated from resources. Eclipse did it on the go, when you edit resources. The step should be handled by Gradle in some point, but I cannot give you ready recipe for this.
