### ISSUE TITLE
Build error opencv with  --contrib opencv_contrib  for iOS with MacBook M1 Pro

### ISSUE THREAD

**Issue by doctor-xray** [opencv/opencv#22961]
### System Information

OpenCV version: 4.6.0
MacBook M1 Pro
Venture 13.1 
Xcode 14.1
Python 3.11.0

Command:
```
python opencv/platforms/ios/build_framework.py ios --contrib opencv_contrib --iphoneos_archs arm64 --iphonesimulator_archs x86_64
```

### Detailed description

Always Build error with different *Ext.swift files
```
---
note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'opencv2')
** BUILD FAILED **

The following build commands failed:
	SwiftCompile normal arm64 Compiling\ PhotoExt.swift,\ Structured_lightExt.swift /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/photo/PhotoExt.swift /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/structured_light/Structured_lightExt.swift (in target 'opencv2' from project 'opencv2')
	CompileSwift normal arm64 /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/photo/PhotoExt.swift (in target 'opencv2' from project 'opencv2')
	CompileSwift normal arm64 /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/structured_light/Structured_lightExt.swift (in target 'opencv2' from project 'opencv2')
(3 failures)
============================================================
ERROR: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=11.0', 'ARCHS=arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '10', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.
============================================================
```

### Steps to reproduce

again compiling error with other *Ext.swift files ?!

### Issue submission checklist

- [X] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by krrishdholakia** [comment]
Does your code run with the same command using a different version of OpenCV? - Clerkie (https://clerkie.co/)

**Comment by doctor-xray** [comment]
I tried it now with OpenCV – 4.5.5 some problem:
error with:
SwiftCompile normal arm64 Compiling\ Typealiases.swift,\ DnnExt.swift,\ FaceExt.swift

--
all *Ext.swift

**Comment by asmorkalov** [comment]
@doctor-xray could you try current 4.x branch and report status. The error log is not complete. There should be compiler error above in the console log.

**Comment by doctor-xray** [comment]
@asmorkalov I know is a compiling bug, but why and how to fix it? pull open CV 4.x today

.....
/opencv2.build/Release-iphoneos/Objects-normal/arm64/FloatVectorExt.o -index-unit-output-path /opencv2.build/Release-iphoneos/Objects-normal/arm64/IntVectorExt.o -index-unit-output-path /opencv2.build/Release-iphoneos/Objects-normal/arm64/MatExt.o
Command SwiftCompile failed with a nonzero exit code

/Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc/framework_build/opencv2.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.1.99. (in target 'ALL_BUILD' from project 'opencv2')
note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'opencv2')
** BUILD FAILED **


The following build commands failed:
	SwiftCompile normal arm64 Compiling\ TextExt.swift,\ VideoExt.swift /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/text/TextExt.swift /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/video/VideoExt.swift (in target 'opencv2' from project 'opencv2')
	CompileSwift normal arm64 /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/text/TextExt.swift (in target 'opencv2' from project 'opencv2')
	CompileSwift normal arm64 /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/video/VideoExt.swift (in target 'opencv2' from project 'opencv2')
	SwiftCompile normal arm64 Compiling\ FloatVectorExt.swift,\ IntVectorExt.swift,\ MatExt.swift /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/FloatVectorExt.swift /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/IntVectorExt.swift /Users/don/Projects/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/MatExt.swift (in target 'opencv2' from project 'opencv2')
(4 failures)
============================================================
ERROR: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=9.0', 'ARCHS=arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '10', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.
============================================================
Traceback (most recent call last):
  File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 181, in build
    self._build(outdir)
  File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 139, in _build
    self.buildOne(target[0], target[1], main_build_dir, cmake_flags)
  File "/Users/don/Projects/opencv/platforms/ios/build_framework.py", line 329, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir + "/modules/objc/framework_build")
  File "/Users/don/Projects/opencv/platforms/apple/cv_build_utils.py", line 13, in execute
    retcode = check_call(cmd, cwd = cwd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/don/.pyenv/versions/3.11.0/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=9.0', 'ARCHS=arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '10', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.

**Comment by doctor-xray** [comment]
Ok I found the problem: I dropped opencv_contrib dir in opencv dir and restart the build again with: python opencv/platforms/ios/build_framework.py ios --contrib opencv_contrib --iphoneos_archs arm64 --iphonesimulator_archs x86_64

**Comment by doctor-xray** [comment]
no the folder must be in the same folder with opencv.

The build without opencv_contrib works fine
But with opencv_contrib I got Build-error like:
note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'opencv2')
** BUILD FAILED **


The following build commands failed:
	SwiftCompile normal arm64 Compiling\ CoreExt.swift,\ CvTypeExt.swift,\ DoubleVectorExt.swift /Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/CoreExt.swift /Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/CvTypeExt.swift /Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/DoubleVectorExt.swift (in target 'opencv2' from project 'opencv2')
	CompileSwift normal arm64 /Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/CoreExt.swift (in target 'opencv2' from project 'opencv2')
	CompileSwift normal arm64 /Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/CvTypeExt.swift (in target 'opencv2' from project 'opencv2')
	CompileSwift normal arm64 /Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/modules/objc_bindings_generator/ios/gen/objc/core/DoubleVectorExt.swift (in target 'opencv2' from project 'opencv2')
(4 failures)

**Comment by doctor-xray** [comment]
same with: https://github.com/opencv/opencv/issues/22694

**Comment by doctor-xray** [comment]
[console-output.txt](https://github.com/opencv/opencv/files/10262499/console-output.txt)
Need help!

**Comment by alalek** [comment]
Help with searching?

```
/Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/opencv2.h:226:9: note: in file included from /Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/opencv2.h:226:
#import <opencv2/TEBLID.h>
        ^
/Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/TEBLID.h:21:5: error: redefinition of enumerator 'SIZE_256_BITS'
    SIZE_256_BITS = 102,
    ^
/Users/don/Projects/buildOpenCV-Modules/ios/build/build-arm64-iphoneos/lib/Release/opencv2.framework/Headers/BEBLID.h:22:5: note: previous definition is here
    SIZE_256_BITS = 101
    ^
```

Duplicate of https://github.com/opencv/opencv_contrib/issues/3302

**Comment by doctor-xray** [comment]
change Target to from 9.0 to 14.0 build with OpenCV: 3.4.18

**Comment by doctor-xray** [comment]
if I want to use the framework: 
terminating with uncaught exception of type cv::Exception: OpenCV(3.4.18) /Users/don/Projects/buildOpenCV-Modules/opencv_contrib/modules/xfeatures2d/src/surf.cpp:1029: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'

**Comment by doctor-xray** [comment]
I try to rebuild 3.4.18 with --dynamic as argument but than get an build error:

** BUILD FAILED **

============================================================
ERROR: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=14.0', 'ONLY_ACTIVE_ARCH=NO', 'BITCODE_GENERATION_MODE=bitcode', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '10', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.
============================================================
Traceback (most recent call last):
  File "/Users/don/Projects/buildOpenCV-Modules/opencv/platforms/ios/build_framework.py", line 120, in build
    self._build(outdir)
  File "/Users/don/Projects/buildOpenCV-Modules/opencv/platforms/ios/build_framework.py", line 112, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "/Users/don/Projects/buildOpenCV-Modules/opencv/platforms/ios/build_framework.py", line 213, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
  File "/Users/don/Projects/buildOpenCV-Modules/opencv/platforms/ios/build_framework.py", line 39, in execute
    retcode = check_call(cmd, cwd = cwd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/don/.pyenv/versions/3.11.0/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xcodebuild', 'IPHONEOS_DEPLOYMENT_TARGET=14.0', 'ONLY_ACTIVE_ARCH=NO', 'BITCODE_GENERATION_MODE=bitcode', '-arch', 'arm64', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '10', '-target', 'ALL_BUILD', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65.

**Comment by doctor-xray** [comment]
changed the default from --enable_nonfree to True. works now
