### PR TITLE
fix MSVC error: use name constexp for alignas array size in INT8 kernel

### PR DESCRIPTION
**Pull request by varun-jaiswal17**
### Problem
Windows CI fails with MSVC error C2131 in `conv2_int8_kernels.simd.hpp`:

    error C2131: expression did not evaluate to a constant
    failure was caused by a read of a variable outside its lifetime
    see usage of 'this'

Two array declarations inside `parallel_for_` lambdas used `constexpr`
variables defined inside the lambda body as array sizes:

    alignas(32) int8_t  wbuf[128 * K0];          // K0 defined inside lambda
    alignas(32) int32_t sumbuf[SPAT_BLOCK_SIZE * K0];  // both defined inside lambda

### Fix
Move the combined size constants to function scope (before the lambda),
where they are true compile-time constants with no `this` involvement:

    constexpr int WBUF_SIZE   = 128 * 8;  // 128 * K0
    constexpr int SUMBUF_SIZE = 8 * 8;    // SPAT_BLOCK_SIZE * K0

### Related
Fixes Windows CI failure introduced by #29126.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
Build warnings:
```
 /home/ci/opencv/modules/dnn/src/int8layers/conv2_int8_kernels.simd.hpp:1166:19: warning: unused variable 'WBUF_SIZE' [-Wunused-variable]

/home/ci/opencv/modules/dnn/src/int8layers/conv2_int8_kernels.simd.hpp:1588:19: warning: unused variable 'SUMBUF_SIZE' [-Wunused-variable]
```

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
Tested locally. Works well for me.
