### ISSUE TITLE
Yolox ONNX graph parsing error

### ISSUE THREAD

**Issue by Abdurrahheem** [opencv/opencv#24671]
### System Information

OpenCV version: 4.8.0
Operating System / Platform: Ubuntu 20.04
Compiler & compiler version: GCC 9.3.0

### Detailed description

Onnx graph parsing error on `ADD` node. Shape of inputs do not match

```
ror: (-2:Unspecified error) in function 'handleNode'
> Node [Add@ai.onnx]:(onnx_node!/head/Add) parse error: OpenCV(4.8.0-dev) opencv/modules/dnn/src/layers/nary_eltwise_layers.cpp:142: error: (-215:Assertion failed) shape[i] == 1 || outShape[i] == 1 in function 'findCommonShape'
```

Error was introduced in #24655 PR. 

### Steps to reproduce

Run yolox test: 

`./bin/opencv_test_dnn --gtest_filter="Test_ONNX_nets.YOLOX/1"  `

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by dkurt** [comment]
@Abdurrahheem, @fengyuentau, please review https://github.com/opencv/opencv/pull/24672

**Comment by fengyuentau** [comment]
Could you elaborate why this happen with https://github.com/opencv/opencv/pull/24655?

**Comment by dkurt** [comment]
> Could you elaborate why this happen with https://github.com/opencv/opencv/pull/24655?

`RemoveSliceAllOptionalInputsSubgraph>(5)` matched the following slice with 5 inputs (both axes and steps have default values, so the subgraph trimmed number of inputs up to 3 (data, starts, ends):
![image](https://github.com/opencv/opencv/assets/25801568/673b577e-05c8-4ba1-80e8-d99f8b123895)

![image](https://github.com/opencv/opencv/assets/25801568/fc8c1c81-a5a8-4e95-9cac-6020cd6cd725)

However, actual axis value is `[2]` while `parseSlice` if axis input missed puts 0 instead:
```
axis : 0
begin : 0, 0, 0
depth : 5
end : 2, 2147483647, 2147483647
has_dynamic_shapes : 0
```

**Comment by fengyuentau** [comment]
Thank you for digging into the problem. It looks more like a default value problem of `axes` in `parseSlice` to me. Could we change it to -1 and normalize in `finalize()` in the slice layer implementation? It requires more changes though but makes more sense in my perspective.

**Comment by dkurt** [comment]
@fengyuentau , am I understood you correctly that proposal is to add missed inputs filled with default values?

**Comment by fengyuentau** [comment]
Mostly correct. I mean adding missing inputs with default values filled in importer though. Then they can be normalized in finalize().

Ideally speaking we should do something like that. But given the fact that the Slice implementation is too complicated, I would say we just accept your proposal and move on with this for now to catch the new release deadline.

**Comment by dkurt** [comment]
@fengyuentau , got it. I wanted to do like this but adding default axes and steps may trigger a different branch in the Slice implementation. So performance analysis may be required. Let’s do it later.
