### ISSUE TITLE
OpenCV cannot import ONNX model: Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes'

### ISSUE THREAD

**Issue by ukoehler** [opencv/opencv#23288]
### System Information

OpenCV = Python opencv-python-rolling-4.7.0.20230211
Operating System / Platform Windows 10 64 bit
Python =3.10.4

### Detailed description

I converted the MODNet-MobileNetV2 model from PaddleSeg https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/Matting to ONNX. OpenCV cannot load the model (I do not get any errors or warnings from Netron). Find the offending model here: https://drive.google.com/file/d/1lOGcYYHSxfaa3fTbhuPHixa6bH3hUg3S/view?usp=sharing
```
[ERROR:0@0.123] global onnx_importer.cpp:1055 cv::dnn::dnn4_v20221220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Concat]:(onnx_node!p2o.Concat.12) from domain='ai.onnx'
Traceback (most recent call last):
  File "d:\Local\devel\Python\OpenCV\dnn_matting_modnet-mobilenetv2\inference.py", line 99, in <module>
    model = cv2.dnn.readNet(model_path)
cv2.error: OpenCV(4.7.0-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1074: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20221220::ONNXImporter::handleNode'
> Node [Concat@ai.onnx]:(onnx_node!p2o.Concat.12) parse error: OpenCV(4.7.0-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\concat_layer.cpp:109: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes'
```

### Steps to reproduce

Load model with the following code

``` Python
model = cv2.dnn.readNet(model_path)
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by fengyuentau** [comment]
It fails because of unsupported dynamic input shape (dynamic batch is Ok, but dynamic height or width is not). So use onnx-simplifier to set a fixed input shape, e.g. 1x3x640x640, and it works with dnn.

**Comment by ukoehler** [comment]
That workaround helps a bit. Since onnxsim works rather unexpected here the instructions for others running into this problem
pip install onnxsim onnxruntime

onnxsim input.onnx output.onnx --overwrite-input-shape 1,3,512,512

The simplified model takes a bit longer to infer!

**Comment by ukoehler** [comment]
Surprisingly now works with opencv-python-rolling-4.8.0.20230624

Note to self: Local\devel\Python\OpenCV\dnn_matting_modnet-mobilenetv2\inference.py

**Comment by stereomatchingkiss** [comment]
> Surprisingly now works with opencv-python-rolling-4.8.0.20230624
> 
> Note to self: Local\devel\Python\OpenCV\dnn_matting_modnet-mobilenetv2\inference.py

Do you mean python version work with dynamic input shape?Including width and height?
