### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_jpeg_default_qtables"

### ISSUE THREAD

**Issue by neilyoung** [opencv/opencv#18541]
##### System information (version)

- OpenCV => 3.4.11
- Operating System / Platform => macOS Catalina 10.15.7
- Compiler => 

##### Detailed description

I recently have updated my mac to 10.15.7. I also made a `brew update`.

I'm able to compile and run OpenCV 3.4.1 from source. At runtime it crashes in a function related to JPEG compression

```
C  [libopencv_imgcodecs.3.4.1.dylib+0x3fd7a]  jpeg_CreateCompress+0x2a
C  [libopencv_imgcodecs.3.4.1.dylib+0x1a5cb]  cv::JpegEncoder::write(cv::Mat const&, std::__1::vector<int, std::__1::allocator<int> > const&)+0xdb
C  [libopencv_imgcodecs.3.4.1.dylib+0x8dd0]   cv::imencode(cv::String const&, cv::_InputArray const&,  std::__1::vector<unsigned char, std::__1::allocator<unsigned  char> >&, std::__1::vector<int,  std::__1::allocator<int> > const&)+0x5d0
```

I was downloading 3.4.11 sources and tried the compilation. It fails, again somewhere in the near of JPEG:

```
[ 50%] Linking CXX shared library ../../lib/libopencv_imgcodecs.dylib
Undefined symbols for architecture x86_64:
  "_jpeg_default_qtables", referenced from:
      cv::JpegEncoder::write(cv::Mat const&, std::__1::vector<int, std::__1::allocator<int> > const&) in grfmt_jpeg.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libopencv_imgcodecs.3.4.11.dylib] Error 1
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make: *** [all] Error 2

```

I'm also no longer able to read JPEG files from disk with a simple C++ sample app (OpenCV 3.4.1)

Is there any chance to approach this issue? I suppose it is something in the environment, which is no longer compatible.

**Comment by neilyoung** [comment]
Found

set(JPEG_LIB_VERSION 62)

in libjpeg-turbo/CMakeList.txt

Set it to

set(JPEG_LIB_VERSION 70)

experimentally.

Now I'm over the link problem, since jpeg_default_qtables is compiled now. To be investigated..

```
[ 50%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/exif.cpp.o
[ 50%] Linking CXX shared library ../../lib/libopencv_imgcodecs.dylib
[ 50%] Built target opencv_imgcodecs
Scanning dependencies of target opencv_videoio
[ 50%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/videoio_registry.cpp.o
[ 50%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/videoio_c.cpp.o
[ 51%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap.cpp.o
[ 51%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_images.cpp.o
[ 51%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_mjpeg_encoder.cpp.o
[ 51%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_mjpeg_decoder.cpp.o
[
```

**Comment by neilyoung** [comment]
No, doesn't compile on macOS 10.15.7.

This time it had problems with some test cases...

```
[ 84%] Building CXX object modules/videoio/CMakeFiles/opencv_test_videoio.dir/test/test_fourcc.cpp.o
[ 84%] Building CXX object modules/videoio/CMakeFiles/opencv_test_videoio.dir/test/test_gstreamer.cpp.o
In file included from /Users/decades/Documents/dragonflyExternal/opencv-3.4.11/modules/videoio/test/test_gstreamer.cpp:5:
In file included from /Users/decades/Documents/dragonflyExternal/opencv-3.4.11/modules/videoio/test/test_precomp.hpp:7:
In file included from /Users/decades/Documents/dragonflyExternal/opencv-3.4.11/modules/ts/include/opencv2/ts.hpp:125:
/Users/decades/Documents/dragonflyExternal/opencv-3.4.11/modules/ts/include/opencv2/ts/ts_gtest.h:1392:53: error: array initializer must be an
      initializer list or string literal
      GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3) : f0_(f0), f1_(f1), f2_(f2),
                                                    ^
/Users/decades/Documents/dragonflyExternal/opencv-3.4.11/modules/ts/include/opencv2/ts/ts_gtest.h:1755:10: note: in instantiation of member function
 

```

Well, my make is pretty straight forward:

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make

```

What could go wrong?

**Comment by neilyoung** [comment]
Well, as long as it is `incomplete question (invalid tracker) labels 6 hours ago` then rest in peace together...

**Comment by liuzhihui2046** [comment]
Have you solved it? I ran into the same problem?

**Comment by neilyoung** [comment]
@liuzhihui2046 Yes, reported here https://github.com/microsoft/vcpkg/issues/13766#issuecomment-706013096

**Comment by liuzhihui2046** [comment]
@neilyoung  it works!!! thank you very much! it took me a whole day！！

**Comment by liuzhihui2046** [comment]
@neilyoung 
Although this was compiled and installed successfully, there was a problem when reading a ".jpg" image.the image data is empty. your image  can be read normally?

**Comment by neilyoung** [comment]
Yes I can. Did you `sudo make install` after build?

Here is my test code, and runs.


```
#include <opencv2/opencv.hpp>

using namespace std;

int main( int argc, char** argv )
{
    // Read image
    cv::Mat img = cv::imread("../res/paris.jpg", cv::IMREAD_COLOR);

    cout << "Input image size: " << img.size() << endl;
    cout << "Input image number of channels: " << img.channels() << endl;

    // Convert it to black and white (3-channel BGR to 1-channel grayscale)
    cv::Mat workingImg;
    cv::cvtColor(img, workingImg, cv::COLOR_BGR2GRAY);

    cout << "Channels after BGR2GRAY conversion: " << workingImg.channels() << endl;

    // Convert it back to 3-channel
    cv::cvtColor(workingImg, workingImg, cv::COLOR_GRAY2BGR);

    cout << "Channels after GRAY2BGR conversion: " << workingImg.channels() << endl;

    // Set JPEG parameters to convert the frame to a byte array later
    std::vector<int> vParams(2);
    vParams[0] = cv::IMWRITE_JPEG_QUALITY;
    vParams[1] = 70;

    // Convert this image to a JPEG byte array

    std::cout << "JPEG conversion..." << endl;

    std::vector<unsigned char> vBytes;
    cv::imencode(".jpg", workingImg, vBytes, vParams);

    // Display the size of the JPEG byte array
    std::cout << "JPEG size: " << vBytes.size() << " bytes" << endl;
}
```

```
./OpenCVTest 
Input image size: [1280 x 853]
Input image number of channels: 3
Channels after BGR2GRAY conversion: 1
Channels after GRAY2BGR conversion: 3
JPEG conversion...
JPEG size: 167690 bytes

```

**Comment by alalek** [comment]
> make install 

It is NOT necessary to run apps, especially with `sudo`.
(avoid using `make install` until you have robust process how to uninstall that)

**Comment by neilyoung** [comment]
??
I wrote this app test app and of course I don't run it as sudo. 

`sudo make install` is the last step of the OpenCV build after make in order to copy the dylibs to a common place...

**Comment by alalek** [comment]
There is conflict between 3rdparty libjpeg and external libjpeg (usually comes with VTK).
Try this workaround: `cmake -DWITH_VTK=OFF ...`

**Comment by alalek** [comment]
Some cases should be resolved by this commit: 387a76ba598fa1e177f8d79a2760ec75a4e9b0e1 (file `cmake/OpenCVFindLibsGrfmt.cmake` )
