### ISSUE TITLE
OpenCV fails to import ONNX model: Can't create layer "2090" of type "ReduceMin"

### ISSUE THREAD

**Issue by ukoehler** [opencv/opencv#22099]
##### System information (version)
- OpenCV => 4.5.5
- Operating System / Platform => Windows 10 64 bit
- Compiler => Python 3.10.4
- Installed packages:
> numpy                 1.22.3
>opencv-contrib-python 4.5.5.64
>pip                   22.0.4
>setuptools            58.1.0

##### Detailed description
When importing https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-12-int8.onnx into OpenCV the ONNXImporter fails.

I wrote a Python script in a different venv to check the model with onnx and infer with the model with onnxruntime. The model imports and executes fine. This is not a problem with the models, but with the importer.

Error message:
```
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
> Node [ReduceMin@ai.onnx]:(2090) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp:621: error: 
(-2:Unspecified error) Can't create layer "2090" of type "ReduceMin" in function 'cv::dnn::dnn4_v20211220::LayerData::getLayerInstance'  
>

##### Steps to reproduce
- Reproducible: yes
- Enforceable: yes

Import the model using
`model = cv2.dnn.readNetFromONNX(model_path)`

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
 - [x] I updated to the latest OpenCV version and the issue is still there
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by zihaomu** [comment]
Hi @ukoehler, We have supported `ReduceMin` at version 4.6.0. Please check the release [Log of 4.6.0](https://github.com/opencv/opencv/wiki/ChangeLog#version460).

BTW, currently, OpenCV does not support dynamic shape. And we are trying to find a solution.

**Comment by ukoehler** [comment]
Hi @zihaomu, man thanks for your help. I can confirm that I do get a different error message after upgrading to OpenCV 4.6:

cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Shape@ai.onnx]:(onnx_node!2030) parse error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:2846: error: (-215:Assertion failed) !isDynamicShape in function 'cv::dnn::dnn4_v20220524::ONNXImporter::parseShape'

The documentation hints that ONNX is the file format of choice for DNN and OpenCV. Naturally, one assumes that it can read models in that format.

Cheers

Uwe

**Comment by zihaomu** [comment]
Hi @ukoehler, Currently, OpenCV does not support dynamic shape. And [FasterRCNN-12.onnx](https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-12.onnx) does use the dynamic shape, that's why you get that Error info. I will try to fix this, and if there is progress here, I will let you know.

**Comment by ukoehler** [comment]
Hi @zihaomu , great. Is there a list of supported and un-supported features.  [fcn-resnet101-11.onnx](https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/fcn/mode/fcn-resnet101-11.onnx) also uses dynamic shape. [ssd-12.onnx](https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/ssd/model/ssd-12.onnx) cannot be loaded because onnx_node!NonMaxSuppression_683 is not supported. Should I create an issue for that?

**Comment by zihaomu** [comment]
This issue is enough @ukoehler. I will check the models' detail and update the latest progress on this issue.

**Comment by ajeshmonr7777** [comment]
@zihaomu While loading yolov7-nms-640.onnx file suing OpenCV I got an error message like this. 

OpenCV(4.6.0) Error: Unspecified error (> Node [NonMaxSuppression@ai.onnx]:(onnx_node!NonMaxSuppression_430) parse error: OpenCV(4.6.0) c:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\layer_internals.hpp:110: error: (-2:Unspecified error) Can't create layer "onnx_node!NonMaxSuppression_430" of type "NonMaxSuppression" in function 'cv::dnn::dnn4_v20220524::detail::LayerData::getLayerInstance'
> ) in cv::dnn::dnn4_v20220524::ONNXImporter::handleNode, file c:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp, line 1040 

Can you confirm whether OpenCV supports YOLOv7 or not ?

**Comment by zihaomu** [comment]
Hi, @ajeshmonr7777, OpenCV has not supported the NMS node of ONNX. 
A possible solution is to use OpenCV's own NMS implementation instead of the ONNX model with NMS.

**Comment by dragan07-07** [comment]
But how do we use it in OpenCvforUnity when there's that node in the model itself? I don't have the ability to get that layer out of the net. And I guess the network works faster precisely because it counts the NMS in the model itself. Is it possible to add a c++ code to the backend OPENCVFORUNITY that will accept the NMS layer?

**Comment by umanniyaz** [comment]
How to load ONNX yolov7 model ysing csv2.readNetONNX(model_path), it produces erro 'cv::dnn::dnn4_v20220524::ONNXImporter::ONNXImporter'

**Comment by zihaomu** [comment]
@umanniyaz Please attach more useful information about your model and your model file. That's important for checking the error.

**Comment by ukoehler** [comment]
I came across another Onnx model that fails to load with that error while running fine with onnxruntime:

https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/fcn
model FCN ResNet-101
`cv2.error: OpenCV(4.6.0-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1065: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'   
> Node [Shape@ai.onnx]:(onnx_node!Shape_0) parse error: OpenCV(4.6.0-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:2581: error: (-215:Assertion failed) !isDynamicShape in function 'cv::dnn::dnn4_v20220524::ONNXImporter::parseShape'
`

I am using the pre-release of OpenCV 4.6: opencv-python-rolling 4.6.0.20220924

**Comment by ukoehler** [comment]
Issue is still in opencv-python-rolling-4.6.0.20221112.

**Comment by PasaOpasen** [comment]
Issue is still in `4.7.0.68`

```
error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Shape@ai.onnx]:(onnx_node!Shape_35) parse error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:2630: error: (-215:Assertion failed) !isDynamicShape in function 'parseShape'
```

**Comment by srivatsacool** [comment]
@zihaomu ,Then atleast can you please tell us how to export the yolov7 model without NMS  .

> > But how do we use it in OpenCvforUnity when there's that node in the model itself? I don't have the ability to get that layer out of the net. And I guess the network works faster precisely because it counts the NMS in the model itself. Is it possible to add a c++ code to the backend OPENCVFORUNITY that will accept the NMS layer?
> 
> Hi @dragan07-07 , for now, OpenCV can not load the Yolov7_NMS version. You can try to find the Yolov7 without NMS, there is some [reference repo](https://github.com/hpc203/yolov7-opencv-onnxrun-cpp-py) which has loaded it successfully in OpenCV. And the model link is [this](https://pan.baidu.com/s/1FoC0n7qMz4Fz0RtDGpI6xQ), password: `7mhs`.

**Comment by srivatsacool** [comment]
How to load ONNX yolov7 model using csv2.readNetONNX(model_path), it produces erro 'cv::dnn::dnn4_v20220524::ONNXImporter::ONNXImporter'

OpenCv Version = 4.5.5
platform  = Python
model file  =  yolov7.pt (Got it from here !!-- https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt )

**Comment by ukoehler** [comment]
Still doesn't work in OpenCV 4.7.0-dev

**Comment by zihaomu** [comment]
Hi @ukoehler, solving this problem requires full dynamic shape support, which conflicts with the existing engine, and we will fix this problem in the new inference engine of `5.x`.

**Comment by ukoehler** [comment]
Thanks for letting me know!

**Comment by YadandlaKumar** [comment]
error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:270: error: (-5:Bad argument) Can't read ONNX file: D:\Egg Grading Project\CODest.onnx in function 'cv::dnn::dnn4_v20221220::ONNXImporter::ONNXImporter'

kindly give me solution

**Comment by ukoehler** [comment]
This is still an issue in for opencv-python-rolling 4.7.0.20230211 models:
fcn-resnet101-11.onnx

ssd-12.onnx produces a different error now (https://github.com/opencv/opencv/issues/23298)
FasterRCNN-12.onnx produces a different error now (https://github.com/opencv/opencv/issues/23297)

**Comment by ukoehler** [comment]
Possible workaround (at least infer does something for fcn-resnet101-11.onnx). @fengyuentau pointed me to the possibility to fix the input size of an image in an ONNX model using onnxsim (https://github.com/opencv/opencv/issues/23288)
```
pip install onnxsim onnxruntime

onnxsim input.onnx output.onnx --overwrite-input-shape 1,3,512,512
``` 
This at least allows to check if the model does roughly the right thing.

**Comment by wynshiter** [comment]
when can we see 5.x released?

**Comment by bingo787** [comment]
Unbelievable, is it impossible to use OpenCV DNN for inference?

**Comment by abhishek-gola** [comment]
@asmorkalov, In 5.x the issue is related to missing `RoiAlign` layer support which is added in the PR: https://github.com/opencv/opencv/pull/28453. It should be resolved once the mentioned PR is merged _[I have tested it with RoiAlign support added in PR #28453 and model parsing is successful with that]_.

Current error in 5.x:
```
'FasterRCNN-12.onnx' cannot be loaded with the new parser. Trying the older parser.  Unsupported operations:
        RoiAlign
'
