### PR TITLE
G-API: fix build with GCC 4.8

### LINKED ISSUE #16133: CMake error at /opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp
##### System information (version)

- OpenCV => :grey_question: 4.1.2
- Operating System / Platform => :grey_question: macOS 10.15
- Compiler => :grey_question: CMake

##### Detailed description

Build error when compiling gfluidbuffer.cpp

```
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp: In function 'std::unique_ptr<cv::gapi::fluid::BufferStorage> cv::gapi::fluid::{anonymous}::createStorage(int, int, int, int, cv::gapi::fluid::BorderOpt)':
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:350:16: error: cannot bind 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithBorder>' lvalue to 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithBorder>&&'
         return storage;
                ^
In file included from /usr/local/include/c++/4.9.4/memory:81:0,
                 from /opencv/modules/core/include/opencv2/core/cvstd_wrapper.hpp:11,
                 from /opencv/modules/core/include/opencv2/core/cvstd.hpp:81,
                 from /opencv/modules/core/include/opencv2/core/base.hpp:58,
                 from /opencv/modules/core/include/opencv2/core.hpp:54,
                 from /opencv/modules/gapi/src/precomp.hpp:12,
                 from /opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:8:
/usr/local/include/c++/4.9.4/bits/unique_ptr.h:220:2: note: initializing argument 1 of 'std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Up = cv::gapi::fluid::BufferStorageWithBorder; _Ep = std::default_delete<cv::gapi::fluid::BufferStorageWithBorder>; <template-parameter-2-3> = void; _Tp = cv::gapi::fluid::BufferStorage; _Dp = std::default_delete<cv::gapi::fluid::BufferStorage>]'
  unique_ptr(unique_ptr<_Up, _Ep>&& __u) noexcept
  ^
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:355:12: error: cannot bind 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithoutBorder>' lvalue to 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithoutBorder>&&'
     return storage;
            ^
In file included from /usr/local/include/c++/4.9.4/memory:81:0,
                 from /opencv/modules/core/include/opencv2/core/cvstd_wrapper.hpp:11,
                 from /opencv/modules/core/include/opencv2/core/cvstd.hpp:81,
                 from /opencv/modules/core/include/opencv2/core/base.hpp:58,
                 from /opencv/modules/core/include/opencv2/core.hpp:54,
                 from /opencv/modules/gapi/src/precomp.hpp:12,
                 from /opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:8:
/usr/local/include/c++/4.9.4/bits/unique_ptr.h:220:2: note: initializing argument 1 of 'std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Up = cv::gapi::fluid::BufferStorageWithoutBorder; _Ep = std::default_delete<cv::gapi::fluid::BufferStorageWithoutBorder>; <template-parameter-2-3> = void; _Tp = cv::gapi::fluid::BufferStorage; _Dp = std::default_delete<cv::gapi::fluid::BufferStorage>]'
  unique_ptr(unique_ptr<_Up, _Ep>&& __u) noexcept
  ^
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp: In function 'std::unique_ptr<cv::gapi::fluid::BufferStorage> cv::gapi::fluid::{anonymous}::createStorage(const cv::gapi::own::Mat&, cv::gapi::own::Rect)':
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:363:12: error: cannot bind 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithoutBorder>' lvalue to 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithoutBorder>&&'
     return storage;
            ^
In file included from /usr/local/include/c++/4.9.4/memory:81:0,
                 from /opencv/modules/core/include/opencv2/core/cvstd_wrapper.hpp:11,
                 from /opencv/modules/core/include/opencv2/core/cvstd.hpp:81,
                 from /opencv/modules/core/include/opencv2/core/base.hpp:58,
                 from /opencv/modules/core/include/opencv2/core.hpp:54,
                 from /opencv/modules/gapi/src/precomp.hpp:12,
                 from /opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:8:
/usr/local/include/c++/4.9.4/bits/unique_ptr.h:220:2: note: initializing argument 1 of 'std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Up = cv::gapi::fluid::BufferStorageWithoutBorder; _Ep = std::default_delete<cv::gapi::fluid::BufferStorageWithoutBorder>; <template-parameter-2-3> = void; _Tp = cv::gapi::fluid::BufferStorage; _Dp = std::default_delete<cv::gapi::fluid::BufferStorage>]'
  unique_ptr(unique_ptr<_Up, _Ep>&& __u) noexcept
  ^
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp: In function 'std::unique_ptr<cv::gapi::fluid::BufferStorage> cv::gapi::fluid::{anonymous}::createStorage(int, int, int, int, cv::gapi::fluid::BorderOpt)':
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:356:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp: In function 'std::unique_ptr<cv::gapi::fluid::BufferStorage> cv::gapi::fluid::{anonymous}::createStorage(const cv::gapi::own::Mat&, cv::gapi::own::Rect)':
/opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:364:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: some warnings being treated as errors
```

##### Steps to reproduce

    ```
    git clone git clone https://github.com/opencv/opencv.git
    cd opencv/
    mkdir build
    cd build
    cmake ..
    ```

### PR DESCRIPTION
**Pull request by alalek**
relates #16081
resolves #16133

Error message:

<cut/>

```
../opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp: In function 'std::unique_ptr<cv::gapi::fluid::BufferStorage> cv::gapi::fluid::{anonymous}::createStorage(int, int, int, int, cv::gapi::fluid::BorderOpt)':
../opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:350:16: error: cannot bind 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithBorder>' lvalue to 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithBorder>&&'
         return storage;
                ^
In file included from /usr/include/c++/4.8.2/memory:81:0,
                 from ../opencv/modules/core/include/opencv2/core/cvstd_wrapper.hpp:11,
                 from ../opencv/modules/core/include/opencv2/core/cvstd.hpp:81,
                 from ../opencv/modules/core/include/opencv2/core/base.hpp:58,
                 from ../opencv/modules/core/include/opencv2/core.hpp:54,
                 from ../opencv/modules/gapi/src/precomp.hpp:12,
                 from ../opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:8:
/usr/include/c++/4.8.2/bits/unique_ptr.h:169:2: error:   initializing argument 1 of 'std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Up = cv::gapi::fluid::BufferStorageWithBorder; _Ep = std::default_delete<cv::gapi::fluid::BufferStorageWithBorder>; <template-parameter-2-3> = void; _Tp = cv::gapi::fluid::BufferStorage; _Dp = std::default_delete<cv::gapi::fluid::BufferStorage>]'
  unique_ptr(unique_ptr<_Up, _Ep>&& __u) noexcept
  ^
../opencv/modules/gapi/src/backends/fluid/gfluidbuffer.cpp:355:12: error: cannot bind 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithoutBorder>' lvalue to 'std::unique_ptr<cv::gapi::fluid::BufferStorageWithoutBorder>&&'
     return storage;
            ^
```

### CODE REVIEW

**Comment by dmatveev** [comment]
Shame on gcc :)
