### ISSUE TITLE
[iOS] expected Info.plist at the root level since the platform uses shallow bundles

### ISSUE THREAD

**Issue by jihchao** [opencv/opencv#28170]
Hello,

I'm working with the opencv-4.12.0-ios-framework.zip and encountering a compilation error in my iOS project:

```
Framework /Users/xxx/Library/Developer/Xcode/DerivedData/Runner-catkfxjjmttbpobgigkxyalkswni/Build/Products/Debug-iphoneos/Runner.app/Frameworks/opencv2.framework contains Versions/Current/Resources/Info.plist, expected Info.plist at the root level since the platform uses shallow bundles
```
As I understand, iOS now requires frameworks to be structured as `shallow bundles`. Could you please advise if this is related to how I'm using the framework, or if there's a recommended way to resolve this?

Thank you for your time and assistance.

Xcode Version 26.1.1 (17B100)

**Comment by VadimLevin** [comment]
Good day, it looks like the error is related to the new Xcode 26 release, but its release notes lack any information related to framework structure changes (e.g. "shallow bundles").
For older versions of Xcode, everything works fine and I suppose this change is not backward compatible...

Can you provide any relevant information related to this "shallow bundles" apart from the build error?

Same issue: https://github.com/XcodesOrg/XcodesApp/issues/760
