### PR TITLE
imgcodecs: force reshaping of imdecode() input into a single row

### LINKED ISSUE #14978: Opencv 4.10 Can't Decode Webp from Memory
Python 3.7.3
opencv-python 4.1.0.25 from pip install opencv-python
I can open and write webp format from file with no problem, but I can't decode from memory. The code (at the end) returns:
> imdecode_(''): can't read data: OpenCV(4.1.0) /io/opencv/modules/imgcodecs/src/grfmt_webp.cpp:164: error: (-215:Assertion failed) data.rows == 1 in function 'readData'
However, it works with opencv 3.4.2 from conda install opencv.
Also, Kaggle kernel environment (Python 3.6.6 and opencv-python 4.1.0.25) just returns None object without throwing an error.

```
img = cv2.imread(file)
retval, buf = cv2.imencode(".webp", img, [cv2.IMWRITE_WEBP_QUALITY, 100])
img = cv2.imdecode(buf, 1)
```

### PR DESCRIPTION
**Pull request by alalek**
OpenCV upstream stuff may reinterpret vector as column.

Fixes Python `imdecode()` interface.

resolves #14978

### CODE REVIEW

**Comment by sunlightyxy** [comment]
Hi All,I also encountered this problem when calling opencv410 in Java,How can I solve this problem?thanks all

Code：
System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        String rotate6 = "/tmp/webp.webp";
        System.out.println("-----imdecode unchange-----");
        Mat imdecode = Imgcodecs.imdecode(new MatOfByte(FileUtils.readFileToByteArray(new File(rotate6))), Imgcodecs.IMREAD_UNCHANGED);
        System.out.println("imdecode width=" + imdecode.width());
        System.out.println("imdecode height=" + imdecode.height());
LOG:
imdecode_(''): can't read data: OpenCV(4.1.0) /home/yuxiaoyang/repo_test/xmss_3rdparty/opencv-4.1.0-imsize/modules/imgcodecs/src/grfmt_webp.cpp:164: error: (-215:Assertion failed) data.rows == 1 in function 'readData'

imdecode width=0
imdecode height=0
