### PR TITLE
Feat: Full OpenCL support for KAZE

### PR DESCRIPTION
**Pull request by manand881**
Add OpenCL rotation-invariant descriptor kernel and OCL
kcontrast histogram computation. Extend OCL dispatch to
handle all descriptor types (upright, extended, normal).

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by manand881** [comment]
let me look into this, this is a rebase problem

**Comment by asmorkalov** [comment]
```
[ 89%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/matchers.cpp.o
/home/alexander/opencv/modules/features2d/src/kaze/KAZEFeatures.cpp: In member function ‘void cv::KAZEFeatures::Feature_Detection_UMat(cv::UTPyramid&, std::vector<cv::KeyPoint>&)’:
/home/alexander/opencv/modules/features2d/src/kaze/KAZEFeatures.cpp:1508:45: error: ‘__gnu_cxx::__alloc_traits<std::allocator<cv::TEvolutionT<cv::UMat> >, cv::TEvolutionT<cv::UMat> >::value_type’ {aka ‘struct cv::TEvolutionT<cv::UMat>’} has no member named ‘octave_ratio’
 1508 |         const int diff_ratio = (int)uPyr[i].octave_ratio / (int)uPyr[i-1].octave_ratio;
      |                                             ^~~~~~~~~~~~
/home/alexander/opencv/modules/features2d/src/kaze/KAZEFeatures.cpp:1508:75: error: ‘__gnu_cxx::__alloc_traits<std::allocator<cv::TEvolutionT<cv::UMat> >, cv::TEvolutionT<cv::UMat> >::value_type’ {aka ‘struct cv::TEvolutionT<cv::UMat>’} has no member named ‘octave_ratio’
 1508 |         const int diff_ratio = (int)uPyr[i].octave_ratio / (int)uPyr[i-1].octave_ratio;
      |                                                                           ^~~~~~~~~~~~
/home/alexander/opencv/modules/features2d/src/kaze/KAZEFeatures.cpp:1515:47: error: ‘__gnu_cxx::__alloc_traits<std::allocator<cv::TEvolutionT<cv::UMat> >, cv::TEvolutionT<cv::UMat> >::value_type’ {aka ‘struct cv::TEvolutionT<cv::UMat>’} has no member named ‘octave_ratio’
 1515 |         const int diff_ratio = (int)uPyr[i+1].octave_ratio / (int)uPyr[i].octave_ratio;
      |                                               ^~~~~~~~~~~~
/home/alexander/opencv/modules/features2d/src/kaze/KAZEFeatures.cpp:1515:75: error: ‘__gnu_cxx::__alloc_traits<std::allocator<cv::TEvolutionT<cv::UMat> >, cv::TEvolutionT<cv::UMat> >::value_type’ {aka ‘struct cv::TEvolutionT<cv::UMat>’} has no member named ‘octave_ratio’
 1515 |         const int diff_ratio = (int)uPyr[i+1].octave_ratio / (int)uPyr[i].octave_ratio;
      |                                                                           ^~~~~~~~~~~~
/home/alexander/opencv/modules/features2d/src/kaze/KAZEFeatures.cpp:1524:15: error: ‘Evolution’ does not name a type; did you mean ‘TEvolution’?
 1524 |         const Evolution<UMat>& e = uPyr[i];
      |               ^~~~~~~~~
      |               TEvolution
/home/alexander/opencv/modules/features2d/src/kaze/KAZEFeatures.cpp:1525:30: error: ‘e’ was not declared in this scope
 1525 |         int max_kpts = (int)(e.Ldet.total() * 0.1f);
      |                              ^
[ 89%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/mser.cpp.o
```

**Comment by asmorkalov** [comment]
@manand881 I fixed build issues, but the implementation looks incomplete. See review notes.

File: modules/features2d/test/ocl/test_akaze.cpp [hunk 1]
```diff
@@ -5,29 +5,126 @@
...
 namespace opencv_test {
 namespace ocl {
-TEST(Features2d_AKAZE, ocl_accuracy)
+
+static void compare_kaze_results(const string& name, const vector<KeyPoint>& kp_cpu, const Mat& desc_cpu, const vector<KeyPoint>& kp_ocl, const Mat& desc_ocl)
+{
+    std::cout << "\n[ INFO ] Comparing " << name << ":" << std::endl;
+
+    float kp_ratio = (float)kp_ocl.size() / kp_cpu.size();
+    std::cout << "  Keypoint count ratio: " << kp_ratio << " (CPU: " << kp_cpu.size() << ", OCL: " << kp_ocl.size() << ")" << std::endl;
```
Comment (asmorkalov) [inline modules/features2d/test/ocl/test_akaze.cpp]: please use SCOPED_TRACE instead of std::cout

File: modules/features2d/test/ocl/test_akaze.cpp [hunk 2]
```diff
@@ -5,29 +5,126 @@
...
+
+    compare_kaze_results("Synthetic Upright 64-dim", kp_cpu, desc_cpu, kp_ocl, desc_ocl);
+
+    ASSERT_FALSE(kp_cpu.empty());
+    ASSERT_FALSE(kp_ocl.empty());
+}
+
+TEST(Features2d_KAZE, ocl_accuracy_real_image)
+{
+    Mat testImg = imread("/home/anand/Desktop/Projects/opencv_testing_dataset/example_building/images/DSC00153.JPG", IMREAD_GRAYSCALE);
```
Comment (asmorkalov) [inline modules/features2d/test/ocl/test_akaze.cpp]: Please use files from opencv_extra. Absolute path is not allowed.

File: modules/features2d/test/ocl/test_akaze.cpp [hunk 3]
```diff
@@ -5,29 +5,126 @@
...
+    Ptr<KAZE> kaze_ocl = KAZE::create(false, true, 0.001f, 4, 4, KAZE::DIFF_PM_G2);
+    vector<KeyPoint> kp_ocl;
+    UMat desc_ocl_umat;
+    kaze_ocl->detectAndCompute(testImg_umat, noArray(), kp_ocl, desc_ocl_umat);
+    Mat desc_ocl = desc_ocl_umat.getMat(ACCESS_READ);
+
+    compare_kaze_results("Synthetic Upright 64-dim", kp_cpu, desc_cpu, kp_ocl, desc_ocl);
+
+    ASSERT_FALSE(kp_cpu.empty());
+    ASSERT_FALSE(kp_ocl.empty());
```
Comment (asmorkalov) [inline modules/features2d/test/ocl/test_akaze.cpp]: it should be before `compare_kaze_results`.

File: modules/features2d/test/ocl/test_akaze.cpp [hunk 4]
```diff
@@ -5,29 +5,126 @@
...
+    Ptr<KAZE> kaze_ocl = KAZE::create(false, true, 0.001f, 4, 4, KAZE::DIFF_PM_G2);
+    vector<KeyPoint> kp_ocl;
+    UMat desc_ocl_umat;
+    kaze_ocl->detectAndCompute(testImg_umat, noArray(), kp_ocl, desc_ocl_umat);
+    Mat desc_ocl = desc_ocl_umat.getMat(ACCESS_READ);
+
+    compare_kaze_results("Real Image Upright 64-dim", kp_cpu, desc_cpu, kp_ocl, desc_ocl);
+
+    ASSERT_FALSE(kp_cpu.empty());
+    ASSERT_FALSE(kp_ocl.empty());
```
Comment (asmorkalov) [inline modules/features2d/test/ocl/test_akaze.cpp]: it should be before `compare_kaze_results`.

File: modules/features2d/test/ocl/test_akaze.cpp [hunk 5]
```diff
@@ -132,7 +229,124 @@ TEST(Features2d_KAZE, ocl_accuracy)
 
     float avg_diff = total_compared > 0 ? (float)(total_diff / total_compared) : 0.0f;
     EXPECT_GT(matched_kpts, (int)(kp_cpu.size() * 0.9f)) << "Should match at least 90% of keypoints by position";
-    EXPECT_LT(avg_diff, 0.01f) << "Average descriptor difference should be < 0.01, got " << avg_diff;
+    EXPECT_LT(avg_diff, 0.05f) << "Average descriptor difference should be < 0.05, got " << avg_diff;
+}
+
+TEST(Features2d_KAZE, performance_benchmark)
```
Comment (asmorkalov) [inline modules/features2d/test/ocl/test_akaze.cpp]: It's not accuracy, but performance test. Please move it to modules/features2d/perf folder and adjust accordingly.

**Comment by manand881** [comment]
I apologize for the bad PR. i kind of screwed up my working code due to some mistakes i made on git.

**Comment by manand881** [comment]
@asmorkalov the branch is ready for CI jobs to be triggered

**Comment by manand881** [comment]
@asmorkalov all my local tests are passing. i dont know why it failed here. there seems to be some issues with dnn which is not a part of features2d

**Comment by asmorkalov** [comment]
JS build error:
```
In file included from /home/ci/opencv/modules/features2d/src/kaze/AKAZEFeatures.cpp:15:
/home/ci/opencv/modules/features2d/src/kaze/akaze_diffusion.hpp:284:61: error: use of undeclared identifier 'ocl_pm_g1'
      if (!(Lx.isUMat() && Ly.isUMat() && Lflow.isUMat() && ocl_pm_g1(Lx, Ly, Lflow, kcontrast)))
                                                            ^
/home/ci/opencv/modules/features2d/src/kaze/akaze_diffusion.hpp:288:61: error: use of undeclared identifier 'ocl_pm_g2'
      if (!(Lx.isUMat() && Ly.isUMat() && Lflow.isUMat() && ocl_pm_g2(Lx, Ly, Lflow, kcontrast)))
                                                            ^
/home/ci/opencv/modules/features2d/src/kaze/akaze_diffusion.hpp:292:61: error: use of undeclared identifier 'ocl_weickert'
      if (!(Lx.isUMat() && Ly.isUMat() && Lflow.isUMat() && ocl_weickert(Lx, Ly, Lflow, kcontrast)))
                                                            ^
/home/ci/opencv/modules/features2d/src/kaze/akaze_diffusion.hpp:296:61: error: use of undeclared identifier 'ocl_charbonnier'
      if (!(Lx.isUMat() && Ly.isUMat() && Lflow.isUMat() && ocl_charbonnier(Lx, Ly, Lflow, kcontrast)))
                                                            ^
4 errors generated.
```
JS does not include OpenCL branch. It means that some OCL functions used unguarded.

**Comment by manand881** [comment]
fixed. @asmorkalov

**Comment by manand881** [comment]
Most of what is failing is not related to my code @asmorkalov

**Comment by manand881** [comment]
@asmorkalov I've Added a 32-bit x86 guard to the KAZE OpenCL dispatch path in modules/features2d/src/kaze.cpp:117-120.
On 32-bit x86, GPU drivers have tight private memory limits per work-item (often ≤256 bytes). Exceeding this causes driver crashes (SEH 0xc0000005) or allocation failures. AKAZE already had this guard and now it's been applied to KAZE as well.

Only one CI Job failed previously due to a code error. I've fixed it. the rest of it are failing due to a git clone issue. most likely due to all the recent issues that github has been having. We can retrigger the CI jobs.

If you want me to look into a way to safeguard the CI jobs from thegit clone issues that's been happening, let me know. I'll look into it

**Comment by asmorkalov** [comment]
The patch passes tests in my GF 2080 Ti, but introduce some stable performance degradation. The execution time is significant and regressions are reproducible. Could you take a look on it:
```
Geometric mean (ms)

                                                         Name of Test                                                            4.x-1   patch-1   patch-1  
                                                                                                                                                      vs    
                                                                                                                                                    4.x-1   
                                                                                                                                                  (x-factor)
detect::OCL_feature2d::(AKAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                    54.650   50.710     1.08   
detect::OCL_feature2d::(AKAZE_DEFAULT, "stitching/a3.png")                                                                       40.176   40.169     1.00   
detect::OCL_feature2d::(AKAZE_DEFAULT, "stitching/s2.jpg")                                                                       73.214  110.058     0.67   
detect::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")            56.206   51.393     1.09   
detect::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/a3.png")                                                               39.796   39.758     1.00   
detect::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/s2.jpg")                                                               75.172  113.056     0.66   
detect::OCL_feature2d::(KAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                    307.158  292.601     1.05   
detect::OCL_feature2d::(KAZE_DEFAULT, "stitching/a3.png")                                                                       241.277  249.211     0.97   
detect::OCL_feature2d::(KAZE_DEFAULT, "stitching/s2.jpg")                                                                       617.102  447.453     1.38   
detect::feature2d::(AKAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                        42.338   42.355     1.00   
detect::feature2d::(AKAZE_DEFAULT, "stitching/a3.png")                                                                           34.366   34.141     1.01   
detect::feature2d::(AKAZE_DEFAULT, "stitching/s2.jpg")                                                                           83.046   77.697     1.07   
detect::feature2d::(AKAZE_DESCRIPTOR_KAZE, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                41.766   41.980     0.99   
detect::feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/a3.png")                                                                   33.183   33.080     1.00   
detect::feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/s2.jpg")                                                                   82.170   77.265     1.06   
detect::feature2d::(KAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                        298.705  289.485     1.03   
detect::feature2d::(KAZE_DEFAULT, "stitching/a3.png")                                                                           241.430  247.406     0.98   
detect::feature2d::(KAZE_DEFAULT, "stitching/s2.jpg")                                                                           612.509  619.492     0.99   
detectAndCompute::OCL_AKAZEFixture::(640x480, 8UC1)                                                                              6.105    6.145      0.99   
detectAndCompute::OCL_AKAZEFixture::(1280x720, 8UC1)                                                                             13.948   15.174     0.92   
detectAndCompute::OCL_AKAZEFixture::(1920x1080, 8UC1)                                                                            34.448   34.721     0.99   
detectAndCompute::OCL_KAZEFixture::(640x480, 8UC1)                                                                              191.622  195.078     0.98   
detectAndCompute::OCL_KAZEFixture::(1280x720, 8UC1)                                                                             435.412  422.047     1.03   
detectAndCompute::OCL_KAZEFixture::(1920x1080, 8UC1)                                                                            918.722  873.443     1.05   
detectAndCompute::OCL_KAZEOclNonUprightFixture::(320x240, 8UC1)                                                                  29.987   40.021     0.75   
detectAndCompute::OCL_KAZEOclNonUprightFixture::(640x480, 8UC1)                                                                 173.973  203.203     0.86   
detectAndCompute::OCL_KAZEOclNonUprightFixture::(960x540, 8UC1)                                                                 286.792  276.320     1.04   
detectAndCompute::OCL_KAZEOclNonUprightFixture::(1280x720, 8UC1)                                                                601.093  432.361     1.39   
detectAndCompute::OCL_KAZEOclNonUprightFixture::(1920x1080, 8UC1)                                                               1397.825 881.307     1.59   
detectAndComputeExtended::OCL_KAZEOclExtendedNonUprightFixture::(320x240, 8UC1)                                                  29.364   36.893     0.80   
detectAndComputeExtended::OCL_KAZEOclExtendedNonUprightFixture::(640x480, 8UC1)                                                 164.069  194.705     0.84   
detectAndComputeExtended::OCL_KAZEOclExtendedNonUprightFixture::(960x540, 8UC1)                                                 291.409  268.691     1.08   
detectAndComputeExtended::OCL_KAZEOclExtendedNonUprightFixture::(1280x720, 8UC1)                                                590.233  425.451     1.39   
detectAndComputeExtended::OCL_KAZEOclExtendedNonUprightFixture::(1920x1080, 8UC1)                                               1418.550 590.703     2.40   
detectAndComputeExtendedUpright::OCL_KAZEOclExtendedUprightFixture::(320x240, 8UC1)                                              40.219   38.757     1.04   
detectAndComputeExtendedUpright::OCL_KAZEOclExtendedUprightFixture::(640x480, 8UC1)                                             193.820  189.903     1.02   
detectAndComputeExtendedUpright::OCL_KAZEOclExtendedUprightFixture::(960x540, 8UC1)                                             277.186  262.973     1.05   
detectAndComputeExtendedUpright::OCL_KAZEOclExtendedUprightFixture::(1280x720, 8UC1)                                            428.724  418.644     1.02   
detectAndComputeExtendedUpright::OCL_KAZEOclExtendedUprightFixture::(1920x1080, 8UC1)                                           906.858  583.211     1.55   
detectAndComputeKAZEUpright::OCL_AKAZEOclKazeUprightFixture::(320x240, 8UC1)                                                     20.033   17.363     1.15   
detectAndComputeKAZEUpright::OCL_AKAZEOclKazeUprightFixture::(640x480, 8UC1)                                                     50.710   49.747     1.02   
detectAndComputeKAZEUpright::OCL_AKAZEOclKazeUprightFixture::(1280x720, 8UC1)                                                   146.033  135.447     1.08   
detectAndComputeMLDB::OCL_AKAZEOclMldbUprightFixture::(320x240, 8UC1)                                                            19.082   19.169     1.00   
detectAndComputeMLDB::OCL_AKAZEOclMldbUprightFixture::(640x480, 8UC1)                                                            42.042   39.512     1.06   
detectAndComputeMLDB::OCL_AKAZEOclMldbUprightFixture::(960x540, 8UC1)                                                            49.135   47.131     1.04   
detectAndComputeMLDB::OCL_AKAZEOclMldbUprightFixture::(1280x720, 8UC1)                                                           67.571   62.751     1.08   
detectAndComputeMLDB::OCL_AKAZEOclMldbUprightFixture::(1920x1080, 8UC1)                                                         118.024  114.316     1.03   
detectAndComputeMLDB::OCL_AKAZEOclMldbUprightFixture::(2560x1440, 8UC1)                                                         207.786  201.213     1.03   
detectAndComputeMLDB::OCL_AKAZEOclMldbUprightFixture::(3840x2160, 8UC1)                                                         418.562  417.458     1.00   
detectAndComputeMLDBRealImages::OCL_AKAZEOclRealImagesFixture::("stitching/boat1.jpg", 0)                                       389.502  381.489     1.02   
detectAndComputeMLDBRealImages::OCL_AKAZEOclRealImagesFixture::("stitching/boat2.jpg", 0)                                       332.361  325.499     1.02   
detectAndComputeMLDBRealImages::OCL_AKAZEOclRealImagesFixture::("stitching/boat3.jpg", 0)                                       392.156  378.734     1.04   
detectAndComputeMLDBRealImages::OCL_AKAZEOclRealImagesFixture::("stitching/boat4.jpg", 0)                                       395.298  381.355     1.04   
detectAndComputeMLDBRealImages::OCL_AKAZEOclRealImagesFixture::("stitching/boat5.jpg", 0)                                       353.535  343.151     1.03   
detectAndComputeMLDBRealImages::OCL_AKAZEOclRealImagesFixture::("stitching/boat6.jpg", 0)                                       415.136  347.721     1.19   
detectAndComputeRealImages::OCL_KAZEOclRealImagesFixture::("stitching/boat1.jpg", 0)                                            4202.398 3832.806    1.10   
detectAndComputeRealImages::OCL_KAZEOclRealImagesFixture::("stitching/boat2.jpg", 0)                                            4188.422 3766.402    1.11   
detectAndComputeRealImages::OCL_KAZEOclRealImagesFixture::("stitching/boat3.jpg", 0)                                            4093.058 3799.717    1.08   
detectAndComputeRealImages::OCL_KAZEOclRealImagesFixture::("stitching/boat4.jpg", 0)                                            4128.391 3861.515    1.07   
detectAndComputeRealImages::OCL_KAZEOclRealImagesFixture::("stitching/boat5.jpg", 0)                                            4288.527 4004.320    1.07   
detectAndComputeRealImages::OCL_KAZEOclRealImagesFixture::("stitching/boat6.jpg", 0)                                            4354.360 4040.910    1.08   
detectAndComputeUpright::OCL_KAZEOclUprightFixture::(320x240, 8UC1)                                                              41.068   36.879     1.11   
detectAndComputeUpright::OCL_KAZEOclUprightFixture::(640x480, 8UC1)                                                             181.273  197.837     0.92   
detectAndComputeUpright::OCL_KAZEOclUprightFixture::(960x540, 8UC1)                                                             255.768  258.173     0.99   
detectAndComputeUpright::OCL_KAZEOclUprightFixture::(1280x720, 8UC1)                                                            422.871  417.486     1.01   
detectAndComputeUpright::OCL_KAZEOclUprightFixture::(1920x1080, 8UC1)                                                           902.499  866.876     1.04   
detectAndComputeUpright::OCL_KAZEOclUprightFixture::(2560x1440, 8UC1)                                                           1656.007 1599.783    1.04   
detectAndComputeUpright::OCL_KAZEOclUprightFixture::(3840x2160, 8UC1)                                                           4122.325 2439.660    1.69   
detectAndExtract::OCL_feature2d::(AKAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")          55.519   55.398     1.00   
detectAndExtract::OCL_feature2d::(AKAZE_DEFAULT, "stitching/a3.png")                                                             43.830   42.858     1.02   
detectAndExtract::OCL_feature2d::(AKAZE_DEFAULT, "stitching/s2.jpg")                                                             87.802  120.256     0.73   
detectAndExtract::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")  63.401   57.852     1.10   
detectAndExtract::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/a3.png")                                                     48.758   43.988     1.11   
detectAndExtract::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/s2.jpg")                                                    101.138  136.414     0.74   
detectAndExtract::OCL_feature2d::(KAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")          316.518  313.975     1.01   
detectAndExtract::OCL_feature2d::(KAZE_DEFAULT, "stitching/a3.png")                                                             254.686  270.824     0.94   
detectAndExtract::OCL_feature2d::(KAZE_DEFAULT, "stitching/s2.jpg")                                                             641.704  470.650     1.36   
detectAndExtract::feature2d::(AKAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")              43.267   43.262     1.00   
detectAndExtract::feature2d::(AKAZE_DEFAULT, "stitching/a3.png")                                                                 33.906   34.933     0.97   
detectAndExtract::feature2d::(AKAZE_DEFAULT, "stitching/s2.jpg")                                                                 87.468   84.555     1.03   
detectAndExtract::feature2d::(AKAZE_DESCRIPTOR_KAZE, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")      47.263   44.210     1.07   
detectAndExtract::feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/a3.png")                                                         39.559   36.141     1.09   
detectAndExtract::feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/s2.jpg")                                                         94.675   94.810     1.00   
detectAndExtract::feature2d::(KAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")              301.428  300.381     1.00   
detectAndExtract::feature2d::(KAZE_DEFAULT, "stitching/a3.png")                                                                 253.414  254.140     1.00   
detectAndExtract::feature2d::(KAZE_DEFAULT, "stitching/s2.jpg")                                                                 649.045  643.384     1.01   
extract::OCL_feature2d::(AKAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                   52.014   48.563     1.07   
extract::OCL_feature2d::(AKAZE_DEFAULT, "stitching/a3.png")                                                                      37.499   37.187     1.01   
extract::OCL_feature2d::(AKAZE_DEFAULT, "stitching/s2.jpg")                                                                      70.540  113.022     0.62   
extract::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")           57.322   51.860     1.11   
extract::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/a3.png")                                                              40.950   38.917     1.05   
extract::OCL_feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/s2.jpg")                                                              79.873  122.875     0.65   
extract::OCL_feature2d::(KAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                   254.767  287.899     0.88   
extract::OCL_feature2d::(KAZE_DEFAULT, "stitching/a3.png")                                                                      212.528  243.333     0.87   
extract::OCL_feature2d::(KAZE_DEFAULT, "stitching/s2.jpg")                                                                      537.885  429.421     1.25   
extract::feature2d::(AKAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                       38.147   37.164     1.03   
extract::feature2d::(AKAZE_DEFAULT, "stitching/a3.png")                                                                          29.942   29.204     1.03   
extract::feature2d::(AKAZE_DEFAULT, "stitching/s2.jpg")                                                                          73.389   72.674     1.01   
extract::feature2d::(AKAZE_DESCRIPTOR_KAZE, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")               38.650   38.544     1.00   
extract::feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/a3.png")                                                                  32.039   31.672     1.01   
extract::feature2d::(AKAZE_DESCRIPTOR_KAZE, "stitching/s2.jpg")                                                                  82.685   79.424     1.04   
extract::feature2d::(KAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")                       272.318  245.439     1.11   
extract::feature2d::(KAZE_DEFAULT, "stitching/a3.png")                                                                          212.777  213.068     1.00   
extract::feature2d::(KAZE_DEFAULT, "stitching/s2.jpg")                                                                          548.520  542.177     1.01   
```

**Comment by manand881** [comment]
I need to rethink a couple of things. i created an end to end GPU pipeline for maximum performance looking at some research papers published in arxiv. but the tests don't really do justice to the pipeline. ill first rethink how we should be testing these contributions and raise PRs for that first @asmorkalov. ill close the PR for now
