### PR TITLE
Fix build regression in Quirc

### PR DESCRIPTION
**Pull request by AleksandrPanov**
Introduced in https://github.com/opencv/opencv/pull/23275
Buildbot report: https://pullrequest.opencv.org/buildbot/builders/4_x_ARMv7-lin/builds/100067/steps/compile%20release/logs/stdio

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@opencv-alalek Could you take a look on armv7 build issue. it's not relevant to the PR changes:
```
In file included from /build/precommit_armv7/4.x/opencv/modules/python/src2/cv2.cpp:5:0:
/build/precommit_armv7/4.x/opencv/modules/python/src2/cv2.hpp:20:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error 1
make[2]: Leaving directory `/build/precommit_armv7/build'
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Review by asmorkalov — APPROVED** [review]
tested manually with jetson-tk1 and ubuntu 16.04 (gcc 5).

**Review by opencv-alalek — APPROVED** [review]
Thank you!
