### ISSUE TITLE
OpenCV 4.13.0 fails to build with FFMPEG version 4.4.4

### ISSUE THREAD

**Issue by Michael-Gunther-KPM** [opencv/opencv#28875]
### System Information

c++ OpenCV version: 4.13.0 Operating System / Platform: Windows 11 Compiler & compiler version: Ninja-MSVC 19.44.35219

### Detailed description

Build of OpenCV fails with the below error code when ffmpeg/4.4.4 is already built on this system.

Build works fine with later versions on FFMPEG (e.g. ffmpeg/7.1.3). Likely just need to update the required minimum version of ffmpeg in conancenter to one that is C++17 compatible.

```cap_ffmpeg_impl.hpp (534) error C4576: a parenthesized type followed by an initializer list is a non-standard explicity type conversion syntax```

### Steps to reproduce

Example conanfile. Note that ffmpeg/4.4.4 was previously built on this computer for OpenCV 4.10
```
from conan import ConanFile
from conan.tools.cmake import cmake_layout
from conan.tools.cmake import CMakeDeps
from conan.tools.cmake import CMakeToolchain

class TestProgram(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    name = "TestProgram"
    version = "4.41"

    def requirements(self):
        self.requires("opencv/4.13.0")
        # self.requires("ffmpeg/7.1.3") # required to build opencv as opencv's requirements aren't strict enough
        generators = "CMakeDeps", "CMakeToolchain"

    def build_requirements(self):
        pass

    def layout(self):
        cmake_layout(self)

    def generate(self):
        cmake = CMakeDeps(self)
        cmake.generate()
        toolchain = CMakeToolchain(self)
        toolchain.generate()

```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by Teddy-Yangjiale** [comment]
Hi, I am interested in this build issue and would like to work on it. I have a Windows 11 + MSVC environment ready for reproduction. Could you please assign this to me?

**Comment by Teddy-Yangjiale** [comment]
Hi @Michael-Gunther-KPM, thanks for the detailed report and the clear reproduction steps!

I've submitted PR #28894 to fix this. It simply replaces the C99 compound literal with FFmpeg's standard av_make_q to resolve the MSVC C4576 error under strict C++17 mode. Waiting for the CI results now!
