### ISSUE TITLE
'Segmentation fault' with gpu video decoding

### ISSUE THREAD

**Issue by cysin** [opencv/opencv#10201]
- OpenCV => 3.3.1-dev (github trunk: 29e4a4940dd81b22b26cbb51a2673d8c17f9f57d)
- Operating System / Platform => CentOS 7.3 64Bit
- Compiler => Default compiler on OS, gcc 4.8.5 20150623 (Red Hat 4.8.5-11)
- Cuda => 9.0
- GPU => 1080 Ti

I am trying 'samples/gpu/video_reader.cpp' to decode video using nvidia's gpu, but got 'segfault'. Cuda 9 now uses 'dynlink_nvcuvid.h' headers, and before that it uses 'nvcuvid.h'. If I changed 'dynlink_nvcuvid.h' to 'nvcuvid.h' (have to copy old 'nvcuvid.h' to cuda include folder), all works fine. 

So I guess this must be something related to 'dynlink_nvcuvid.h'

**Comment by naemshaz** [comment]
I am facing similar issue using both CUDA 9.0 and CUDA 8.0. I posted this question [here](http://answers.opencv.org/question/179986/opencv-331-sigsegv-in-cvcudacodeccreatevideoreader/) but no one responded. Does it mean Cuda support is totally broken in OpenCV w.r.t. video decoding?

**Comment by mprevot** [comment]
Hello, do you have the same problem with cuda 9.1 and opencv head ?

**Comment by naemshaz** [comment]
Well, I tried with OpenCV3.4 and Cuda 9.1. It's still crashing.

Thread 1 "gpu_vid.bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ba2fcc in cv::cudacodec::detail::CuvidVideoSource::CuvidVideoSource (this=0x6dc400, fname=...)
    at [REMOVED]/OpenCV/3.4/opencv/modules/cudacodec/src/cuvid_video_source.cpp:63
63          CUresult cuRes = cuvidCreateVideoSource(&videoSource_, fname.c_str(), &params);

**Comment by pdstc** [comment]
I have this same segfault when trying to run video_reader.cpp (ocv 3.4.0, cuda 9.1, nvidia 384.111).

The cuda sample NVIDIA_CUDA-9.0_Samples/3_Imaging/cudaDecodeGL makes similar cuvid calls and that works, so I tried I adding dynlink_nvcuvid.cpp from that sample to the video_reader build and called its `cuvidInit` function from video_reader before `createVideoReader`. This makes video_reader work without segfaulting and frames were correctly decoded to GpuMat.

However I'm not clear why it fixes it. The init function appears to just dlopen libnvcuvid.so and dlsym its functions but opencv is already linking to libnvcuvid.so.

NVCUVID was enabled in opencv cmake with `-D WITH_NVCUVID=ON -D CUDA_nvcuvid_LIBRARY=/usr/lib/nvidia-384/libnvcuvid.so`

**Comment by look-recognize** [comment]
Hi @pdstc 
I faced the same problem, then I added the cuvidinit before createVideoReader. However, I got some error:

/usr/bin/ld: nvcuvid/libdynlink_nvcuvid.a(dynlink_nvcuvid.cpp.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/readvideo_ffmpeg.dir/build.make:124: recipe for target 'readvideo_ffmpeg' failed
make[2]: *** [readvideo_ffmpeg] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/readvideo_ffmpeg.dir/all' failed
make[1]: *** [CMakeFiles/readvideo_ffmpeg.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Could you tell me the way that you call the function cuvidInit? Thanks a lot.

**Comment by look-recognize** [comment]
Hi @pdstc 

I fixed the link problem, but it is still segmentation fault(core dump)

**Comment by kevinlieb** [comment]
I am having the same problem with the demo app.  Also CUDA 9.1 and opencv 3.4

**Comment by jaredcasper** [comment]
The segfault happens because with the `dynlink_nvcuvid.h` header files you have to actually do the dynamic linking (i.e. use dlopen and set the function pointers that are in `dynlink_nvcuvid.h`).  All of the function pointer are initialized to 0 in `dynlink_nvcuvid.h`, so attempting to call any of those functions without loading the symbols first will result in a segfault. The Video Codec SDK samples do this in the `cuvidInit()` function in `dynlink_nvcuvid.cpp`.  You can also see this done [in FFmpeg](https://github.com/FFmpeg/FFmpeg/blob/cd98f20b4abac8241ef7f922eb85ba6fe3fe230b/compat/cuda/dynlink_loader.h).

With the latest release of the Video Codec SDK, 8.1, they have gone back to using `nvcuvid.h` and normal linking. CUDA 9.1 still ships with the `dynlink_nvcuvid.h` header, but you can get the new one by downloading it directly.  The header file itself is BSD licensed so the easiest thing may be to just include the one you are going to use in the OpenCV repo.

**Comment by nazikus** [comment]
can anyone provide clear instructions how to fix this?

@pdstc 
>so I tried I adding dynlink_nvcuvid.cpp from that sample to the video_reader build and called its cuvidInit"

how exactly did you add `dynlink_nvcuvid.cpp` code to yours? I explicitly added this .cpp by including it at the beginning, but it doesn't compile. 

@jaredcasper 
Where do I download `nvcuvid.h`? I tried downloading [nvcuvid.h](https://www.ffmpeg.org/doxygen/3.2/dir_1171acc0d24ee592809cc87e1bf3a9b4.html) (and cuviddec.h) from FFMPEG project, include it in my sources, it compiles but fails with the same segmentation fault. Any hints how to fix it?

Thanks

**Comment by pavel-shvetsov** [comment]
Hello, I've just walked through all the same issues and can share my experience.
Here is how I've successfully compile my project with `cv::cudacodec::VideoReader`

My setup:
- Ubuntu 16.04
- OpenCV 3.4.0
- CUDA 9.1
- CMake 3.5.1

1. Copy `dynlink_nvcuvid.cpp` somewhere inside your project. File itself located in `/usr/local/cuda/samples/3_Imaging/cudaDecodeGL/dynlink_nvcuvid.cpp` if you've properly installed CUDA Toolkit
2. Link CUDA library to your project
  - CMake 
  ```cmake
  include_directories(${CUDA_INCLUDE_DIRS})
  target_link_libraries(project_name cuda)
  ```
  - gcc
  ```
  -lcuda
  ```
3. Include CUDA headers in your project
```cpp
#include <dynlink_nvcuvid.h>
#include <dynlink_cuviddec.h>
```
4. Init the device before using `cv::cuda` stuff
```cpp
// Init CUDA
void* hHandleDriver = nullptr;
CUresult cuda_res = cuInit(0, __CUDA_API_VERSION, hHandleDriver);
if (cuda_res != CUDA_SUCCESS) {
    throw exception();
}
cuda_res = cuvidInit(0);
if (cuda_res != CUDA_SUCCESS) {
    throw exception();
}
std::cout << "CUDA init: SUCCESS" << endl;
cv::cuda::printCudaDeviceInfo(cv::cuda::getDevice());
```
And you're good to go.

If you still getting this nasty access violation - you should try to recompile OpenCV with `WITH_NVCUVID = ON`

---
Source of inspiration: http://answers.opencv.org/question/178227/cvcudacodeccreatevideoreader-segfault/

**Comment by nazikus** [comment]
@pavel-shvetsov 

This worked for me! But one more step was missing. I did exactly according to your instructions, and still I had an error:

    /usr/bin/ld: /tmp/ccUX3mNP.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
    //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status

For this error one more lib was missing in compiler args `-ldl`. Afterward I've managed to run cuda video decoding  (x12 faster! then CPU decoding on my laptop). By the way, `-lcuda` lib is not necessary in my case.

Spasibo!

OpenCV 3.4.1
CUDA 9.0
Ubuntu 18.04

P.S.
cuda::VideoReader works fine, but cuda::VideoWriter is not.

    OpenCV(3.4.1) Error: The function/feature is not implemented (The called functionality is disabled for current build or platform) in throw_no_cuda, file /home/naz/opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp, line 111
    terminate called after throwing an instance of 'cv::Exception'
    what():  OpenCV(3.4.1) 
    /home/naz/opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp:111: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda


But that is an issue for another thread to post, i guess.

**Comment by pavel-shvetsov** [comment]
`cv::cuda::VideoWriter` is yet not implemented for Linux version of the lib, even for 4.0.0-pre. Only for Windows.
It is stated in docs here:
* https://docs.opencv.org/ref/master/df/dde/classcv_1_1cudacodec_1_1VideoWriter.html

![capture](https://user-images.githubusercontent.com/1812009/42494229-4b4709d2-8428-11e8-8ae7-88f30ede7879.PNG)

**Comment by Dyex719** [comment]
@pavel-shvetsov 
Do you have any idea whether the procedure you mentioned will work using CUDA 8.0? 
Cuda 8.0 doesn't have `usr/local/cuda/samples/3_Imaging/cudaDecodeGL/dynlink_nvcuvid.cpp` by default.

**Comment by pavel-shvetsov** [comment]
Not sure about CUDA 8.0
I think that current issue is only related to CUDA >= 9.0

`cv::cudacodec::VideoReader` should work right out of the box with CUDA 8.0

**Comment by zhu-ty** [comment]
I am currently using windows, but still, I get "The function/feature is not implemented" when I tried to use cv::cudacodec::VideoWriter, anyone knows how to fix it?

```
OpenCV Error: The function/feature is not implemented (The called functionality 
is disabled for current build or platform) in throw_no_cuda, 
file E:\libs\build\build\opencv-3.4.0\modules\core\include\opencv2/core/private.cuda.hpp, line 111
```

**Comment by Cugtyt** [comment]
> @pavel-shvetsov
> 
> This worked for me! But one more step was missing. I did exactly according to your instructions, and still I had an error:
> 
> ```
> /usr/bin/ld: /tmp/ccUX3mNP.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
> //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> ```
> 
> For this error one more lib was missing in compiler args `-ldl`. Afterward I've managed to run cuda video decoding (x12 faster! then CPU decoding on my laptop). By the way, `-lcuda` lib is not necessary in my case.
> 
> Spasibo!
> 
> OpenCV 3.4.1
> CUDA 9.0
> Ubuntu 18.04
> 
> P.S.
> cuda::VideoReader works fine, but cuda::VideoWriter is not.
> 
> ```
> OpenCV(3.4.1) Error: The function/feature is not implemented (The called functionality is disabled for current build or platform) in throw_no_cuda, file /home/naz/opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp, line 111
> terminate called after throwing an instance of 'cv::Exception'
> what():  OpenCV(3.4.1) 
> /home/naz/opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp:111: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda
> ```
> 
> But that is an issue for another thread to post, i guess.

I have the same error:

```
/usr/bin/ld: CMakeFiles/read_video.dir/dynlink_nvcuvid.cpp.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/read_video.dir/build.make:149: recipe for target 'read_video' failed
make[2]: *** [read_video] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/read_video.dir/all' failed
make[1]: *** [CMakeFiles/read_video.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

and my CMakeLists.txt, I dont know if I done it right,  cmake script is from internet search:

```
cmake_minimum_required(VERSION 2.8)
project( read-video)

set(CMAKE_CXX_STANDARD 11)
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
include_directories( ${CUDA_INCLUDE_DIRS}  )
add_definitions( "-ldl" )
add_executable( read_video video_reader_gpu_test.cpp dynlink_nvcuvid.cpp)
target_link_libraries( read_video ${OpenCV_LIBS} )
target_link_libraries( read_video cuda )
```

My code is the example:

``` c++
#include <iostream>

#include "opencv2/opencv_modules.hpp"

#if defined(HAVE_OPENCV_CUDACODEC)

#include <string>
#include <vector>
#include <algorithm>
#include <numeric>

#include <opencv2/core.hpp>
#include <opencv2/core/opengl.hpp>
#include <opencv2/cudacodec.hpp>
#include <opencv2/highgui.hpp>

#include <dynlink_nvcuvid.h>
#include <dynlink_cuviddec.h>


int main(int argc, const char* argv[])
{
    if (argc != 2)
        return -1;

    const std::string fname(argv[1]);

    // Init CUDA
    void* hHandleDriver = nullptr;
    CUresult cuda_res = cuInit(0, __CUDA_API_VERSION, hHandleDriver);
    if (cuda_res != CUDA_SUCCESS) {
        std::cout << "cuda_res exception" << std::endl;
    }
    cuda_res = cuvidInit(0);
    if (cuda_res != CUDA_SUCCESS) {
        std::cout << "cuda_res exception" << std::endl;
    }
    std::cout << "CUDA init: SUCCESS" << std::endl;
    cv::cuda::printCudaDeviceInfo(cv::cuda::getDevice());

    cv::namedWindow("CPU", cv::WINDOW_NORMAL);
    cv::namedWindow("GPU", cv::WINDOW_OPENGL);
    cv::cuda::setGlDevice();
    cv::Mat frame;
    cv::VideoCapture reader(fname);

    cv::cuda::GpuMat d_frame;
    cv::Ptr<cv::cudacodec::VideoReader> d_reader = cv::cudacodec::createVideoReader(fname);

    cv::TickMeter tm;
    std::vector<double> cpu_times;
    std::vector<double> gpu_times;

    int gpu_frame_count=0, cpu_frame_count=0;
    for (;;)
    {
        std::cout << "first loop" << std::endl;
        tm.reset(); tm.start();
        if (!reader.read(frame))
            break;
        tm.stop();
        cpu_times.push_back(tm.getTimeMilli());
        cpu_frame_count++;

        cv::imshow("CPU", frame);

        if (cv::waitKey(3) > 0)
            break;
    }

    for (;;)
    {
        std::cout << "second loop" << std::endl;
        tm.reset(); tm.start();
        if (!d_reader->nextFrame(d_frame))
            break;
        tm.stop();
        gpu_times.push_back(tm.getTimeMilli());
        gpu_frame_count++;

        cv::imshow("GPU", d_frame);

        if (cv::waitKey(3) > 0)
            break;
    }

    if (!cpu_times.empty() && !gpu_times.empty())
    {
        std::cout << std::endl << "Results:" << std::endl;

        std::sort(cpu_times.begin(), cpu_times.end());
        std::sort(gpu_times.begin(), gpu_times.end());

        double cpu_avg = std::accumulate(cpu_times.begin(), cpu_times.end(), 0.0) / cpu_times.size();
        double gpu_avg = std::accumulate(gpu_times.begin(), gpu_times.end(), 0.0) / gpu_times.size();

        std::cout << "CPU : Avg : " << cpu_avg << " ms FPS : " << 1000.0 / cpu_avg << " Frames " << cpu_frame_count << std::endl;
        std::cout << "GPU : Avg : " << gpu_avg << " ms FPS : " << 1000.0 / gpu_avg << " Frames " << gpu_frame_count << std::endl;
     }

    return 0;
}
```

and I build opencv with this:

``` 
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_OPENGL=ON -D WITH_CUBLAS=ON -D CUDA_NVCC_FLAGS="-D_FORCE_INLINES --expt-relaxed-constexpr" -D WITH_GDAL=ON -D WITH_XINE=ON -D WITH_CUDA=ON -D WITH_NVCUVID=ON -D WITH_GTK_2_X=ON -D FORCE_VTK=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 ..
``` 
and I use:

Ubuntu 16.04
opencv 3.4.3
cuda 9.0

I dont know how to fix it, can you help me? Thanks

**Comment by chuanli11** [comment]
@pavel-shvetsov Thanks a lot for the nice solution. 

I made it work on Windows by following the gist of your method. However I used a newer version of OpenCV and Video Codec SDK, which saved the trouble of dealing with dynlinks in Windows.

Details can be found here: https://github.com/opencv/opencv/issues/11220#issuecomment-530653535
