### ISSUE TITLE
Compilation Errors during build

### ISSUE THREAD

**Issue by rare72** [opencv/opencv#28629]
### System Information

System & Environment Information

Before deploying fixes, here is the environment data captured from your current build state:

Operating System: Linux 6.17.0-14-generic (x86_64)

Compiler: GNU (GCC) 13.3.0

CMake Version: 3.28.3

Python Version: 3.12.3

Python Libraries: /usr/lib/x86_64-linux-gnu/libpython3.12.so

Target Integration: OpenVINO (2026.1.0) + oneVPL + TBB + Contrib

**Python Env Info:**
$ pip freeze
bitsandbytes==0.49.2
build==1.4.0
certifi==2026.2.25
charset-normalizer==3.4.4
dpcpp-cpp-rt==2025.3.1
filelock==3.20.0
fsspec==2025.12.0
hf-xet==1.3.2
huggingface_hub==0.36.2
idna==3.11
impi-rt==2021.17.0
intel-cmplr-lib-rt==2025.3.1
intel-cmplr-lib-ur==2025.3.1
intel-cmplr-lic-rt==2025.3.1
intel-opencl-rt==2025.3.1
intel-openmp==2025.3.1
intel-pti==0.15.0
intel-sycl-rt==2025.3.1
Jinja2==3.1.6
joblib==1.5.3
markdown-it-py==4.0.0
MarkupSafe==3.0.2
mdurl==0.1.2
mkl==2025.3.0
ml_dtypes==0.5.4
mpmath==1.3.0
networkx==3.4.2
ninja==1.13.0
nncf @ git+https://github.com/openvinotoolkit/nncf.git@ec73d5636337e94883d101d3fe4fd87ef6feccf9
numpy==2.2.6
oneccl==2021.17.1
oneccl-devel==2021.17.1
onemkl-license==2025.3.0
onemkl-sycl-blas==2025.3.0
onemkl-sycl-dft==2025.3.0
onemkl-sycl-lapack==2025.3.0
onemkl-sycl-rng==2025.3.0
onemkl-sycl-sparse==2025.3.0
onnx==1.20.1
onnx-ir==0.2.0
onnxscript==0.6.2
openvino @ file:///home/phil-vinson/data/projects/supernpu_linux/openvino_2026_nightly/build_trio/wheels/openvino-2026.1.0-21232-cp312-cp312-manylinux_2_39_x86_64.whl#sha256=50a46cd114fed3b2b3c0caac8921a29f8ccb78e77fcd5be1c3e391f63d4e86ed
openvino-telemetry==2025.2.0
openvino-tokenizers==2026.0.0.0
optimum @ git+https://github.com/huggingface/optimum@114647f51404f9747410afc287a8079f1f16389b
optimum-intel @ git+https://github.com/huggingface/optimum-intel.git@98517678c995ea9e8e0ee88cecfbad1bcb8db713
optimum-onnx @ git+https://github.com/huggingface/optimum-onnx.git@9ca6f688046d1824e3e0b660b1044fa0b39717f2
packaging==26.0
pandas==2.3.3
patchelf==0.17.2.4
pillow==12.0.0
protobuf==7.34.0
psutil==7.2.2
pydot==3.0.4
pyelftools==0.32
Pygments==2.19.2
pyparsing==3.3.2
pyproject_hooks==1.2.0
python-dateutil==2.9.0.post0
pytz==2026.1.post1
PyYAML==6.0.3
regex==2026.2.28
requests==2.32.5
rich==14.3.3
safetensors==0.7.0
scikit-learn==1.8.0
scipy==1.17.1
setuptools==82.0.0
six==1.17.0
sympy==1.14.0
tabulate==0.10.0
tbb==2022.3.0
tcmlib==1.4.1
threadpoolctl==3.6.0
tokenizers==0.22.2
torch==2.10.0+xpu
torchao==0.16.0
torchaudio==2.10.0+xpu
torchvision==0.25.0+xpu
tqdm==4.67.3
transformers==4.57.6
triton-xpu==3.6.0
typing_extensions==4.15.0
tzdata==2025.3
umf==1.0.2
urllib3==2.6.3
wheel==0.46.3

### Detailed description

Individual Errors:

1. **3. OpenJPEG Configuration Error:**
```text
The imported target "openjpip" references the file "/usr/lib/x86_64-linux-gnu/libopenjpip.so.2.5.0" but this file does not exist.
[cite_start]

2. **Expected Behavior:**
The build should complete without attempting to allocate maximum `size_t` values, and CMake should correctly map system OpenJPEG libraries.

**Actual Behavior:**
The build triggers `-Walloc-size-larger-than` warnings which may indicate deep-seated logic errors or compatibility issues with GCC 13.3.0's stricter analysis. The OpenJPEG configuration is also broken despite the library being present on the host.

**Steps to Reproduce:**
1. Use GCC 13.3.0 on a Linux x86_64 environment.
2. Configure OpenCV 4.14.0-pre with OpenVINO 2026.1.0 and Contrib modules.
3. Run the build command.
2. **3. OpenJPEG Configuration Error:**
```text
The imported target "openjpip" references the file "/usr/lib/x86_64-linux-gnu/libopenjpip.so.2.5.0" but this file does not exist.
[cite_start]

3. **2. Allocation issue in Caffe Importer (`populateNet`):**
```text
/opencv/modules/core/include/opencv2/core/utility.hpp:1096:15: warning: argument 1 value ‘18446744073709551615’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
 1096 | ptr = new _Tp[_size];
      | ^
Note: In member function ‘populateNet’
[cite_start]

Possible Solution's:
OpenCV Build Dependency Fixes

Based on the logs, several key modules were disabled or misconfigured. Running the following commands will address the missing TBB, Glog, Gflags, and OpenJPEG issues.

1. Core Development & Parallelism (TBB)

The log showed TBB: _lib-NOTFOUND. TBB is crucial for high-performance parallel processing in OpenCV.

sudo apt-get update
sudo apt-get install -y \
    libtbb-dev \
    libatlas-base-dev \
    liblapack-dev


2. Structure from Motion (SfM) Dependencies

The opencv_sfm module was disabled because Glog and Gflags were missing.

sudo apt-get install -y \
    libgoogle-glog-dev \
    libgflags-dev \
    libeigen3-dev


3. Image Format Support (Fixing OpenJPEG)

The log indicated a broken reference to libopenjpip.so.2.5.0. Reinstalling the development headers and ensuring the runtime library is present should fix this.

sudo apt-get install -y \
    libopenjp2-7-dev \
    libopenjp2-7 \
    libopenjpip7 \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev


4. Video & VPL Support

Since you are targeting oneVPL and OpenVINO, ensure the media transport and hardware acceleration headers are available.

sudo apt-get install -y \
    libva-dev \
    libmfx-dev \
    libvpl-dev \
    libdrm-dev


5. Cleaning and Reconfiguring

After installing these packages, you must clear your CMake cache to ensure it detects the new libraries instead of using the old "NOTFOUND" paths.

# Navigate to your build directory
cd path/to/your/opencv/build

# Remove the cache and re-run your CMake command
rm CMakeCache.txt
# Re-run your specific CMake command here...


Note on OpenJPEG Error

If the OpenJPEG error persists after installation, it is often due to a symlink mismatch in Ubuntu 24.04/22.04. You can manually create the link if CMake still complains:

sudo ln -s /usr/lib/x86_64-linux-gnu/libopenjpip.so.7 /usr/lib/x86_64-linux-gnu/libopenjpip.so.2.5.0

[phase2_opencv_final_fusion_VPL_20260309_062633.log](https://github.com/user-attachments/files/25840163/phase2_opencv_final_fusion_VPL_20260309_062633.log)

### Steps to reproduce

Steps to Reproduce Build Failures

This guide outlines the procedure to reproduce the compilation errors and configuration warnings observed in the OpenCV 4.14.0-pre build on Ubuntu 24.04 (Noble Numbat) with GCC 13.3.0.

1. Environment Setup

The failure occurs in an environment with the following specifications:

OS: Ubuntu 24.04 LTS (Kernel 6.17.0-14-generic)

Compiler: GCC 13.3.0 / G++ 13.3.0

Python: 3.12.3 (Virtual Environment)

OpenVINO: 2026.1.0 (Installed at /home/phil-vinson/data/projects/...)

2. Source Acquisition

Clone the OpenCV and Contrib repositories at the specific commits identified in the log:

# Clone OpenCV main repo
git clone [https://github.com/opencv/opencv.git](https://github.com/opencv/opencv.git)
cd opencv
git checkout fe160f3eed

# Clone OpenCV Contrib repo
cd ..
git clone [https://github.com/opencv/opencv_contrib.git](https://github.com/opencv/opencv_contrib.git)
cd opencv_contrib
git checkout abaddbcd


3. Configuration (CMake)

Run the CMake configuration using the parameters used in the "Final Integrated Fusion" phase. Ensure OpenVINO_DIR points to your local 2026.1.0 installation.

mkdir -p opencv/build && cd opencv/build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      -D WITH_TBB=ON \
      -D WITH_VPL=ON \
      -D WITH_OPENCL=ON \
      -D WITH_OPENVINO=ON \
      -D OpenVINO_DIR=/path/to/your/openvino_2026.1.0/cmake \
      -D BUILD_opencv_python3=ON \
      -D PYTHON3_EXECUTABLE=$(which python3) \
      ..


4. Observed Configuration Failures

During the cmake step, verify the following in the output:

OpenJPEG: Look for the error: The imported target "openjpip" references the file "/usr/lib/x86_64-linux-gnu/libopenjpip.so.2.5.0" but this file does not exist.

SFM Module: Check if opencv_sfm is disabled due to missing glog and gflags.

5. Compilation

Run the build. The integer overflow warnings typically appear during the compilation of the core and dnn modules.

make -j$(nproc)


Expected Warnings/Errors to Capture:

Integer Underflow Warning:
Search the build output for: warning: argument 1 value ‘18446744073709551615’ exceeds maximum object size.
Locations: cvMixChannels and CaffeImporter::populateNet.

Linker Errors:
If the build proceeds to linking, it may fail on OpenJPEG or TBB components due to the "NOTFOUND" paths established during configuration.

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by ziyuanLi-alex** [comment]
I'd like to work on this. Here's my plan:

1. alloc-size-larger-than: Locate the exact code paths in `cvMixChannels` and `CaffeImporter::populateNet` where `SIZE_MAX` is passed as allocation size, and add defensive size checks. 

2. OpenJPEG jpip: Add validation in `OpenCVFindLibsGrfmt.cmake` to detect broken `openjpip` imported targets.

3. TBB detection: Improve fallback logic in `OpenCVDetectTBB.cmake` to handle Ubuntu 24.04 library paths.
