### ISSUE TITLE
Codeblock-Opencv-windows installation error-bin/opencv_test_core.exe' failed?

### ISSUE THREAD

**Issue by selvakarna** [opencv/opencv#14928]
Codeblock-Opencv-windows installation error-bin/opencv_test_core.exe' failed?

Error: during installation ?

E:\cod_block\30_6_2017_succes_opencv_install\opencv\build\x86\mingw>mingw32-make install
[  2%] Built target zlib
[  6%] Built target libtiff
[  9%] Built target libjpeg
[ 14%] Built target libwebp
[ 18%] Built target libjasper
[ 19%] Built target libpng
[ 25%] Built target IlmImf
[ 27%] Built target opencv_core_pch_dephelp
[ 27%] Built target pch_Generate_opencv_core
[ 32%] Built target opencv_core
[ 32%] Built target opencv_test_core_pch_dephelp
[ 32%] Built target opencv_highgui_pch_dephelp
[ 32%] Built target pch_Generate_opencv_highgui
[ 33%] Built target opencv_imgcodecs_pch_dephelp
[ 33%] Built target pch_Generate_opencv_imgcodecs
[ 34%] Built target opencv_imgproc_pch_dephelp
[ 34%] Built target pch_Generate_opencv_imgproc
[ 39%] Built target opencv_imgproc
[ 40%] Built target opencv_imgcodecs
[ 40%] Built target opencv_videoio_pch_dephelp
[ 40%] Built target pch_Generate_opencv_videoio
[ 41%] Built target opencv_videoio
[ 43%] Built target opencv_highgui
[ 43%] Built target pch_Generate_opencv_test_core
[ 43%] Built target opencv_ts_pch_dephelp
[ 43%] Built target pch_Generate_opencv_ts
[ 44%] Built target opencv_ts
[ 44%] Linking CXX executable ..\..\bin\opencv_test_core.exe
../../lib/libopencv_ts310.a(ts.cpp.obj):ts.cpp:(.text$_ZN6cvtest2TS4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x119): undefined reference to `cv::redirectError(int (*)(int, char const*, char const*, char const*, int, void*), void*, void**)'
collect2.exe: error: ld returned 1 exit status
modules\core\CMakeFiles\opencv_test_core.dir\build.make:885: recipe for target 'bin/opencv_test_core.exe' failed
mingw32-make[2]: *** [bin/opencv_test_core.exe] Error 1
CMakeFiles\Makefile2:1719: recipe for target 'modules/core/CMakeFiles/opencv_test_core.dir/all' failed
mingw32-make[1]: *** [modules/core/CMakeFiles/opencv_test_core.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

Unfortunately, we don't have builds (or environment setup) with mentioned configuration so we can't help with problem investigation.

Anyway, we can take a look on **the clear reason of the problem** and suggest some fix/workaround.
But please ensure that you are working with fresh code base (OpenCV 3.1 has been released more than 3 years ago and many things are fixed already).

**Comment by selvakarna** [comment]
How to solve alalek?
