### ISSUE TITLE
ppc64le: build fails on GCC 4.9.2

### ISSUE THREAD

**Issue by seiko2plus** [opencv/opencv#13210]
##### System information (version)

- OpenCV => 3.4.*, 4.0.*, master
- Operating System / Platform => ppc64le GNU/Linux
- Compiler => GCC 4.9.2

##### Detailed description

````
In file included from /worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:158:0,
                 from /worker/buildbot/Power8_Linux_gcc-4_9__opencv/build/modules/core/precomp.hpp:85:
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp: In function 'void cv::hal::cpu_baseline::cmp_loop(const T1*, size_t, const T1*, size_t, uchar*, size_t, int, int) [with OP = cv::hal::cpu_baseline::op_cmplt; T1 = double; Tvec = cv::hal_baseline::v_float64x2; size_t = long unsigned int; uchar = unsigned char]':
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:405:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ab = vec_pack(a.val, b.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:406:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 cd = vec_pack(c.val, d.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:407:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ef = vec_pack(e.val, f.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:408:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 gh = vec_pack(g.val, h.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp: In function 'void cv::hal::cpu_baseline::cmp_loop(const T1*, size_t, const T1*, size_t, uchar*, size_t, int, int) [with OP = cv::hal::cpu_baseline::op_cmple; T1 = double; Tvec = cv::hal_baseline::v_float64x2; size_t = long unsigned int; uchar = unsigned char]':
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:405:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ab = vec_pack(a.val, b.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:406:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 cd = vec_pack(c.val, d.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:407:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ef = vec_pack(e.val, f.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:408:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 gh = vec_pack(g.val, h.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp: In function 'void cv::hal::cpu_baseline::cmp_loop(const T1*, size_t, const T1*, size_t, uchar*, size_t, int, int) [with OP = cv::hal::cpu_baseline::op_cmpeq; T1 = double; Tvec = cv::hal_baseline::v_float64x2; size_t = long unsigned int; uchar = unsigned char]':
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:405:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ab = vec_pack(a.val, b.val);
````
CI url:
https://ocv-power.imavr.com/#/builders/5/builds/1

##### Steps to reproduce

build on GCC 4.9.2
