### ISSUE TITLE
Python bindings: ORB is broken

### ISSUE THREAD

**Issue by PolarNick239** [opencv/opencv#6081]
Following code fails:

``` python
import cv2
img = cv2.imread('some_image.jpg')
orb = cv2.ORB_create(nfeatures=5000)
ps, descs = orb.detectAndCompute(img, None)
```

Error output:

```
OpenCV Error: Assertion failed (The data should normally be NULL!) in allocate, file /home/polarnick/coding/forks/opencv_3.1/modules/python/src2/cv2.cpp, line 163
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-4-03ae3bc0ea38> in <module>()
----> 1 ps, descs = orb.detectAndCompute(img, None)

error: /home/polarnick/coding/forks/opencv_3.1/modules/python/src2/cv2.cpp:163: error: (-215) The data should normally be NULL! in function allocate
```

Environment: Python 3.4, Ubuntu

Affects **master** and **3.1.0**.

**Workaround:** if passing `cv2.UMat(img)` (see https://github.com/Itseez/opencv/pull/6078) - everything works

Can I pull-request this test case?

**UPD:**
The better **workaround** is `cv2.ocl.setUseOpenCL(False)` before ORB execution

The bug was introduced in commit 190d00ea3e46feedd38a7417c0a5ab08b900a56b (Pull request: https://github.com/Itseez/opencv/pull/5317)

**Comment by alalek** [comment]
Looks like it is related to #6009
Real problem is more general (these fixes violate T-API principles actually).
More accurate fix is to patch somehow allocator for python bindings

I believe you can create pull request with problem reproducer.

**Comment by sssruhan1** [comment]
Looks like detectAndCompute assumes img is InputArray. So it should be either Mat or Vector.

**Comment by kwiechen** [comment]
Same problem with python 3.4 Windows 10 x64 using computers with 12 or 16 GB RAM.
The code works using a workstaion with 32 GB  RAM
Is there a solution?

**Comment by ddintzner** [comment]
Same problem on python3.5.2 | OSX 10 | opencv3 3.1.0_1

OpenCV Error: Assertion failed (The data should normally be NULL!) in allocate, file /tmp/opencv320160302-5467-cybcsk/opencv-3.1.0/modules/python/src2/cv2.cpp, line 163
Traceback (most recent call last):
  File "/Volumes/Data RAID Set 1/Dropbox/python/opencv3/tests/orb.py", line 19, in <module>
    kp, des = orb.detectAndCompute(img, None)
cv2.error: /tmp/opencv320160302-5467-cybcsk/opencv-3.1.0/modules/python/src2/cv2.cpp:163: error: (-215) The data should normally be NULL! in function allocate

**Comment by patricksnape** [comment]
@alalek Unfortunately I don't understand the internals of the T-API well enough to really be of help. My previous fix was merely pattern matching on what I was seeing used somewhere else. It seems like when the T-API stuff was introduced either a) the Python bindings were not updated sufficiently to account for the new range of types that can be passed or b) the Python allocators do not properly understand how to marshall data back and forth between the T-API types. 

This must be at least the 4th place that I've seen these errors been reported so clearly this is a fairly widespread issue!

**Comment by tzickel** [comment]
As a temporary working stop-gap till the UMat / T-API issue is resolved, just disabling OpenCL support in run-time works for me: cv2.ocl.setUseOpenCL(False)

**Comment by adaviding** [comment]
Same problem with OpenCV 3.1, Python 2.7, Windows 10.  This seems to be a general problem with the Python bindings.  I have seen other chatter on the internet about a similar type of error message when using Python, but unrelated to usage of ORB.

```python
# -*- coding: utf-8 -*-
import numpy as np
import cv2
import matplotlib
from matplotlib import pyplot as plt

img = cv2.imread('C:/Dev/bs/data-tools/TestCollateral/Mars3/final0.jpg',cv2.IMREAD_GRAYSCALE)
mask = np.ones(img.shape, np.uint8);

orb = cv2.ORB_create()

# ERROR OCCURS ON NEXT LINE:
kp, des = orb.detectAndCompute(img,None)
```

In the IPython console I get:

```
Traceback (most recent call last):

  File "<ipython-input-3-906d4ad4cd53>", line 1, in <module>
    runfile('C:/Users/davidi/Desktop/cvplay.py', wdir='C:/Users/davidi/Desktop')

  File "C:\Programs\Anaconda-py-2.7\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Programs\Anaconda-py-2.7\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/davidi/Desktop/cvplay.py", line 13, in <module>
    kp, des = orb.detectAndCompute(img,None)

error: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\python\src2\cv2.cpp:163: error: (-215) The data should normally be NULL! in function NumpyAllocator::allocate
```

**Comment by tzickel** [comment]
iirc #6078 is supposed to fix this issues.

**Comment by Filarius** [comment]
Same issue on Windows 7, Python 3.4.3 OpenCV 3.1.0 
```
descriptor = cv2.ORB_create()
# ERROR OCCURS ON NEXT LINE:
kp1,des1 = descriptor.detectAndCompute(image,None)
```
Also same issue in Stitcher.stitch - seems used same code.

**Comment by PolarNick239** [comment]
> iirc #6078 is supposed to fix this issues.

Sadly no.
I found this issue, while writing tests for UMat support.
ORB for numpy array images is broken (in that PR too), while new version for UMat thin wrapper in that PR - works.

Workaround `cv2.UMat(img)` is not a golden bullet, because if image small - CPU implementation will be faster (memory transfer to GPU is quite expensive).

ORB was working before, so somebody should just make regression testing and find changes in past, that lead to these bugs.

**Comment by PolarNick239** [comment]
The bug introduced in commit 190d00ea3e46feedd38a7417c0a5ab08b900a56b

**Comment by tzickel** [comment]
Ok, what happens here (when OpenCL is enabled), the code flow is:

1. The python wrapper function (auto generated) for ORB's detectAndCompute defines an Mat called descriptors (in C++) and calls pyopencv_to on an input argument for it (which is usually not defined) and thus it set's descriptors allocator to numpy allocator and returns:
https://github.com/Itseez/opencv/blob/master/modules/python/src2/cv2.cpp#L229
afterwards it calls ORB_Impl::detectAndCompute with descriptors as OutputArray.

2. Because the Mat is empty, it creates it (allocates) inorder to save the data:
https://github.com/Itseez/opencv/blob/master/modules/features2d/src/orb.cpp#L1129

3. ocl_computeOrbDescriptors needs the input as an UMat, not a Mat, so the error described here occurs when _descriptors is converted to an UMat:
https://github.com/Itseez/opencv/blob/master/modules/features2d/src/orb.cpp#L1170

4. the Mat::getUMat function calls the Mat allocator (but now since the Mat is created in step 2 already, it has an allocated data pointer):
https://github.com/Itseez/opencv/blob/master/modules/core/src/umatrix.cpp#L292

5. Remember in the start the Mat allocator is set to be NumpyAllocator, but it does not accept an allocate call with allocated data, and aborts:
https://github.com/Itseez/opencv/blob/master/modules/python/src2/cv2.cpp#L163

----
Now someone who understands UMat and Python bindings should figure out how to fix this :)

**Comment by PolarNick239** [comment]
These steps were working before, but in https://github.com/Itseez/opencv/commit/ad70ab404cb6954aa08b4172b32fd40e23100c8d - UMat was changed, and that change (that affects step 4 in your description) leaded to such conflict.
I think @alalek could help with this.

**Comment by alalek** [comment]
OpenCL code path [should not be executed](https://github.com/Itseez/opencv/search?utf8=%E2%9C%93&q=CV_OCL_RUN) in case of non-UMat arguments.

Try to replace [here](https://github.com/Itseez/opencv/blob/3942b1f36261b196a264eb35c996222848fe3c93/modules/features2d/src/orb.cpp#L973):
```
bool useOCL = ocl::useOpenCL();
```
to
```
bool useOCL = _descriptors.isUMat() && ocl::useOpenCL();
```

I believe this should resolve this issue (but not a real problem)

**Comment by tzickel** [comment]
@alalek so basically OpenCL shouldn't be used when running OpenCV via Python yes ? if so, why doesn't cv2.cpp just disable OpenCL by default ? (also how is it not a real problem ? python bindings isn't working for anyone with an OCL supported computer for some of the functionality that worked in OpenCV 2....).

**Comment by tzickel** [comment]
I think your solution isn't optimal since there are many code path before the descriptors (like computing the pyramids, etc...) that can be done in OCL and are internal to the function, no ?

Is there any documentation on UMatData implementation and on OCL not running with non UMat args ?

I guess all the python bindings code needs to be auto scanned for stuff like this (in case someone adds such code in the future and/or there currently exists other stuff like this)

**Comment by alalek** [comment]
> OpenCL shouldn't be used when running OpenCV via Python

OpenCL should not be used when using non-UMat args.
It is due unexpected performance issues with discrete GPUs (data trasfer) / iGPU (creating/managing/destruction a lot of OpenCL objects).

**Comment by tzickel** [comment]
@alalek Seeing there are quite a few problematic interactions between the python bindings and OpenCL, and there are no tests to figure out what is going on, maybe by default cv2.cpp should disable OpenCL on load, and if a user wants it, he will explicitly enable it ? (I can see bug reports here about stuff like the MOG2 as well, and who knows what else).

**Comment by lmiguelmh** [comment]
I think there is a fix for this: 
https://github.com/opencv/opencv/pull/6847

T-API python support implemented #6847

**Comment by PolarNick239** [comment]
No, that pull request does not contain fix.
It will lead to possibility to workaround the problem by using OpenCL implementation of ORB, but the CPU ORB still broken.

**Comment by ManuelZ** [comment]
Hi, I'm facing the same error after doing this:

```
import cv2
stitcher = cv2.createStitcher(False)
a = cv2.imread("image1.jpg")
b = cv2.imread("image2.jpg")
stitcher.stitch((a, b))
```

**Details:**
OpenCV compiled from sources version 3.1.0
Python 2.7.6
I'm setting cv2.ocl.setUseOpenCL(False)

**Error mesage:**
(...)/opencv/modules/python/src2/cv2.cpp:163: error: (-215) The data should normally be NULL! in function allocate

**Comment by Asalle** [comment]
same as #6969?

**Comment by Rajashalini** [comment]
hi. im very new to image processing. When i execute the below line,

cv2.ocl.setUseOpenCL(False)


it shows 'module' object has no attribute 'ocl' .
could anyone please help me..thank you..

**Comment by RoshanADK** [comment]
@Rajashalini  , It's 'oc1' not 'ocl' . Replace 'L' by 'ONE' 1 .

**Comment by PrasadNR** [comment]
I am facing the same issue in my Windows 8.1 on Lenovo Y50-70.

"Python has stopped working A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available".

It is happening at this line
`kp1, des1 = orb.detectAndCompute(cv_image, None)`

I am on Anaconda. Setting ocl to false didn't help.
