### PR TITLE
Fix create aruco Board in Python

### LINKED ISSUE #23176: Cannot use cv2.aruco.Board
### System Information

OpenCV python version: 4.7.0.68
Operating System / Platform: Windows 11
Python version: 3.10.9

### Detailed description

I am porting code from 4.6.0.66 to 4.7.0.68. Aruco has moved from contrib to the main package, and some functions have been renamed. One of these is the constructor for an aruco board. It has been renamed from `cv2.aruco.Board_create` to `cv2.aruco.Board`. Its input arguments have not changed.
However, i am no longer able to call it with the same input arguments as in 4.6.0.66. Even though i put in a list of points and a list of ids of the same size, it always gives me an error that they are not the same length.:
```
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\aruco\aruco_board.cpp:160: error: (-215:Assertion failed) ids.size() == objPoints.size() in function 'cv::aruco::Board::Board'
```
Since the signature has not changed, i assume this is some error in the python wrapper or some change internal to the function?

### Steps to reproduce

Code that worked with 4.6.0.66:
```python
# boardCornerPoints is a list of 4x2 float32 matrices, e.g.:
# boardCornerPoints[0] ->
# array([[-178.05125, -151.86725],
#        [-136.15675, -151.86725],
#        [-136.15675, -109.97275],
#        [-178.05125, -109.97275]], dtype=float32)
boardCornerPoints = np.dstack(boardCornerPoints)        # list of 2D arrays -> 3D array
boardCornerPoints = np.rollaxis(boardCornerPoints,-1)   # 4x2xN -> Nx4x2
boardCornerPoints = np.pad(boardCornerPoints,((0,0),(0,0),(0,1)),'constant', constant_values=(0.,0.)) # Nx4x2 -> Nx4x3
cv2.aruco.Board_create(boardCornerPoints, self.aruco_dict, np.array(ids))
```
For 4.7.0.68, the last line should be changed to:
```python
cv2.aruco.Board(boardCornerPoints, self.aruco_dict, np.array(ids))
```
That however does not work, see error above.

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by AleksandrPanov**
This PR fixes #23176

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]
:+1: Thanks!

**Comment by siilats** [comment]
I think the same is needed for charucoboard and charucodiamond

**Comment by asmorkalov** [comment]
@AleksandrPanov Please take a look on it.
