### PR TITLE
imgproc: fix connectedComponents assert on boolean mask

### LINKED ISSUE #29593: cv::connectedComponentsWithStats asserts on input mask of type CV_Bool
### System Information

OpenCV version: 4.13 and 5.0.0
OS: Windows+macOS
Compilers: MSVS 2022/2026 and XCode 16.1/26.4 Clang

### Detailed description

In OpenCV 4.x, `cv::Mat_<bool>::depth()` returns 0 (==`CV_8U`)
In OpenCV 5.0.0, `cv::Mat_<bool>::depth()` returns 9 (==`CV_Bool`)

In both versions, `cv::connectedComponentsWithStats` calls `connectedComponents_sub1`. This function contains following assertion:

    CV_Assert(iDepth == CV_8U || iDepth == CV_8S);

When passed a `cv::Mat_<bool>`, this worked fine in 4.x, but now asserts on this condition.

I believe this function was missed when `CV_Bool` was added, and the assertion should be extended to allow `CV_Bool` as `iDepth` value.

This behaviour violates [the expectation expressed in the migration guide ](https://github.com/opencv/opencv/wiki/OpenCV-4-to-5-migration#new-data-types) as
> `CV_Bool` matrices can now be used as masks wherever a `CV_8U` or `CV_8S` mask was previously accepted.

Workarounds include not using `cv::Mat_<bool>` as a mask type (at least for `cv::connectedComponentsWithStats`), which seems contrary to the intention of having a boolean datatype?
See also previous similar issue: #29578

### Steps to reproduce

```cpp
#include <opencv2/imgproc.hpp>

int main()
{
    cv::Mat1w labels;
    cv::Mat1i stats;
    cv::Mat1d centroids;
    int num_labels = 0;
    cv::Mat_<bool> mask(2,2);
    num_labels = cv::connectedComponentsWithStats(mask, labels, stats, centroids, 8, CV_16U);
}
```
This works with OpenCV 4.13 but asserts with OpenCV 5.0.0:

    cv::Exception: OpenCV(5.0.0) .../modules/imgproc/src/connectedcomponents.cpp:5662: error: (-215:Assertion failed) iDepth == CV_8U || iDepth == CV_8S in function 'connectedComponents_sub1'

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by lazerg**
Fixes #29593

In 5.0 cv::Mat_<bool>::depth() returns CV_Bool instead of CV_8U, so connectedComponents_sub1 tripped its `iDepth == CV_8U || iDepth == CV_8S` assert and threw on boolean masks. This worked in 4.x.

CV_Bool is a 1-byte 0/1 type that the labeling code reads the same way as CV_8U/CV_8S, so the assert just needs to allow it through.

Added a test comparing a Mat_<bool> mask against the equivalent CV_8UC1 mask across every connectivity and CCL algorithm.

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]

File: modules/imgproc/test/test_connectedcomponents.cpp [hunk 1]
```diff
@@ -795,5 +795,33 @@ TEST(Imgproc_ConnectedComponents, regression_27568)
...
+        false, false, false, true,
+        true,  false, true,  true);
+    EXPECT_EQ(mask.depth(), CV_Bool);
+
+    cv::Mat1b ref = (cv::Mat1b(3, 4) <<
+        255, 255,   0, 255,
+          0,   0,   0, 255,
+        255,   0, 255, 255);
+
+    for (const int connectivity : {4, 8})
```
Comment (asmorkalov) [inline modules/imgproc/test/test_connectedcomponents.cpp]: I propose to convert the test to parameterized test and invoke each connectivity type and ccl type as test parameter. The cases are isolated then and it case of failure the broken configuration is obvious without debugger.

**Review by asmorkalov — CHANGES_REQUESTED** [review]

File: modules/imgproc/test/test_connectedcomponents.cpp (hunk 1 above)
Comment (lazerg) [reply modules/imgproc/test/test_connectedcomponents.cpp]: Converted to a parameterized test (`Imgproc_ConnectedComponents_BoolMask`, combining connectivity x ccltype) in 69104e6, so each configuration now runs and reports as its own test case.

**Review by abhishek-gola — APPROVED** [review]

**Comment by abhishek-gola** [comment]
Duplicates: https://github.com/opencv/opencv/pull/29622
