### PR TITLE
core: fix JacobiSVD SIMD accumulation to match scalar path

### PR DESCRIPTION
**Pull request by madanm3**
Replace FMA with mul-add in dotD/givensD to avoid Windows MSVC rounding drift.
- Address the FMA drift introduced in https://github.com/opencv/opencv/pull/29720

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by madanm3** [comment]
image

**Comment by asmorkalov** [comment]
It does not help:
```
    PID: 13928
    [ RUN      ] Photo_CalibrateDebevec.regression
    C:\GHA-OCV-3\_work\opencv\opencv\opencv\modules\photo\test\test_hdr.cpp(292): error: Expected: (max) < (0.15), actual: 0.214742 vs 0.15
    [  FAILED  ] Photo_CalibrateDebevec.regression (1539 ms)
    [----------] Global test environment tear-down
    [==========] 75 tests from 34 test cases ran. (63007 ms total)
    [  PASSED  ] 74 tests.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] Photo_CalibrateDebevec.regression
     1 FAILED TEST
```

**Comment by asmorkalov** [comment]
The last change triggers similar issue on Alpine Linux too:
```
    Run: [PosixPath('/home/ci/build/bin/opencv_test_photo'), '--skip_unstable=1']
    Env: {}
    Log: /home/ci/build/out_opencv_test_photo.txt
    PID: 25341
    [ RUN      ] Photo_CalibrateDebevec.regression
    /home/ci/opencv/modules/photo/test/test_hdr.cpp:292: Failure
    Expected: (max) < (0.15), actual: 0.214742 vs 0.15
    [  FAILED  ] Photo_CalibrateDebevec.regression (1324 ms)
    [----------] Global test environment tear-down
    [==========] 75 tests from 34 test cases ran. (57745 ms total)
    [  PASSED  ] 74 tests.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] Photo_CalibrateDebevec.regression
```

**Comment by asmorkalov** [comment]
@madanm3 I Tunned the failed test threshold for now in https://github.com/opencv/opencv/pull/29728 just to make CI green and not bother other contributors. Please revert the modification in your PR to track changes.

**Comment by madanm3** [comment]
@asmorkalov, Reverted the threshold changes, as suggested.

There seems to be CI differences: 
```
fatal: repository 'https://github.com/madanm3/opencv/' not found
##[end-action id=__self.__run_3;outcome=skipped;conclusion=skipped]
```
Fails since the PR is raised from org repo: https://github.com/amd/opencv. 

- Windows, Linux, and Alpine use checkout-and-merge, which looks up the PR author’s fork (madanm3/opencv). That repo doesn’t exist, so the merge is skipped and CI builds plain 4.x.
- ARM64 and macOS pull from the PR head repo (amd/opencv), so the merge works and CI tests the actual PR branch.

**Comment by madanm3** [comment]
Five workflows use the different pattern from the rest (checkout-and-merge + PR author's fork):
1. OCV-PR-Windows.yaml
2. OCV-PR-Linux.yaml
3. OCV-PR-Linux-Alpine.yaml
4. OCV-PR-Linux-NoHAL.yaml
5. OCV-CodeQL.yaml

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
Testes passed locally on Windows and Linux. Also I do not se perf regressions. Thanks a lot.
We are looking on CI. Thanks for highlighting the bug.
