### ISSUE TITLE
object_detection.cpp gives some error with Faster rcnn inception v2 tensorflow model.

### ISSUE THREAD

**Issue by farshadopencv** [opencv/opencv#12250]
I am working on object detection with the following sample in opencv dnn

[object_detection.cpp](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp)

for yolo model and ssd models it works nice but when I use faster rcnn inception v2 the program doesn't run. 

 System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2015
- Model : faster_rcnn_inception_v2_coco
[model pb file](http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz)

- Config pbtxt: faster_rcnn_inception_v2_coco_2018_01_28.pbtxt
[file](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/faster_rcnn_inception_v2_coco_2018_01_28.pbtxt)

- Classes : object_detection_classes_coco.txt
[file](https://github.com/opencv/opencv/blob/master/samples/data/dnn/object_detection_classes_coco.txt)

- My cmd command : 
`object_detection --model=frozen_inference_graph.pb --config=faster_rcnn_inception_v2_coco_2018_01_28.pbtxt --width=300 --height=300 --classes=object_detection_classes_coco.txt --thr=.9 --scale=0.00784  --mean="127.5 127.5 127.5"  --input=JV0A1194.jpg --rgb=RGB`

- Log and Errors: 
[ INFO:0] VIDEOIO: Enabled backends(6, sorted by priority): FFMPEG(1000); MSMF(990); DSHOW(980); VFW(970); CV_IMAGES(960); CV_MJPEG(950)
[ INFO:0] Initialize OpenCL runtime...
OpenCV(3.4.2) Error: Assertion failed ((int)_numAxes == inputs[0].size()) in cv::dnn::PermuteLayerImpl::getMemoryShapes, file C:\build\3_4_winpack-build-win64-vc14\opencv\modules\dnn\src\layers\permute_layer.cpp, line 137
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(3.4.2) Error: Assertion failed ((int)_numAxes == inputs[0].size()) in cv::dnn::PermuteLayerImpl::getMemoryShapes, file C:\build\3_4_winpack-build-win64-vc14\opencv\modules\dnn\src\layers\permute_layer.cpp, line 137

**Comment by dkurt** [comment]
@farshadopencv, Could you please regenerate a `.pbtxt` file using corresponding [tf_text_graph_faster_rcnn.py](https://github.com/opencv/opencv/blob/3.4/samples/dnn/tf_text_graph_faster_rcnn.py) script from your source code?

Or just try to use a confing file from opencv_extra of the same tag as your OpenCV installation (see https://github.com/opencv/opencv_extra/blob/3.4.2/testdata/dnn/faster_rcnn_inception_v2_coco_2018_01_28.pbtxt).

**Comment by farshadopencv** [comment]
@dkurt, Thanks for response. I used the config file from opencv github and previous error came from that opencv config file pbtxt (https://github.com/opencv/opencv_extra/blob/3.4.2/testdata/dnn/faster_rcnn_inception_v2_coco_2018_01_28.pbtxt) and pre-trained tensorflow model  faster_rcnn_inception_v2_coco (http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz). 

Also, using your mentioned tf_text_graph_faster_rcnn.py,  I regenerate the config text file but I get new errors now:

- `test2 --model=frozen_inference_graph1.pb --config=new1.pbtxt --width=300 --height=300 --classes=object_detection_classes_coco.txt --thr=.9 --scale=0.00784  --mean="127.5 127.5 127.5"  --input=space_shuttle.jpg`

- OpenCV(3.4.2) Error: Unspecified error (Input layer not found: FirstStageFeatureExtractor/InceptionV2/Conv2d_1a_7x7/depthwise_weights/read/_58__cf__64) in cv::dnn::experimental_dnn_v5::`anonymous-namespace'::TFImporter::connect, file C:\build\3_4_winpack-build-win64-vc14\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 495
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(3.4.2) Error: Unspecified error (Input layer not found: FirstStageFeatureExtractor/InceptionV2/Conv2d_1a_7x7/depthwise_weights/read/_58__cf__64) in cv::dnn::experimental_dnn_v5::`anonymous-namespace'::TFImporter::connect, file C:\build\3_4_winpack-build-win64-vc14\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 495

I dont know why this command works very good for yolo and ssd models but doesn't work with faster rcnn inception v2.

**Comment by kilchem182** [comment]
I am having the same problem. Using faster_rcnn_inceptionV2 from the tensorflow model zoo, as well as the .pbtxt file from opencv_extra I receive the '(int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'' error. Any help would be greatly appreciated.

Thanks

**Comment by dkurt** [comment]
@farshadopencv, @kilchem182, please specify your OpenCV versions from the following command:
```python
import cv2 as cv
print (cv.getBuildInformation())
```

**Comment by kilchem182** [comment]
@dkurt OpenCV version is 3.4.2

**Comment by dkurt** [comment]
@farshadopencv, @kilchem182, try to reproduce my steps:

1. Go to OpenCV 3.4.2 release
```
cd /path/to/opencv_extra && git checkout 3.4.2
cd /path/to/opencv && git checkout 3.4.2
```

2. Fix a command line arguments bug in [a sample](https://github.com/opencv/opencv/blob/3.4.2/samples/dnn/object_detection.cpp): replace
```
"{ thr         | .4 | Non-maximum suppression threshold. }"
```

to 
```
"{ nms         | .4 | Non-maximum suppression threshold. }"
```

2. Build OpenCV with examples
```
cd /path/to/opencv && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_EXAMPLES=ON -DBUILD_LIST=dnn,ts,python2 .. && make -j4
```
3. Run an object detection application:
```
./bin/example_dnn_object_detection --config=opencv_extra/testdata/dnn/faster_rcnn_inception_v2_coco_2018_01_28.pbtxt --model=faster_rcnn_inception_v2_coco_2018_01_28.pb --width=300 --height=300 --scale=0.00784 --mean="127.5 127.5 127.5" --rgb --input=example.jpg
```
![out](https://user-images.githubusercontent.com/25801568/44536982-51463c80-a706-11e8-9118-8e7d68dea868.png)

**Comment by farshadopencv** [comment]
@dkurt Thank you so much. It works nice finally! 

But I have two questions now. 
- How can I modify the following code to make OpenCv with X64 architecture  and both of debug and release options as well? the following code generate opencv for win32 only.
`cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_EXAMPLES=ON -DBUILD_LIST=dnn,ts,python2 ..`

and the second qustion:

- when I replace the pre-trained faster_rcnn_inception_v2_coco model with my own trained inception model on my own dataset, I get the following error:
`example_dnn_object_detection --config=C:/Users/ngm/Documents/occ/opencv_extra/testdata/dnn/faster_rcnn_inception_v2_coco_2018_01_28.pbtxt --model=my_inception_model.pb --width=300 --height=300 --scale=0.00784 --mean="127.5 127.5 127.5" --rgb --input=JV0A1194.jpg`

erorr:
- OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(3.4.2) Error: Unspecified error (Const input blob for weights not found) in cv::dnn::experimental_dnn_v5::`anonymous-namespace'::TFImporter::getConstBlob, file C:\Users\ngm\Documents\occ\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 528

Then, using  tf_text_graph_faster_rcnn.py, I generate pbtxt file for my inception model. and now I get this error:

`example_dnn_object_detection --config=my_inception_model.pbtxt --model=my_inception_model.pb --width=300 --height=300 --scale=0.00784 --mean="127.5 127.5 127.5" --rgb --input=JV0A1194.jpg`

error:
- OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(3.4.2) Error: Unspecified error (Input layer not found: FirstStageFeatureExtractor/InceptionV2/Conv2d_1a_7x7/depthwise_weights) in cv::dnn::experimental_dnn_v5::`anonymous-namespace'::TFImporter::connect, file C:\Users\ngm\Documents\occ\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 495

Is there any way to modify my trained inception model to work fine as pre-trained faster_rcnn_inception_v2_coco model?

**Comment by dkurt** [comment]
@farshadopencv, May I ask you to update your OpenCV to the latest state of [3.4 branch](https://github.com/opencv/opencv/tree/3.4) and test your model again? Thanks!

**Comment by farshadopencv** [comment]
@dkurt Thanks again.

I downloaded the [3.4 branch](https://github.com/opencv/opencv/tree/3.4) version and then using following command, I build OpenCv:

`git checkout 3.4`
`cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_EXAMPLES=ON -DBUILD_LIST=dnn,ts,python2 ..  && make -j4`



Then i tried to generate the pbtxt file for my own faster_inception_rcnn model by:
`python tf_text_graph_faster_rcnn.py --input=fasterCarPlate.pb --output=fasterCarPlate.pbtxt --config=faster_rcnn_inception_v2_pets.config`

and i get this error
`Number of classes: 1
Scales:            [0.25, 0.5, 1.0, 2.0]
Aspect ratios:     [0.5, 1.0, 2.0]
Width stride:      16.000000
Height stride:     16.000000
Features stride:   16.000000
Traceback (most recent call last):
  File "tf_text_graph_faster_rcnn.py", line 228, in <module>
    createFasterRCNNGraph(args.input, args.config, args.output)
  File "tf_text_graph_faster_rcnn.py", line 45, in createFasterRCNNGraph
    cv.dnn.writeTextGraph(modelPath, outputPath)
AttributeError: module 'cv2.dnn' has no attribute 'writeTextGraph'
`.

Also, using `optimize_for_inference.py `, I produced the optimize version of my model but I encontered the same error again. I tried this commonds after using graph transformation tools in [OpenCv wiki page](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API) but error still remains. 


I used python 3 : 
`Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) 
[GCC 7.2.0] on linux
`

and opencv : 
`import cv2 as cv
>>> cv.__version__
'3.4.2'
`

**Comment by alalek** [comment]
> 3.4.2

The current version of 3.4 branch is 3.4.3-dev.
Wrong cv2 module is imported into Python.
Use 'cv.__file__' to confirm this and `PYTHONPATH` to fix (point to `<build>/lib/python3`).

**Comment by farshadopencv** [comment]
@alalek  Im confused a little. First I clone  3.4 branch and I build opencv by `git checkout 3.4` and cmake. then i update opencv-python on Anaconda using pip on win10 : `pip install opencv-python` and now:

 >>> import cv2 as cv
>>> cv.__file__
'C:\\Users\\ngm\\Anaconda3\\envs\\tensorflow1\\lib\\site-packages\\cv2.cp35-win_amd64.pyd'
>>> cv.__version__
'3.4.3'
>>>
 and  the error still remains :  ` module 'cv2.dnn' has no attribute 'writeTextGraph'`


should I use `git checkout 3.4.3`  instead of  `git checkout 3.4`   before building Opencv by cmake? whats wrong with me?

**Comment by dkurt** [comment]
@farshadopencv, you need to specify a path to cv2.so by `PYTHONPATH` environment variable:
for python2
```
export PYTHONPATH=/path/to/opencv/build/lib:$PYTHONPATH
```
for python3
```
export PYTHONPATH=/path/to/opencv/build/lib/python3:$PYTHONPATH
```

**Comment by alalek** [comment]
What is about `print(cv.getBuildInformation())` ? (like above)

> pip install opencv-python

This is non-official prebuilt binary packages. We don't maintain it: https://github.com/skvark/opencv-python
From OpenCV sources you built other binaries.

> git checkout 3.4.3

Use this to get samples which work with OpenCV 3.4.3

**Comment by farshadopencv** [comment]
@dkurt @alalek .Thank you so much. I updated opencv version to 
```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'3.4.3-dev
```
and I generated pbtxt file for my model. But still there is another issue: The following command con not detect any object in images:
`./example_dnn_object_detection --config=carmodelsfaster.pbtxt --model=carmodelsfaster.pb --width=300 --height=300 --scale=0.00784 --mean="127.5 127.5 127.5" --rgb --input=img2.jpg`  

If I remove arg `--scale=0.00784` it can detect some objects but now accuracy of detected objects and accuracy of rectangle boxes are very low. should I change any argument config in command?

**Comment by dkurt** [comment]
@farshadopencv, please keep both scripts and library from the same versions. Especially it's about dev states. 
If your `.pbtxt` file contains `Mul` and `Sub` nodes at the beginning, you do not need to specify mean and scale normalization.

**Comment by zhouteng** [comment]
@farshadopencv, I have the same error "module 'cv2.dnn' has no attribute 'writeTextGraph'", no matter I use "pip install" or compile the source codes 3.4.3 by myself. Could you please let me know how you solved this problem? Thanks!

**Comment by farshadopencv** [comment]
@zhouteng .Dont use pip for opencv at all! On obuntu 16.4,   First I cloned opencv master and then I used `git cheeckout 3.4`. then I made a virtual env and compile opencv with `cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_EXAMPLES=ON -DBUILD_LIST=dnn,ts,python2 .. && make -j4`. I followed the tutorial from [this link ](https://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/) for python opencv   and  problam disappeared. However, the accuracy of prediction is still very low.  Please let me know how is  the accuracy of your model  after solving this issue.

**Comment by dkurt** [comment]
@farshadopencv, do you use `faster_rcnn_inception_v2_coco_2018_01_28`? This models is tested in OpenCV. Please check [test_tf_importer.cpp](https://github.com/opencv/opencv/blob/3.4/modules/dnn/test/test_tf_importer.cpp):

https://github.com/opencv/opencv/blob/58ac3e09da332cd23126500b9e49059633522c5a/modules/dnn/test/test_tf_importer.cpp#L351-L378

**Comment by farshadopencv** [comment]
@dkurt faster_rcnn_inception_v2_coco_2018_01_28 pretrained model has very good performance  with openc object detection cpp.    I trained `faster_rcnn_inception_v2_coco_2018_01_28` on my own car plate number dataset with a high prediction accuracy. Also, using   tf_text_graph_faster_rcnn.py I generated .pbtxt file for my model. but the result of prediction is not good. As you said, my pbtxt file contains Mul and Sub nodes at the beginning and therefore, I removed  mean and scale normalization in command line. but this trick has no effect.

**Comment by farshadopencv** [comment]
@zhouteng  @dkurt 

Wow. I changed the image size `--width=300 --height=300 ` from 300*300 to 800*600 and now it works very  good.  According to faster_rcnn_inception_v2.config file, the min and max dimension for images should be 600 and 1024. My model now weorks very goog in this image size range. Thanks alot @dkurt  and @zhouteng  for help.

**Comment by zhouteng** [comment]
@farshadopencv, sure, sounds great!

**Comment by zhouteng** [comment]
@farshadopencv , no problem! sounds great!
