### ISSUE TITLE
Meta's Segment Anything with dnn

### ISSUE THREAD

**Issue by dkurt** [opencv/opencv#23470]
### Descripe the feature and motivation

A novel model with published trained weights https://github.com/facebookresearch/segment-anything.
- [x] Export model to ONNX. Need to export carefully. See [below](https://github.com/opencv/opencv/issues/23470#issuecomment-1506627997) for details.
- [x] Model can be imported with dnn. Requires a fix for Expand to support broadcast axis > 1.
- [x] Model can be inferred
- [ ] Compare accuracy with PyTorch
- [ ] Create a sample

**Comment by ShiqiYu** [comment]
@fengyuentau Can the ONNX model be imported into OpenCV Zoo, and run by OpenCV DNN?

**Comment by fengyuentau** [comment]
Thank you @dkurt and @ShiqiYu.  I will do these steps on my side. This model has great potential and it worths a position in our zoo.

**Comment by dkurt** [comment]
Great, @fengyuentau! I hope this activity will be interesting. Let me know if I could help with one the of the steps.

**Comment by itsvikash104** [comment]
@fengyuentau @ShiqiYu Let me know of any beginner tasks that might be involved in this feature.

**Comment by fengyuentau** [comment]
@ShiqiYu @dkurt  Updates on my side:

- [x] Export model to ONNX. Link to models: https://drive.google.com/drive/folders/110JBApuq0_37C0gTlMzqs9B3var2oCGY?usp=sharing
- [ ] Model can be imported with dnn. All the exported ONNX model cannot be loaded with dnn. Some operators are not supported under various conditions, such as Expand with unknown shape input, Where (completely unsupported).
- [ ] Model can be inferred
- [ ] Compare accuracy with PyTorch
- [ ] Create a sample

Regarding the import problem, I am going to try:

- Simplify with `onnxsim`, then retry loading.
- Look into the model structure to see whether it can be split into multiple sub models, then simplify each one.
- Submit patches to support operators (it takes more effort than the previous two possible solutions).

Will update soon.

**Comment by dkurt** [comment]
@fengyuentau, thank you! May I ask add a code snippet to generate ONNX files?

**Comment by fengyuentau** [comment]
Looks like we still need the support of Where operator. Ping @zihaomu 

![image](https://user-images.githubusercontent.com/17219438/231385367-6cbb71e1-10d7-4c73-a0ac-b1fb5e36783d.png)

**Comment by fengyuentau** [comment]
Tried again with:

1. SAM with fixed input shape (basically remove dynamic_axes when exporting to ONNX in the script).
2. simplify the above model.

It fails at Expand. I will have a look into the problem. Models are uploaded to the above GDrive link.

**Comment by zihaomu** [comment]
The `where` layer will be supported at this PR:https://github.com/opencv/opencv/pull/23485

**Comment by fengyuentau** [comment]
> It fails at Expand

Another update:

The Expand can be fixed but the model contains a Slice with dynamic input `ends`, which cannot be supported in the current dnn engine. However, we could try split the model to avoid this issue. Note that `orig_im_size` is used only for post processing, and can be implemented seperately.

![image](https://user-images.githubusercontent.com/17219438/231688517-29d22616-e28d-4f98-94c8-880b9454b942.png)

**Comment by fengyuentau** [comment]
Looks like this model is much more complicated than I thought. Image needs to be pre-processed with another model to get embeddings for the input of SAM.

Now looking into the model for pre-processings ...

**Comment by zihaomu** [comment]
Update: the `where node` is mereged at https://github.com/opencv/opencv/pull/23485

**Comment by stuz5000** [comment]
Oh -- SAM looks pretty neat. It seems like I should be able to get something like a semantic embedding vector for each segment out of this model too, but its not clear how (e.g. a descriptor of what each segment component is). I see

```
#1x256x64x64 tensor    0..255 segments??
SamPredictor.features = model.image_encoder(input_image)
```

Can this be used to cluster segments by their semantic content? Or track (find similar) segments between video frames?

**Comment by fengyuentau** [comment]
@stuz5000 the `image_encoder` is used to extract features from an input image and then the features become the input of SAM. So it is not something you expect if you want [num_seg, feature_seg].

**Comment by AbsurdePhoton** [comment]
Hey, I'd really like to be able to use this model with opencv.

Any progress since may ?

**Comment by fengyuentau** [comment]
@AbsurdePhoton SAM already works with opencv if you use the ones exported by me. `sam_vit_b.fixed.nopost.sim.onnx` and `sam_encoder_vit_b.sim.onnx` from [this link](https://drive.google.com/drive/folders/110JBApuq0_37C0gTlMzqs9B3var2oCGY?usp=sharing).

**Comment by AbsurdePhoton** [comment]
Thanks. Is sam_encoder_vit_b.sim.onnx the preprocess step for the image, and sam_vit_b.fixed.nopost.sim.onnx SAM itself ?

Did you publish some code yet ? I work with C++ but python would also be nice to understand exactly how to the models.

**Comment by fengyuentau** [comment]
> Is sam_encoder_vit_b.sim.onnx the preprocess step for the image, and sam_vit_b.fixed.nopost.sim.onnx SAM itself ?

Yes, you are right.

---

Unfortunately I do not have code for SAM encoder / SAM inference. You can take a look at the official repo to find some clues.

**Comment by LaurentBerger** [comment]
> Unfortunately I do not have code for SAM encoder / SAM inference. You can take a look at the official repo to find some clues.

I have got the code but encoder is  quite good :relative to onnx inference (sam_encoder_vit_b_sim.onnx) : 
```
Quadratic error  6.0651753e-05
Max error  0.19099993 

```

but decoding mask is not good at all... still working on it

**Comment by AbsurdePhoton** [comment]
I figured out the code for the encoder... It's pretty straightforward, and I fed the result to SAM itself.

Now the big part is SAM's output. I successfully tried a test inference - apart from the encoder part, these were random values, for now. All went well, no error from OpenCV.

Now like you @LaurentBerger, I have to figure out the rest.

The masks should be low-res, look out the output layer's name: "low_res_masks" :)

**Comment by LaurentBerger** [comment]
Something is weird in model sam_vit_b.fixed.nopost.sim.onnx

My code

```
import numpy as np
import cv2 as cv
image_org = cv.imread(cv.samples.findFile("classroom__rgb_00283_1024.png"))

# ENCODER MODEL 
encoder_name = "sam_encoder_vit_b_sim.onnx"
net_encoder = cv.dnn.readNet(encoder_name)
paramSAMEncoder = cv.dnn.Image2BlobParams()
paramSAMEncoder.datalayout = cv.dnn.DNN_LAYOUT_NCHW
paramSAMEncoder.ddepth = cv.CV_32F
paramSAMEncoder.mean = (0, 0, 0)
paramSAMEncoder.scalefactor = (1, 1, 1)
paramSAMEncoder.size = (1024, 1024)
paramSAMEncoder.swapRB = True
paramSAMEncoder.paddingmode = cv.dnn.DNN_PMODE_NULL;
blobOpencv = cv.dnn.blobFromImageWithParams(image_org, paramSAMEncoder)

net_encoder.setInput(blobOpencv)
img_encoded = net_encoder.forward()

# PREPARE MASK DATA
input_point = np.array([[540, 224], [736, 506]], dtype=np.float32 )
input_label = np.array([2, 3,], dtype=np.float32)

coord = np.concatenate([input_point, np.zeros((3,2))], axis=0)[None, :, :]
label = np.concatenate([input_label, -np.ones((3))], axis=0)[None, :]
# Create an empty mask input and an indicator for no mask.
mask_input = np.zeros((1, 1, 256, 256), dtype=np.float32)
has_mask_input = np.zeros((1), dtype=np.float32)

#DECODING WITH OPENCV USING MODEL GIVEN IN OPENCV ISSUE 23470
decoder_name =  "sam_vit_b.fixed.nopost.sim.onnx"
net_decoder = cv.dnn.readNet(decoder_name)
net_decoder.setInput(img_encoded, "image_embeddings")
net_decoder.setInput(cv.Mat(coord), "point_coords")
net_decoder.setInput(label, "point_labels")
net_decoder.setInput(mask_input, "mask_input")
net_decoder.setInput(has_mask_input, "has_mask_input")
net_decoder.setPreferableBackend(cv.dnn.DNN_BACKEND_OPENCV)
net_decoder.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)

decoder_ocv = net_decoder.forward(["iou_predictions", "low_res_masks"])
print("confidence scores ",decoder_ocv[0]) 
for idx in range(decoder_ocv[1].shape[1]):
    mask = decoder_ocv[1][0,idx] > 0
    mask = cv.resize(mask.astype(np.uint8), image_org.shape[:2], cv.INTER_NEAREST )
    image2 = image_org.copy()
    image_m = image2.copy()
    image2 = (image2/3).astype(np.uint8)
    cv.copyTo(image_m, mask.astype(np.uint8), image2)
    cv.imshow("Inference" + str(idx), image2)
cv.waitKey()

cv.destroyAllWindows()
```

Image used
![classroom__rgb_00283_1024](https://github.com/opencv/opencv/assets/3591626/cf7ba78a-3f95-40ca-be51-b8527d7b044a)


and one result
![image](https://github.com/opencv/opencv/assets/3591626/d2b0f282-58d5-4d69-a326-295ad0bcf071)

**Comment by AbsurdePhoton** [comment]
I didn't go as far as you for the moment, still struggling to decode the output in C++...
I'll try your code tonight and see if I have an idea.
First thinking, looking at he scattered pixels of the mask: for the encoder part, is the mean (0,0,0) ? it could have an impact if it is not that value.

**Comment by AbsurdePhoton** [comment]
@LaurentBerger - This line doesn't work for me:
`net_decoder.setInput(cv.Mat(coord), "point_coords")`
-> AttributeError: module 'cv2' has no attribute 'mat'

I tried to replace with
`net_decoder.setInput(coord, "point_coords")`
the forward crashes

I barely know python, what's happening ? I'm using python 3.10

**Comment by LaurentBerger** [comment]
use latest  opencv-python version (should work with >4.6)

**Comment by fengyuentau** [comment]
Although many things can go wrong, one thing I would like to point out is I manually extract `Einsum` operator to several operators (matmul, transpose, ...) for the reason that `Einsum` is unsupported in dnn. That manual extraction can be wrong and I did not verify the correctness of output between the original one (with `Einsum`) and mine (with `Einsum` extracted) using onnxruntime.

Good news is there is already a pull request for the support of `Einsum` https://github.com/opencv/opencv/pull/24037.

**Comment by LaurentBerger** [comment]
> I didn't go as far as you for the moment, still struggling to decode the output in C++...

  ```
  string defaultDir("c:/users/laurent/desktop/segment-anything/");
    String modelPath(defaultDir + "sam_encoder_vit_b_sim.onnx");
    cout << getBuildInformation() << endl;
    cout << "Reading sam_vit_b.fixed.nopost.sim.onnx\n";
    //Net netMask = readNet(defaultDir + "sam_vit_b.fixed.nopost.sim.onnx");
    Net netMask = readNet(defaultDir + "sam_vit_b.fixed.nopost.sim.onnx");
    Mat image = imread(samples::findFile("c:/users/laurent/desktop/adabins_kitty/classroom__rgb_00283_1024.png"));
    Image2BlobParams paramSAMEncoder;
    paramSAMEncoder.datalayout = DNN_LAYOUT_NCHW;
    paramSAMEncoder.ddepth = CV_32F;
    paramSAMEncoder.mean = Scalar(0, 0, 0);
    paramSAMEncoder.scalefactor = Scalar(1, 1, 1);
    paramSAMEncoder.size = Size(1024, 1024);
    paramSAMEncoder.swapRB = true;
    paramSAMEncoder.paddingmode = DNN_PMODE_NULL;
    Mat blobOpencv = blobFromImageWithParams(image, paramSAMEncoder);
    Net netEncoder = readNet(modelPath);
    netEncoder.setInput(blobOpencv);
    cout << "Inference sam_encoder_vit_b_sim.onnx\n";
    Mat encoderOutput = netEncoder.forward();
    netMask.setInput(encoderOutput, "image_embeddings");
    Mat inputPoint = (Mat_<float>(5, 2) << 590, 620, 0, 0, 0, 0, 0, 0, 0, 0);
    vector<int> dimPoint{ 1, 5, 2 };
    Mat blobPoint = inputPoint.reshape(1, dimPoint);

    netMask.setInput(blobPoint, "point_coords");
    Mat blobLabel(1, 5, CV_32FC1, Scalar(-1));
    blobLabel.at<float>(0, 0) = 1;
    netMask.setInput(blobLabel, "point_labels");
    displayBlobSize(blobLabel, "point_labels ");


    Mat maskInput(vector<int> {1, 1, 256, 256}, CV_32FC1);
    netMask.setInput(maskInput, "mask_input");
    displayBlobSize(maskInput, "maskInput ");

    Mat hasMaskInputMat(vector<int> {1}, CV_32FC1, Scalar::all(0));
    netMask.setInput(hasMaskInputMat, "has_mask_input");
    vector<Mat> blobOut(2);
    const vector<string> outputName{ "iou_predictions", "low_res_masks" };
    netMask.setPreferableBackend(DNN_BACKEND_OPENCV);
    netMask.setPreferableTarget(DNN_TARGET_CPU);
    netMask.forward(blobOut, outputName);
    displayBlobSize(blobOut[0], "iou_predictions");
    cout << "iou_predictions" << blobOut[0] << endl;
    displayBlobSize(blobOut[1], "low_res_masks");
    Mat img;
    image.copyTo(img);
    img = img / 3;
    Mat x = blobOut[1].reshape(1, vector<int>{4, 256 * 256});
    vector<Mat> y(3);
    y[0] = x.row(0).reshape(0, 256);
    y[1] = x.row(1).reshape(0, 256);
    y[2] = x.row(2).reshape(0, 256);
    Mat mask;
    imshow("Original", image);
    y[0].convertTo(mask, CV_8U);
    resize(mask, mask, Size(1024, 1024));
    imshow("Mask", mask * 255);
    y[1].convertTo(mask, CV_8U);
    resize(mask, mask, Size(1024, 1024));
    imshow("Mask1", mask * 255);
    y[2].convertTo(mask, CV_8U);
    resize(mask, mask, Size(1024, 1024));
    imshow("Mask2", mask * 255);
    waitKey();

```

**Comment by LaurentBerger** [comment]
```
# https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/modeling/sam.py#L27-L28
paramSAMEncoder.mean = (123.675, 116.28, 103.53)
paramSAMEncoder.scalefactor = (1/58.395, 1/57.12, 1/57.375 )

```

**Comment by AbsurdePhoton** [comment]
Yay, better isn't it :)

This is the kind of result I already got with Mask-RCNN, the difference is that we have here a resolution of 256x256, with Mask-RCNN it's 15x15, so the resolution is ~17x better.

I already made a masking utility that computes the mask with Mask-RCNN and feeds it to a classic grabcut algorithm, or trimap, with a manual input. I'll try to replace Mask-RCNN with SAM and see if it is really better at this stage.
