### PR TITLE
 Generate shallow bundle structure for iOS framework to resolve Xcode build errors

### LINKED ISSUE #28170: [iOS] expected Info.plist at the root level since the platform uses shallow bundles
Hello,

I'm working with the opencv-4.12.0-ios-framework.zip and encountering a compilation error in my iOS project:

```
Framework /Users/xxx/Library/Developer/Xcode/DerivedData/Runner-catkfxjjmttbpobgigkxyalkswni/Build/Products/Debug-iphoneos/Runner.app/Frameworks/opencv2.framework contains Versions/Current/Resources/Info.plist, expected Info.plist at the root level since the platform uses shallow bundles
```
As I understand, iOS now requires frameworks to be structured as `shallow bundles`. Could you please advise if this is related to how I'm using the framework, or if there's a recommended way to resolve this?

Thank you for your time and assistance.

Xcode Version 26.1.1 (17B100)

### PR DESCRIPTION
**Pull request by satyam102006**
### Summary
This PR modifies the iOS framework build script (`platforms/ios/build_framework.py`) to generate a **Shallow Bundle** structure instead of a Deep Bundle structure. This ensures compatibility with modern Xcode versions (Xcode 15/16+) and resolves build errors related to `Info.plist` placement.

### Problem
Currently, the build script creates a "Deep Bundle" structure (standard for macOS), placing the binary and `Info.plist` inside `Versions/A/`.
When using the generated framework in recent iOS projects, Xcode fails with the error:
> `expected Info.plist at the root level since the platform uses shallow bundles`

### Solution
* Updated `platforms/ios/build_framework.py` to stop creating the `Versions/A` directory hierarchy.
* The binary, `Info.plist`, `Headers`, and `Modules` are now placed directly at the root of the `.framework` folder.
* Removed unneeded symlink creation logic for `Versions/Current`.

### Changes
- Modified `makeFramework` method in `platforms/ios/build_framework.py`.
- Changed destination directory `dstdir` to point to the framework root.
- Updated `Info.plist` copy logic to target the root directory.

### Related Issue
Fixes #28170

### CODE REVIEW

**Comment by satyam102006** [comment]
Hi @asmorkalov , it looks like the `Ubuntu2404-ARM64-Debug` check failed due to an infrastructure timeout (403 Forbidden on artifact upload), which seems unrelated to my changes.


 Thanks!

**Comment by satyam102006** [comment]
@asmorkalov can you check

**Comment by vulinhnopro2704** [comment]
Hi @asmorkalov, could you please share a bit of context on why this PR was closed? Was this approach rejected, or is there an alternative plan for this issue? Thank you!

I am still getting this error in OpenCV 5 when building using platforms/apple/build_xcframework.py. The result is not a shallow bundle, so it gets rejected when I build the IPA in Xcode 26. I only target iOS Mobile, not other platforms.

Based on Apple's official documentation on [Placing content in a bundle](https://developer.apple.com/documentation/bundleresources/placing-content-in-a-bundle), a shallow bundle is strictly required for iOS frameworks (no Versions folder, with Info.plist placed at the root of the .framework folder).
