### ISSUE TITLE
OpenCV3.1 cannot build on OSX 10.12 because of 'opencv2/highgui.hpp' file not found

### ISSUE THREAD

**Issue by gregorypierce** [opencv/opencv#7147]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => OSX 10.12
- Compiler => Command line cmake / make -j4

##### Detailed description

When attempting to build on OSX 10.12 several issues are encountered. The first comes from QTKit, but that can be avoided by adding the flag - "-D BUILD_opencv_videoio=OFF". The next comes while building and refers to opencv2/highgui.hpp not being found.

[ 67%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/inpainting.cpp.o
/projects/opencv_contrib/modules/xphoto/src/inpainting.cpp:61:10: fatal error: 'opencv2/highgui.hpp' file not found
#include "opencv2/highgui.hpp"

##### Steps to reproduce

Pull source for 3.1.

cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D PYTHON3_PACKAGES_PATH=~/.virtualenvs/cv3/lib/python3.5/site-packages -D PYTHON3_LIBRARY=/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib -D PYTHON3_INCLUDE_DIR=/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/include/python3.5m -D PYTHON3_NUMPY_INCLUDE_DIRS=~/.virtualenvs/cv3/lib/python3.5/site-packages/numpy/core/include -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D BUILD_opencv_python3=ON -D OPENCV_EXTRA_MODULES_PATH=/projects/opencv_contrib/modules -D BUILD_opencv_videoio=OFF ..

make -j4

Specifically the configuration as identified by the tool is:
```
-- General configuration for OpenCV 3.1.0 =====================================
--   Version control:               3.1.0
--
--   Platform:
--     Host:                        Darwin 16.0.0 x86_64
--     CMake:                       3.6.1
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               RELEASE
--
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /Users/gpierce/Downloads/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 8.0.0.8000036)
--     C++ flags (Release):         -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /Users/gpierce/Downloads/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):
--     Linker flags (Debug):
--     Precompiled headers:         NO
--     Extra dependencies:          -framework OpenCL
--     3rdparty dependencies:       zlib libjpeg libwebp libpng libtiff libjasper IlmImf libprotobuf
--
--   OpenCV modules:
--     To be built:                 core flann imgproc ml objdetect photo reg surface_matching video xphoto bioinspired dnn dpm face features2d fuzzy imgcodecs shape superres calib3d ccalib stitching videostab aruco python3
--     Disabled:                    videoio world contrib_world
--     Disabled by dependency:      highgui ts bgsegm line_descriptor optflow plot rgbd saliency stereo structured_light text tracking xfeatures2d ximgproc xobjdetect datasets
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 viz cvv hdf matlab sfm
--
--   GUI:
--     QT:                          NO
--     Cocoa:                       YES
--     OpenGL support:              NO
--     VTK support:                 NO
--
--   Media I/O:
--     ZLib:                        build (ver 1.2.8)
--     JPEG:                        build (ver 90)
--     WEBP:                        build (ver 0.3.1)
--     PNG:                         build (ver 1.6.19)
--     TIFF:                        build (ver 42 - 4.0.2)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 1.7.1)
--     GDAL:                        NO
--
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  NO
--     FFMPEG:                      YES
--       codec:                     YES (ver 57.48.101)
--       format:                    YES (ver 57.41.100)
--       util:                      YES (ver 55.28.100)
--       swscale:                   YES (ver 4.1.100)
--       resample:                  YES (ver 3.0.0)
--       gentoo-style:              YES
--     GStreamer:                   NO
--     OpenNI:                      NO
--     OpenNI PrimeSensor Modules:  NO
--     OpenNI2:                     NO
--     PvAPI:                       NO
--     GigEVisionSDK:               NO
--     QuickTime:                   NO
--     QTKit:                       YES
--     V4L/V4L2:                    NO/NO
--     XIMEA:                       NO
--     gPhoto2:                     NO
--
--   Parallel framework:            GCD
--
--   Other third-party libraries:
--     Use IPP:                     9.0.1 [9.0.1]
--          at:                     /projects/opencv/3rdparty/ippicv/unpack/ippicv_osx
--     Use IPP Async:               NO
--     Use VA:                      NO
--     Use Intel VA-API/OpenCL:     NO
--     Use Eigen:                   YES (ver 3.2.9)
--     Use Cuda:                    NO
--     Use OpenCL:                  YES
--     Use custom HAL:              NO
--
--   OpenCL:
--     Version:                     static
--     libraries:                   -framework OpenCL
--     Use AMDFFT:                  NO
--     Use AMDBLAS:                 NO
--
--   Python 2:
--     Interpreter:                 /usr/local/bin/python2.7 (ver 2.7.11)
--
--   Python 3:
--     Interpreter:                 /Users/gpierce/.virtualenvs/cv3/bin/python3 (ver 3.5.1)
--     Libraries:                   /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib (ver 3.5.1)
--     numpy:                       /Users/gpierce/.virtualenvs/cv3/lib/python3.5/site-packages/numpy/core/include (ver 1.11.1)
--     packages path:               /Users/gpierce/.virtualenvs/cv3/lib/python3.5/site-packages
--
--   Python (for build):            /usr/local/bin/python2.7
--
--   Java:
--     ant:                         NO
--     JNI:                         /Users/gpierce/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Users/gpierce/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Users/gpierce/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers
--     Java wrappers:               NO
--     Java tests:                  NO
--
--   Matlab:                        Matlab not found or implicitly disabled
--
--   Documentation:
--     Doxygen:                     NO
--     PlantUML:                    NO
--
--   Tests and samples:
--     Tests:                       NO
--     Performance tests:           NO
--     C/C++ Examples:              YES
--
--   Install path:                  /usr/local
--
--   cvconfig.h is in:              /projects/opencv/build
-- -----------------------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/opencv/build
```

**Comment by StevenPuttemans** [comment]
Hi there!

First of all, questions like this will likely be solved much faster when addressed at http://answers.opencv.org/questions!

As to your problem

>> The first comes from QTKit, but that can be avoided by adding the flag - "-D BUILD_opencv_videoio=OFF".

That is a very bad practice because you are disabling one of the main modules of OpenCV, leaving you with an installation not being able to open video files and such. Better is to disable QT support by adding `-D WITH_QT=OFF`.

As to the second error, I am not able to reproduce this, building OpenCV on Ubuntu, latest master branch. Are you sure that both opencv repo and opencv_contrib repo are in sync? So the latest possible master pull of that repo?

**Comment by StevenPuttemans** [comment]
Ow the solution is simple after looking at your CMAKE output!

```
--   OpenCV modules:
--     To be built:                 core flann imgproc ml objdetect photo reg surface_matching video xphoto bioinspired dnn dpm face features2d fuzzy imgcodecs shape superres calib3d ccalib stitching videostab aruco python3
--     Disabled:                    videoio world contrib_world
--     Disabled by dependency:      highgui ts bgsegm line_descriptor optflow plot rgbd saliency stereo structured_light text tracking xfeatures2d ximgproc xobjdetect datasets
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java python2 viz cvv hdf matlab sfm
```

By disabling the videoio module, you are disabling highgui and several other core libraries from OpenCV because they depend on the videoio module. This results in xphoto not being able to built, simply because it depends on highgui which was disabled also! So please adjust your command like suggested.

As a small bug, we could state that xphoto should have a dependency on highgui, which it seems to have not, because it is not disabled by dependency! I will see if I can create a pullrequest for that!

**Comment by lucadigiammarino** [comment]
Hi @gregorypierce  I'd like to know if you solved your problem, because I am having the same errors here. If I disable opencv_videoio I got errors on highgui.hpp and vice-versa. 

Please let me know if you solved it, please.

Thank you

**Comment by StevenPuttemans** [comment]
@lucadigiammarino did you actually read the solution that fixed it all? Disabling videoio is not a good idea due to dependencies. Also if you grab the latest OpenCV master branch, it should build without problems.

**Comment by romeoyacobs** [comment]
Hi, guys! Is there a solution for all this problems?
I have WITH_QT=OFF, but if I'm not disabling videoio i get:

[ 47%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o
~/Applications/opencv-3.1.0/modules/videoio/src/cap_qtkit.mm:46:9: fatal error: 
      'QTKit/QTKit.h' file not found
#import <QTKit/QTKit.h>

If I disable videoio, I get the same the same error with highgui:

[ 67%] Building CXX object modules/xphoto/CMakeFiles/opencv_xphoto.dir/src/inpainting.cpp.o
~/opencv_contrib/modules/xphoto/src/inpainting.cpp:61:10: fatal error: 'opencv2/highgui.hpp' file not found

To build opencv with nonfree on MacOS 10.12 is a total disaster :(

**Comment by alalek** [comment]
> opencv-3.1.0

@romeoyacobs You need to get the latest code from master branch (opencv_contrib too).
