### ISSUE TITLE
WHY cv2.imshow DOES NOT WORK ON UBUNTU 18.04 WITH ANACONDA ?

### ISSUE THREAD

**Issue by BryanWoo77** [opencv/opencv#14478]
```
import cv2
import numpy as np

img = cv2.imread('/home/user/Desktop/Pro/source/icon1.png')
print(np.shape(img))
cv2.imshow('asdfawe', img)
cv2.waitKey()
cv2.destroyAllWindows()
```

Why doesn't work this on ubuntu 18.04 with anaconda? I got a error like below:

`cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:632: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'`

I installed all lib, which are related to opencv. What is the problem here?

**Comment by alalek** [comment]
> Rebuild the library

You should ask Anaconda maintainers.
We don't support this package here.

> 3.4.2

You got some old package. It is really old (4 releases ago ~ 1 year).

---

As issue's template states, usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

**Comment by ashok3t** [comment]
Reproduced this issue with OpenCV 3.4.5 without Anaconda (just the C++ SDK).  imShow worked until I updated Ubuntu from 16.04 to 18.04.  The call stack shows that the overload of setWindowTitle for gtk is not being called although the cmake configuration finds the latest GTK that is installed.  The problem cannot be resolved by installing the libraries in the error message or gtk3.  The problem does not occur with OpenCV 4.1.0.  Note that I am not building with Qt.

**Comment by krikru** [comment]
[This](https://stackoverflow.com/a/51013434/1070480) is what solved the same problem on Ubuntu 18.04.2 LTS for me.

**Comment by hg2051** [comment]
It's because of ''opencv-python-headless". Uninstall it!

**Comment by Axel-Erfurt** [comment]
> It's because of ''opencv-python-headless". Uninstall it!

cv2.imread will then no longer work.

**Comment by lvZic** [comment]
> Reproduced this issue with OpenCV 3.4.5 without Anaconda (just the C++ SDK). imShow worked until I updated Ubuntu from 16.04 to 18.04. The call stack shows that the overload of setWindowTitle for gtk is not being called although the cmake configuration finds the latest GTK that is installed. The problem cannot be resolved by installing the libraries in the error message or gtk3. The problem does not occur with OpenCV 4.1.0. Note that I am not building with Qt.

version 4.x worked

**Comment by kirisakow** [comment]
```sh
python3 -m pip uninstall opencv-python-headless

python3 -m pip install --upgrade opencv-python
```
