### ISSUE TITLE
How to access detail_ImageFeatures.keypoint correctly in python?

### ISSUE THREAD

**Issue by f-sky** [opencv/opencv#16371]
I'm trying to use class ImageFeatures in python, but I cannot access keypoint attribute in cv2.detail_ImageFeatures. What should I do?
I'm working on MacOS with python 3.7 and opencv-python 4.1.2.30
Here is my code:
```python
import cv2
In[1]: cv2.detail_ImageFeatures().getKeypoints
Out[1]:<function detail_ImageFeatures.getKeypoints>
In[2]: cv2.detail_ImageFeatures().keypoints
Out[2]: AttributeError: 'cv2.detail_ImageFeatures' object has no attribute 'keypoints'

```

**Comment by alalek** [comment]
It is a method: `.getKeypoints()`
