### PR TITLE
cmake: fix lapack

### LINKED ISSUE #7970: libopencv_core.so.3.2.0: undefined reference to `dpotrf_'
I'm installing opencv 3.2 and when I use :+1: 
cmake -DWITH_QT=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON ..

and 

make -j4  , this error is showing , how can be solved ?

[ 75%] Linking CXX executable ../../bin/opengl-example-opengl_interop
../../lib/libopencv_core.so.3.2.0: undefined reference to `dpotrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgesv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgels_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgesv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sposv_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgetrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgetrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgels_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgeqrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `spotrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgeqrf_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `sgesdd_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dgesdd_'
../../lib/libopencv_core.so.3.2.0: undefined reference to `dposv_'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opencv_version] Error 1
make[1]: *** [apps/version/CMakeFiles/opencv_version.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 75%] Built target opencv_annotation
[ 75%] Built target opencv_visualisation
[ 75%] Built target example_opengl_opengl_interop

### PR DESCRIPTION
**Pull request by alalek**
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/944

resolves #7970

- added compile check with multiple tries for different configurations
- restored find_package(LAPACK)
- avoided modification of OPENCV_LINKER_LIBS

OpenBLAS from Ubuntu 14.04 doesn't support some functions like `sposv_`. But it works fine in Ubuntu 16.04.
Also there is some problem with Atlas detection on Ubuntu 14.04 (liblapack.so: undefined reference to `ATL_chemv').

To resolve this problem compilation check was added.
Also multiple tries was implemented for different LAPACK implementations.

CMake logs examples:
- Ubuntu 14.04:
```
-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- LAPACK(OpenBLAS): LAPACK_LIBRARIES: /usr/lib/libopenblas.so
-- LAPACK(OpenBLAS): Can't build LAPACK check code. This LAPACK version is not supported.
-- Found Atlas: /usr/include  
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- LAPACK(Atlas): LAPACK_LIBRARIES: /usr/lib/liblapack.so;/usr/lib/libcblas.so;/usr/lib/libatlas.so
-- LAPACK(Atlas): Can't build LAPACK check code. This LAPACK version is not supported.
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- LAPACK(LAPACK/Generic): LAPACK_LIBRARIES: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- LAPACK(LAPACK/Generic): Support is enabled.
```
- Ubuntu 16.04:
```
-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- LAPACK(OpenBLAS): LAPACK_LIBRARIES: /usr/lib/libopenblas.so
-- LAPACK(OpenBLAS): Support is enabled.
```
- Linux with Intel MKL:
```
-- Found MKL 2017.0.1 at: /opt/intel/mkl
-- LAPACK(MKL): LAPACK_LIBRARIES: /opt/intel/mkl/lib/intel64/libmkl_core.so;/opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_sequential.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;/opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_sequential.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;/opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_sequential.so;-lpthread;-lm;-ldl
-- LAPACK(MKL): Support is enabled.
```
- Windows with Intel MKL:
```
-- Found MKL 2017.0.1 at: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl
-- LAPACK(MKL): LAPACK_LIBRARIES: C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_core.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_intel_lp64.lib;C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64/mkl_sequential.lib
-- LAPACK(MKL): Support is enabled.
```
- MacOS X
```
-- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
-- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
-- Could NOT find Atlas (missing:  Atlas_CBLAS_INCLUDE_DIR Atlas_CLAPACK_INCLUDE_DIR Atlas_BLAS_LIBRARY) 
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- LAPACK(LAPACK/Apple): LAPACK_LIBRARIES: /System/Library/Frameworks/Accelerate.framework;/System/Library/Frameworks/Accelerate.framework
-- Looking for Accelerate/Accelerate.h
-- Looking for Accelerate/Accelerate.h - found
-- Looking for Accelerate/Accelerate.h
-- Looking for Accelerate/Accelerate.h - found
-- LAPACK(LAPACK/Apple): Support is enabled.
```

### CODE REVIEW

**Comment by alalek** [comment]
:+1:
