### ISSUE TITLE
DNN: Test_ONNX_nets.ResNet101_DUC_HDC regression (3.4.10 release)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#20777]
Caused by #16738: https://github.com/opencv/opencv/blame/3.4.10/modules/dnn/src/onnx/onnx_importer.cpp#L527

```
[ RUN      ] Test_ONNX_nets.ResNet101_DUC_HDC/2, where GetParam() = OCV/CPU
[ INFO:0] DNN/ONNX: loading ONNX v3 model produced by ''. Number of nodes = 355, inputs = 540, outputs = 1
[ERROR:0] DNN/ONNX: ERROR during processing node with 4 inputs and 1 outputs: [Sum]:(fc1_cityscapes)
[ INFO:0]     Input[0] = 'fc1_cityscapes_c0'
[ INFO:0]     Input[1] = 'fc1_cityscapes_c1'
[ INFO:0]     Input[2] = 'fc1_cityscapes_c2'
[ INFO:0]     Input[3] = 'fc1_cityscapes_c3'
[ INFO:0]     Output[0] = 'fc1_cityscapes'
unknown file: Failure
C++ exception with description "OpenCV(3.4.15) /home/alalek/projects/opencv/dev/modules/dnn/src/onnx/onnx_importer.cpp:1953: error: (-2:Unspecified error) in function 'handleNode'
> Node [Sum]:(fc1_cityscapes) parse error: OpenCV(3.4.15) /home/alalek/projects/opencv/dev/modules/dnn/src/onnx/onnx_importer.cpp:772: error: (-2:Unspecified error) in function 'void cv::dnn::experimental_dnn_34_v22::ONNXImporter::handleNode(const opencv_onnx::NodeProto&)'
> >  (expected: 'node_proto.input_size() == 2'), where
> >     'node_proto.input_size()' is 4
> > must be equal to
> >     '2' is 2
> " thrown in the test body.
[  FAILED  ] Test_ONNX_nets.ResNet101_DUC_HDC/2, where GetParam() = OCV/CPU (1435 ms)
```

Command:

```
./bin/opencv_test_dnn --test_tag_enable=mem_6gb,verylong,debug_verylong --gtest_filter=Test_ONNX_nets.ResNet101_DUC_HDC*
```
