### ISSUE TITLE
compile with intel computer_vision_sdk_2018.5.445 failed

### ISSUE THREAD

**Issue by juxiangwu** [opencv/opencv#13529]
```
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp: In member function ‘virtual cv::Ptr<cv::dnn::dnn4_v20181221::BackendNode> cv::dnn::ConvolutionLayerImpl::initInfEngine(const std::vector<cv::Ptr<cv::dnn::dnn4_v20181221::BackendWrapper> >&)’:
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:528:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_kernel’; did you mean ‘_kernel_x’?
         ieLayer->_kernel.insert(InferenceEngine::X_AXIS, kernel.width);
                  ^~~~~~~
                  _kernel_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:528:50: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_kernel.insert(InferenceEngine::X_AXIS, kernel.width);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:529:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_kernel’; did you mean ‘_kernel_x’?
         ieLayer->_kernel.insert(InferenceEngine::Y_AXIS, kernel.height);
                  ^~~~~~~
                  _kernel_x
```

<details>

/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp: In member function ‘virtual cv::Ptr<cv::dnn::dnn4_v20181221::BackendNode> cv::dnn::ConvolutionLayerImpl::initInfEngine(const std::vector<cv::Ptr<cv::dnn::dnn4_v20181221::BackendWrapper> >&)’:
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:528:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_kernel’; did you mean ‘_kernel_x’?
         ieLayer->_kernel.insert(InferenceEngine::X_AXIS, kernel.width);
                  ^~~~~~~
                  _kernel_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:528:50: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_kernel.insert(InferenceEngine::X_AXIS, kernel.width);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:529:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_kernel’; did you mean ‘_kernel_x’?
         ieLayer->_kernel.insert(InferenceEngine::Y_AXIS, kernel.height);
                  ^~~~~~~
                  _kernel_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:529:50: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_kernel.insert(InferenceEngine::Y_AXIS, kernel.height);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:530:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_stride’; did you mean ‘_stride_x’?
         ieLayer->_stride.insert(InferenceEngine::X_AXIS, stride.width);
                  ^~~~~~~
                  _stride_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:530:50: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_stride.insert(InferenceEngine::X_AXIS, stride.width);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:531:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_stride’; did you mean ‘_stride_x’?
         ieLayer->_stride.insert(InferenceEngine::Y_AXIS, stride.height);
                  ^~~~~~~
                  _stride_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:531:50: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_stride.insert(InferenceEngine::Y_AXIS, stride.height);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:532:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_padding’; did you mean ‘_padding_x’?
         ieLayer->_padding.insert(InferenceEngine::X_AXIS, pad.width);
                  ^~~~~~~~
                  _padding_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:532:51: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_padding.insert(InferenceEngine::X_AXIS, pad.width);
                                                   ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:533:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_padding’; did you mean ‘_padding_x’?
         ieLayer->_padding.insert(InferenceEngine::Y_AXIS, pad.height);
                  ^~~~~~~~
                  _padding_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:533:51: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_padding.insert(InferenceEngine::Y_AXIS, pad.height);
                                                   ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:534:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_pads_end’
         ieLayer->_pads_end.insert(InferenceEngine::X_AXIS, pad.width);
                  ^~~~~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:534:52: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_pads_end.insert(InferenceEngine::X_AXIS, pad.width);
                                                    ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:535:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_pads_end’
         ieLayer->_pads_end.insert(InferenceEngine::Y_AXIS, pad.height);
                  ^~~~~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:535:52: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_pads_end.insert(InferenceEngine::Y_AXIS, pad.height);
                                                    ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:536:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_dilation’; did you mean ‘_dilation_x’?
         ieLayer->_dilation.insert(InferenceEngine::X_AXIS, dilation.width);
                  ^~~~~~~~~
                  _dilation_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:536:52: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_dilation.insert(InferenceEngine::X_AXIS, dilation.width);
                                                    ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:537:18: error: ‘using element_type = class InferenceEngine::ConvolutionLayer {aka class InferenceEngine::ConvolutionLayer}’ has no member named ‘_dilation’; did you mean ‘_dilation_x’?
         ieLayer->_dilation.insert(InferenceEngine::Y_AXIS, dilation.height);
                  ^~~~~~~~~
                  _dilation_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:537:52: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_dilation.insert(InferenceEngine::Y_AXIS, dilation.height);
                                                    ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp: In member function ‘virtual cv::Ptr<cv::dnn::dnn4_v20181221::BackendNode> cv::dnn::DeConvolutionLayerImpl::initInfEngine(const std::vector<cv::Ptr<cv::dnn::dnn4_v20181221::BackendWrapper> >&)’:
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1757:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_kernel’; did you mean ‘_kernel_x’?
         ieLayer->_kernel.insert(InferenceEngine::X_AXIS, kernel.width);
                  ^~~~~~~
                  _kernel_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1757:50: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_kernel.insert(InferenceEngine::X_AXIS, kernel.width);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1758:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_kernel’; did you mean ‘_kernel_x’?
         ieLayer->_kernel.insert(InferenceEngine::Y_AXIS, kernel.height);
                  ^~~~~~~
                  _kernel_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1758:50: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_kernel.insert(InferenceEngine::Y_AXIS, kernel.height);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1759:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_stride’; did you mean ‘_stride_x’?
         ieLayer->_stride.insert(InferenceEngine::X_AXIS, stride.width);
                  ^~~~~~~
                  _stride_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1759:50: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_stride.insert(InferenceEngine::X_AXIS, stride.width);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1760:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_stride’; did you mean ‘_stride_x’?
         ieLayer->_stride.insert(InferenceEngine::Y_AXIS, stride.height);
                  ^~~~~~~
                  _stride_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1760:50: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_stride.insert(InferenceEngine::Y_AXIS, stride.height);
                                                  ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1761:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_padding’; did you mean ‘_padding_x’?
         ieLayer->_padding.insert(InferenceEngine::X_AXIS, pad.width);
                  ^~~~~~~~
                  _padding_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1761:51: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_padding.insert(InferenceEngine::X_AXIS, pad.width);
                                                   ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1762:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_padding’; did you mean ‘_padding_x’?
         ieLayer->_padding.insert(InferenceEngine::Y_AXIS, pad.height);
                  ^~~~~~~~
                  _padding_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1762:51: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_padding.insert(InferenceEngine::Y_AXIS, pad.height);
                                                   ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1763:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_pads_end’
         ieLayer->_pads_end.insert(InferenceEngine::X_AXIS, pad.width);
                  ^~~~~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1763:52: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_pads_end.insert(InferenceEngine::X_AXIS, pad.width);
                                                    ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1764:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_pads_end’
         ieLayer->_pads_end.insert(InferenceEngine::Y_AXIS, pad.height);
                  ^~~~~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1764:52: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_pads_end.insert(InferenceEngine::Y_AXIS, pad.height);
                                                    ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1765:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_dilation’; did you mean ‘_dilation_x’?
         ieLayer->_dilation.insert(InferenceEngine::X_AXIS, dilation.width);
                  ^~~~~~~~~
                  _dilation_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1765:52: error: ‘X_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_dilation.insert(InferenceEngine::X_AXIS, dilation.width);
                                                    ^~~~~~
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1766:18: error: ‘using element_type = class InferenceEngine::DeconvolutionLayer {aka class InferenceEngine::DeconvolutionLayer}’ has no member named ‘_dilation’; did you mean ‘_dilation_x’?
         ieLayer->_dilation.insert(InferenceEngine::Y_AXIS, dilation.height);
                  ^~~~~~~~~
                  _dilation_x
/opt/develop/computervision/sources/opencv/modules/dnn/src/layers/convolution_layer.cpp:1766:52: error: ‘Y_AXIS’ is not a member of ‘InferenceEngine’
         ieLayer->_dilation.insert(InferenceEngine::Y_AXIS, dilation.height);
                                                    ^~~~~~
modules/dnn/CMakeFiles/opencv_dnn.dir/build.make:619: recipe for target 'modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/convolution_layer.cpp.o' failed
make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/src/layers/convolution_layer.cpp.o] Error 1
CMakeFiles/Makefile2:3369: recipe for target 'modules/dnn/CMakeFiles/opencv_dnn.dir/all' failed

</details>

**Comment by juxiangwu** [comment]
cmake -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_CUDA=ON -DWITH_OPENCL=ON -DWITH_TBB=ON -DWITH_VIZ=ON -DBUILD_opencv_cudacodec=OFF  -DOPENCV_EXTRA_MODULES_PATH=/opt/develop/computervision/sources/opencv_contrib/modules -D CMAKE_BUILD_TYPE=RELEASE -D INSTALL_C_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D BUILD_opencv_python2=OFF -D CMAKE_INSTALL_PREFIX=$(python -c "import sys; print(sys.prefix)") -D PYTHON_EXECUTABLE=$(which python) -D PYTHON3_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -D PYTHON3_PACKAGES_PATH=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") -D WITH_EIGEN=ON -DBUILD_TIFF=ON -DWITH_INF_ENGINE=ON -DENABLE_CXX11=ON ..

**Comment by dkurt** [comment]
@juxiangwu, Could you please provide an output from CMake's summery related to Inference Engine?

```
--     Inference Engine:            YES (2018050000 / 1.5.0)
--                 libs:            /opt/intel/computer_vision_sdk_2018.5.445/deployment_tools/inference_engine/lib/ubuntu_16.04/intel64/libinference_engine.so
--             includes:            /opt/intel/computer_vision_sdk_2018.5.445/deployment_tools/inference_engine/include
```

**Comment by juxiangwu** [comment]
I have solved.Before compiling opencv from source,I have compiled and installed dldt,maybe comflit with intel computer vision sdk.After uninstalling dldt,it works! Thanks!
Here is my CMake's summary related to Inference Engine:
--     Inference Engine:            YES (2018050000 / 1.5.0)
--                 libs:            /opt/intel/computer_vision_sdk_2018.5.445/deployment_tools/inference_engine/lib/ubuntu_18.04/intel64/libinference_engine.so
--             includes:            /usr/local/include
