### PR TITLE
OCL: stop using of OpenCL without explicit UMat arguments

### LINKED ISSUE #4967: Facedetect does not detect any faces with OpenCL enabled
Transferred from http://code.opencv.org/issues/4275

```
|| Kevron Rees on 2015-04-13 00:16
|| Priority: Normal
|| Affected: branch 'master' (3.0-dev)
|| Category: ocl
|| Tracker: Bug
|| Difficulty: 
|| PR: 
|| Platform: x64 / Linux
```
## Facedetect does not detect any faces with OpenCL enabled

```
Using the following code, I can get detection to work if I turn off OpenCL.  However, with OpenCL on, I never get any faces.

<pre>
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

faceCascade = cv2.CascadeClassifier("/usr/share/OpenCV/haarcascades/haarcascade_frontalface_alt_tree.xml")

faces = []
img = None

def detectFaces():
    retval, img = cap.read()

    grayImg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


    faces = faceCascade.detectMultiScale(grayImg, 1.1, 2)
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

    cv2.imshow("Video", img)
    return faces

def testDetection():
    cv2.ocl.setUseOpenCL(False)
    while True:
        faces = detectFaces()
        if len(faces) > 0:
            print("face detected, punk")
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
</pre>

I've tried different cascades: frontfacial_defaul.xml and even lbpcascase_frontalface.xml with the same results.  OpenCL no work.  CPU-only, works.
```
##### Steven Puttemans on 2015-04-13 08:48

```
Might be a leap to far, but in order to get the CUDA implementation to work, we added a GPU specific model folder, since the GPU implementation only seems to work with those models.
Can you please try using one of those models?

For 2.4 branch https://github.com/Itseez/opencv/tree/2.4/data/haarcascades_GPU
For master branch https://github.com/Itseez/opencv/tree/master/data/haarcascades_cuda
-   Status changed from New to Open
```
##### Kevron Rees on 2015-04-13 19:32

```
Steven Puttemans wrote:
> Might be a leap to far, but in order to get the CUDA implementation to work, we added a GPU specific model folder, since the GPU implementation only seems to work with those models.
> Can you please try using one of those models?
> 
> For 2.4 branch https://github.com/Itseez/opencv/tree/2.4/data/haarcascades_GPU
> For master branch https://github.com/Itseez/opencv/tree/master/data/haarcascades_cuda

I do not have an nvidia GPU.  I'm using Intel graphics hence why i'm playing with OpenCL.  Do I still need GPU specific cascades?
```
##### Philip L on 2015-04-13 22:06

```
seems like the cpu models should be the correct ones
https://github.com/Itseez/opencv/commit/302a5adcc20d96720248c23719f33d3da72886b3
```
##### Kevron Rees on 2015-04-14 01:31

```
Philip L wrote:
> seems like the cpu models should be the correct ones
> https://github.com/Itseez/opencv/commit/302a5adcc20d96720248c23719f33d3da72886b3

Should I try these instead of the ones in master?
```
##### Philip L on 2015-04-14 19:24

```
no the ones in currently in the cascade folders are the correct ones for cpu and opencl thats what i just wanted to confirm.
```
##### Vadim Pisarevsky on 2015-04-27 11:14

```
-   Category set to ocl
```
##### Kevron Rees on 2015-05-26 22:05

```
Anyone been able to reproduce this?
```
##### Vadim Pisarevsky on 2015-05-29 15:52

```
face detection tests pass on my macbook pro with HD5200 running OSX and the live demo work well. We also run tests on AMD machine with discrete GPU. I know that other team runs it on Intel GPUs under Windows.

So - no, we are not able to reproduce it so far.  Try Windows if you have access to one. I know that Linux OpenCL drivers for Intel chips are rather fresh, may be it's drivers that are to blame.
```
##### Vadim Pisarevsky on 2015-05-29 15:53

```
face detection tests pass on my macbook pro with HD5200 running OSX and the live demo work well. We also run tests on AMD machine with discrete GPU. I know that other team runs it on Intel GPUs under Windows.

So - no, we are not able to reproduce it so far.  Try Windows if you have access to one. I know that Linux OpenCL drivers for Intel chips are rather fresh, may be it's drivers that are to blame.
-   Assignee set to Vadim Pisarevsky
```
##### Bruno Nascimento on 2015-06-12 14:36

```
Im actually having issues on opencl cascade lbp code.
I trained a LBP cascade, where sometimes the cascade gets "stuck" at one particular position. no matter what the image is after that, the detection is always there. 
someone else getting the issue?
this does not happen with opencl switched off.
im using a mac book pro, on windows x64. opencv 3.0.0
```

### LINKED ISSUE #4968: OpenCv3, OCL :  Assertion failed clEnqueueUnmapMemObject_pfn
Transferred from http://code.opencv.org/issues/4277

```
|| Thibault Lelore on 2015-04-13 17:57
|| Priority: Low
|| Affected: branch 'master' (3.0-dev)
|| Category: t-api
|| Tracker: Bug
|| Difficulty: Medium
|| PR: 
|| Platform: x86 / Windows
```
## OpenCv3, OCL :  Assertion failed clEnqueueUnmapMemObject_pfn

```
Hi!
I'm using latest version of opencv (3.0-dev git), and sometime my code throws an exception:
@OpenCV Error: Assertion failed (clEnqueueUnmapMemObject_pfn(q, (cl_mem)u->handle, data, 0, 0, 0) == 0) in cv::ocl::OpenCLAllocator::deallocate, file D:\XXX\modules\core\src\ocl.cpp, line 4446
exception caught: D:\XXX\modules\core\src\ocl.cpp:4446: error: (-215) clEnqueueUnmapMemObject_pfn(q, (cl_mem)u->handle, data, 0, 0, 0) == 0 in function cv::ocl::OpenCLAllocator::deallocate@

It seems to be related to ORB (OCL version)... I first compute points, then descriptors, and after 50 iterations, the exception is thrown!
```
##### Thibault Lelore on 2015-04-14 10:10

```
I'm sorry, the problem was my side (memory corruption).
-   Status changed from New to Cancelled
```
##### Thibault Lelore on 2015-04-14 13:45

```
Finally, I think there is a problem in ORB implementation... Here is the smallest code I use which produce the previous error: Assertion failed (clEnqueueUnmapMemObject_pfn...
<pre>
VideoCapture cap(0);
  cv::Ptr<cv::xfeatures2d::SURF> ptDetect = xfeatures2d::SURF::create();
  cv::Ptr<cv::ORB> descExtract = ORB::create();
  cv::Mat frame, desc;
  std::vector<cv::KeyPoint> points;
  while (1)
  {
    cap >> frame; // read a new frame from video

    if (frame.empty()) //if not success, break loop
      break;

    ptDetect->detect(frame, points);
    descExtract->compute(frame, points, desc);

    imshow("MyVideo", frame);
    waitKey(15);
  }
</pre>
After 15-30 frames, the exception is thrown... Can someone confirm this issue?
-   Status changed from Cancelled to Open
```
##### Maksim Shabunin on 2015-04-27 10:50

```
Can not reproduce with your code on Linux, Intel HD Graphics Haswell GT2, using beignet 1.0.0.
Can you, please, provide some information about your platform
-   Target version changed from 3.0 to 3.1
-   Priority changed from Normal to Low
-   Assignee set to Maksim Shabunin
-   Status changed from Open to Incomplete
-   Category set to ocl
```
##### Vadim Pisarevsky on 2015-04-28 12:05

```
-   Category changed from ocl to t-api
```

### LINKED ISSUE #6081: Python bindings: ORB is broken
Following code fails:

``` python
import cv2
img = cv2.imread('some_image.jpg')
orb = cv2.ORB_create(nfeatures=5000)
ps, descs = orb.detectAndCompute(img, None)
```

Error output:

```
OpenCV Error: Assertion failed (The data should normally be NULL!) in allocate, file /home/polarnick/coding/forks/opencv_3.1/modules/python/src2/cv2.cpp, line 163
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-4-03ae3bc0ea38> in <module>()
----> 1 ps, descs = orb.detectAndCompute(img, None)

error: /home/polarnick/coding/forks/opencv_3.1/modules/python/src2/cv2.cpp:163: error: (-215) The data should normally be NULL! in function allocate
```

Environment: Python 3.4, Ubuntu

Affects **master** and **3.1.0**.

**Workaround:** if passing `cv2.UMat(img)` (see https://github.com/Itseez/opencv/pull/6078) - everything works

Can I pull-request this test case?

**UPD:**
The better **workaround** is `cv2.ocl.setUseOpenCL(False)` before ORB execution

The bug was introduced in commit 190d00ea3e46feedd38a7417c0a5ab08b900a56b (Pull request: https://github.com/Itseez/opencv/pull/5317)

### LINKED ISSUE #6969: Issue using stitching module
##### System information (version)

- OpenCV => 3.1.0-dev (master branch of 22nd July 2016)
- Operating System / Platform => Windows 10 64 bit
- Compiler => Visual Studio 2013
##### Detailed description

I wanted to do some research of image stitching with `stitching` module.

I compiled OpenCV 3.1.0-dev, master branch of 22nd July 2016 for **Python 2**. Then I executed following code:

```
import cv2

stitcher = cv2.createStitcher(False)
foo = cv2.imread('K:/foo.JPG')
bar = cv2.imread('K:/bar.JPG')
result = stitcher.stitch((foo,bar))
```

which resulted with following error message:

`error: K:\opencv_install\opencv\modules\python\src2\cv2.cpp:163: error: (-215) The data should normally be NULL! in function NumpyAllocator::allocate`

I'd appreciate some help regarding this issue. There were some workarounds for other functions like BackgroundSubtractorMOG2, but not for stitcher, so please help.

### PR DESCRIPTION
**Pull request by alalek**
Resolves #6081
Resolves #6969
Resolves #4968
Resolves #4967
and many others...

### CODE REVIEW

**Comment by alalek** [comment]
:+1:
