### ISSUE TITLE
Cannot use cv2.aruco.Board

### ISSUE THREAD

**Issue by dcnieho** [opencv/opencv#23176]
### System Information

OpenCV python version: 4.7.0.68
Operating System / Platform: Windows 11
Python version: 3.10.9

### Detailed description

I am porting code from 4.6.0.66 to 4.7.0.68. Aruco has moved from contrib to the main package, and some functions have been renamed. One of these is the constructor for an aruco board. It has been renamed from `cv2.aruco.Board_create` to `cv2.aruco.Board`. Its input arguments have not changed.
However, i am no longer able to call it with the same input arguments as in 4.6.0.66. Even though i put in a list of points and a list of ids of the same size, it always gives me an error that they are not the same length.:
```
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\aruco\aruco_board.cpp:160: error: (-215:Assertion failed) ids.size() == objPoints.size() in function 'cv::aruco::Board::Board'
```
Since the signature has not changed, i assume this is some error in the python wrapper or some change internal to the function?

### Steps to reproduce

Code that worked with 4.6.0.66:
```python
# boardCornerPoints is a list of 4x2 float32 matrices, e.g.:
# boardCornerPoints[0] ->
# array([[-178.05125, -151.86725],
#        [-136.15675, -151.86725],
#        [-136.15675, -109.97275],
#        [-178.05125, -109.97275]], dtype=float32)
boardCornerPoints = np.dstack(boardCornerPoints)        # list of 2D arrays -> 3D array
boardCornerPoints = np.rollaxis(boardCornerPoints,-1)   # 4x2xN -> Nx4x2
boardCornerPoints = np.pad(boardCornerPoints,((0,0),(0,0),(0,1)),'constant', constant_values=(0.,0.)) # Nx4x2 -> Nx4x3
cv2.aruco.Board_create(boardCornerPoints, self.aruco_dict, np.array(ids))
```
For 4.7.0.68, the last line should be changed to:
```python
cv2.aruco.Board(boardCornerPoints, self.aruco_dict, np.array(ids))
```
That however does not work, see error above.

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by dcnieho** [comment]
@asmorkalov: do you know what may cause this?
Comparing https://github.com/opencv/opencv/blob/4.7.0/modules/objdetect/src/aruco/aruco_board.cpp#L158 to https://github.com/opencv/opencv_contrib/blob/4.6.0/modules/aruco/src/aruco.cpp#L1613) shows that the assert that fails in 4.7 (`CV_Assert(ids.size() == objPoints.size());`) was not there in 4.6. Should that assert be there even though the interface did not otherwise change and something about size is checked on the next assert, or is it some copy-paste error or so?

**Comment by dcnieho** [comment]
@AleksandrPanov since i see you do a lot of work around this code

**Comment by asmorkalov** [comment]
@AleksandrPanov  Please take a look.

**Comment by daniel1v** [comment]
same issue for me. a downgrade to 4.6 solved it. i hope it gets fixed in the future.

**Comment by abcamiletto** [comment]
Same problem for me, I add a quick reproducible code for reference:

```
import numpy as np
import cv2

n_markers = 10
obj_points = np.random.rand(n_markers, 4, 3).astype(np.float32)
dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_5X5_1000)
ids = np.arange(n_markers).astype(np.int32).reshape(-1, 1)

board = cv2.aruco.Board(obj_points, dictionary, ids)
# [opencv-4.7.0/modules/objdetect/src/aruco/aruco_board.cpp:160): error: (-215:Assertion failed) ids.size() == objPoints.size() in function 'Board'
```

I would love to contribute to the fix if somebody is willing to give some direction on the desired solution. Is it just a matter of removing the assert https://github.com/opencv/opencv/blob/4.7.0/modules/objdetect/src/aruco/aruco_board.cpp#L158?

**Comment by AleksandrPanov** [comment]
Aruco board constuctor uses 3d points, see [getObjPoints()](https://docs.opencv.org/4.x/d4/db2/classcv_1_1aruco_1_1Board.html#a2df6cf10c3d6169f2f31708644ac5b19)

I will add this information to the documentation.

I changed @adamwhats's sample to 3d points:
```
import numpy as np
import cv2 as cv
p1 = np.array([[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 0, 0]], dtype=np.float32)
p2 = np.array([[1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0]], dtype=np.float32)
objPoints = np.array([p1, p2])
dictionary = cv.aruco.getPredefinedDictionary(cv.aruco.DICT_4X4_50)
ids = np.array([0, 1])
board = cv.aruco.Board(objPoints, dictionary, ids)
```
Should work after the fix https://github.com/opencv/opencv/pull/23399

**Comment by dcnieho** [comment]
@AleksandrPanov has this fix been tested? I (and clearly a bunch of other people) are missing 4.7 now because of this bug, it would be good to know whether it is fixed before the next version is released. Thanks!

**Comment by asmorkalov** [comment]
Yes. the fix includes python test. The test is executed automatically by CI system.

**Comment by ronsys11** [comment]
I tried running this 
import numpy as np
import cv2 as cv
p1 = np.array([[0, 0, 0], [0, 1, 0], [1, 1, 0], [1, 0, 0]], dtype=np.float32)
p2 = np.array([[1, 0, 0], [1, 1, 0], [2, 1, 0], [2, 0, 0]], dtype=np.float32)
objPoints = np.array([p1, p2])
dictionary = cv.aruco.getPredefinedDictionary(cv.aruco.DICT_4X4_50)
ids = np.array([0, 1])
board = cv.aruco.Board(objPoints, dictionary, ids)

It still showed me the same error "cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\aruco\aruco_board.cpp:160: error: (-215:Assertion failed) ids.size() == objPoints.size() in function 'cv::aruco::Board::Board'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\Major Project\Vision\test.py", line 8, in <module>
    board = cv.aruco.Board(objPoints, dictionary, ids)
SystemError: <class 'cv2.aruco.Board'> returned a result with an exception set"

following are my dependencies version:
Python                  3.10.2
numpy                  1.22.2
opencv-contrib-python  4.7.0.68
opencv-python          4.7.0.68
opencv-python-headless 4.8.1.78

**Comment by dcnieho** [comment]
You install is messed up. You should have only one of the four opencv-* packages installed, not more. I guess whichever is being picked up is too old and has this bug
