### ISSUE TITLE
Android native: updated from 4.0.1 to 4.1.0, compiling fails due to undefined reference to 'fegetenv' in 3rdparty/tbb

### ISSUE THREAD

**Issue by PhilLab** [opencv/opencv#14419]
The same configuration works with OpenCV 4.0.1 but fails when I try to upgrade to 4.1.0

- OpenCV 4.1.0 on Android, prebuilts taken from the official release
- ANDROID_STL=c++_shared
- NDK: 19c

I get the following build failure:
```
[armeabi-v7a] SharedLibrary  : libinitializer.so
/build/master_pack-android/build/o4a/3rdparty/tbb/tbb-2018_U1/src/tbb/scheduler_common.h:431: error: undefined reference to 'fegetenv'
/build/master_pack-android/build/o4a/3rdparty/tbb/tbb-2018_U1/src/tbb/scheduler_common.h:435: error: undefined reference to 'fesetenv'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build/intermediates/ndk/obj/local/armeabi-v7a/libinitializer.so] Error 1
```

The NDK build command in the build.gradle looks like this:
```
task ndkBuild(type: Exec, description: 'Compile JNI source via NDK') {

        File ndkDir = android.ndkDirectory
        if (ndkDir == null) {
            final String ndkPath = System.getenv('ANDROID_NDK')
            if (ndkPath == null) {
                throw new Exception('NDK directory is not configured. Set ANDROID_NDK')
            }
            ndkDir = new File(ndkPath)
        }

        String ndkBuildCmd = "$ndkDir/"
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            ndkBuildCmd += "ndk-build.cmd"
        } else {
            ndkBuildCmd += "ndk-build"
        }
        // opencvUnzippedDir contains the "sdk/native" folder from the OpenCV Android pre-builts
        logger.lifecycle("OPENCV_ROOT=" + opencvUnzippedDir)

        commandLine ndkBuildCmd,
                'NDK_PROJECT_PATH=build/intermediates/ndk',
                'NDK_LIBS_OUT=build/intermediates/ndk/libs/', //Output directory for .so - not under source control!
                'APP_BUILD_SCRIPT=src/main/jni/Android.mk',
                'NDK_APPLICATION_MK=src/main/jni/Application.mk',
                'ANDROID_STL=c++_shared',
                "OPENCV_ROOT=$opencvUnzippedDir"
    }

    tasks.withType(JavaCompile) {
        compileTask -> compileTask.dependsOn ndkBuild
    }
```
Application.mk:
```
APP_ABI := armeabi-v7a x86
APP_PLATFORM := android-16
APP_CPPFLAGS := -frtti -fexceptions -std=c++11
APP_STL :=  c++_shared
```

Android.mk:
```
LOCAL_PATH := $(call my-dir)

#
# Initializer lib
#
include $(CLEAR_VARS)

# <OpenCV>
OPENCV_CAMERA_MODULES:=off
OPENCV_INSTALL_MODULES:=on
OPENCV_LIB_TYPE:=STATIC
include ${OPENCV_ROOT}/native/jni/OpenCV.mk
# </OpenCV>

LOCAL_SRC_FILES := main_initializer.cpp Function_Wrappers.cpp Point_Matcher.cpp
LOCAL_LDLIBS += -llog -ldl
LOCAL_MODULE := initializer

include $(BUILD_SHARED_LIBRARY)
```

**Comment by alalek** [comment]
Try to exclude TBB from the build

**Comment by PhilLab** [comment]
@alalek Are there pre-builts available without TBB?

**Comment by alalek** [comment]
> LOCAL_LDLIBS += -llog -ldl

Try to add `-lm`

**Comment by PhilLab** [comment]
@alalek Unfortunately, this did not work. Behavior was the same.
> LOCAL_LDLIBS += -lm -llog -ldl

Using fenv in my own code does work, no matter if I leave the -lm in or remove it again:

```
#include <fenv.h>
MyClass::MyClass()
{
    fenv_t curr_env;
    fegetenv(&curr_env);
}
```

And also the more complex example from https://en.cppreference.com/w/c/numeric/fenv/feenv
produced output on the Android logcat

**Comment by PhilLab** [comment]
Also, it did not matter if I modified the LOCAL_LDLIBS before the inclusion of OpenCV.mk or after

**Comment by pnduffy** [comment]
Target Android 21 or greater to fix this.

**Comment by Palladinium** [comment]
I'm having the same issue despite targeting Android 21 and up.

I have the following settings in my `build.gradle`:
```
compileSdkVersion 28
buildToolsVersion "28.0.3"
targetSdkVersion 28
```

**Comment by PhilLab** [comment]
Yes, targeting Android 21 does not solve the problem
```
compileSdkVersion = 28
targetSdkVersion = 28
minSdkVersion = 21
'com.android.tools.build:gradle:3.3.2'
```

**Comment by Palladinium** [comment]
Turns out that yes, targeting Android 21 *is* how you solve this, but `build.gradle` is not the only place where you need to set that. In `Application.mk`, make sure you have:
```
APP_PLATFORM := android-21
```

I can't test if it runs in an actual app for a few days, but it compiles and links for me.

**Comment by PhilLab** [comment]
@Palladinium Yes, that did it 👍 Compiles and runs

**Comment by c1ph3r-j** [comment]
Application.mk I am unable to find this may i know where do i get this file in my project.

**Comment by c1ph3r-j** [comment]
@Palladinium  NO Worries, I have fixed my issues. Thank You guys.
