### PR TITLE
calib: fix fisheye::calibrate failing on Nx1 point arrays

### LINKED ISSUE #29692: cv2.fisheye.calibrate() fails with (N, 1, C) point arrays in OpenCV 5.0.0
### System Information

OpenCV Python version 5.0.0.93 (compared against 4.14.0.94)
*(Python libraries installed using UV, which I believe uses pip internally.)*
Platform: MacOS 26.5.2 running on Arm (Apple M4)
Python version: 3.14.6 (main, Jun 10 2026, 15:27:46) [Clang 17.0.0 (clang-1700.6.4.2)]

### Detailed description

cv2.fisheye.calibrate() fails in OpenCV 5.0.0 when the calibration point arrays are represented as (N, 1, 3) for object points and (N, 1, 2) for image points.  This is (was?) the default output of the Charuco board marker/corner point detection code in OpenCV 3(? I think that was the version I originally wrote this code on), and was still needed, or at least worked, in OpenCV 4.  The current detection functions seem to mostly output (N,2) or (N,3) arrays now, but those also break (albeit with a different set of errors) if fed directly into cv2.fisheye.calibrate().  The exact same data and array representation I'm using work in OpenCV 4 (4.14.0.94).

Changing the representation to (1, N, 3) and (1, N, 2) allows the calibration to succeed.

The error is:
```
    ret, cameraMatrix, distCoeffs, rvecs, tvecs = cv2.fisheye.calibrate(objp, imgp, imsize, aprioriK, aprioriD)
                                                  ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(5.0.0) /Users/xperience/GHA-OpenCV-Python/_work/opencv-python/opencv-python/opencv/modules/core/src/arithm.cpp:691: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
```

### Steps to reproduce

```python
#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "numpy>=2.4.6",
#     "opencv-python==5.0.0.93",
# ]
# ///

# The two versions tested:
#     "opencv-python==4.14.0.94",
#     "opencv-python==5.0.0.93",

import cv2
import numpy as np

# Test data (apologies if this is too long, I tried cut it down until just before it started throwing different errors)
imgpoints = [np.array([[[3938.2031  , 1998.1097  ]],
       [[3825.9392  , 1975.5667  ]],
       [[3718.7632  , 1953.5919  ]],
       [[3618.055   , 1932.9668  ]],
       [[3524.0574  , 1913.5465  ]],
       [[3436.9363  , 1895.5947  ]],
       [[3356.8042  , 1879.0228  ]],
       [[3283.6746  , 1863.7391  ]],
       [[3216.9587  , 1850.0328  ]],
       [[3155.9087  , 1837.3     ]],
       [[3099.4817  , 1825.6403  ]],
       [[3048.386   , 1814.8158  ]],
       [[3001.285   , 1804.9496  ]],
       [[2957.9866  , 1795.8983  ]],
       [[2918.252   , 1787.5631  ]],
       [[2881.488   , 1779.9025  ]],
       [[3960.4854  , 1812.2389  ]],
       [[3844.9558  , 1800.6023  ]],
       [[3734.7395  , 1789.2517  ]],
       [[3630.835   , 1778.6511  ]],
       [[3535.47    , 1768.4932  ]],
       [[3446.6614  , 1759.1504  ]]], dtype=np.float32), np.array([[[2961.8066 , 1584.4417 ]],
       [[2921.9766 , 1585.1133 ]],
       [[2885.395  , 1585.7448 ]],
       [[2851.7642 , 1586.4434 ]],
       [[2820.7034 , 1587.0093 ]],
       [[2791.7468 , 1587.5143 ]],
       [[2960.729  , 1494.7284 ]],
       [[2921.027  , 1499.4994 ]],
       [[2884.4773 , 1503.9607 ]],
       [[2851.0479 , 1507.99   ]],
       [[2819.3494 , 1511.573  ]],
       [[2791.2314 , 1515.2996 ]],
       [[2957.9924 , 1405.7168 ]],
       [[2918.6936 , 1414.5    ]],
       [[2882.5183 , 1422.5543 ]],
       [[2849.1409 , 1430.0212 ]],
       [[2818.5051 , 1436.8982 ]],
       [[2789.7522 , 1443.2908 ]],
       [[2953.5054 , 1317.7615 ]],
       [[2914.818  , 1330.425  ]],
       [[2878.8374 , 1341.876  ]],
       [[2846.2952 , 1352.7683 ]],
       [[2815.767  , 1362.4504 ]],
       [[2787.3728 , 1372.0793 ]],
       [[2947.2556 , 1231.5514 ]]], dtype=np.float32), np.array([[[2828.197 , 2660.4216]],
       [[2802.9211, 2622.4282]],
       [[2843.074 , 2603.7092]],
       [[2816.3948, 2566.3206]],
       [[2791.4817, 2531.0981]],
       [[2857.3984, 2543.4028]],
       [[2829.7017, 2507.2878]],
       [[2803.3098, 2473.0645]],
       [[2778.6245, 2440.496 ]],
       [[2872.1028, 2480.4746]],
       [[2842.6519, 2445.0027]],
       [[2815.226 , 2412.1367]],
       [[2789.3176, 2381.1204]],
       [[2765.0134, 2351.8035]],
       [[2741.4583, 2324.0098]],
       [[2719.9487, 2298.1616]],
       [[2886.0332, 2413.8276]],
       [[2855.3281, 2380.159 ]],
       [[2825.7905, 2348.7717]],
       [[2799.6614, 2318.917 ]],
       [[2774.2434, 2291.184 ]],
       [[2750.3276, 2265.186 ]],
       [[2727.4128, 2240.2996]]], dtype=np.float32)]

objpoints = [np.array([[[0.1016, 0.0508, 0.    ]],
       [[0.1524, 0.0508, 0.    ]],
       [[0.2032, 0.0508, 0.    ]],
       [[0.254 , 0.0508, 0.    ]],
       [[0.3048, 0.0508, 0.    ]],
       [[0.3556, 0.0508, 0.    ]],
       [[0.4064, 0.0508, 0.    ]],
       [[0.4572, 0.0508, 0.    ]],
       [[0.508 , 0.0508, 0.    ]],
       [[0.5588, 0.0508, 0.    ]],
       [[0.6096, 0.0508, 0.    ]],
       [[0.6604, 0.0508, 0.    ]],
       [[0.7112, 0.0508, 0.    ]],
       [[0.762 , 0.0508, 0.    ]],
       [[0.8128, 0.0508, 0.    ]],
       [[0.8636, 0.0508, 0.    ]],
       [[0.1016, 0.1016, 0.    ]],
       [[0.1524, 0.1016, 0.    ]],
       [[0.2032, 0.1016, 0.    ]],
       [[0.254 , 0.1016, 0.    ]],
       [[0.3048, 0.1016, 0.    ]],
       [[0.3556, 0.1016, 0.    ]]], dtype=np.float32), np.array([[[0.0508, 0.0508, 0.    ]],
       [[0.1016, 0.0508, 0.    ]],
       [[0.1524, 0.0508, 0.    ]],
       [[0.2032, 0.0508, 0.    ]],
       [[0.254 , 0.0508, 0.    ]],
       [[0.3048, 0.0508, 0.    ]],
       [[0.0508, 0.1016, 0.    ]],
       [[0.1016, 0.1016, 0.    ]],
       [[0.1524, 0.1016, 0.    ]],
       [[0.2032, 0.1016, 0.    ]],
       [[0.254 , 0.1016, 0.    ]],
       [[0.3048, 0.1016, 0.    ]],
       [[0.0508, 0.1524, 0.    ]],
       [[0.1016, 0.1524, 0.    ]],
       [[0.1524, 0.1524, 0.    ]],
       [[0.2032, 0.1524, 0.    ]],
       [[0.254 , 0.1524, 0.    ]],
       [[0.3048, 0.1524, 0.    ]],
       [[0.0508, 0.2032, 0.    ]],
       [[0.1016, 0.2032, 0.    ]],
       [[0.1524, 0.2032, 0.    ]],
       [[0.2032, 0.2032, 0.    ]],
       [[0.254 , 0.2032, 0.    ]],
       [[0.3048, 0.2032, 0.    ]],
       [[0.0508, 0.254 , 0.    ]]], dtype=np.float32), np.array([[[0.0508, 0.1524, 0.    ]],
       [[0.1016, 0.1524, 0.    ]],
       [[0.0508, 0.2032, 0.    ]],
       [[0.1016, 0.2032, 0.    ]],
       [[0.1524, 0.2032, 0.    ]],
       [[0.0508, 0.254 , 0.    ]],
       [[0.1016, 0.254 , 0.    ]],
       [[0.1524, 0.254 , 0.    ]],
       [[0.2032, 0.254 , 0.    ]],
       [[0.0508, 0.3048, 0.    ]],
       [[0.1016, 0.3048, 0.    ]],
       [[0.1524, 0.3048, 0.    ]],
       [[0.2032, 0.3048, 0.    ]],
       [[0.254 , 0.3048, 0.    ]],
       [[0.3048, 0.3048, 0.    ]],
       [[0.3556, 0.3048, 0.    ]],
       [[0.0508, 0.3556, 0.    ]],
       [[0.1016, 0.3556, 0.    ]],
       [[0.1524, 0.3556, 0.    ]],
       [[0.2032, 0.3556, 0.    ]],
       [[0.254 , 0.3556, 0.    ]],
       [[0.3048, 0.3556, 0.    ]],
       [[0.3556, 0.3556, 0.    ]]], dtype=np.float32)]



# Reshaped version needed by OpenCV 5
objpoints2 = [
    np.ascontiguousarray(x.reshape(1, -1, 3))
    for x in objpoints
]

imgpoints2 = [
    np.ascontiguousarray(x.reshape(1, -1, 2))
    for x in imgpoints
]


# Other inputs
imsize=(4168, 3058)
aprioriK = np.array([[1717., 0., 2098.],[0., 1717., 1561.],[0., 0., 1.]], dtype=np.float32)
aprioriD = np.zeros((4, 1), dtype=np.float32)



def run_test(objp, imgp):
    print("obj:", objp[0].shape, objp[0].dtype, objp[0].strides)
    print("img:", imgp[0].shape, imgp[0].dtype, imgp[0].strides)
    print("n:", len(objp), len(imgp))
    for i in range(len(objp)):
        print(objp[i].shape, imgp[i].shape)
    
    ret, cameraMatrix, distCoeffs, rvecs, tvecs = cv2.fisheye.calibrate(objp, imgp, imsize, aprioriK, aprioriD)
    
    
    print("Camera Matrix : ")
    print(f"{cameraMatrix[0,0]:10.1f} {cameraMatrix[0,1]:10.4f} {cameraMatrix[0,2]:10.1f}")
    print(f"{cameraMatrix[1,0]:10.4f} {cameraMatrix[1,1]:10.1f} {cameraMatrix[1,2]:10.1f}")
    print(f"{cameraMatrix[2,0]:10.3f} {cameraMatrix[2,1]:10.4f} {cameraMatrix[2,2]:10.0f}")
    print("Distortion Coefficients : ")
    print(f"{distCoeffs[0,0]:7.4f} {distCoeffs[1,0]:7.4f} {distCoeffs[2,0]:7.4f} {distCoeffs[3,0]:7.4f}")
#



print("TEST 1: OpenCV 3(?)-style Arrays")
try:
    run_test(objpoints, imgpoints)
except Exception as e:
    print(e)

print("\n\n\nTEST 2: Reshaped Arrays: 1,N,3")
try:
    run_test(objpoints2, imgpoints2)
except Exception as e:
    print(e)
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by ArneshBanerjee**
Fixes #29692

`ComputeJacobians` and `EstimateUncertainties` in `modules/calib/src/fisheye.cpp` decided whether to transpose the image points array using:

```cpp
bool imT = image.channels() == 1 && image.rows > image.cols;
```

`image` here is always 2-channel (`CV_64FC2`), so `image.channels() == 1` is never true and the transpose never happens. As a result, calibration only works when points are passed as `1xN` arrays; passing them as `Nx1` (a common shape, e.g. output of `cv::Mat(vector<Point2f>)` reshaped, or numpy `(N,1,C)` arrays from Python) leaves the row/column shapes mismatched between the image points and the projected points, which corrupts the least-squares solve and throws a size-mismatch assertion.

Fix: drop the bogus `channels() == 1` check, matching the transpose logic already used correctly in `CalibrateExtrinsics` a few lines above.

Added a regression test (`fisheyeTest.CalibrationWithColumnPoints`) that calibrates the same synthetic points passed as both `1xN` and `Nx1` arrays and checks the results match. Verified it fails with the old code and passes with the fix.

### CODE REVIEW

**Comment by asmorkalov** [comment]
Build warnings:
```
    Warning: /home/ci/opencv/modules/calib/test/test_fisheye.cpp:486:18: warning: declaration of 'K' shadows a member of 'opencv_test::{anonymous}::fisheyeTest_CalibrationWithColumnPoints_Test' [-Wshadow]
    Warning: /home/ci/opencv/modules/calib/test/test_fisheye.cpp:489:16: warning: declaration of 'D' shadows a member of 'opencv_test::{anonymous}::fisheyeTest_CalibrationWithColumnPoints_Test' [-Wshadow]
```

**Comment by ArneshBanerjee** [comment]
Thanks for review, will resolve soon!

**Comment by ArneshBanerjee** [comment]
Fixed, thanks. Renamed the local `K`/`D` in the new test to `theK`/`theD` so they no longer shadow the fixture members, matching the naming already used in the other tests in this file.

**Comment by asmorkalov** [comment]
The original condition is correct. The function expects array of 2d points. It may be 1-d array of 2 channel pints or 2d array 1xN or Nx1. The last case should has `channel == 1`. The mentioned issue reproducer uses 3d array with redundant dimension.

**Comment by ArneshBanerjee** [comment]
My PR description was wrong on one point, and I think that is what it looked like I was claiming. I wrote that `image` is always `CV_64FC2` so `channels() == 1` can never be true. That is incorrect: `convertTo(image, CV_64FC2)` only sets the depth, the channel count comes from the input, so a single channel Nx2 array does reach that line with `channels() == 1`. You are right that the branch is live code.

The change does not affect that case though. The condition is a conjunction, so dropping `channels() == 1 &&` can only make more inputs transpose, never fewer:

- single channel Nx2 (N > 2): `imT` is true before, true after
- single channel 2xN: false before, false after

The only inputs whose behaviour changes are 2 channel Nx1, which is the case from the issue. Those do not currently throw, they broadcast. `Mat(std::vector<Point2d>)` is 1xN in 5.x, and `1xN - Nx1` yields an NxN matrix rather than an error, so the residual is silently wrong before it later trips the gemm assert.

`CalibrateExtrinsics` a few lines above uses `bool imT = image.rows < image.cols;` with no channel check, so 2 channel Nx1 is already handled there.

On the redundant dimension: (N, 1, 2) is what `findChessboardCorners` returns, so it is a fairly common shape to pass in rather than an unusual one.

Would you consider reopening? If you would rather fix it by normalising the point layout at the API entry, in line with your 0d/1d comment on #29692, I am happy to redo it that way instead.

One caveat: locally I could only run the two fisheye tests that do not need opencv_extra, so I have not verified the rest.
