### ISSUE TITLE
OpenCL error CL_INVALID_CONTEXT worked with 3.4.12

### ISSUE THREAD

**Issue by arpu** [opencv/opencv#18859]
##### System information (version)

- OpenCV =>4.5.1-pre
- Operating System / Platform => fedora 33 
- Compiler => gcc

##### Detailed description
update from  3.4.12   to 4.5.1-pre master i get 

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.1-pre) /home/arpu/Work/githubsources/opencv4/modules/core/src/ocl.cpp:5937: error: (-220:Unknown error code -220) OpenCL error CL_INVALID_CONTEXT (-34) during call: clEnqueueReadBuffer(q, (cl_mem)u->handle, CL_TRUE, srcrawofs, total, alignedPtr.getAlignedPtr(), 0, 0, 0) in function 'download'

```
err = clEnqueueCopyBuffer(m_queue, (cl_mem)image0.handle(cv::ACCESS_READ), buf[0],
                            srcrawofs, 0, total, 0, 0, 0);
```

**Comment by arpu** [comment]
i think the problematic part is more the cv::ocl::attachContext

what i do is 
```
  cl_int res = CL_SUCCESS;
  cl_uint num_entries = 0;

  res = clGetPlatformIDs(0, 0, &num_entries);

  m_platform_ids.resize(num_entries);

  res = clGetPlatformIDs(num_entries, &m_platform_ids[0], 0);

  unsigned int i;

  // create context from first platform with GPU device
   std::cout << m_platform_ids.size() << std::endl;
  for (i = 0; i < m_platform_ids.size(); i++)
  {

    std::cout << m_platform_ids[i] << std::endl;

    cl_context_properties props[] =
        {
            CL_CONTEXT_PLATFORM,
            (cl_context_properties)(m_platform_ids[i]),
            0};

    m_context = clCreateContextFromType(props, CL_DEVICE_TYPE_GPU, 0, 0, &res);
    if (0 == m_context || CL_SUCCESS != res)
      continue;

    res = clGetContextInfo(m_context, CL_CONTEXT_DEVICES, sizeof(cl_device_id), &m_device_id, 0);

    m_queue = clCreateCommandQueue(m_context, m_device_id, 0, &res);

    cv::ocl::attachContext("AMD Accelerated Parallel Processing", m_platform_ids[i], m_context, m_device_id);
  }
```

@alalek anything in mind, what changed for opencv4? ( works fine with latest opencv3)

**Comment by arpu** [comment]
ok found this example and will test with this 
https://github.com/opencv/opencv/blob/master/samples/android/tutorial-4-opencl/jni/CLprocessor.cpp

**Comment by alalek** [comment]
Significant changes in OpenCL contexts area have been done between 4.4.0 and 4.5.0 releases here: #18186

**Comment by arpu** [comment]
thx @alalek  this looks awesome!
one question to this new Interface how can i get the cl_context from the opencv cv::ocl::OpenCLExecutionContext::getCurrent()

what i get is 
cannot convert 'cv::ocl::OpenCLExecutionContext' to 'cl_context'

**Comment by arpu** [comment]
for reference i do now:
```
  auto& currentExe = cv::ocl::OpenCLExecutionContext::getCurrent();
  auto currentContext = currentExe.getContext();
  m_context = (cl_context)currentContext.ptr();
  auto currentQuery = currentExe.getQueue();
  m_queue = (cl_command_queue)currentQuery.ptr();

```

**Comment by arpu** [comment]
@alalek thx for your Time and this new OpenCL Api
