### PR TITLE
Resolve Compilation Error for v_func Function in SIMD Emulator

### PR DESCRIPTION
**Pull request by WanliZhong**
This PR tries to fix the compilation  error introduced by https://github.com/opencv/opencv/pull/24941
Error detail: https://github.com/opencv/opencv/pull/24941#issuecomment-2213266919
Merged after https://github.com/opencv/opencv/pull/26109

Additionally, this PR adds the missing documentation for the v_log function.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
build_image:Custom=simd-emulator
buildworker:Custom=linux-1,linux-4
```

### CODE REVIEW

**Comment by WanliZhong** [comment]
@asmorkalov I removed the macros `OPENCV_HAL_MATH_HAVE_XXX` defined in `intrin_cpp.hpp`. This change will fix the error. I passed the compilation and the tests in the local machine with `-DCV_FORCE_SIMD128_CPP=1`

**Review by asmorkalov — APPROVED** [review]

**Comment by vpisarev** [comment]
@opencv-alalek, could you please review it? Frankly speaking, I don't understand logic behind all those myriads of flags that we have, so you are the best person to review it

File: modules/core/include/opencv2/core/hal/intrin_cpp.hpp [hunk 1]
```diff
@@ -742,7 +742,6 @@ OPENCV_HAL_IMPL_MATH_FUNC(v_sqrt, std::sqrt, _Tp)
  * @note The precision of the calculation depends on the implementation and the data type of the input vector.
  */
 OPENCV_HAL_IMPL_MATH_FUNC(v_exp, std::exp, _Tp)
-#define OPENCV_HAL_MATH_HAVE_EXP 1
```
Comment (opencv-alalek) [inline modules/core/include/opencv2/core/hal/intrin_cpp.hpp:745]: It is expected that tests like `hal_intrin*CPP_EMULATOR` call the code from `intrin_cpp.hpp`. But they don't.

To debug modify `intrin_cpp.hpp`:

```.diff
 #define OPENCV_HAL_IMPL_MATH_FUNC(func, cfunc, _Tp2) \
 template<typename _Tp, int n> inline v_reg<_Tp2, n> func(const v_reg<_Tp, n>& a) \
 { \
+    printf(#func " is called\n"); \
     v_reg<_Tp2, n> c; \
     for( int i = 0; i < n; i++ ) \
         c.s[i] = cfunc(a.s[i]); \

```

Run tests: `./bin/opencv_test_core --gtest_filter=*intrin*EMULATOR*`

```
[ RUN      ] hal_intrin128.float32x4_CPP_EMULATOR
SIMD128: void opencv_test::hal::intrin128::opt_EMULATOR_CPP::test_hal_intrin_float32()
v_abs is called
v_sqrt is called
v_abs is called
<<<<<<< missing v_exp call through generic C++ exp() >>>>>>>>>
v_abs is called
v_abs is called
v_abs is called
...
```

(both build configurations: with/without -DOPENCV_EXTRA_FLAGS="-DCV_FORCE_SIMD128_CPP=1")


---

BTW, without this PR the correct version is called (in "default" build):

```
[ RUN      ] hal_intrin128.float32x4_CPP_EMULATOR
SIMD128: void opencv_test::hal::intrin128::opt_EMULATOR_CPP::test_hal_intrin_float32()
v_abs is called
v_sqrt is called
v_abs is called
v_exp is called
v_exp is called
v_exp is called
v_exp is called
v_exp is called
...
v_log is called
...

```

Comment (WanliZhong) [reply modules/core/include/opencv2/core/hal/intrin_cpp.hpp:745]: This happens may because we introduce `v_erf` function, but the test call v_exp with the implementation in `intrin_math.hpp`.  I think I should add a line after erf defination: `#define OPENCV_HAL_MATH_HAVE_ERF 1`

```c++
/**
 * @brief Error function.
 *
 * @note Support FP32 precision for now.
 */
OPENCV_HAL_IMPL_MATH_FUNC(v_erf, std::erf, _Tp)
```

**Comment by WanliZhong** [comment]
This bug is a bit complicated. If I add this non-meaningful code in `intrin_avx.cpp` and `intrin_avx512.cpp`, the code will be complied successfully and run `OPENCV_HAL_IMPL_MATH_FUNC` correctly. That's mean there are some code related to avx platform wrong. I will continually dig this issue.
```
inline v_float32x8 v_exp(const v_float32x8 a) { return a;}
inline v_float64x4 v_exp(const v_float64x4 a) { return a;}
```

**Comment by WanliZhong** [comment]
@opencv-alalek @vpisarev @asmorkalov Hi, sorry for the delayed fix. I finally found out why this error occurs. That's because the `intrin_cpp.hpp` will only generate functions for SIMD128 (`v_float32x4` and `v_float64x2`). 

However, on `AVX2`, `AVX512`, and `LASX` platforms, SIMD256 or SIMD512 are used, which has more lanes. As a result, tests or other codes are unable to find the corresponding functions. In this case, I made the implementation of 'v_float' work, and then fixed this error.

**Comment by WanliZhong** [comment]
@opencv-alalek  @vpisarev  @asmorkalov  Hi, sorry for the delayed fix. I finally found out why this error occurs. That's because the `intrin_cpp.hpp` will only generate functions for SIMD128 (`v_float32x4` and `v_float64x2`). 

However, on `AVX2`, `AVX512`, and `LASX` platforms, SIMD256 or SIMD512 are used, which has more lanes. As a result, tests or other codes cannot find the corresponding functions. In this case, I made the implementation of 'v_float' work, and then fixed this error.

**Comment by asmorkalov** [comment]
@opencv-alalek could you take a look again?

**Comment by WanliZhong** [comment]
This PR includes https://github.com/opencv/opencv/pull/26109. For this PR，you can only focus on intrin_math.hpp file.

File: modules/core/include/opencv2/core/hal/intrin_math.hpp [hunk 2]
```diff
@@ -34,434 +30,428 @@ namespace CV__SIMD_NAMESPACE {
...
+        const v_float##TpSuffix _vexp_p0_f16 = VPrefix##_setall_f16(1.9875691500E-4f); \
+        const v_float##TpSuffix _vexp_p1_f16 = VPrefix##_setall_f16(1.3981999507E-3f); \
+        const v_float##TpSuffix _vexp_p2_f16 = VPrefix##_setall_f16(8.3334519073E-3f); \
+        const v_float##TpSuffix _vexp_p3_f16 = VPrefix##_setall_f16(4.1665795894E-2f); \
+        const v_float##TpSuffix _vexp_p4_f16 = VPrefix##_setall_f16(1.6666665459E-1f); \
+        const v_float##TpSuffix _vexp_p5_f16 = VPrefix##_setall_f16(5.0000001201E-1f); \
+        const v_int##TpSuffix _vexp_bias_s16 = VPrefix##_setall_s16(0xf); \
+\
+        v_float##TpSuffix _vexp_, _vexp_x, _vexp_y, _vexp_xx; \
+        v_int##TpSuffix _vexp_mm; \
```
Comment (asmorkalov) [inline modules/core/include/opencv2/core/hal/intrin_math.hpp:57]: I propose to use templates here. v_int##TpSuffix and v_float##TpSuffix will be template arguments.

Comment (WanliZhong) [reply modules/core/include/opencv2/core/hal/intrin_math.hpp:57]: OK, but it will introduce many parameters and may use the macro to maintain the code.

**Comment by asmorkalov** [comment]
@WanliZhong  I merged related PR. Please rebase and fix conflicts.

**Comment by WanliZhong** [comment]
OK, I will fix it later

File: modules/core/include/opencv2/core/hal/intrin_math.hpp (hunk 2 above)
Comment (WanliZhong) [reply modules/core/include/opencv2/core/hal/intrin_math.hpp:57]: @asmorkalov How is `VPrefix` (e.g., v256_setall_f32, v512_setall_f32) set depending on the platform? The function implementation cannot utilize templates.

**Comment by WanliZhong** [comment]
@vpisarev @asmorkalov I still don't know how to use the template to rewrite the code. The problem is vector datatype can use the template to represent, but `v_setall()` and `v_setzero()` are dependent on the specific vector width functions. So how can we generate different functions for different backends by using a template? Currently my code still use macro functions

File: modules/core/include/opencv2/core/hal/intrin_math.hpp (hunk 2 above)
Comment (asmorkalov) [reply modules/core/include/opencv2/core/hal/intrin_math.hpp:57]: I see. Thanks a lot for the investigation!

**Review by asmorkalov — APPROVED** [review]
:+1:

File: modules/core/include/opencv2/core/hal/intrin_math.hpp (hunk 2 above)
Comment (mshabunin) [reply modules/core/include/opencv2/core/hal/intrin_math.hpp:57]: Wouldn't wide intrinsics like `vx_setall_f32` work here? Or maybe we can introduce traits type (or extend existing ones) which would map `_setall_` to corresponding types.

Comment (WanliZhong) [reply modules/core/include/opencv2/core/hal/intrin_math.hpp:57]: @mshabunin The code will generate v_func for all backends. So when the user passes the widest vector variable, it will call the widest implementation version. (vx_setall_f32 will set the widest vector)

**Comment by WanliZhong** [comment]
As the discussion with Vadim, I will try to create new functions `v_setall`, `v_setzero`, `v_load` etc. The implementation will be like `v_setall(float vlaue, float32x4 /*unused*/)` for 128-bit, `v_setall(float, float32x8 /*unused*/)` for 256-bit ... Using the unused parameters to distinguish among platforms. Then use template to rewrite the v_func.

**Comment by WanliZhong** [comment]
I have changed the implementation by using templates, how about this implementation?

**Comment by opencv-alalek** [comment]
See #15839

**Review by vpisarev — APPROVED** [review]

**Comment by vpisarev** [comment]
excellent job! :+1:

File: modules/core/include/opencv2/core/hal/intrin_avx.hpp [hunk 3]
```diff
@@ -447,6 +447,10 @@ OPENCV_HAL_IMPL_AVX_LOADSTORE_FLT(v_float64x4, double, pd, __m128d)
     { return _Tpvec(_mm256_setzero_si256()); }                                   \
     inline _Tpvec v256_setall_##suffix(_Tp v)                                    \
     { return _Tpvec(_mm256_set1_##ssuffix((ctype_s)v)); }                        \
+    inline _Tpvec v_setzero(_Tpvec /*unused*/)                                   \
+    { return v256_setzero_##suffix(); }                                          \
```
Comment (opencv-alalek) [inline modules/core/include/opencv2/core/hal/intrin_avx.hpp:451]: Mess of v256_ / v_ (which is used for 128-bit)

**Comment by vpisarev** [comment]
Let's move forward
