### ISSUE TITLE
Problems with C API in OpenCV 3.4.1

### ISSUE THREAD

**Issue by AlexeyAB** [opencv/opencv#10969]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Windows 64 Bit and Linux Debian 7  64 Bit
- Compiler => Visual Studio 2015 and GCC 4.9.3

##### Detailed description

**Problems with C API in OpenCV 3.4.1.** 
Any OpenCV 3.x.x and OpenCV 2.x.x works fine, except for OpenCV 3.4.1

When I include `opencv2/core/core_c.h` file in any C-file `source.c` and try to compile with OpenCV 3.4.1 - I get errors:
* Windows 7x64 MSVS2015: 
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(18): error C2054: expected '(' to follow 'using'

* Linux Debian 7 x64 GCC 4.9.3:
> /usr/local/include/opencv2/core/cvdef.h:485:1: error: unknown type name ‘namespace’

##### Steps to reproduce

```c
// C code example
#include "opencv2/core/core_c.h"
int main() {
  return 0;
}
```

**Comment by wangyarui** [comment]
I met the same problem with you, waiting for someone to  help...

**Comment by nathantsoi** [comment]
@alalek what is this a duplicate of?

**Comment by alalek** [comment]
Duplicate of #10963 and others.
