### ISSUE TITLE
4.3.0:  build faails with vulkan-headers 1.2.140

### ISSUE THREAD

**Issue by kloczek** [opencv/opencv#17239]
```
[ 21%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/buffer.cpp.o
cd /home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/x86_64-redhat-linux-gnu/modules/dnn && /usr/bin/g++  -DCVAPI_EXPORTS -DHAVE_PROTOBUF=1 -DOPENCV_DNN_EXTERNAL_PROTOBUF=1 -DVK_NO_PROTOTYPES -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/x86_64-redhat-linux-gnu -I/usr/include/vulkan -I/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/include -I/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/x86_64-redhat-linux-gnu/modules/dnn -I/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/core/include -I/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/imgproc/include -isystem /usr/include/gdal -isystem /usr/include/eigen3 -isystem /usr/include/coin -isystem /usr/include/openblas  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -Wno-deprecated -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-sign-compare -Wno-invalid-offsetof -fPIC   -std=c++11 -o CMakeFiles/opencv_dnn.dir/src/vkcom/src/buffer.cpp.o -c /home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/buffer.cpp
In file included from /home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/common.hpp:25,
                 from /home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/buffer.cpp:9:
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkCmdProcessCommandsNVX’ does not name a type; did you mean ‘PFN_vkCmdExecuteCommand ’?
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:257:1: note: in expansion of macro ‘VK_FUNC’
  257 | VK_FUNC(vkCmdProcessCommandsNVX)
      | ^~~~~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkCmdReserveSpaceForCommandsNVX’ does not name a type
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:258:1: note: in expansion of macro ‘VK_FUNC’
  258 | VK_FUNC(vkCmdReserveSpaceForCommandsNVX)
      | ^~~~~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkCreateIndirectCommandsLayoutNVX’ does not name a type; did you mean ‘PFN_vkCreateIndirectCommandsLayoutNV’?
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:259:1: note: in expansion of macro ‘VK_FUNC’
  259 | VK_FUNC(vkCreateIndirectCommandsLayoutNVX)
      | ^~~~~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkDestroyIndirectCommandsLayoutNVX’ does not name a type; did you mean ‘PFN_vkDestroyIndirectCommandsLayoutNV’?
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:260:1: note: in expansion of macro ‘VK_FUNC’
  260 | VK_FUNC(vkDestroyIndirectCommandsLayoutNVX)
      | ^~~~~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkCreateObjectTableNVX’ does not name a type
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:261:1: note: in expansion of macro ‘VK_FUNC’
  261 | VK_FUNC(vkCreateObjectTableNVX)
      | ^~~~~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkDestroyObjectTableNVX’ does not name a type
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:262:1: note: in expansion of macro ‘VK_FUNC’
  262 | VK_FUNC(vkDestroyObjectTableNVX)
      | ^~~~~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkRegisterObjectsNVX’ does not name a type
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:263:1: note: in expansion of macro ‘VK_FUNC’
  263 | VK_FUNC(vkRegisterObjectsNVX)
      | ^~~~~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkUnregisterObjectsNVX’ does not name a type
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:264:1: note: in expansion of macro ‘VK_FUNC’
  264 | VK_FUNC(vkUnregisterObjectsNVX)
      | ^~~~~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/vk_functions.hpp:18:30: error: ‘PFN_vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX’ does not name a type; did you mean ‘VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV’?
   18 | #define VK_FUNC(func) extern PFN_##func func;
      |                              ^~~~
/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/modules/dnn/src/vkcom/src/../vulkan/function_list.inl.hpp:265:1: note: in expansion of macro ‘VK_FUNC’
  265 | VK_FUNC(vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX)
      | ^~~~~~~
make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/build.make:1167: modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/buffer.cpp.o] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/x86_64-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:7019: modules/dnn/CMakeFiles/opencv_dnn.dir/all] Error 2
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/opencv-4.3.0/x86_64-redhat-linux-gnu'
```

**Comment by kloczek** [comment]
Just done regression test and looks like last version of thevulkan-headers with which opencv builds correctly is **1.2.134**

**Comment by kloczek** [comment]
So just for the record last release fails wind last SDK version of the vulkan-headers which is **1.2.135.0**.

**Comment by mshabunin** [comment]
@kloczek , please take a look at the PR #17296 

BTW, OpenCV has own copy of headers and Vulkan support can be built even without Vulkan SDK.

**Comment by kloczek** [comment]
Temporary I cannot confirm that that patch is working because I've started working on switching to CharLS 3.1 which is used by gdcm which is used by opencv which seems is a bit messy :)
https://sourceforge.net/p/gdcm/bugs/504/

Will let you know about result of using your patch when will that issue will be sorted out :)

Thx

**Comment by kloczek** [comment]
BTW I think that you should abandon distributing other projects code in you own tree. It is nothing more tan asking for trouble. vulkan-heders have well done pkgconfig description and opencv should use only that interface in cmake build automation.
