### PR TITLE
python: properly handle step for multichannel case

### LINKED ISSUE #20968: cv2.cvtColor does not work with single pixel in OpenCV 4.5.4-dev
##### System information (version)

- OpenCV => 4.5.4-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => precompiled from opencv-contrib-python-headless 4.5.4.58

##### Detailed description

Issue encountered in python: https://github.com/opencv/opencv-python/issues/575
cvtColor should be able to convert a single pixel's color as it does in version 4.5.3

##### Steps to reproduce

```
import cv2
import numpy as np

pixel = np.uint8([[[40, 50, 200]]])
new_pixel = cv2.cvtColor(pixel, cv2.COLOR_RGB2BGR)
print(new_pixel)
```

with OpenCV 4.5.3, this runs successfully. With OpenCV 4.5.4-dev, I get the following error:
`OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix.cpp:466: error: (-215:Assertion failed) _step >= minstep in function 'cv::Mat::Mat'`

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by alalek**
resolves #20968
relates #20558

### CODE REVIEW

**Comment by alalek** [comment]
:+1:
