### PR TITLE
imgproc: support CV_Bool in morphology filters 🤖🤖🤖

### LINKED ISSUE #29798: cv::dilate asserts on input mask of type CV_Bool
### System Information

OpenCV version: 4.13 and 5.0.0
OS: Windows+macOS
Compilers: MSVS 2022/2026 and XCode 16.1/26.4 Clang

### Detailed description

When cv::dilate is passed a cv::Mat_<bool>, this worked fine in 4.x, but now throws an exception.

I believe this function was missed when CV_Bool was added, and the assertion should be extended to allow CV_Bool as iDepth value.

This behaviour violates [the expectation expressed in the migration guide ](https://github.com/opencv/opencv/wiki/OpenCV-4-to-5-migration#new-data-types)as

    CV_Bool matrices can now be used as masks wherever a CV_8U or CV_8S mask was previously accepted.

See also previous similar issues: https://github.com/opencv/opencv/issues/29578, https://github.com/opencv/opencv/issues/29593 https://github.com/opencv/opencv/issues/29596 

### Steps to reproduce

```cpp
#include <opencv2/imgproc.hpp>

int main()
{
    cv::Mat_<bool> mask(2,2);
    cv::dilate(mask, mask);
}
```

This works with OpenCV 4.13 but throws an exception with OpenCV 5.0.0:

OpenCV(5.0.0) .../modules/imgproc/src/morph.simd.hpp:762: error: (-213:The function/feature is not implemented) Unsupported data type (

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by naumanAhmed3**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      A focused regression test is included in `modules/imgproc/test/test_filter.cpp`; no external test data is needed.
- [ ] The feature is well documented and sample code can be built with the project CMake

## Summary

Fixes #29798.

`cv::dilate` now accepts `CV_Bool` matrices by routing the boolean depth through the existing one-byte morphology SIMD implementations for row, column, and full-kernel filters.

Added `Imgproc_Morphology.bool_dilate` to verify a boolean mask is dilated correctly and retains `CV_Bool` output type.

## Validation

- `git diff --check` passes.
- Native OpenCV tests were not run locally because this environment has no CMake, Ninja, or OpenCV source build.
- OpenCV CI should validate the change across supported compilers and architectures.

### CODE REVIEW

**Comment by asmorkalov** [comment]
Duplicates https://github.com/opencv/opencv/pull/29799
