### ISSUE TITLE
Opencv 4.10 Can't Decode Webp from Memory   use Java1.8

### ISSUE THREAD

**Issue by sunlightyxy** [opencv/opencv#15047]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 5.4.0-6ubuntu1~16.04.10
- Compiler => Java

##### Detailed description

I use jdk1.8 and opencv410 to read webp picture，I can open and write webp format from file with no problem, but I can't decode from memory. The code (at the end) returns:

imdecode_(''): can't read data: OpenCV(4.1.0) /home/yuxiaoyang/repo_test/xmss_3rdparty/opencv-4.1.0-imsize/modules/imgcodecs/src/grfmt_webp.cpp:164: error: (-215:Assertion failed) data.rows == 1 in function 'readData'

However, it works with opencv 3.1.0 

**Code：**,
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        String rotate6 = "/tmp/webp.webp";
        Mat imdecode = Imgcodecs.imdecode(new MatOfByte(FileUtils.readFileToByteArray(new File(rotate6))), Imgcodecs.IMREAD_UNCHANGED);
        System.out.println("imdecode width=" + imdecode.width());
        System.out.println("imdecode height=" + imdecode.height());

**Code Return：**
imdecode_(''): can't read data: OpenCV(4.1.0) /home/yuxiaoyang/repo_test/xmss_3rdparty/opencv-4.1.0-imsize/modules/imgcodecs/src/grfmt_webp.cpp:164: error: (-215:Assertion failed) data.rows == 1 in function 'readData'

imdecode width=0
imdecode height=0

**Comment by sunlightyxy** [comment]
> ##### System information (version)
> * OpenCV => 4.1.0
> * Operating System / Platform => Ubuntu 5.4.0-6ubuntu1~16.04.10
> * Compiler => Java
> 
> ##### Detailed description
> I use jdk1.8 and opencv410 to read webp picture，I can open and write webp format from file with no problem, but I can't decode from memory. The code (at the end) returns:
> 
> imdecode_(''): can't read data: OpenCV(4.1.0) /home/yuxiaoyang/repo_test/xmss_3rdparty/opencv-4.1.0-imsize/modules/imgcodecs/src/grfmt_webp.cpp:164: error: (-215:Assertion failed) data.rows == 1 in function 'readData'
> 
> However, it works with opencv 3.1.0
> 
> **Code：**,
> System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
> String rotate6 = "/tmp/webp.webp";
> Mat imdecode = Imgcodecs.imdecode(new MatOfByte(FileUtils.readFileToByteArray(new File(rotate6))), Imgcodecs.IMREAD_UNCHANGED);
> System.out.println("imdecode width=" + imdecode.width());
> System.out.println("imdecode height=" + imdecode.height());
> 
> **Code Return：**
> imdecode_(''): can't read data: OpenCV(4.1.0) /home/yuxiaoyang/repo_test/xmss_3rdparty/opencv-4.1.0-imsize/modules/imgcodecs/src/grfmt_webp.cpp:164: error: (-215:Assertion failed) data.rows == 1 in function 'readData'
> 
> imdecode width=0
> imdecode height=0
> 
> ##### Steps to reproduce

https://github.com/opencv/opencv/issues/15047#issue-468054510

**Comment by sunlightyxy** [comment]
familiar with this question:https://github.com/opencv/opencv/issues/15047#issue-468054510

**Comment by sunlightyxy** [comment]
familiar with this question：https://answers.opencv.org/question/215146/cant-decode-webp/

**Comment by alalek** [comment]
problem is duplicate of #14978
fixed here: #14989 (next release)

**Comment by sunlightyxy** [comment]
I'd like to know when the next version will be released？thanks
