### ISSUE TITLE
Opencv cv::dnn::readNetFromONNX throws error

### ISSUE THREAD

**Issue by carter54** [opencv/opencv#20643]
When I try to load an onnx model in opencv by 
```
#include <opencv2/dnn.hpp>
#include <iostream>
model_path = "path to the onnx model";
Net net = cv::dnn::readNetFromONNX(model_path);
```
It throws this error:
```
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp (429) cv::dnn::dnn4_v20210608::ONNXImporter::populateNet DNN/ONNX: loading ONNX v6 model produced by 'pytorch':1.9. Number of nodes = 137, inputs = 1, outputs = 1
OpenCV(4.5.3) Error: The function/feature is not implemented (Unsupported Expand op) in cv::dnn::dnn4_v20210608::ONNXImporter::handleNode, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp, line 1719
[ERROR:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp (2127) cv::dnn::dnn4_v20210608::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Expand]:(505)
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp (2131) cv::dnn::dnn4_v20210608::ONNXImporter::handleNode     Input[0] = '491'
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp (2131) cv::dnn::dnn4_v20210608::ONNXImporter::handleNode     Input[1] = '504'
[ INFO:0] global C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp (2135) cv::dnn::dnn4_v20210608::ONNXImporter::handleNode     Output[0] = '505'
OpenCV(4.5.3) Error: Unspecified error (> Node [Expand]:(505) parse error: OpenCV(4.5.3) C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1719: error: (-213:The function/feature is not implemented) Unsupported Expand op in function 'cv::dnn::dnn4_v20210608::ONNXImporter::handleNode'
> ) in cv::dnn::dnn4_v20210608::ONNXImporter::handleNode, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp, line 2146
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.3) Error: Unspecified error (> Node [Expand]:(505) parse error: OpenCV(4.5.3) C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1719: error: (-213:The function/feature is not implemented) Unsupported Expand op in function 'cv::dnn::dnn4_v20210608::ONNXImporter::handleNode'
> ) in cv::dnn::dnn4_v20210608::ONNXImporter::handleNode, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp, line 2146
```

##### System information (version)
- OpenCV => 4.5.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Onnx model
[sinet_optim.zip](https://github.com/opencv/opencv/files/7096074/sinet_optim.zip)

**Comment by rogday** [comment]
The `Expand` layer is failing because it does nothing, it should be fixed by https://github.com/opencv/opencv/pull/20605. The second problem is that `PReLU` layer access pattern of blob with one element inside is not correct, https://github.com/opencv/opencv/pull/20674 fixes it.
