### ISSUE TITLE
4.5.2 static library, highgui module compile failure LNK2019

### ISSUE THREAD

**Issue by LiuPeiqi-CNHN** [opencv/opencv#19870]
##### System information (version)

- OpenCV => 4.5.2 **static library**
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description
I have a application use highgui, but when I upgrade opencv from 451 to 452, a LNK2019 error come out:

`
1>opencv_highgui452.lib(window.obj) : error LNK2019: 无法解析的外部符号【unresolved external symbol】 "double __cdecl cvGetPropVsync_W32(char const *)" (?cvGetPropVsync_W32@@YANPEBD@Z)，函数【Function】 "double __cdecl cv::getWindowProperty(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?getWindowProperty@cv@@YANAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) 中引用了该符号
1>opencv_highgui452.lib(window.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl cvSetPropVsync_W32(char const *,bool)" (?cvSetPropVsync_W32@@YAXPEBD_N@Z)，函数 "void __cdecl cv::setWindowProperty(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,double)" (?setWindowProperty@cv@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HN@Z) 中引用了该符号
`

cvGetPropVsync_W32 and cvSetPropVsync_W32 is define in [highgui/src/precomp.hpp](https://github.com/opencv/opencv/blob/6e8daaec0f46aaba9ea22e2afce47307b1dbff9f/modules/highgui/src/precomp.hpp#L118), both of them is only defined but without implement. 
```cs
double cvGetPropVsync_W32(const char* name);
void cvSetPropVsync_W32(const char* name, const bool enabled);
```

So I delete them in opencv source code and build highgui module again, then LNK2019 don't happen and complie success:
1. highgui/src/window.cpp, [Line195](https://github.com/opencv/opencv/blob/6e8daaec0f46aaba9ea22e2afce47307b1dbff9f/modules/highgui/src/window.cpp#L95)
```cs
//case cv::WND_PROP_VSYNC:
//    #if defined (HAVE_WIN32UI)
//        cvSetPropVsync_W32(name, (prop_value != 0));
//    #else
//        // not implemented yet for other toolkits
//    #endif
//break;
```
2. highgui/src/window.cpp, [Line193](https://github.com/opencv/opencv/blob/6e8daaec0f46aaba9ea22e2afce47307b1dbff9f/modules/highgui/src/window.cpp#L193)
```cs
//case cv::WND_PROP_VSYNC:
//    #if defined (HAVE_WIN32UI)
//        return cvGetPropVsync_W32(name);
//    #else
//        return -1;
//    #endif
//break;
```

**Comment by berak** [comment]
definitions are in window_w32.cpp

[cvGetPropVsync_W32](https://github.com/opencv/opencv/blob/9d227641c9db68e1b39fab6d8e12042d0684012b/modules/highgui/src/window_w32.cpp#L599)
[cvSetPropVsync_W32](https://github.com/opencv/opencv/blob/9d227641c9db68e1b39fab6d8e12042d0684012b/modules/highgui/src/window_w32.cpp#L642)

(can't reproduce it, either)

**Comment by LiuPeiqi-CNHN** [comment]
> definitions are in window_w32.cpp
> 
> [cvGetPropVsync_W32](https://github.com/opencv/opencv/blob/9d227641c9db68e1b39fab6d8e12042d0684012b/modules/highgui/src/window_w32.cpp#L599)
> [cvSetPropVsync_W32](https://github.com/opencv/opencv/blob/9d227641c9db68e1b39fab6d8e12042d0684012b/modules/highgui/src/window_w32.cpp#L642)
> 
> (can't reproduce it, either)

**Probably I build opencv highgui with QT.**

**Full build options:**
```
General configuration for OpenCV 4.5.2 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            D:/cmake/opencv/opencv_contrib/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2021-04-03T02:09:33Z
    Host:                        Windows 10.0.17763 AMD64
    CMake:                       3.20.0-rc5
    CMake generator:             Visual Studio 16 2019
    CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe
    MSVC:                        1928
    Configuration:               Debug Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (15 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (29 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (4 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe  (ver 19.28.29913.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MT /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MTd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MT /O2 /Ob2 /DNDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MTd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /NODEFAULTLIB:atlthunk.lib /INCREMENTAL:NO  /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libcpmtd.lib /NODEFAULTLIB:msvcrtd.lib
    Linker flags (Debug):        /machine:x64  /NODEFAULTLIB:atlthunk.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcpmt.lib /NODEFAULTLIB:msvcrt.lib
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          wsock32 comctl32 gdi32 ole32 setupapi ws2_32 Qt5::Test Qt5::Concurrent Qt5::OpenGL D:/vcpkg/installed/x64-windows-static/lib/jpeg.lib D:/vcpkg/installed/x64-windows-static/lib/webp.lib D:/vcpkg/installed/x64-windows-static/lib/tiff.lib openjp2 D:/vcpkg/installed/x64-windows-static/lib/zlib.lib Qt5::Core Qt5::Gui Qt5::Widgets D:/vcpkg/installed/x64-windows-static/lib/libhdf5.lib correspondence multiview numeric D:/vcpkg/installed/x64-windows-static/lib/glog.lib gflags_static VTK::FiltersExtraction VTK::FiltersSources VTK::FiltersTexture VTK::IOExport VTK::IOGeometry VTK::IOPLY VTK::InteractionStyle VTK::RenderingCore VTK::RenderingLOD VTK::RenderingOpenGL2 opengl32 glu32
    3rdparty dependencies:       ittnotify libprotobuf ade IlmImf quirc ippiw ippicv

  OpenCV modules:
    To be built:                 alphamat aruco bgsegm bioinspired calib3d ccalib core cvv datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot quality rapid reg rgbd saliency sfm shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab viz wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    java_bindings_generator python_bindings_generator python_tests world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java julia matlab ovis python2 python3 ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         YES

  Windows RT support:            NO

  GUI: 
    QT:                          YES (ver 5.15.2)
      QT OpenGL support:         YES (Qt5::OpenGL 5.15.2)
    Win32 UI:                    YES
    OpenGL support:              YES (opengl32 glu32)
    VTK support:                 YES (ver 9.0.1)

  Media I/O: 
    ZLib:                        D:/vcpkg/installed/x64-windows-static/lib/zlib.lib (ver 1.2.11)
    JPEG:                        D:/vcpkg/installed/x64-windows-static/lib/jpeg.lib (ver 62)
    WEBP:                        D:/vcpkg/installed/x64-windows-static/lib/webp.lib (ver encoder: 0x020f)
    PNG:                         optimized D:/vcpkg/installed/x64-windows-static/lib/libpng16.lib debug D:/vcpkg/installed/x64-windows-static/debug/lib/libpng16d.lib (ver 1.6.37)
    TIFF:                        D:/vcpkg/installed/x64-windows-static/lib/tiff.lib (ver 42 / 4.1.0)
    JPEG 2000:                   OpenJPEG (ver 2.3.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.91.100)
      avformat:                  YES (58.45.100)
      avutil:                    YES (56.51.100)
      swscale:                   YES (5.7.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   D:/cmake/opencv/build_win_x64_static/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                D:/cmake/opencv/build_win_x64_static/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Eigen:                       YES (ver 3.3.9)
    OpenVX:                      NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (SVM NVD3D11)
    Include path:                D:/cmake/opencv/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            D:/Anaconda3/python.exe

  Install to:                    D:/cmake/opencv/build_win_x64_static/install
-----------------------------------------------------------------
```

**Comment by crackwitz** [comment]
@LiuPeiqi-CNHN please try a clean build, i.e. run `Build menu -> Clean solution`, then build.

the above-mentioned pull request shouldn't cause this problem.

functions such as `cvGetPropTopmost_W32` (existed before) are declared in `precomp.hpp` but defined in `window_w32.cpp`... but only actually used if `HAVE_WIN32UI`. _these_ functions don't cause this issue. I put `cvGetPropVsync_W32` (and ...set...) in place symmetrically to what already existed, so it should build exactly as the existing code.

I could offer to change `precomp.hpp` to guard all the `_W32` declarations same as the `_QT` declarations. that shouldn't be necessary.

I'd like to wait for whether a clean build fixes the issue.

**Comment by albertchristianto** [comment]
hi, @LiuPeiqi-CNHN, I have the same problem and have tried to clean, then rebuild it. it doesn't work. 
do you know where I can find the implementation of these _W32 function? or what is the solution for this bug? 
just comment the _W32 part?
best regards,
Albert Christianto

**Comment by alalek** [comment]
Need to properly align `#if` guards between files and backends:
- `#if defined (HAVE_WIN32UI)`
- `#if defined _WIN32` in `window_w32.cpp`

**Comment by crackwitz** [comment]
still can't reproduce. I can make changes but I have no way to check if that "fixes" anything.

**Comment by crackwitz** [comment]
big question once again, pull request against master or not?

**Comment by alalek** [comment]
> pull request against master or 3.4

We should start from "master" branch (at least to check fix for the problem).

---

> why people only see any issue just now.

Because `WITH_QT` is disabled by default (and we don't have such builds for Windows platform on CI).

```
 GUI: 
    QT:                          YES (ver 5.15.2)
      QT OpenGL support:         YES (Qt5::OpenGL 5.15.2)
```

**Comment by crackwitz** [comment]
I've added HAVE_QT checks in the accessor functions.

that brings my previous changes properly in line with existing code.

would you also like me to change the `#if defined _WIN32` guard in `window_w32.cpp` to `HAVE_WIN32UI`?

**Comment by albertchristianto** [comment]
hi, @crackwitz . 
I have tried your fix and it is built successfully. 
Thank you very much for your time.

**Comment by wei1224hf** [comment]
I have the same failure too.
Befor install QT5 , I can build it successfully, after install QT5 , build come this failure.
But how to fix this?
how to modify the sources\modules\highgui\src\window_w32.cpp ?
can't find the code 
`#if defined (HAVE_WIN32UI)`
nor
`#if defined _WIN32`

**Comment by wei1224hf** [comment]
I have the same failure too.
Befor install QT5 , I can build it successfully, after install QT5 , build come this failure.
But how to fix this?
how to modify the sources\modules\highgui\src\window_w32.cpp ?
can't find the code
`#if defined (HAVE_WIN32UI)`
nor
`#if defined _WIN32`

**Comment by albertchristianto** [comment]
hi @wei1224hf, 
I suggest you to use openCV 4.5.1 for a while. because OpenCV 4.5.2 WITH_QT is not stable yet. Actually I ran to another error message while build opencv WITH_QT in the python_binding project
best regards

**Comment by crackwitz** [comment]
this is the patch for the issue. it has been committed.

https://github.com/opencv/opencv/pull/19873/files
