### ISSUE TITLE
error: OpenCV(4.2.0) error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes

### ISSUE THREAD

**Issue by AliButtar** [opencv/opencv#18778]
##### System information (version)

- OpenCV => 4.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Anaconda Python

##### Detailed description

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\concat_layer.cpp:102: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes

I am using the OpenCV DNN module to do some predictions on images but in OpenCV 4.2 it's not working and giving me this error above. The same happens with Google Colab where OpenCV 4.2 is installed by default but as soon as I changed it to 4.1.0 it works right away. The error is also there from version 4.1.2 to 4.4.0, I didn't check every version in between but I did check the latest.

##### Steps to reproduce

https://colab.research.google.com/drive/1ciNEO_WbG6W72U1GOa6-jCOeAxBoz5VC?usp=sharing

Just run the cells in this notebook to reproduce the error. Do not run the first cell to see the error. Run it after you see the error so you see that everything works fine in 4.1.0

##### Issue submission checklist

 - [X] I report the issue, it's not a question
   
 - [X] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [X] I updated to latest OpenCV version and the issue is still there
   
 - [X] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by dkurt** [comment]
> OpenCV => 4.2

Please use the latest release

**Comment by LupusSanctus** [comment]
Text graph for the SSD Mobilenet V2 model obtained with:
```
gdown --id 1a-1vXD2K-XoVFYS_jl93zjKu3LyTi4O6
```
causes this error. I've regenerated the text graph using [``tf_text_graph_ssd.py``](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py) OpenCV tool:
```
python tf_text_graph_ssd.py --input <YOUR_PATH>/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb --config <YOUR_PATH>/ssd_mobilenet_v2_coco_2018_03_29/pipeline.config --output <YOUR_PATH>/ssd_mobilenet_v2_graph.pbtxt
```
then the pipeline from the attached [``colab notebook``](https://colab.research.google.com/drive/1ciNEO_WbG6W72U1GOa6-jCOeAxBoz5VC?usp=sharing) passed ([ssd_mobilenet_v2_graph.zip](https://github.com/opencv/opencv/files/5857207/ssd_mobilenet_v2_graph.zip)).

It should be noticed that there is a helpful OpenCV resource: ["TensorFlow Object Detection API"](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API#use-existing-config-file-for-your-model). It contains details about running TF object detection models with OpenCV and also a list of tested TF detection models and their text graphs: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API#use-existing-config-file-for-your-model

**Comment by ljburtz** [comment]
@LupusSanctus I'm having the same error. Thanks to the .pbtxt file that you provided in your comment, that error disappears. Thank you.
However the detected objects all have a score of 0, and therefore no bounding boxes are displayed on the baseball image.
I attach the [Colab](https://colab.research.google.com/drive/1OSng0TGjW8si3pOFWUVLhZa7EJ6ky6hO?usp=sharing) where I just download and unzip your .pbtxt and reproduce the issue.
Did you do an additional step appart from updating the .pbtxt to get the expected object detection bounding boxes?
Thanks!

**Comment by LupusSanctus** [comment]
@ljburtz, the problem is `def detect_objects(net, im):` function. Change it in the following way:
```
# For ach file in the directory
def detect_objects(net, im):
    dim = 300
    blob = cv2.dnn.blobFromImage(im, size=(dim, dim), swapRB=True, crop=False)

    # Pass blob to the network
    net.setInput(blob)

    # Peform Prediction
    objects = net.forward()
    return objects
```

Then we will get the expected result:
![baseball_res1](https://user-images.githubusercontent.com/7347318/105747738-38cf5180-5f52-11eb-9f61-9a8e98b6a975.png)

**Comment by ljburtz** [comment]
Thanks @LupusSanctus updating the arguments of blobFromImage() as you show works perfectly.
I wonder where is the best place to warn about this opencv version gotcha. How about in  the [list of tested TF detection models ](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API#use-existing-config-file-for-your-model) that you mention?

**Comment by asmorkalov** [comment]
The issue resolved. Close the ticket.
