### PR TITLE
GAPI: fix C++17 compilation errors in GNetPackage 

### LINKED ISSUE #17385: Build failure with GCC C++17 due to GNetPackage constructor
##### System information (version)

- OpenCV => 4.3.0-dev (4.3.0-317-g4e97c69792)
- Operating System / Platform => Linux 64 Bit
- Compiler => GCC 7.5.0

##### Detailed description

Using the C++17 standard, the compiler exits due to the following error:

```
<path_to_opencv>/opencv/modules/gapi/include/opencv2/gapi/infer.hpp:188:35: error: constructor delegates to itself
     GNetPackage() : GNetPackage({}) {}
```

By reverting the fix for MSVS2017/2019 introduced by commit 5e527d22e3a492f7504ae3006308d7f454d3fd54, the code compiles, however, this apparently breaks the build with MSVS2017/2019.
Concretely, one needs to change this part of `infer.hpp`

```
struct GAPI_EXPORTS GNetPackage {
    GNetPackage() : GNetPackage({}) {}
    explicit GNetPackage(std::initializer_list<GNetParam> &&ii);
```

back to

```
struct GAPI_EXPORTS GNetPackage {
    explicit GNetPackage(std::initializer_list<GNetParam> &&ii = {});
```

##### Steps to reproduce

These are the commands I've used, with the build directory residing in the OpenCV root directory.
I needed to build OpenEXR, as the version that was already installed on the system was out of date.

```
cmake -DCMAKE_CXX_STANDARD=17 -DBUILD_OPENEXR=ON ../
make -j16
```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by anton-potapov**
- explicitly declared default constructor
- made initilizer_list  constructor to accept the list by copy
   -- as it is  more canonical (and as copying the initializer_list does
not force copy of the list items)
   -- current version anyway does not do what it is intended to

(fixes #17385)

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

force_builders=ARMv7,Custom
build_image:Custom=centos:7
buildworker:Custom=linux-1
build_gapi_standalone:Custom=ade-0.1.1f

build_gapi_standalone:Linux x64=ade-0.1.1f
build_gapi_standalone:Win64=ade-0.1.1f
build_gapi_standalone:Mac=ade-0.1.1f
build_gapi_standalone:Linux x64 Debug=ade-0.1.1f

### CODE REVIEW

**Review by dmatveev — APPROVED** [review]
Thanks
