### ISSUE TITLE
Problem initializing Mat_

### ISSUE THREAD

**Issue by pauljurczak** [opencv/opencv#19412]
This OpenCV 4.5.1-dev snippet compiles with clang 10.0.0 and 11.0.1 and runs as expected on Ubuntu 18.04.5:
```
  constexpr int size = 64;  
  auto grid2{Mat_<Vec3i>(3, array<int, 3>{size, size, size}.data(), {42, 42, 42})};   
  cout << grid2(1, 2, 3) << endl;
```
but it fails to compile with gcc 9.3.0 and 10.1.0 (`CXX_STANDARD` 17 and 20) with this template instantiation error:
```
[build] [1/2  50% :: 2.801] Building CXX object CMakeFiles/ocv.dir/main.cpp.o
[build] FAILED: CMakeFiles/ocv.dir/main.cpp.o 
[build] /usr/local/bin/cmake -E time /usr/bin/g++-9 -DFMT_LOCALE -I/home/paul/include -isystem /usr/local/include/opencv4 -O3 -DNDEBUG -Wno-narrowing -std=gnu++2a -MD -MT CMakeFiles/ocv.dir/main.cpp.o -MF CMakeFiles/ocv.dir/main.cpp.o.d -o CMakeFiles/ocv.dir/main.cpp.o -c ../main.cpp
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp: In instantiation of ‘cv::Mat_<_Tp>::Mat_(std::initializer_list<_Tp>) [with _Tp = cv::Vec<int, 3>]’:
[build] ../main.cpp:14:91:   required from here
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: error: no matching function for call to ‘cv::Mat::Mat(std::initializer_list<cv::Vec<int, 3> >&)’
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:2076:5: note: candidate: ‘cv::Mat::Mat(cv::Mat&&)’
[build]  2076 |     Mat(Mat&& m);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:2076:15: note:   no known conversion for argument 1 from ‘std::initializer_list<cv::Vec<int, 3> >’ to ‘cv::Mat&&’
[build]  2076 |     Mat(Mat&& m);
[build]       |         ~~~~~~^
[build] In file included from /usr/local/include/opencv4/opencv2/core/cuda.hpp:1053,
[build]                  from /usr/local/include/opencv4/opencv2/stitching/detail/warpers.hpp:47,
[build]                  from /usr/local/include/opencv4/opencv2/stitching/warpers.hpp:46,
[build]                  from /usr/local/include/opencv4/opencv2/stitching.hpp:48,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:86,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/cuda.inl.hpp:627:1: note: candidate: ‘cv::Mat::Mat(const cv::cuda::GpuMat&)’
[build]   627 | Mat::Mat(const cuda::GpuMat& m)
[build]       | ^~~
[build] /usr/local/include/opencv4/opencv2/core/cuda.inl.hpp:627:30: note:   no known conversion for argument 1 from ‘std::initializer_list<cv::Vec<int, 3> >’ to ‘const cv::cuda::GpuMat&’
[build]   627 | Mat::Mat(const cuda::GpuMat& m)
[build]       |          ~~~~~~~~~~~~~~~~~~~~^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1044:37: note: candidate: ‘template<class _Tp> cv::Mat::Mat(const cv::MatCommaInitializer_<_Tp>&)’
[build]  1044 |     template<typename _Tp> explicit Mat(const MatCommaInitializer_<_Tp>& commaInitializer);
[build]       |                                     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1044:37: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: note:   ‘std::initializer_list<cv::Vec<int, 3> >’ is not derived from ‘const cv::MatCommaInitializer_<_Tp>’
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1040:37: note: candidate: ‘template<class _Tp> cv::Mat::Mat(const cv::Point3_<_Tp>&, bool)’
[build]  1040 |     template<typename _Tp> explicit Mat(const Point3_<_Tp>& pt, bool copyData=true);
[build]       |                                     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1040:37: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: note:   ‘std::initializer_list<cv::Vec<int, 3> >’ is not derived from ‘const cv::Point3_<_Tp>’
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1036:37: note: candidate: ‘template<class _Tp> cv::Mat::Mat(const cv::Point_<_Tp>&, bool)’
[build]  1036 |     template<typename _Tp> explicit Mat(const Point_<_Tp>& pt, bool copyData=true);
[build]       |                                     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1036:37: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: note:   ‘std::initializer_list<cv::Vec<int, 3> >’ is not derived from ‘const cv::Point_<_Tp>’
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1032:51: note: candidate: ‘template<class _Tp, int m, int n> cv::Mat::Mat(const cv::Matx<_Tp, m, n>&, bool)’
[build]  1032 |     template<typename _Tp, int m, int n> explicit Mat(const Matx<_Tp, m, n>& mtx, bool copyData=true);
[build]       |                                                   ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1032:51: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: note:   ‘std::initializer_list<cv::Vec<int, 3> >’ is not derived from ‘const cv::Matx<_Tp, m, n>’
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1028:44: note: candidate: ‘template<class _Tp, int n> cv::Mat::Mat(const cv::Vec<_Tp, m>&, bool)’
[build]  1028 |     template<typename _Tp, int n> explicit Mat(const Vec<_Tp, n>& vec, bool copyData=true);
[build]       |                                            ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1028:44: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: note:   ‘std::initializer_list<cv::Vec<int, 3> >’ is not derived from ‘const cv::Vec<_Tp, m>’
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1024:49: note: candidate: ‘template<class _Tp, long unsigned int _Nm> cv::Mat::Mat(const std::array<_Tp, _Nm>&, bool)’
[build]  1024 |     template<typename _Tp, size_t _Nm> explicit Mat(const std::array<_Tp, _Nm>& arr, bool copyData=false);
[build]       |                                                 ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1024:49: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: note:   ‘std::initializer_list<cv::Vec<int, 3> >’ is not derived from ‘const std::array<_Tp, _Nm>’
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1020:37: note: candidate: ‘template<class _Tp> cv::Mat::Mat(std::initializer_list<int>, std::initializer_list<_Tp>)’
[build]  1020 |     template<typename _Tp> explicit Mat(const std::initializer_list<int> sizes, const std::initializer_list<_Tp> list);
[build]       |                                     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1020:37: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: note:   candidate expects 2 arguments, 1 provided
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1016:14: note: candidate: ‘template<class _Tp, class> cv::Mat::Mat(std::initializer_list<_Tp>)’
[build]  1016 |     explicit Mat(const std::initializer_list<_Tp> list);
[build]       |              ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1016:14: note:   template argument deduction/substitution failed:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1015:28: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
[build]  1015 |     template<typename _Tp, typename = typename std::enable_if<std::is_arithmetic<_Tp>::value>::type>
[build]       |                            ^~~~~~~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1011:37: note: candidate: ‘template<class _Tp> cv::Mat::Mat(const std::vector<_RealType>&, bool)’
[build]  1011 |     template<typename _Tp> explicit Mat(const std::vector<_Tp>& vec, bool copyData=false);
[build]       |                                     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:1011:37: note:   template argument deduction/substitution failed:
[build] In file included from /usr/local/include/opencv4/opencv2/core/mat.hpp:3723,
[build]                  from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.inl.hpp:1345:15: note:   ‘std::initializer_list<cv::Vec<int, 3> >’ is not derived from ‘const std::vector<_RealType>’
[build]  1345 |     : Mat(list)
[build]       |               ^
[build] In file included from /usr/local/include/opencv4/opencv2/core.hpp:59,
[build]                  from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
[build]                  from ../common.hpp:10,
[build]                  from ../main.cpp:1:
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:993:5: note: candidate: ‘cv::Mat::Mat(const cv::Mat&, const std::vector<cv::Range>&)’
[build]   993 |     Mat(const Mat& m, const std::vector<Range>& ranges);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:993:5: note:   candidate expects 2 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:983:5: note: candidate: ‘cv::Mat::Mat(const cv::Mat&, const cv::Range*)’
[build]   983 |     Mat(const Mat& m, const Range* ranges);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:983:5: note:   candidate expects 2 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:973:5: note: candidate: ‘cv::Mat::Mat(const cv::Mat&, const Rect&)’
[build]   973 |     Mat(const Mat& m, const Rect& roi);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:973:5: note:   candidate expects 2 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:963:5: note: candidate: ‘cv::Mat::Mat(const cv::Mat&, const cv::Range&, const cv::Range&)’
[build]   963 |     Mat(const Mat& m, const Range& rowRange, const Range& colRange=Range::all());
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:963:5: note:   candidate expects 3 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:951:5: note: candidate: ‘cv::Mat::Mat(const std::vector<int>&, int, void*, const size_t*)’
[build]   951 |     Mat(const std::vector<int>& sizes, int type, void* data, const size_t* steps=0);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:951:5: note:   candidate expects 4 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:937:5: note: candidate: ‘cv::Mat::Mat(int, const int*, int, void*, const size_t*)’
[build]   937 |     Mat(int ndims, const int* sizes, int type, void* data, const size_t* steps=0);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:937:5: note:   candidate expects 5 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:922:5: note: candidate: ‘cv::Mat::Mat(cv::Size, int, void*, size_t)’
[build]   922 |     Mat(Size size, int type, void* data, size_t step=AUTO_STEP);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:922:5: note:   candidate expects 4 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:906:5: note: candidate: ‘cv::Mat::Mat(int, int, int, void*, size_t)’
[build]   906 |     Mat(int rows, int cols, int type, void* data, size_t step=AUTO_STEP);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:906:5: note:   candidate expects 5 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:890:5: note: candidate: ‘cv::Mat::Mat(const cv::Mat&)’
[build]   890 |     Mat(const Mat& m);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:890:20: note:   no known conversion for argument 1 from ‘std::initializer_list<cv::Vec<int, 3> >’ to ‘const cv::Mat&’
[build]   890 |     Mat(const Mat& m);
[build]       |         ~~~~~~~~~~~^
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:880:5: note: candidate: ‘cv::Mat::Mat(const std::vector<int>&, int, const Scalar&)’
[build]   880 |     Mat(const std::vector<int>& sizes, int type, const Scalar& s);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:880:5: note:   candidate expects 3 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:870:5: note: candidate: ‘cv::Mat::Mat(int, const int*, int, const Scalar&)’
[build]   870 |     Mat(int ndims, const int* sizes, int type, const Scalar& s);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:870:5: note:   candidate expects 4 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:859:5: note: candidate: ‘cv::Mat::Mat(const std::vector<int>&, int)’
[build]   859 |     Mat(const std::vector<int>& sizes, int type);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:859:5: note:   candidate expects 2 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:852:5: note: candidate: ‘cv::Mat::Mat(int, const int*, int)’
[build]   852 |     Mat(int ndims, const int* sizes, int type);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:852:5: note:   candidate expects 3 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:844:5: note: candidate: ‘cv::Mat::Mat(cv::Size, int, const Scalar&)’
[build]   844 |     Mat(Size size, int type, const Scalar& s);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:844:5: note:   candidate expects 3 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:833:5: note: candidate: ‘cv::Mat::Mat(int, int, int, const Scalar&)’
[build]   833 |     Mat(int rows, int cols, int type, const Scalar& s);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:833:5: note:   candidate expects 4 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:822:5: note: candidate: ‘cv::Mat::Mat(cv::Size, int)’
[build]   822 |     Mat(Size size, int type);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:822:5: note:   candidate expects 2 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:814:5: note: candidate: ‘cv::Mat::Mat(int, int, int)’
[build]   814 |     Mat(int rows, int cols, int type);
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:814:5: note:   candidate expects 3 arguments, 1 provided
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:806:5: note: candidate: ‘cv::Mat::Mat()’
[build]   806 |     Mat();
[build]       |     ^~~
[build] /usr/local/include/opencv4/opencv2/core/mat.hpp:806:5: note:   candidate expects 0 arguments, 1 provided
```

Note that this similar code doesn't exhibit that problem:
```
  constexpr int size = 64;  
  auto grid1{Mat_<int>(3, array<int, 3>{size, size, size}.data(), 42)};   
  cout << grid1(1, 2, 3) << endl;
```

**Comment by alalek** [comment]
This works with GCC 10 (C++14):
```.diff
-Mat_<Voxel2> grid2{Mat_<Voxel2>(3, array<int, 3>{size, size, size}.data(), {42, 42, 42})};
+Mat_<Voxel2> grid2(3, array<int, 3>{size, size, size}.data(), {42, 42, 42});
```

**Comment by pauljurczak** [comment]
Indeed, it does. It solves my problem.
