### PR TITLE
doc: js: unwrap promise-typed cv object

### LINKED ISSUE #27129: Basic example for opencv.js doesn't work with version 4.11.0 and later
### System Information

iOS 15.8.3, both Chrome and Safari

### Detailed description

```TypeError: cv.imread is not a function. (In 'cv.imread(imgElement)', 'cv.imread' is undefined)```

### Steps to reproduce

https://docs.opencv.org/4.11.0/d0/d84/tutorial_js_usage.html

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by Kumataro**
Close #27129 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
build_image:Docs=docs-js
build_image:Custom=javascript
buildworker:Custom=linux-1,linux-4,linux-f1
```

### CODE REVIEW

**Comment by Kumataro** [comment]
Unfortunately, we cannot check this fix on the preview where opencv.js is not installed.

https://pullrequest.opencv.org/buildbot/export/pr/27148/docs/d0/d84/tutorial_js_usage.html

**Comment by Kumataro** [comment]
@opencv-alalek  Thank you to custom CI/CD setting, we can confirm that it works fine in preview.

**Review by opencv-alalek — APPROVED** [review]
@Kumataro Thank you :+1:
