### ISSUE TITLE
Basic example for opencv.js doesn't work with version 4.11.0 and later

### ISSUE THREAD

**Issue by freealise** [opencv/opencv#27129]
### System Information

iOS 15.8.3, both Chrome and Safari

### Detailed description

```TypeError: cv.imread is not a function. (In 'cv.imread(imgElement)', 'cv.imread' is undefined)```

### Steps to reproduce

https://docs.opencv.org/4.11.0/d0/d84/tutorial_js_usage.html

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by Kumataro** [comment]
Hello, thank you for your report. I can reproduce this problem, and it seems to be related  not only `imread()` but also all features.

Maybe it is same problem, see https://github.com/opencv/opencv/issues/25057

- https://docs.opencv.org/4.10.0/js_setup_usage.html-> it works well.
- https://docs.opencv.org/4.11.0/js_setup_usage.html -> it does not work well
- https://docs.opencv.org/4.x/js_setup_usage.html -> it does not work well

**Comment by Kumataro** [comment]
Workaround is here for the promise-typed cv.

```diff
kmtr@kmtr-VMware-Virtual-Platform:~/work/opencv4$ git diff
diff --git a/doc/js_tutorials/js_assets/js_setup_usage.html b/doc/js_tutorials/js_assets/js_setup_usage.html
index 4f00dc3bd9..be97649156 100644
--- a/doc/js_tutorials/js_assets/js_setup_usage.html
+++ b/doc/js_tutorials/js_assets/js_setup_usage.html
@@ -37,9 +37,11 @@ inputElement.addEventListener('change', (e) => {
 }, false);

 imgElement.onload = function() {
-    let mat = cv.imread(imgElement);
-    cv.imshow('canvasOutput', mat);
-    mat.delete();
+    cv.then((cv2) => {
+        let mat = cv2.imread(imgElement);
+        cv2.imshow('canvasOutput', mat);
+        mat.delete();
+    });
 };

 function onOpenCvReady() { // eslint-disable-line no-unused-vars
```

**Comment by Kumataro** [comment]
After fix, it seems work well. We need `cv = await cv ` to unwrap for promise-typed `cv` object.

https://pullrequest.opencv.org/buildbot/export/pr/27148/docs/d0/d84/tutorial_js_usage.html
