### PR TITLE
Support Yolov4

### PR DESCRIPTION
**Pull request by l-bat**
**Merge with extra:** opencv/opencv_extra#753
resolves: #17148 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under OpenCV (BSD) License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2020.1.0:16.04
build_image:Custom Win=openvino-2020.2.0
build_image:Custom Mac=openvino-2020.2.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```
**Performance tests**
**CPU:** Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
| Net               | Backend                      | branch 3.4 | branch yolov4 |
|-------------------|------------------------------|------------|---------------|
| TinyYoloVOC       | DNN_BACKEND_INFERENCE_ENGINE | 23.29      | 23.15         |
| TinyYoloVOC       | DNN_BACKEND_OPENCV           | 35.24      | 35.29         |
| YoloVOC @ 416x416 | DNN_BACKEND_INFERENCE_ENGINE | 88.42      | 88.54         |
| YoloVOC @ 416x416 | DNN_BACKEND_OPENCV           | 129.50     | 130.03        |
| YOLOv3 @ 416x416  | DNN_BACKEND_INFERENCE_ENGINE | 200.76     | 200.93        |
| YOLOv3 @ 416x416  | DNN_BACKEND_OPENCV           | 273.93     | 274.48        |
| YOLOv4 @ 416x416  | DNN_BACKEND_INFERENCE_ENGINE |      -     | 537.48        |
| YOLOv4 @ 416x416  | DNN_BACKEND_OPENCV           |      -     | 712.38        |

```python
import cv2 as cv

net = cv.dnn_DetectionModel(yolov4.cfg', 'yolov4.weights)
net.setInputSize(608, 608)
net.setInputScale(1.0 / 255)
net.setInputSwapRB(True)

frame = cv.imread('example.jpg')

with open('coco.names', 'rt') as f:
    names = f.read().rstrip('\n').split('\n')

classes, confidences, boxes = net.detect(frame, confThreshold=0.1, nmsThreshold=0.4)
for classId, confidence, box in zip(classes.flatten(), confidences.flatten(), boxes):
    label = '%.2f' % confidence
    label = '%s: %s' % (names[classId], label)
    labelSize, baseLine = cv.getTextSize(label, cv.FONT_HERSHEY_SIMPLEX, 0.5, 1)
    left, top, width, height = box
    top = max(top, labelSize[1])
    cv.rectangle(frame, box, color=(0, 255, 0), thickness=3)
    cv.rectangle(frame, (left, top - labelSize[1]), (left + labelSize[0], top + baseLine), (255, 255, 255), cv.FILLED)
    cv.putText(frame, label, (left, top), cv.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0))

cv.imshow('out', frame)
```

yolo_out

### CODE REVIEW

**Comment by dkurt** [comment]
Can you please describe what "before" and "after" means?

**Comment by dkurt** [comment]
> Yolov3 | OpenCV | 17210.52 | 14720.49
-- | -- | -- | --

Have you used `perf_dnn` for  bahcnmarking? Seems incorrect for me

File: modules/dnn/src/layers/elementwise_layers.cpp [hunk 1]
```diff
@@ -654,11 +654,19 @@ struct SwishFunctor : public BaseFunctor
 struct MishFunctor : public BaseFunctor
 {
     typedef MishLayer Layer;
+    float MISH_THRESHOLD;
```
Comment (dkurt) [inline modules/dnn/src/layers/elementwise_layers.cpp:657]: What is the source of this new parameter?

**Comment by l-bat** [comment]
> Can you please describe what "before" and "after" means?

“Before” means the results of running performance tests before this PR changes (without Yolov4 support)

**Comment by l-bat** [comment]
> > Yolov3 | OpenCV | 17210.52 | 14720.49
> 
> Have you used `perf_dnn` for bahcnmarking? Seems incorrect for me

Yes, I used `perf_dnn`

File: modules/dnn/src/layers/region_layer.cpp [hunk 2]
```diff
@@ -292,8 +293,10 @@ class RegionLayerImpl CV_FINAL : public RegionLayer
                             if (classfix == -1 && scale < .5) scale = 0;  // if(t0 < 0.5) t0 = 0;
                             int box_index = index_sample_offset + index * cell_size;
 
-                            dstData[box_index + 0] = (x + logistic_activate(srcData[box_index + 0])) / cols;
-                            dstData[box_index + 1] = (y + logistic_activate(srcData[box_index + 1])) / rows;
+                            float x_tmp = logistic_activate(srcData[box_index + 0]) * scale_x_y - (scale_x_y - 1) / 2;
+                            float y_tmp = logistic_activate(srcData[box_index + 1]) * scale_x_y - (scale_x_y - 1) / 2;
```
Comment (dkurt) [inline modules/dnn/src/layers/region_layer.cpp:297]: Maybe better
```cpp
float x_tmp = (logistic_activate(srcData[box_index + 0]) - 0.5f) * scale_x_y + 0.5f;
```

File: modules/dnn/src/layers/elementwise_layers.cpp (hunk 1 above)
Comment (l-bat) [reply modules/dnn/src/layers/elementwise_layers.cpp:657]: https://github.com/AlexeyAB/darknet/blob/36c73c5b9e3f2e72049fb68566e32632f6c70e85/src/activations.c#L150

Comment (dkurt) [reply modules/dnn/src/layers/elementwise_layers.cpp:657]: Do we still need threshold or can revert layer?

**Comment by rgov** [comment]
Great to see that this is in the 3.4.11 milestone. Will this reach the 4.x branch as well?

**Comment by l-bat** [comment]
Thank you for your interest @rgov, @wooseokyourself! These PR changes will be merged into master branch next week.

**Comment by sqiprasanna** [comment]
Hi @l-bat , Can I know how to inference on video using OpenCV(cv2.dnn). I'm getting below error when trying to load. Please help with this.
`---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: mish in function 'ReadDarknetFromCfgStream'


The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-1-704183f19471> in <module>()
      1 import cv2 as cv
      2 
----> 3 net = cv.dnn_DetectionModel('/datadrive/INTERN/darknet/yolov4-custom.cfg', '/datadrive/INTERN/darknet/backup/yolov4-custom_6000.weights')
      4 net.setInputSize(416, 416)
      5 net.setInputScale(1.0 / 255)

SystemError: <class 'cv2.dnn_DetectionModel'> returned a result with an error set`  



`---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-3-716457c5e28a> in <module>()
     24 
     25 # Define network from configuration file and load the weights from the given weights file
---> 26 net = cv2.dnn.readNet(args['weights'],args['config'])
     27 
     28 

error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: mish in function 'ReadDarknetFromCfgStream'`

**Comment by dkurt** [comment]
@sqiprasanna, please read all the messages carefully - you're trying to use OpenCV 4.2.0. We just merged the changes yesterday.

**Comment by AlexeyAB** [comment]
@l-bat @dkurt 
Is Yolov4 more than 2 times slower than Yolov3 due to MISH-activation?

**Comment by sqiprasanna** [comment]
@l-bat Thanks for the reply. I just used this yolov4 for training on my custom dataset. It really worked well on detecting images. I'm more excited to test this model on real-time detection using OpenCV. As I see here you're trying to include yolov4 in OpenCV dnn. I just want to really appreciate the work you've done and would like to see adding yolov4 into OpenCV. 

Thank you again for your hard work. Have a nice day.

**Comment by dkurt** [comment]
@AlexeyAB, it might be, yes. I'd like to recommend to open an issue for YOLOv4 optimization (some research with per-layer performance will be very helpful). Thanks!

File: modules/dnn/src/layers/elementwise_layers.cpp (hunk 1 above)
Comment (YashasSamaga) [reply modules/dnn/src/layers/elementwise_layers.cpp]: `MISH_THRESHOLD` is simply a cutoff for switching from a numerically unstable expression to a numerically stable expression in softplus.

The current OpenCV implementation which is `x * tanh(log(1 + exp(x)))` is numerically unstable. This implementation goes to zero when x is more negative than `-16`. Using `std::log1p` instead of `std::log(1 + std::exp(x))` might improve the numerical accuracy but this will still suffer as numbers become even more negative.

Darknet has been using `log(1 + exp(x))` and it seems to be very inaccurate (and so will OCV CPU implementation) for numbers smaller than `-2`. I have dumped the values [here](https://gist.github.com/YashasSamaga/3fdf001d32f04062e3f36495d5c962db) comparing darknet with [other implementations](https://cs.stackexchange.com/questions/125002/fast-and-stable-x-tanhlog1pexpx-computation).

If I remember correctly, the dynamic range of activations in YOLOv4 seems to cover the range ~`[-12000, 2000]` for a bunch of random 10 natural images. The middle 50% is covered in ~`[-100, 100]`.

Both Darknet and OpenCV CPU are giving really good results with their implementations. I don't know if there is a need to have a numerically stable implementation. But just for record sake, I have made a reply here.

Comment (AlexeyAB) [reply modules/dnn/src/layers/elementwise_layers.cpp]: Now we use such Mish-implementation  https://github.com/AlexeyAB/darknet/issues/5452#issuecomment-627414024
```cpp
 __device__ float mish_yashas(float x) 
 { 
     float e = __expf(x); 
     if (x <= -18.0f) 
         return x * e; 
  
     float n = e * e + 2 * e; 
     if (x <= -5.0f) 
         return x * __fdividef(n, n + 2); 
  
     return x - 2 * __fdividef(x, n + 2); 
 } 
```
And get:
* +3% speedup
* the same accuracy on MSCOCO (testdev) yolov4.cfg 512x512 - 43.0% AP, 64.9% AP50
```
overall performance
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.430
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.649
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.465
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.243
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.461
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.552
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.341
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.542
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.572
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.375
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.612
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.729
Done (t=506.74s)
```

**Comment by marcusbrito** [comment]
Hello,
I had understood that yolov4 was already working on version 3.4.10, but I tried and got the error:

`cv2.error: OpenCV(3.4.10) /opencv-3.4.10/modules/dnn/src/darknet/darknet_io.cpp:821: error: (-212:Parsing error) Unsupported activation: mish in function 'ReadDarknetFromCfgStream'`

I'm buildin OpenCV 3.4.10 from source on a docker container. I'm cloning this repository:
https://github.com/Itseez/opencv/archive/3.4.10.zip

I'm not very familiar with this, so can someone please give me a simple answer like "It's not working yet" or "It's already working, you can git clone this link", instead of referencing another one confused thread.

**Comment by mshabunin** [comment]
It's not working yet, wait for the next release.

**Comment by KyloEntro** [comment]
Hi,
Any date for the next release ? 

Thanks

**Comment by dkurt** [comment]
> @l-bat @dkurt
Is Yolov4 more than 2 times slower than Yolov3 due to MISH-activation?

@AlexeyAB, please take a look at Mish optimization for CPU: https://github.com/opencv/opencv/pull/17624
