### PR TITLE
imgproc: accept CV_Bool masks in distanceTransform 🤖🤖🤖

### LINKED ISSUE #29596: cv::distanceTransform throws exception on input mask of type CV_Bool
### System Information

OpenCV version: 4.13 and 5.0.0
OS: Windows+macOS
Compilers: MSVS 2022/2026 and XCode 16.1/26.4 Clang

### Detailed description

In OpenCV 4.x, `cv::Mat_<bool>::depth()` returns 0 (==`CV_8U`)
In OpenCV 5.0.0, `cv::Mat_<bool>::depth()` returns 9 (==`CV_Bool`)

In OpenCV 5.0.0, `cv::distanceTransform` is implemented with CALL_HAL, e.g.

    CALL_HAL(distanceTransform, cv_hal_distanceTransform, src.ptr<uchar>(), src.step, dst.ptr<uchar>(), dst.step,
             src.cols, src.rows, CV_32F, distType, cv::DIST_MASK_5);

When passed a `cv::Mat_<bool>`, `cv::distanceTransform` worked fine in 4.x, but now asserts at modules/imgproc/src/distransform.cpp:1024:

    CV_Assert( src.type() == CV_8UC1);

I believe this function was **(and all other related functions were)** missed when `CV_Bool` was added, and the assertion should be extended to allow `CV_Bool` as `src.type()` value.

This behaviour violates [the expectation expressed in the migration guide ](https://github.com/opencv/opencv/wiki/OpenCV-4-to-5-migration#new-data-types) as
> `CV_Bool` matrices can now be used as masks wherever a `CV_8U` or `CV_8S` mask was previously accepted.

Workarounds include not using `cv::Mat_<bool>` as a mask type (at least for `cv::connectedComponentsWithStats`), which seems contrary to the intention of having a boolean datatype?
See also previous similar issues: #29578, #29593

### Steps to reproduce

```cpp
#include <opencv2/imgproc.hpp>

int main()
{
    cv::Mat_<bool> input(2,2);
    cv::Mat_<float> result;
    cv::distanceTransform(input, result, cv::DIST_L2, cv::DIST_MASK_PRECISE);
}
```
This works with OpenCV 4.13 throws an exception with OpenCV 5.0.0:

    cv::Exception: OpenCV(5.0.0) .../modules/imgproc/src/distransform.cpp:1034: error: (-215:Assertion failed) src.type() == CV_8UC1 in function 'distanceTransform'

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by biconcavelens**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

Closes #29596.

## Problem

`cv::Mat_<bool>::depth()` returns `CV_Bool` in 5.0, where it returned `CV_8U` in 4.x. `distanceTransform` therefore rejects boolean masks that worked in 4.x:

```
error: (-215:Assertion failed) src.type() == CV_8UC1 in function 'distanceTransform'
```

This contradicts the [4→5 migration guide](https://github.com/opencv/opencv/wiki/OpenCV-4-to-5-migration#new-data-types), which states that `CV_Bool` matrices can be used as masks wherever a `CV_8U` or `CV_8S` mask was previously accepted.

## Change

`CV_Bool` is a 1-byte type (`CV_ELEM_SIZE1(CV_Bool) == 1`) and every read of `src` on these paths is a plain zero-test (`if (!s[j])`, `srcptr[j] == 0`, `sbase[0] == 0 ? 0 : 255`), never a use of the stored value. So a `CV_Bool` mask is byte-compatible and semantically identical to a `CV_8UC1` mask here.

The type checks are relaxed to accept `CV_BoolC1`, following the existing convention in `accum.cpp`, `histogram.cpp`, `homography_decomp.cpp`, `levmarq.cpp`, `ptsetreg.cpp` and the recently merged #29580.

The issue only names the assert at `distransform.cpp:981`, but there are **four** reachable type checks; relaxing only the reported one moves the failure deeper instead of fixing it:

| Location | Reached via |
|---|---|
| `cv::distanceTransform` (public wrapper) | all calls |
| `distanceTransform_L1_8U` | `DIST_L1` + `dstType == CV_8U` |
| `trueDistTrans` | `DIST_MASK_PRECISE` |
| `distanceATS_L1_8u` | `DIST_L1` + `dstType == CV_8U` |

## Testing

Added `Imgproc_DistanceTransform.bool_mask_29596`, which exercises all four paths and asserts the `CV_Bool` result is identical to the equivalent `CV_8UC1` mask result (float output for `DIST_MASK_3`/`5`/`PRECISE`, the `CV_8U` output path, and the labels overload).

Verified against a local build (Ninja + MinGW-w64 g++ 15.2, `BUILD_LIST=imgproc,ts,imgcodecs`):

- The new test **fails without the source change**, reproducing exactly the assertion from the report (`distransform.cpp:981: (-215:Assertion failed) src.type() == CV_8UC1`), and passes with it.
- Full `opencv_test_imgproc` suite (1592 tests): no new failures. 5 pre-existing failures (`Imgproc_AdaptiveThreshold.*`, `GaussianBlur_Bitexact.regression_9863`) reproduce identically on unmodified `5.x` in this environment and are unrelated to this change.

No `opencv_extra` data is needed — the test builds its masks in-code.

---

_Authored with AI assistance, tagged per the note in the PR template. All claims above were verified empirically against a local build rather than assumed; the accompanying analysis (1-byte element size, zero-test-only usage, and the four reachable assert sites) was checked directly against the source._

### CODE REVIEW

**Review by abhishek-gola — APPROVED** [review]

File: modules/imgproc/src/distransform.cpp [hunk 1]
```diff
@@ -957,7 +957,9 @@ static void distanceTransform_L1_8U(InputArray _src, OutputArray _dst)
 
     Mat src = _src.getMat();
 
-    CV_Assert( src.type() == CV_8UC1);
+    // CV_Bool is a 1-byte mask type (added in 5.0) and is only ever zero-tested
+    // here, so accept it wherever a CV_8UC1 mask was accepted. See #29596.
```
Comment (asmorkalov) [inline modules/imgproc/src/distransform.cpp]: Please remove obvious comment.

File: modules/imgproc/src/distransform.cpp [hunk 2]
```diff
@@ -978,7 +980,9 @@ void cv::distanceTransform( InputArray _src, OutputArray _dst, OutputArray _labe
     Mat src = _src.getMat(), labels;
     bool need_labels = _labels.needed();
 
-    CV_Assert( src.type() == CV_8UC1);
+    // CV_Bool is a 1-byte mask type (added in 5.0) and is only ever zero-tested
+    // here, so accept it wherever a CV_8UC1 mask was accepted. See #29596.
```
Comment (asmorkalov) [inline modules/imgproc/src/distransform.cpp]: Please remove obvious comment.

Comment (biconcavelens) [reply modules/imgproc/src/distransform.cpp]: removed comment, please approve

**Review by asmorkalov — APPROVED** [review]

**Comment by biconcavelens** [comment]
hey, i got this about the checks failing, can i get a rerun

"GitHub Actions has encountered an internal error when running your job.
Internal server error. Correlation ID: dc93c619-2203-4ea0-9d44-c3289c203e86"
