### PR TITLE
Fix #12542

### LINKED ISSUE #12542: opencv_test_dnn: sporadic failures of Test_ONNX_nets.TinyYolov2/0
[Coverage](http://pullrequest.opencv.org/buildbot/builders/3_4_coverage-lin64-debug/builds/154) (Debug / AVX2):
```
[ RUN      ] Test_ONNX_nets.TinyYolov2/0, where GetParam() = OCV/CPU
/build/3_4_coverage-lin64-debug/opencv/modules/dnn/test/test_common.hpp:95: Failure
Expected: (normL1) <= (l1), actual: 8.48328e+25 vs 1e-05
/build/3_4_coverage-lin64-debug/opencv/modules/dnn/test/test_common.hpp:98: Failure
Expected: (normInf) <= (lInf), actual: 7.84223e+26 vs 0.0001
[  FAILED  ] Test_ONNX_nets.TinyYolov2/0, where GetParam() = OCV/CPU (3368 ms)
```

[Win64](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-win64-vc14/builds/151):
```
[ RUN      ] Test_ONNX_nets.TinyYolov2/0, where GetParam() = OCV/CPU
c:\build\3_4_noocl_noicv_nosse-win64-vc14\opencv\modules\dnn\test\test_common.hpp(95): error: Expected: (normL1) <= (l1), actual: 2.63622e+11 vs 1e-05
c:\build\3_4_noocl_noicv_nosse-win64-vc14\opencv\modules\dnn\test\test_common.hpp(98): error: Expected: (normInf) <= (lInf), actual: 2.43701e+12 vs 0.0001
[  FAILED  ] Test_ONNX_nets.TinyYolov2/0, where GetParam() = OCV/CPU (358 ms)
```

[MacOSX](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL-mac/builds/153):
```
[ RUN      ] Test_ONNX_nets.TinyYolov2/0, where GetParam() = OCV/CPU
/build/3_4_noOCL-mac/opencv/modules/dnn/test/test_common.hpp:95: Failure
Expected: (normL1) <= (l1), actual: 110.836 vs 1e-05
/build/3_4_noOCL-mac/opencv/modules/dnn/test/test_common.hpp:98: Failure
Expected: (normInf) <= (lInf), actual: 925.761 vs 0.0001
[  FAILED  ] Test_ONNX_nets.TinyYolov2/0, where GetParam() = OCV/CPU (774 ms)
```

Probably related OpenCL failure on [Linux](http://pullrequest.opencv.org/buildbot/builders/3_4_noICV-lin64/builds/153) (without IPP, OpenCL):
```
[ RUN      ] Test_ONNX_nets.TinyYolov2/2, where GetParam() = OCV/OCL_FP16
/build/3_4_noICV-lin64/opencv/modules/dnn/test/test_common.hpp:95: Failure
Expected: (normL1) <= (l1), actual: nan vs 0.017
[  FAILED  ] Test_ONNX_nets.TinyYolov2/2, where GetParam() = OCV/OCL_FP16 (259 ms)
```

### PR DESCRIPTION
**Pull request by dkurt**
* resolves https://github.com/opencv/opencv/issues/12542
* remove `-Werror=non-virtual-dtor` suppression introduced in https://github.com/opencv/opencv/pull/10608 (related: http://answers.opencv.org/question/199796/opencv-343-compiling-with-mingw-64-810-and-cmake-for-eclipse/)

```
force_builders=Custom
docker_image:Custom=ubuntu-openvino:16.04
buildworker:Custom=linux-2
test_opencl:Custom=ON
```

### CODE REVIEW

**Comment by vpisarev** [comment]
:+1:

**Comment by WenyinWei** [comment]
Hello dkurt, it seems that the bug remains in opencv 4. The same problem as `http://answers.opencv.org/question/199796/opencv-343-compiling-with-mingw-64-810-and-cmake-for-eclipse/`  has arisen in my procedure of compiling opencv 4. And I have check that my `modules/dnn/src/tensorflow/tf_graph_simplifier.cpp` file has contain 
```class Subgraph  // Interface to match and replace TensorFlow subgraphs.
{
public:
    virtual ~Subgraph() {}
```
Is it very imporatant? Or can I just ignore the warnings? Thanks for your reply.

**Comment by dkurt** [comment]
@WenyinWei, please add error messages which you observed. Thanks in advance!

**Comment by WenyinWei** [comment]
Hello, @dkurt . Thanks for your prompt reply. The error messages are almost the same with that one in the website. 
I have fixed the problem by unsetting most of unnecessary the options in cmake-gui, including opencv_dnn_PERF_CAFFE and opencv_dnn_PERF_CLCAFFE. I guess some cmake options would invoke some old files to be compiled, but I am not sure if the problem arose because of those two options I mentioned. Thanks again!

**Comment by dkurt** [comment]
@WenyinWei, I mean that in forum's topic the message was
```
S:\SYSTEMS\CPP\OpenCV\sources\modules\dnn\src\tensorflow\tf_graph_simplifier.cpp:20:7: error: 'class cv::dnn::experimental_dnn_34_v7::Subgraph' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class Subgraph  // Interface to match and replace TensorFlow subgraphs.
```

Which classes are mentioned in yours?
