### ISSUE TITLE
5.x: CI failure in wechat_qrcode tests due to missing detect.onnx

### ISSUE THREAD

**Issue by Kumataro** [opencv/opencv#29337]
### System Information

At https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/101829

OpenCV version: 5.x
Operating System / Platform: Ubuntu 20.04
Compiler & compiler version: GCC 9.3.0

### Detailed description

`detect.onnx` seems not be found on 5.x CIs.
It is introduced by https://github.com/opencv/opencv_extra/pull/1329 .

Could you confirm this problem, please ?

https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/101829/steps/test_wechat_qrcode/logs/stdio

```
[ RUN      ] Objdetect_QRCode_points_position.rotate45
unknown file: Failure
C++ exception with description "OpenCV(5.1.0-dev) /build/precommit-contrib_linux64/5.x/opencv/modules/ts/src/ts.cpp:1007: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: dnn/wechat_2021-01/detect.onnx in function 'findData'
" thrown in the test body.
[  FAILED  ] Objdetect_QRCode_points_position.rotate45 (1 ms)
[----------] 1 test from Objdetect_QRCode_points_position (1 ms total)

[----------] 1 test from Objdetect_QRCode_Big
[ RUN      ] Objdetect_QRCode_Big.regression
unknown file: Failure
C++ exception with description "OpenCV(5.1.0-dev) /build/precommit-contrib_linux64/5.x/opencv/modules/ts/src/ts.cpp:1007: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: dnn/wechat_2021-01/detect.onnx in function 'findData'
" thrown in the test body.
[  FAILED  ] Objdetect_QRCode_Big.regression (0 ms)
[----------] 1 test from Objdetect_QRCode_Big (0 ms total)

[----------] 1 test from Objdetect_QRCode_Tiny
[ RUN      ] Objdetect_QRCode_Tiny.regression
unknown file: Failure
C++ exception with description "OpenCV(5.1.0-dev) /build/precommit-contrib_linux64/5.x/opencv/modules/ts/src/ts.cpp:1007: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: dnn/wechat_2021-01/detect.onnx in function 'findData'
" thrown in the test body.
[  FAILED  ] Objdetect_QRCode_Tiny.regression (0 ms)
[----------] 1 test from Objdetect_QRCode_Tiny (0 ms total)
```

### Steps to reproduce

Run 5.x CI and confirm its result.

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by Kumataro** [comment]
There are same problems.

https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/101829 
https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/101825
https://pullrequest.opencv.org/buildbot/builders/precommit-contrib_linux64/builds/101821

**Comment by asmorkalov** [comment]
@abhishek-gola Could you take a look?
