### ISSUE TITLE
Error readNetFromDarknet OpenCV 4.3 Mac OS Catalina

### ISSUE THREAD

**Issue by hect1995** [opencv/opencv#17298]
##### System information (version)
- OpenCV => 4.3
- Operating System / Platform => Mac OS Catalina

- OpenCV => 4.3.0
- Compiler => LLDB

##### Detailed description

The command : 
` cv::dnn::Net net = cv::dnn::readNetFromDarknet(modelConfiguration, modelWeights);
`
Gives the error:
`libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(4.3.0) /tmp/opencv-20200408-5080-l00ytm/opencv-4.3.0/modules/dnn/src/darknet/darknet_io.cpp:847: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'`

This same command with the same parameters works in another OS with Open CV 4.1 but I cannot install Open CV 4.1 in Mac to confirm is an issue with the version

**Comment by dkurt** [comment]
Can you refer the model to reproduce problem?
