### PR TITLE
geometry: fix boundingRect throwing for boolean masks

### LINKED ISSUE #29578: cv::boundingRect called with cv::Mat_<bool> throws exception in 5.0.0, works in 4.x
### System Information

OpenCV version: 4.13 and 5.0.0
OS: Windows+macOS
Compilers: MSVS 2022/2026 and XCode 16.1/26.4 Clang

### Detailed description

In OpenCV 4.x, `cv::Mat_<bool>::depth()` returns 0 (==`CV_8U`)
In OpenCV 5.0.0, `cv::Mat_<bool>::depth()` returns `9` (==`CV_Bool`)

In both versions, `cv::boundingRect` is implemented as:

    return m.depth() <= CV_8U ? maskBoundingRect(m) : pointSetBoundingRect(m);

When passed a `cv::Mat_<bool>`, this worked fine in 4.x, but now throws an exception from `pointSetBoundingRect` that depth needs to be `CV_32F` or `CV_32S`.

I believe this function was missed when `CV_Bool` was added, and it should follow (conceptually) the `maskBoundingRect` path. Unfortunately, that function seems to assume 1 byte wide element type so it will need a specific `CV_Bool` implementation.

This behaviour violates [the expectation expressed in the migration guide ](https://github.com/opencv/opencv/wiki/OpenCV-4-to-5-migration#new-data-types)as
> CV_Bool matrices can now be used as masks wherever a CV_8U or CV_8S mask was previously accepted.

Workarounds include not using `cv::Mat_<bool>` as a mask type (at least for `cv::boundingRect`, which seems contrary to the intention of having a boolean datatype?

### Steps to reproduce

```cpp
#include <opencv2/imgproc.hpp>
#if CV_VERSION_MAJOR > 4
#include <opencv2/geometry/2d.hpp>
#endif

int main()
{
    cv::Mat_<bool> m(2,2);
    [[maybe_unused]] const auto rect = cv::boundingRect(m);
}
```
This works with OpenCV 4.13 but throws an exception with OpenCV 5.0.0:

    .../modules/geometry/src/geometry.cpp:599: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'pointSetBoundingRect'

    

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by ArneshBanerjee**
Fixes #29578

In 5.0 cv::Mat_<bool>::depth() returns CV_Bool instead of CV_8U, so
boundingRect routed boolean masks into pointSetBoundingRect, which expects
a CV_32S/CV_32F point set and threw. This worked in 4.x.

CV_Bool is a 1-byte 0/1 type, so it's handled like CV_8U/CV_8S and routed
through the byte-wise maskBoundingRect path.

Added a test comparing a Mat_<bool> mask against the equivalent CV_8UC1 mask.

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]

**Review by asmorkalov — APPROVED** [review]

**Review by abhishek-gola — APPROVED** [review]

**Comment by ArneshBanerjee** [comment]
Are the failed checks just flaky runs or also broken in the main as well.
Or something I'll have to adress?
