### ISSUE TITLE
highgui GTK2 with OpenGL broken in master

### ISSUE THREAD

**Issue by huangqinjin** [opencv/opencv#20850]
##### System information (version)

- OpenCV => master https://github.com/opencv/opencv/tree/c2e65bafb554dada3a714b978f67dbe3990bf726
- Operating System / Platform => openSUSE Tumbleweed
- Compiler => gcc 11.2

##### Case 1 (resolved, 4.5.5)
```cmake
cmake .. -DWITH_GTK=ON -DWITH_GTK_2_X=ON -DWITH_OPENGL=ON
```
```
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: lib/libopencv_core.so.4.5.4: undefined reference to `glXGetCurrentDisplay'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: lib/libopencv_core.so.4.5.4: undefined reference to `glXGetCurrentContext'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: lib/libopencv_core.so.4.5.4: undefined reference to `glXGetProcAddressARB'
```

##### Case 2
```cmake
cmake .. -DWITH_GTK=ON -DWITH_GTK_2_X=ON -DWITH_OPENGL=ON -DHIGHGUI_ENABLE_PLUGINS=OFF
```
```c++
#include <opencv2/highgui.hpp>
#include <opencv2/core/opengl.hpp>

int main(int argc, char* argv[])
{
    bool use_texture = argc > 1;

    cv::namedWindow("img", cv::WINDOW_OPENGL | cv::WINDOW_AUTOSIZE);
    cv::Mat img = cv::Mat(200, 200, CV_8UC3, CV_RGB(255, 0, 0));

    if (use_texture)
    {
        cv::ogl::Texture2D tex;
        tex.copyFrom(img);
        cv::imshow("img", tex);
    }
    else
    {
        cv::imshow("img", img);
    }

    cv::waitKey(0);
}
```

|  `use_texture` |  Window |
| --------|------|
|  true |  red (OK) |
| false | black ( X ) |

##### Case 3
```cmake
cmake .. -DWITH_GTK=ON -DWITH_GTK_2_X=ON -DWITH_OPENGL=ON -DWITH_QT=ON -DHIGHGUI_PLUGIN_LIST=all
```
```c++
#include <opencv2/highgui.hpp>

int main()
{
    cv::namedWindow("img", cv::WINDOW_OPENGL | cv::WINDOW_AUTOSIZE);
}
```

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4-pre) /home/huangqinjin/Projects/opencv/modules/highgui/src/window_gtk.cpp:1137: error: (-218:No OpenGL support) Library was built without OpenGL support in function 'namedWindow_'
```

##### Issue submission checklist

 - [X] I report the issue, it's not a question
   
 - [X] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [X] I updated to latest OpenCV version and the issue is still there
   
 - [X] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by huangqinjin** [comment]
Tested case 2 with 4.5.2, whether `use_texture` or not, always show red window.

**Comment by sl1pkn07** [comment]
the case 1 same here with GTK 3

**Comment by sl1pkn07** [comment]
maybe related? (in my case)

https://github.com/opencv/opencv/issues/20001

**Comment by Aladdin-Ark** [comment]
getting the same if try to build master branch or 4.5.4 only with apps enabled.

same as Case 1
`cmake .. -DWITH_OPENGL:BOOL=ON -DWITH_GTK:BOOL=ON -DWITH_GTK_2_X:BOOL=ON`

build is OK

Adding Apps (Case1 + BUILD_opencv_apps) 
`cmake .. -DWITH_OPENGL:BOOL=ON -DWITH_GTK:BOOL=ON -DWITH_GTK_2_X:BOOL=ON
-DBUILD_opencv_apps:BOOL=ON`

```
/usr/bin/ld: ../../../../lib/libopencv_core.so.4.5.4: undefined reference to `glXGetProcAddressARB'
/usr/bin/ld: ../../../../lib/libopencv_core.so.4.5.4: undefined reference to `glXGetCurrentDisplay'
/usr/bin/ld: ../../../../lib/libopencv_core.so.4.5.4: undefined reference to `glXGetCurrentContext'
```

**Comment by Moddingear** [comment]
I have the same issue as Case 1, with 4.5.4, 
`cmake -D WITH_OPENGL=ON` (other settings default, with opencv_contrib) Auto detected gtk is gtk3.

**Comment by alalek** [comment]
"Case 1" has been fixed here: #21213

**Comment by 46cv8** [comment]
I can confirm "Case 2" is a real issue for me too with GTK2, highgui and OpenGL. I just upgraded from 4.4.0 to 4.5.5 and my python application shows a black screen now unless I turn off the opengl flag.

The config of 4.5.5 is as follows.
```
--   GUI:                           GTK2
--     GTK+:                        YES (ver 2.24.32)
--       GThread :                  YES (ver 2.64.6)
--       GtkGlExt:                  YES (ver 1.2.0)
--     OpenGL support:              YES (/usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libGLU.so)
```

The config that was working with 4.4.0 was as follows.
```
--   GUI: 
--     GTK+:                        YES (ver 2.24.32)
--       GThread :                  YES (ver 2.56.4)
--       GtkGlExt:                  YES (ver 1.2.0)
--     OpenGL support:              YES (/usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libGLU.so)
```

The only other change was an upgrade from ubuntu 18.04 to 20.04.
I am testing via a modified version of a docker container based on https://github.com/datamachines/cuda_tensorflow_opencv/tree/master/BuildInfo-OpenCV but built with the additional required libraries and the following additional configuration options set to enable GTK 2 OPENGL support.

```
+    -DOPENCV_ENABLE_NONFREE=ON \
+    -DWITH_GTK_2_X=ON \
+    -DWITH_OPENGL=ON \
+# QT can be used for OpenGL but not at the same time as GTK
+    -DWITH_QT=OFF \
+    -DWITH_NVCUVID=ON \
```
The 4.4.0 build I was using that was working fine was based on: datamachines/cuda_tensorflow_opencv:10.2_2.3.0_4.4.0-20200803
while the new build of 4.5.5 I am testing is based on: 
datamachines/cudnn_tensorflow_opencv:11.4.2_2.7.0_4.5.5-20220103

I can also confirm that the example provided by @huangqinjin for case 2 functions exactly as he describes in my environment.

One other piece of interesting information is that if I close the initial window with the black screen using the X in the top right corner, a new window will open which properly shows the image, but doesn't interact with the GUI properly any longer. This seems very curious behavior that it would start working when the window is respawned, perhaps it properly initializes some internal Texture2D behind the scenes when re-spawning a window(?)

Unfortunately the workaround suggested by @huangqinjin of using a Texture2D to pass the image to imshow won't work for me as my software is written in Python and Texture2D does not have Python bindings. Is anyone aware of another workaround to get this working again that might be compatible with Python? I can also patch the source code to do the Texture2D stuff inside opencv if that will fix the issue. I'm not too sure what changed in the code between 4.4.0 and 4.5.5 but I will take a look and see if I can spot anything.

**Comment by asmorkalov** [comment]
The issue is still there for current 4.x and 5.x, but not reproducible with 3.4. `-lGLU -lGL` is missing from linker list.

**Comment by asmorkalov** [comment]
OpenGL works with GTK2 only. Configuration that works for me on Ubuntu 18.04:
```
cmake -DWITH_OPENGL=ON -DWITH_GTK_2_X=ON ../opencv-master
```

**Comment by pacientes** [comment]
anyone have been solved?
