### ISSUE TITLE
opengl_testdata_generator.cpp fails to build in 5.0

### ISSUE THREAD

**Issue by antonio-rojas** [opencv/opencv#29292]
### System Information

OpenCV 5.0.0
Arch Linux x86_64
GCC 16.1.1

### Detailed description

opengl_testdata_generator.cpp fails to build with lots of undeclared functions and classes:
```
/build/opencv/src/opencv/samples/opengl/opengl_testdata_generator.cpp: In constructor ‘ModelData::ModelData(ModelType, std::string)’:
/build/opencv/src/opencv/samples/opengl/opengl_testdata_generator.cpp:104:13: error: ‘loadMesh’ was not declared in this scope
  104 |             loadMesh(objectPath, vertices, indvec);
      |             ^~~~~~~~
/build/opencv/src/opencv/samples/opengl/opengl_testdata_generator.cpp: In constructor ‘ModelData::ModelData(std::string, double, double, double, double, cv::Vec3d, cv::Vec3d, cv::Vec3d)’:
/build/opencv/src/opencv/samples/opengl/opengl_testdata_generator.cpp:240:9: error: ‘loadMesh’ was not declared in this scope
  240 |         loadMesh(objectPath, vertices, indvec, noArray(), colors);
      |         ^~~~~~~~
/build/opencv/src/opencv/samples/opengl/opengl_testdata_generator.cpp: At global scope:
/build/opencv/src/opencv/samples/opengl/opengl_testdata_generator.cpp:281:43: error: ‘TriangleShadingType’ has not been declared
  281 | static void generateImage(cv::Size imgSz, TriangleShadingType shadingType, TriangleCullingMode cullingMode,
      |                                           ^~~~~~~~~~~~~~~~~~~
/build/opencv/src/opencv/samples/opengl/opengl_testdata_generator.cpp:281:76: error: ‘TriangleCullingMode’ has not been declared
  281 | static void generateImage(cv::Size imgSz, TriangleShadingType shadingType, TriangleCullingMode cullingMode,
      |                                                                            ^~~~~~~~~~~~~~~~~~~
```
and so on.

### Steps to reproduce

Try to compile 5.0.0 with `BUILD_EXAMPLES=ON`

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)
