### ISSUE TITLE
Failure to compile with CUDA 7.0 + clang on OSX

### ISSUE THREAD

**Issue by opencv-pushbot** [opencv/opencv#4908]
Transferred from http://code.opencv.org/issues/4125
```
|| Kevin Squire on 2015-01-15 22:19
|| Priority: Normal
|| Affected: branch 'master' (3.0-dev)
|| Category: gpu (cuda)
|| Tracker: Bug
|| Difficulty: 
|| PR: 
|| Platform: x86 / Mac OSX
```

Failure to compile with CUDA 7.0 + clang on OSX
-----------
```
When trying to compile OpenCV 3.0 (fresh github clone) on OSX with CUDA 7.0 (and clang, which is the default on OSX), I get the following error:

<pre>
/Users/kevin/src/opencv/opencv-git/modules/core/include/opencv2/core/cvstd.hpp(1048): error: "swap" is not a class or function template name in the current scope
</pre>

Compiling is fixed by the following diff:

<pre>
diff --git a/modules/core/include/opencv2/core/cvstd.hpp b/modules/core/include/opencv2/core/cvstd.hpp
index 0da8faf..8c2e96f 100644
--- a/modules/core/include/opencv2/core/cvstd.hpp
+++ b/modules/core/include/opencv2/core/cvstd.hpp
@@ -1040,16 +1040,15 @@ static inline bool operator>= (const String& lhs, const char*   rhs) { return lh

 #ifndef OPENCV_NOSTL_TRANSITIONAL
 namespace std
+{
+    static inline void swap(cv::String& a, cv::String& b) { a.swap(b); }
+}
 #else
 namespace cv
-#endif
 {
-    template<> inline
-    void swap<cv::String>(cv::String& a, cv::String& b)
-    {
-        a.swap(b);
-    }
+    template<> inline void swap<cv::String>(cv::String& a, cv::String& b) { a.swap(b); }
 }
+#endif

 #include "opencv2/core/ptr.inl.hpp"

</pre>

If this fix will work, I can submit a PR, but I highly suspect there is a better fix.
```

History
-------
##### Vladislav Vinogradov on 2015-01-16 08:31
```
Hello Kevin,

Thank you for you fix! 
Please submit a PR with your patch, so it can be tested by buildbot on different configurations.

I think you can use

<pre>
static inline void swap(cv::String& a, cv::String& b) { a.swap(b); }
</pre>

implementation for both cases (@cv@ and @std@).

But it will be better to ask authors of @opencv2/core/cvstd.hpp@ header in GitHub Pull Request.
-   Assignee changed from Vladislav Vinogradov to Kevin Squire
-   Status changed from New to Open
```
##### Maksim Shabunin on 2015-04-27 09:12
```
-   Target version changed from 3.0-beta to 3.0
```

**Comment by ilya-lavrenov** [comment]
The fix was merged more then 1 year ago. See https://github.com/opencv/opencv/commit/decbdd1abb61a823edd25cedea272a4c0c89ba17
