### PR TITLE
fix compilation errors caused by namespace

### PR DESCRIPTION
**Pull request by AvenSun**
related: #25199
The regressions introduced in https://github.com/opencv/opencv/pull/25147 and https://github.com/opencv/opencv/pull/25630

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]
Looks good. tried compilation with following OpenVINO versions on Linux: 2022.1.0.643, 2024.0.0.14509, 2024.3.0.16041.
