### ISSUE TITLE
OpenVINO 2024 not working properly

### ISSUE THREAD

**Issue by CSBVision** [opencv/opencv#25916]
### System Information

OpenCV Version: 4.10.0
Operating System / Platform: Windows 11 x64
Compiler & compiler version: VS 2022

### Detailed description

With the 4.10.0 release, support for OpenVINO 2024 is included. Compiling and linking against OpenVINO 2024 works, however activating at runtime results in runtime error.s

### Steps to reproduce

1. Compile OpenVINO 2024. We used 2024.2.0, only using the CPU plugin and compiled it as static libraries.
2. Compile OpenCV using OpenVINO, except those necessary for OpenVINO, further CMake configurations are not required.
3. Thereafter, run the following code:

```python
import numpy as np
import cv2 as cv

# model is available in models/image_classification_mobilenet inside OpenCV's zoo repository
model = cv.dnn.readNet('image_classification_mobilenetv2_2022apr.onnx')

# use OpenVINO backend (no error if DNN_BACKEND_OPENCV is used instead)
model.setPreferableBackend(cv.dnn.DNN_BACKEND_INFERENCE_ENGINE)

# forward zero image
model.setInput(np.zeros((1,3,224,224), dtype=np.float32))
model.forward()
```

Here, `forward()` terminates with the following error:

> error: OpenCV(4.10.0) opencv\modules\dnn\src\ie_ngraph.cpp:558: error: (-215:Assertion failed) blobIt != allBlobs.end() in function 'cv::dnn::InfEngineNgraphNet::forward'

As both, OpenCV's backend as well as OpenVINO 2023 work fine, the issue is caused by using OpenVINO 2024.

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by asmorkalov** [comment]
@CSBVision Am I right that you do not use pre-built binaries of OpenVINO, but built it by yourself? Could you add build steps to the issue then?

**Comment by CSBVision** [comment]
Yes, correct, we compiled OpenVINO as static libraries for testing purposes, skipping most parts not required for OpenCV:
```
BUILD_SHARED_LIBS=False
ENABLE_TBBBIND_2_5=False
ENABLE_SYSTEM_TBB=True
TBB_DIR=/path/to/TBB
ENABLE_INTEL_CPU=True
ENABLE_OV_IR_FRONTEND=True
BUILD_template_extension=False
ENABLE_FASTER_BUILD=True
ENABLE_AUTO=False
ENABLE_AUTO_BATCH=False
ENABLE_HETERO=False
ENABLE_INTEL_GPU=False
ENABLE_INTEL_NPU=False
ENABLE_MULTI=False
ENABLE_SAMPLES=False
ENABLE_TEMPLATE=False
ENABLE_OV_ONNX_FRONTEND=False
ENABLE_OV_PADDLE_FRONTEND=False
ENABLE_OV_PYTORCH_FRONTEND=False
ENABLE_OV_TF_FRONTEND=False
ENABLE_OV_TF_LITE_FRONTEND=False
ENABLE_PYTHON=False
ENABLE_SAMPLES=False
```
We used this build configuration for both, 2023 and 2024 releases, and 2023 works fine whereas 2024 does not.

**Comment by CSBVision** [comment]
After your comment, we retested the official OpenVINO build.
The following steps reproduce exactly the same issue, too, at least in all our tests:
1. Download [OpenVINO 2024.2.0](https://storage.openvinotoolkit.org/repositories/openvino/packages/2024.2/windows/w_openvino_toolkit_windows_2024.2.0.15519.5c0f38f83f6_x86_64.zip) and unpack the archive.
2. Clone OpenCV 4.10.0.
3. Run CMake with only these custom flags (assumes that Python is found automatically, otherwise extend it for your Python installation accordingly):
```
WITH_OPENVINO=True
OPENCV_DNN_OPENVINO=True
OpenVINO_DIR=/Path/to/OpenVINO/runtime/cmake
```
4. Compile OpenCV.
5. Setup the cv2 package (might require to copy the OpenVINO runtime DLLs to OpenCV's `x64\vcXX\bin` directory).
6. Use above Python code to reproduce the issue.

**Comment by asmorkalov** [comment]
@CSBVision @AvenSun please attach a model for test.

**Comment by asmorkalov** [comment]
Reproduced with current 4.x and fresh OpenVINO release w_openvino_toolkit_windows_2024.3.0.16041.1e3b88e4e3f_x86_64.

C++ code:
```
#include <iostream>
#include <opencv2/opencv.hpp>

void main()
{
	// model is available in models / image_classification_mobilenet inside OpenCV's zoo repository
	cv::dnn::Net model = cv::dnn::readNet("image_classification_mobilenetv2_2022apr.onnx");

	// use OpenVINO backend(no error if DNN_BACKEND_OPENCV is used instead)
	model.setPreferableBackend(cv::dnn::DNN_BACKEND_INFERENCE_ENGINE);

	// forward zero image

	cv::Mat input_image = cv::Mat::zeros(224, 224, CV_8UC3);
	cv::Mat input_blob = cv::dnn::blobFromImage(input_image);
	model.setInput(input_blob);
	printf("Before forward\n");
	model.forward();
	printf("After forward\n");
}
```
Error:
```
Before forward
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.10.0-dev) Error: Assertion failed (blobIt != allBlobs.end()) in cv::dnn::InfEngineNgraphNet::forward, file D:\opencv\modules\dnn\src\ie_ngraph.cpp, line 558
```

**Comment by asmorkalov** [comment]
@dkurt could you take a look on it?

**Comment by fuatka** [comment]
Same issue with OpenCV-4.10 and OpenVINO-2024.3 when calling net.forward.

What is latest stable versions for OpenCV and OpenVINO when building OpenCV with OpenVINO backend support?

**Comment by JulienMaille** [comment]
Spend a couple hours after I had updated my toolchain to Openvino 2024.3. I too have a:
`OpenCV(4.10.0-dev) D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp:558: error: (-215:Assertion failed) blobIt != allBlobs.end() in function 'cv::dnn::InfEngineNgraphNet::forward'`
Is there a known workaround?

**Comment by AvenSun** [comment]
@fuatka 

OenCV(4.10) works well with OpenVINO-2024.0.

**Comment by JulienMaille** [comment]
> @fuatka 
> 
> OpenCV(4.10) works well with OpenVINO-2024.0.

Have you tried 2024.1?

**Comment by Bleach665** [comment]
Same problem with OpenVINO 2024.5.0 (62309fb88a5dd4c2938505d102fe51af4d275ad8), OpenCV 4100 (f503890c2b2ba73f4f94971c1845ead941143262). VS 2022, CUDA 12.4, cuDNN 9.4.

**Comment by lz1004** [comment]
@dkurt From debugging I noticed that the problem seems to be related to the output layer names. From openvino > 2024.0, the output layer names end with "_1", "_2" etc.

**Comment by lz1004** [comment]
> > @dkurt From debugging I noticed that the problem seems to be related to the output layer names. From openvino > 2024.0, the output layer names end with "_1", "_2" etc.
> 
> Can you elaborate? Does it break OpenCV name parsing? What were were the layer names in OpenVino 2023?

The outputlayer names with openvino <= 2024.0 are the same, except for the new suffix "_1". E.g. "output" (<= 2024.0) and "output_1" (>2024.0). The output layer in opencv is found searching for the old name, which results in the mentioned error (assert in ie_ngraph cpp l.588, opencv tag 4.10.0)

**Comment by JulienMaille** [comment]
Shall we try something like this but cutting '_' instead?
https://github.com/opencv/opencv/blob/40428d919dedc079c779eea4962a010a8e56b317/modules/dnn/src/net_openvino.cpp#L740-L749

**Comment by lz1004** [comment]
I debugged into that part, and there the output layer name is correct, without "_". I also noticed, that this also happens with *.pb models, not only with models in IR format. So it must be somewhere else then in net_openvino.cpp.

**Comment by dkurt** [comment]
Sorry for delay and thanks for the investigation! I will open a PR woth necessary updates this week if nobody mind.

**Comment by JulienMaille** [comment]
@dkurt Have you identified what the fix should be? Can we help?

**Comment by dkurt** [comment]
@JulienMaille, reproduced problem with https://storage.openvinotoolkit.org/repositories/openvino/packages/2024.4/linux/l_openvino_toolkit_ubuntu24_2024.4.0.16579.c3152d32c9c_x86_64.tgz, thanks for keeping in touch

**Comment by dkurt** [comment]
Please check the proposed solution: https://github.com/opencv/opencv/pull/26357

**Comment by lz1004** [comment]
Checked it with my older custom *.pb models and various newer IR models (convnext, yolo series). Works just fine, thank you!

**Comment by JulienMaille** [comment]
@dkurt I get an error when compiling in debug mode
`1>D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp(166,13): error C2143: syntax error: missing ';' before 'for'`
https://github.com/opencv/opencv/blob/8791cd147cb03dd0653e7457ed97fce95e9d4e2d/modules/dnn/src/ie_ngraph.cpp#L166

**Comment by Bleach665** [comment]
> @dkurt I get an error when compiling in debug mode `1>D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp(166,13): error C2143: syntax error: missing ';' before 'for'`
> 
> https://github.com/opencv/opencv/blob/8791cd147cb03dd0653e7457ed97fce95e9d4e2d/modules/dnn/src/ie_ngraph.cpp#L166

to hotfix just put `;` after
`std::string name = output_node_it->first + (output_node_it->second->node.get_node()->get_output_size() == 1 ? "" : ".0")`
line 165 in this file.

**Comment by dkurt** [comment]
@JulienMaille, @Bleach665 oh sorry, hotfix is here: https://github.com/opencv/opencv/pull/26381

**Comment by JulienMaille** [comment]
Thanks. I'm curious: how was this passing the tests? Thanks to the macro following the missing `;`?

**Comment by JulienMaille** [comment]
I confirm the problem is gone, tested with OpenVino 2024.3, has anyone tested 2024.4.1?

**Comment by dkurt** [comment]
@JulienMaille macro includes only the content inside `()` so `;` keeps in both versions:
debug:
```
std::string name = output_node_it->first + (output_node_it->second->node.get_node()->get_output_size() == 1 ? "" : ".0")
CV_LOG_DEBUG(NULL, "DNN-IE: Change friendly name from " << out->get_friendly_name() << " to " << name);
out->set_friendly_name(name);
```
release:
```
std::string name = output_node_it->first + (output_node_it->second->node.get_node()->get_output_size() == 1 ? "" : ".0")
;
out->set_friendly_name(name);
```
