### ISSUE TITLE
OpenCV cannot import ONNX model: inputs.size() > 0 in function 'cv::dnn::ReduceLayerImpl::getMemoryShapes'

### ISSUE THREAD

**Issue by ukoehler** [opencv/opencv#23297]
### System Information

Windows 10
opencv-python-rolling 4.7.0.20230211
Python 3.10.4

### Detailed description

I am trying to load the https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-12.onnx model and get the following error
```
[ERROR:0@0.591] global onnx_importer.cpp:1055 cv::dnn::dnn4_v20221220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [ReduceMin]:(onnx_node!2085) from domain='ai.onnx'
Traceback (most recent call last):
  File "d:\Local\devel\Python\OpenCV\dnn_segmentation_faster_rcnn\inference.py", line 94, in <module>
    model = cv2.dnn.readNet(model_path)
cv2.error: OpenCV(4.7.0-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1074: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20221220::ONNXImporter::handleNode'
> Node [ReduceMin@ai.onnx]:(onnx_node!2085) parse error: OpenCV(4.7.0-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\reduce_layer.cpp:336: error: (-215:Assertion failed) inputs.size() > 0 in function 'cv::dnn::ReduceLayerImpl::getMemoryShapes'
```

### Steps to reproduce

```
model = cv2.dnn.readNet(model_path)
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by zihaomu** [comment]
Thanks for your feedback. Dynamic shape input is not supported. 
duplicated https://github.com/opencv/opencv/issues/22099

**Comment by ukoehler** [comment]
Still doen't load in opencv-python-rolling-4.8.0.20230624

```
Traceback (most recent call last):
  File "d:\Local\devel\Python\OpenCV\dnn_segmentation_faster_rcnn\inference.py", line 95, in <module>
    model = cv2.dnn.readNet(model_path)
cv2.error: OpenCV(4.8.0-pre) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1083: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20230620::ONNXImporter::handleNode'
> Node [TopK@ai.onnx]:(onnx_node!2088) parse error: OpenCV(4.8.0-pre) d:\a\opencv-python\opencv-python\opencv\modules\dnn\src\net_impl.hpp:108: error: (-2:Unspecified error) Can't create layer "onnx_node!2088" of type "TopK" in function 'cv::dnn::dnn4_v20230620::Net::Impl::getLayerInstance'
>
```

Note to self: Local\devel\Python\OpenCV\dnn_segmentation_faster_rcnn\inference.py

**Comment by zihaomu** [comment]
I think it only will be fixed at 5.x release, since this is related about the our dnn memory strategy.

**Comment by ukoehler** [comment]
Thanks, I am just going through all my open issues on OpenCV after upgrading to 4.8.0 and check the progress.
