### ISSUE TITLE
detect_blob.cpp  detect_mser.cpp using sintax not supported by clang C++11 compiler

### ISSUE THREAD

**Issue by OtacilioNeto** [opencv/opencv#7676]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => FreeBSD 11
- Compiler => Clang 3.8.0

##### Detailed description

When compiling samples/cpp/detect_blob.cpp and samples/cpp/detect_mser.cpp clang C++ compiler raises so many errors like bellow. This is related with lines like this: 

String inf = static_cast<ostringstream*>(&(ostringstream() << pAct.minArea))->str(); 

[ 95%] Built target example_image_sequence
--- samples/cpp/CMakeFiles/example_select3dobj.dir/all ---
/usr/bin/make -f samples/cpp/CMakeFiles/example_select3dobj.dir/build.make samples/cpp/CMakeFiles/example_select3dobj.dir/depend
--- samples/cpp/CMakeFiles/example_select3dobj.dir/depend ---
cd /usr/ports/graphics/opencv3/work/opencv-3.1.0 && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /usr/ports/graphics/opencv3/work/opencv-3.1.0 /usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp /usr/ports/graphics/opencv3/work/opencv-3.1.0 /usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp /usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/CMakeFiles/example_select3dobj.dir/DependInfo.cmake --color=
--- samples/cpp/CMakeFiles/example_detect_mser.dir/all ---
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:76:46: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    String inf = static_cast<ostringstream*>(&(ostringstream() << pAct.minArea))->str();
                                             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:77:46: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    String sup = static_cast<ostringstream*>(&(ostringstream() << pAct.maxArea))->str();
                                             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:80:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << pAct.delta))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:82:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << pAct.maxVariation))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:84:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.minDiversity))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:86:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.pass2Only))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:88:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.maxEvolution))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:90:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.areaThreshold))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:92:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.minMargin))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:94:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.edgeBlurSize))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

##### Steps to reproduce

 Compile using clang 3.8.0 with C++11 enabled.

Attached are the patches to solve this problem. 

[patch-samples_cpp_detect__blob.txt](https://github.com/opencv/opencv/files/591940/patch-samples_cpp_detect__blob.txt)
[patch-samples_cpp_detect__mser.txt](https://github.com/opencv/opencv/files/591939/patch-samples_cpp_detect__mser.txt)

**Comment by LaurentBerger** [comment]
@OtacilioNeto  Hi, can you check if this source file are OK with clang 3.8.0 with C++11 enabled? thanks
https://github.com/LaurentBerger/opencv/blob/I7676/samples/cpp/detect_mser.cpp
https://github.com/LaurentBerger/opencv/blob/I7676/samples/cpp/detect_blob.cpp

**Comment by OtacilioNeto** [comment]
@LaurentBerger Hi. Fails with this error message:

--- samples/cpp/CMakeFiles/example_detect_mser.dir/all ---
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:76:52: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    String inf = static_cast<const ostringstream*>(&(ostringstream() << pAct.minArea))->str();
                                                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:77:52: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    String sup = static_cast<const ostringstream*>(&(ostringstream() << pAct.maxArea))->str();
                                                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:80:45: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<const ostringstream*>(&(ostringstream() << pAct.delta))->str();
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:82:45: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<const ostringstream*>(&(ostringstream() << pAct.maxVariation))->str();
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:84:45: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<const ostringstream*>(&(ostringstream() << (int)pAct.minDiversity))->str();
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:86:45: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<const ostringstream*>(&(ostringstream() << (int)pAct.pass2Only))->str();
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:88:45: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<const ostringstream*>(&(ostringstream() << (int)pAct.maxEvolution))->str();
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:90:45: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<const ostringstream*>(&(ostringstream() << (int)pAct.areaThreshold))->str();
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:92:45: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<const ostringstream*>(&(ostringstream() << (int)pAct.minMargin))->str();
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:94:45: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<const ostringstream*>(&(ostringstream() << (int)pAct.edgeBlurSize))->str();
                                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 errors generated.

**Comment by LaurentBerger** [comment]
Sorry it was false and false.
When  everything is green (http://pullrequest.opencv.org/#/summary/opencv in 7691) can you check it again
https://github.com/LaurentBerger/opencv/blob/I7676/samples/cpp/detect_mser.cpp
https://github.com/LaurentBerger/opencv/blob/I7676/samples/cpp/detect_blob.cpp

**Comment by OtacilioNeto** [comment]
Dear,  sorry by my ignorance. But, I need only download detec_mser and detect_blob or a full update of opencv3.1 is need?

**Comment by OtacilioNeto** [comment]
This two last files compiles fine here. They are using the same patch that I have submitted?

**Comment by LaurentBerger** [comment]
Yes I hope so. You must download only files using my link personal fork. I made a pull request using your patch. Now you have  to wait that @alalek validate new source code. If it is OK he will be merge  in opencv 3.1.-dev
