### ISSUE TITLE
cv::dilate asserts on input mask of type CV_Bool

### ISSUE THREAD

**Issue by rubenvb** [opencv/opencv#29798]
### System Information

OpenCV version: 4.13 and 5.0.0
OS: Windows+macOS
Compilers: MSVS 2022/2026 and XCode 16.1/26.4 Clang

### Detailed description

When cv::dilate is passed a cv::Mat_<bool>, this worked fine in 4.x, but now throws an exception.

I believe this function was missed when CV_Bool was added, and the assertion should be extended to allow CV_Bool as iDepth value.

This behaviour violates [the expectation expressed in the migration guide ](https://github.com/opencv/opencv/wiki/OpenCV-4-to-5-migration#new-data-types)as

    CV_Bool matrices can now be used as masks wherever a CV_8U or CV_8S mask was previously accepted.

See also previous similar issues: https://github.com/opencv/opencv/issues/29578, https://github.com/opencv/opencv/issues/29593 https://github.com/opencv/opencv/issues/29596 

### Steps to reproduce

```cpp
#include <opencv2/imgproc.hpp>

int main()
{
    cv::Mat_<bool> mask(2,2);
    cv::dilate(mask, mask);
}
```

This works with OpenCV 4.13 but throws an exception with OpenCV 5.0.0:

OpenCV(5.0.0) .../modules/imgproc/src/morph.simd.hpp:762: error: (-213:The function/feature is not implemented) Unsupported data type (

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by 0xMudit** [comment]
Right, this is squarely a gap in the CV_Bool rollout: `CV_Bool = 9` (core/hal/interface.h), and the morphological filter depth switch at `morph.simd.hpp:762` simply has no case that accepts it — hence the `StsNotImplemented` from the "anything beyond the handled depths" branch. The migration-guide promise ("CV_Bool accepted wherever CV_8U/CV_8S masks were") makes this a legit bug rather than a feature request, in the same family as #29578/#29593/#29596.

A few implementation considerations while someone picks it up:

**Where the fix belongs**

The kernels themselves are byte-oriented templates (`MorphRowFilter`/`MorphColumnFilter` operate on `*src.ptr()`, comparisons and min/max on bytes), and a `std::vector<bool>`-backed Mat is a 1-byte storage type — so `CV_Bool` should be able to ride the CV_8U path exactly. In practice that means the depth validation needs to treat `CV_Bool` as a legal 1-byte input depth wherever the mask/source is read, e.g.:

```cpp
if (sdepth != CV_8U && sdepth != CV_Bool) CV_Error(...);
```

The trick is doing it *without* spraying `CV_Bool` into every per-op type switch. Since `cv::dilate`/`cv::erode`/`morphologyEx` share the same FilterEngine, the cleanest is probably a normalization at the entry: convert the `CV_Bool` input to `CV_8U` (a 1:1 byte copy) when it's used as a mask/kernel, and translate any `CV_Bool` *requested* output type back if in-place `Mat_<bool>` semantics are expected (the repro uses `cv::dilate(mask, mask)` in-place, so the round-trip matters).

**Worth covering in the regression:**

- `dilate`/`erode`/`morphologyEx` (`open`,`close`,`gradient`,`tophat`,`blackhat`) on `Mat_<bool>`, in-place and out-of-place, and with a `CV_Bool` kernel as well as a `CV_8U` one.
- Compare against the `CV_8U` result bit-for-bit — bool-as-valid-values means that equivalence is the contract, not just "doesn't throw".
- The other `CV_Bool` gap issues (#29578 calcBackProject, #29593, #29596) probably share the same "missing depth case somewhere" shape; if the reporter/author of those wants, this could be fixed as a batch sweep over the mask-taking APIs in imgproc rather than one function at a time.

The earlier related issues were labeled with their own scopes, but the *root* cause here is a recurring pattern — a validator enumerating depths that forgot `CV_Bool` — so a sweep (grep for `CV_8U` in depth-validation switches in imgproc) would clear a whole class at once.
