### ISSUE TITLE
QTKit problem : OpenCV 3.1.0 can't build on Mac OS 10.11.6

### ISSUE THREAD

**Issue by varunkworld** [opencv/opencv#7292]
##### System description
- OpenCV => 3.1.0
- Operating System / Platform => Mac OS 10.11.6
- Compiler => gcc

##### Detailed description

I was following instruction to install opencv with python2.7 on 
"http://www.pyimagesearch.com/2015/06/15/install-opencv-3-0-and-python-2-7-on-osx/".
Everything works fine till I run "make -j4" command in build folder and error occur : 

[  1%] Built target zlib
[  3%] Built target libjpeg
[  5%] Built target libjasper
[  8%] Built target libwebp
[ 10%] Built target libpng
[ 12%] Built target libprotobuf
[ 13%] Built target libtiff
[ 17%] Built target IlmImf
[ 20%] Built target opencv_core
[ 20%] Built target opencv_flann
[ 20%] Built target opencv_surface_matching
[ 21%] Built target opencv_ml
[ 23%] Built target opencv_imgproc
[ 25%] Built target opencv_reg
[ 25%] Built target opencv_video
[ 26%] Built target opencv_dnn
[ 27%] Built target opencv_photo
[ 28%] Built target opencv_imgcodecs
[ 28%] Built target opencv_fuzzy
[ 28%] Built target opencv_shape
[ 28%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o
/Users/varunkumar/opencv/modules/videoio/src/cap_qtkit.mm:46:9: fatal error: 
      'QTKit/QTKit.h' file not found
#import <QTKit/QTKit.h>
        ^
1 error generated.
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o] Error 1
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [all] Error 2

**Comment by alalek** [comment]
Please check this patch: #7266
