### PR TITLE
imgproc: accept CV_Bool input in morphological operations

### LINKED ISSUE #29798: cv::dilate asserts on input mask of type CV_Bool
### System Information

OpenCV version: 4.13 and 5.0.0
OS: Windows+macOS
Compilers: MSVS 2022/2026 and XCode 16.1/26.4 Clang

### Detailed description

When cv::dilate is passed a cv::Mat_<bool>, this worked fine in 4.x, but now throws an exception.

I believe this function was missed when CV_Bool was added, and the assertion should be extended to allow CV_Bool as iDepth value.

This behaviour violates [the expectation expressed in the migration guide ](https://github.com/opencv/opencv/wiki/OpenCV-4-to-5-migration#new-data-types)as

    CV_Bool matrices can now be used as masks wherever a CV_8U or CV_8S mask was previously accepted.

See also previous similar issues: https://github.com/opencv/opencv/issues/29578, https://github.com/opencv/opencv/issues/29593 https://github.com/opencv/opencv/issues/29596 

### Steps to reproduce

```cpp
#include <opencv2/imgproc.hpp>

int main()
{
    cv::Mat_<bool> mask(2,2);
    cv::dilate(mask, mask);
}
```

This works with OpenCV 4.13 but throws an exception with OpenCV 5.0.0:

OpenCV(5.0.0) .../modules/imgproc/src/morph.simd.hpp:762: error: (-213:The function/feature is not implemented) Unsupported data type (

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by lazerg**
### Pull Request Readiness Checklist

Fixes #29798

In 5.0 `cv::Mat_<bool>::depth()` returns `CV_Bool` instead of `CV_8U`, so the morphology filter factories in `morph.simd.hpp` no longer matched any branch and threw `Unsupported data type`. This worked in 4.x.

`CV_Bool` is a 1-byte 0/1 type, so it is dispatched through the same `uchar` min/max filters as `CV_8U`, and the default border value follows the `CV_8U` case (1 for erode, 0 for dilate). The OpenCL path bails out for `CV_Bool` and falls back to the CPU implementation, since `ocl::typeToStr` has no mapping for it.

Accepting `CV_Bool` also exposed a latent bug in `FilterEngine::init`: `borderElemSize` was computed from `CV_MAT_DEPTH(srcType) >= CV_32S`, which assumes the depth enum is ordered by element size. `CV_Bool` is 9, so a 1-byte type took the `sizeof(int)` branch and `borderElemSize` became 0, leaving `borderTab` empty and making every non-`BORDER_CONSTANT` erode/dilate read through a null pointer. It now keys off `CV_ELEM_SIZE1` instead. `CV_16F`/`CV_16BF` had the same latent miscomputation.

Added a test comparing `Mat_<bool>` against the equivalent `CV_8UC1` mask for erode, dilate, open and close over the three structuring element shapes and four border types, plus in-place and multi-iteration calls.

`MORPH_GRADIENT`/`TOPHAT`/`BLACKHAT` remain unsupported for `CV_Bool`: they subtract two masks, which has no meaning for a boolean type, and they throw rather than returning a wrong result.

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/imgproc/test/test_filter.cpp [hunk 1]
```diff
@@ -1075,6 +1075,61 @@ TEST(Imgproc, morphologyEx_small_input_22893)
...
+    mask(6, 7) = true;
+
+    Mat_<uchar> ref;
+    mask.convertTo(ref, CV_8U);
+
+    ASSERT_EQ(mask.depth(), CV_Bool);
+
+    const int ops[] = { MORPH_ERODE, MORPH_DILATE, MORPH_OPEN, MORPH_CLOSE };
+    const int shapes[] = { MORPH_RECT, MORPH_CROSS, MORPH_ELLIPSE };
+    const int borderTypes[] = { BORDER_CONSTANT, BORDER_REPLICATE, BORDER_REFLECT, BORDER_REFLECT_101 };
```
Comment (asmorkalov) [inline modules/imgproc/test/test_filter.cpp]: Please convert the test into parameterized with TEST_P macro.

File: modules/imgproc/src/filter.dispatch.cpp [hunk 2]
```diff
@@ -145,7 +145,7 @@ void FilterEngine::init( const Ptr<BaseFilter>& _filter2D,
     CV_Assert( 0 <= anchor.x && anchor.x < ksize.width &&
                0 <= anchor.y && anchor.y < ksize.height );
 
-    borderElemSize = srcElemSize/(CV_MAT_DEPTH(srcType) >= CV_32S ? sizeof(int) : 1);
+    borderElemSize = srcElemSize/(CV_ELEM_SIZE1(srcType) >= (int)sizeof(int) ? sizeof(int) : 1);
```
Comment (asmorkalov) [inline modules/imgproc/src/filter.dispatch.cpp]: `CV_ELEM_SIZE1` is size of one channel of matrix element. `int srcElemSize = (int)getElemSize(srcType);`
`static inline size_t getElemSize(int type) { return (size_t)CV_ELEM_SIZE(type); }`
`CV_ELEM_SIZE` is `(CV_MAT_CN(type)*CV_ELEM_SIZE1(type))`. So the condition is about amount of channels. It sounds strange and incorrect.

**Review by asmorkalov — CHANGES_REQUESTED** [review]

File: modules/imgproc/test/test_filter.cpp (hunk 1 above)
Comment (lazerg) [reply modules/imgproc/test/test_filter.cpp]: Done in 841d3a043. The test is now `Imgproc_Morphology_Bool.bool_mask_29798`, a `TEST_P` over (op, structuring element shape, border type) with `INSTANTIATE_TEST_CASE_P` + `Combine`. The same 48 combinations run, and all of them pass.

File: modules/imgproc/src/filter.dispatch.cpp (hunk 2 above)
Comment (lazerg) [reply modules/imgproc/src/filter.dispatch.cpp]: The line reads badly, agreed. I rewrote it with a comment in 841d3a043. The value it produces is correct, and here is the math behind it.

`FilterEngine__proceed()` reads `borderTab` in two ways (filter.simd.hpp:247-263): as int offsets when `borderElemSize*sizeof(int) == CV_ELEM_SIZE(srcType)`, and as byte offsets in all other cases. So `borderElemSize` must be `CV_ELEM_SIZE(srcType)/sizeof(int)` for channel types of int size or larger, and `CV_ELEM_SIZE(srcType)` for the smaller ones.

For CV_32S and CV_32F the first form happens to equal the channel count, because the channel is 4 bytes wide. That is a coincidence of those depths, not the intent. For CV_64F the same form gives 2*cn.

The condition uses `CV_ELEM_SIZE1` only, so it tests the channel type size and not the channel count. The old form was `CV_MAT_DEPTH(srcType) >= CV_32S`, which assumes the depth enum is sorted by element size. CV_16F=7, CV_16BF=8 and CV_Bool=9 break that assumption, so a 1 or 2 byte type took the divide by 4 branch. For CV_BoolC1 the result is 0, `borderTab` stays empty, and the border loop then dereferences a null pointer. `erode`/`dilate` on a `Mat_<bool>` with BORDER_REPLICATE or BORDER_REFLECT segfaults without this fix.

I compared the new form against the rule above for every depth with 1 to 4 channels. It matches everywhere, and it differs from the old form only for CV_16F, CV_16BF and CV_Bool.

**Review by fallenmi — APPROVED** [review]
Reviewed exact head `841d3a043687905446ba7d8c82576cc16214baa0`. I found no blocking issue.

The `CV_Bool` dispatch restores the 4.x boolean-mask behavior while preserving the type's 0/1 representation. The revised `borderElemSize` also matches `FilterEngine__proceed()`'s actual contract: element types at least four bytes use int-unit offsets, while smaller channel types use byte offsets for the complete multi-channel element.

An independent exact-revision oracle makes exact base `8b7dc43c` fail immediately with `Unsupported data type (=9)`. Exact head and current synthetic merge `8354a7dd` each pass 5,040 cases covering `CV_BoolC1` through `CV_BoolC4`, erode/dilate/open/close, five rectangular/cross/ellipse/custom kernels (including a non-centered anchor), one to three iterations, seven constant/nonconstant/isolated border configurations, non-contiguous ROIs, out-of-place and in-place calls, and `UMat` CPU fallback. Ten repeated head runs processed 14,981,400 output values apiece with the same digest. The submitted 48-case parameterized suite also passed five repetitions (240/240), and the existing morphology/filter-engine-focused tests passed.

The two red upstream jobs on Ubuntu 20.04 and 22.04 are unrelated to this diff: both fail the same eight DNN tests because the corresponding ONNX model files are missing from the test-data checkout. The other 25 exact-head checks are green, including Alpine, Windows, ARM64, macOS, iOS, Android, CUDA/OpenVINO, docs, and RISC-V.

AI disclosure: I used OpenAI Codex to inspect the exact diff and filter-engine contracts, build the exact revisions, construct and run the base/head/current-merge boundary oracle, classify the CI failures, and draft this review. I manually verified the code paths, outputs, exact commits, policy, interactions, and conclusion.
