### ISSUE TITLE
OpenCV 4.0.1 + Cuda 10.1, failed to build?

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv#13952]
It looks it's still a kind of buggy? Did any of you have successfully built OpenCV 4.0.1 with Cuda 10.1?

```
....../opencv/modules/core/include/opencv2/core/cvstd_wrapper.hpp(45): error: incomplete type is not allowed
          detected during:
            instantiation of "cv::sfinae::has_parenthesis_operator<C, Ret, Args...>::check [with C=cv::DefaultDeleter<<unnamed>::LookUpTableImpl>, Ret=void, Args=<<unnamed>::LookUpTableImpl *>]" based on template argument <cv::DefaultDeleter<<unnamed>::LookUpTableImpl>> 
(49): here
            instantiation of class "cv::sfinae::has_parenthesis_operator<C, Ret, Args...> [with C=cv::DefaultDeleter<<unnamed>::LookUpTableImpl>, Ret=void, Args=<<unnamed>::LookUpTableImpl *>]" 
(138): here
            instantiation of "cv::Ptr<_Tp> cv::makePtr<_Tp,A1...>(const A1 &...) [with _Tp=<unnamed>::LookUpTableImpl, A1=<cv::_InputArray>]" 
....../opencv_contrib/modules/cudaarithm/src/cuda/lut.cu(207): here

....../opencv/modules/core/include/opencv2/core/cvstd_wrapper.hpp(49): error: template instantiation resulted in unexpected function type of "std::true_type (std::integral_constant<__nv_bool, false> *)" (the meaning of a name may have changed since the template declaration -- the type of the template is "std::true_type (std::is_same<std::decay<decltype((<expression>))>::type, void>::type *)")
          detected during:
            instantiation of "cv::sfinae::has_parenthesis_operator<C, Ret, Args...>::check [with C=cv::DefaultDeleter<<unnamed>::LookUpTableImpl>, Ret=void, Args=<<unnamed>::LookUpTableImpl *>]" based on template argument <cv::DefaultDeleter<<unnamed>::LookUpTableImpl>> 
(49): here
            instantiation of class "cv::sfinae::has_parenthesis_operator<C, Ret, Args...> [with C=cv::DefaultDeleter<<unnamed>::LookUpTableImpl>, Ret=void, Args=<<unnamed>::LookUpTableImpl *>]" 
(138): here
            instantiation of "cv::Ptr<_Tp> cv::makePtr<_Tp,A1...>(const A1 &...) [with _Tp=<unnamed>::LookUpTableImpl, A1=<cv::_InputArray>]" 
....../opencv_contrib/modules/cudaarithm/src/cuda/lut.cu(207): here

....../opencv/modules/core/include/opencv2/core/cvstd_wrapper.hpp(52): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "cv::sfinae::has_parenthesis_operator<C, Ret, Args...> [with C=cv::DefaultDeleter<<unnamed>::LookUpTableImpl>, Ret=void, Args=<<unnamed>::LookUpTableImpl *>]" 
(138): here
            instantiation of "cv::Ptr<_Tp> cv::makePtr<_Tp,A1...>(const A1 &...) [with _Tp=<unnamed>::LookUpTableImpl, A1=<cv::_InputArray>]" 
....../opencv_contrib/modules/cudaarithm/src/cuda/lut.cu(207): here

3 errors detected in the compilation of "/tmp/tmpxft_00006477_00000000-6_lut.cpp1.ii".
-- Removing ....../opencv/build/modules/cudaarithm/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_lut.cu.o
/usr/bin/cmake -E remove ....../opencv/build/modules/cudaarithm/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_lut.cu.o
CMake Error at cuda_compile_1_generated_lut.cu.o.Release.cmake:279 (message):
  Error generating file
  ....../opencv/build/modules/cudaarithm/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_lut.cu.o


modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/build.make:6764: recipe for target 'modules/cudaarithm/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_lut.cu.o' failed
make[2]: *** [modules/cudaarithm/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_lut.cu.o] Error 1
make[2]: Leaving directory '....../opencv/build'
CMakeFiles/Makefile2:2276: recipe for target 'modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/all' failed
make[1]: *** [modules/cudaarithm/CMakeFiles/opencv_cudaarithm.dir/all] Error 2
make[1]: Leaving directory '....../opencv/build'
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
```

Cheers

**Comment by alalek** [comment]
Related links: [1](https://github.com/opencv/opencv/commit/b80c978f5dc29a8d307424c06a929bd454248c0f#r32544466), #13941

Please keep issues open until fixes are merged into code.
Avoid creation of similar issues.

**Comment by qc2105** [comment]
I have successfully built OpenCV 4.0.1 with Cuda 10.1.
Check this: [modified cvstd_wrapper.hpp](https://github.com/qc2105/opencv/commit/b32ba55150c5d678836a80700a126dae8c5b67f8)

**Comment by qc2105** [comment]
With the two changes mentioned in https://github.com/opencv/opencv/issues/13941#issuecomment-468775830, I have built all cuda modules successfully.

**Comment by nglee** [comment]
Summary of build failures on various settings(with CUDA enabled):

| CUDA | OpenCV(Branch) |  Compiler | Build Failure                     |
|:----:|:--------------:|:---------:|-----------------------------------|
| 10.1 | master         | GCC 7.3.0 | YES (#13941, #13952)              |
| 10.1 | master         | GCC 5.4.0 | YES (#13941, #13952)              |
| 10.1 | master         | VS2015    | YES (#13491, #13952)              |
| 10.1 | 3.4            | GCC 7.3.0 | YES (#13941)                      |
| 10.1 | 3.4            | GCC 5.4.0 | YES (#13941)                      |
| 10.1 | 3.4            | VS2015    | NO                                |
| 10.0 | master         | GCC 7.3.0 | NO                                |
| 10.0 | master         | GCC 5.4.0 | NO                                |
| 10.0 | master         | VS2015    | YES (#13491)                      |
| 10.0 | 3.4            | GCC 7.3.0 | NO                                |
| 10.0 | 3.4            | GCC 5.4.0 | NO                                |
| 10.0 | 3.4            | VS2015    | YES (dynlink_nvcuvid.h not found) |

**Comment by qc2105** [comment]
> Summary of build failures on various settings(with CUDA enabled):
> 
> CUDA	OpenCV(Branch)	Compiler	Build Failure
> 10.1	master	GCC 7.3.0	YES (#13941, #13952)
> 10.1	master	GCC 5.4.0	YES (#13941, #13952)
> 10.1	master	VS2015	YES (#13491, #13952)
> 10.1	3.4	GCC 7.3.0	YES (#13941)
> 10.1	3.4	GCC 5.4.0	YES (#13941)
> 10.1	3.4	VS2015	NO
> 10.0	master	GCC 7.3.0	NO
> 10.0	master	GCC 5.4.0	NO
> 10.0	master	VS2015	YES (#13491)
> 10.0	3.4	GCC 7.3.0	NO
> 10.0	3.4	GCC 5.4.0	NO
> 10.0	3.4	VS2015	YES (dynlink_nvcuvid.h not found)
HI @nglee :
Have you run "make test" with cuda 10.0?, although I have built it with cuda10.1/master/GCC 7.3.0 successfully, I've got lots of failed tests. I wonder with cuda 10.0 whether we had failed tests or not?

**Comment by nglee** [comment]
Hi @qc2105,
Have you set up test data as described in step 8 of [this manual](https://github.com/opencv/opencv/wiki/How_to_contribute#the-instruction-in-brief)?

In my case for `master` branch with CUDA 10.0, GCC 7.3.0:
```
The following tests FAILED:
         12 - opencv_test_cudaimgproc (Failed)
         19 - opencv_test_photo (Failed)
         44 - opencv_test_face (Failed)
         46 - opencv_test_stitching (Failed)
         47 - opencv_test_tracking (Failed)
```
For `3.4` branch(CUDA 10.0, GCC 7.3.0), all tests passed.

**Comment by qc2105** [comment]
> Hi @qc2105,
> Have you set up test data as described in step 8 of [this manual](https://github.com/opencv/opencv/wiki/How_to_contribute#the-instruction-in-brief)?
> 
> In my case for `master` branch with CUDA 10.0, GCC 7.3.0:
> 
> ```
> The following tests FAILED:
>          12 - opencv_test_cudaimgproc (Failed)
>          19 - opencv_test_photo (Failed)
>          44 - opencv_test_face (Failed)
>          46 - opencv_test_stitching (Failed)
>          47 - opencv_test_tracking (Failed)
> ```
> For `3.4` branch(CUDA 10.0, GCC 7.3.0), all tests passed.


Thank you for your reply! Although setting up test data improved the results, I still have 82 tests failed. I'll try to switch to branch 3.4.

**Comment by haijun-dgp** [comment]
Modified cvstd_wrapper.hpp as suggested. Still having some errors. With Visual Studio 15 2017 Win64

![image](https://user-images.githubusercontent.com/33161305/53773264-a9c97400-3eb7-11e9-837c-d9a91dcef471.png)

**Comment by Adhders** [comment]
> Summary of build failures on various settings(with CUDA enabled):
> 
> CUDA	OpenCV(Branch)	Compiler	Build Failure
> 10.1	master	GCC 7.3.0	YES (#13941, #13952)
> 10.1	master	GCC 5.4.0	YES (#13941, #13952)
> 10.1	master	VS2015	YES (#13491, #13952)
> 10.1	3.4	GCC 7.3.0	YES (#13941) NO(Fixed)
> 10.1	3.4	GCC 5.4.0	YES (#13941) NO(Fixed)
> 10.1	3.4	VS2015	NO
> 10.0	master	GCC 7.3.0	NO
> 10.0	master	GCC 5.4.0	NO
> 10.0	master	VS2015	YES (#13491) NO(Fixed)
> 10.0	3.4	GCC 7.3.0	NO
> 10.0	3.4	GCC 5.4.0	NO
> 10.0	3.4	VS2015	YES (dynlink_nvcuvid.h not found)


CUDA 10.1 with OpenCV_contrib 3.4 ,GCC 7.3.0	Build error 

imgcodecs_c.h:1:2: error: #error "This header with legacy C API declarations has been removed from OpenCV.

**Comment by nglee** [comment]
@alalek 

From `cvstd_wrapper.hpp`, replacing following code block:
https://github.com/opencv/opencv/blob/332c37f332733e5a2d717fc6eb4d605a304cda70/modules/core/include/opencv2/core/cvstd_wrapper.hpp#L32-L37
to following:
```
template<typename Y> struct DefaultDeleter
{
    void operator()(Y* p) const = delete; // not available by default; enabled for specializations only
};
```
seems to fix this issue. The `master` branch successfully builds with CUDA 10.1, and also with CUDA 10.0.

This fix tries to declare the function `DefaultDeleter::operator()`. I've got the idea of how it should be declared from the code's history.

The error message complains about using incomplete type, and the only incomplete type involved here seems to be `DefaultDeleter`. So I think this is a viable solution.

---------------------

The [NVIDIA CUDA Toolkit Release Notes(for 10.1)](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-compiler-resolved-issues) says:

> Within a template function, the CUDA compiler previously incorrectly allowed the use of an undeclared function. In CUDA 10.1, this compiler bug has been fixed and may cause diagnostics to be emitted for code that was previously incorrectly accepted.

May be using the undeclared function `DefaultDeleter::operator()` from the template function `has_parenthesis_operator::check` is not allowed starting from CUDA 10.1 and this might be the reason for this build failure.

**Comment by alalek** [comment]
@nglee Thank you for investigation!
I suggest to start from note (2).

1.
Can we extract "Ptr"-related code from `lut.cu` to new `lut.cpp` (which is not handled by NVCC)?

2.
CUDA code should not have `Ptr` wrappers for legacy C structs, so we can force `has_custom_delete` to `std::false_type` under NVCC (and drop via `#if` declarations of `has_parenthesis_operator` and `DefaultDeleter`).

3.
> = delete

It was here, but it can't be used for MSVS for some reason. See #12509.

**Comment by nglee** [comment]
@alalek 
> CUDA code should not have `Ptr` wrappers for legacy C structs, so we can force `has_custom_delete` to `std::false_type` under NVCC (and drop via `#if` declarations of `has_parenthesis_operator` and `DefaultDeleter`).

Are we trying to make compiling step to fail when someone writes `Ptr` wrapper for legacy C structs in CUDA codes? If so, I don't think we should force `has_custom_delete` to `std::false_type` because it would make `makePtr` to always succeed for CUDA code.

**Comment by alalek** [comment]
> make compiling step to fail

No.
It will not fail. This change will disable (ignore) usage for all custom implicit cv::DefaultDeleter.
`std::make_shared` still work if we need custom deleter somewhere.

However, compile-time check for `cv::DefaultDeleter` will be disabled. But it is not critical, because OpenCV doesn't need custom deleters (`delete` operator is enough) in CUDA code.
Until CUDA compiler support SFINAE, this compile-time check can be explicitly disabled by `#ifdef __CUDACC__`.

**Comment by nglee** [comment]
Ok, I'll first open a PR that does this:
> CUDA code should not have `Ptr` wrappers for legacy C structs, so we can force `has_custom_delete` to `std::false_type` under NVCC (and drop via `#if` declarations of `has_parenthesis_operator` and `DefaultDeleter`).

and work on this:
>Can we extract `Ptr`-related code from `lut.cu` to new `lut.cpp` (which is not handled by NVCC)?

afterwards.
