### ISSUE TITLE
Build regression with Eigen 3.4.0 on Windows & MSVC 19.1

### ISSUE THREAD

**Issue by KelSolaar** [opencv/opencv#21675]
##### System information (version)

- OpenCV => 4.5.5
- Operating System / Platform => Windows 10
- Compiler => Visual Studio 2017 version 15.0 (MSVC 19.1)

##### Detailed description

Hello,

I have been having issues trying to build with Eigen 3.4.0 on Windows and MSVC 19.1. It seems like it is a regression and is similar to https://github.com/opencv/opencv/issues/15525. OpenCV builds just fine with Eigen 3.3.9.

```shell
eigen\eigen\eigen\src/Core/GenericPacketMath.h(788): error C2665: 'exp': none of the 3 overloads could convert all the argument types [opencv\build\platform-windows\arch-AMD64\msvc-19.1\python-3.9\opencv\modules\core\opencv_core_AVX512_SKX.vcxproj]
eigen\eigen\eigen\src/Core/GenericPacketMath.h(796): error C2665: 'log': none of the 3 overloads could convert all the argument types [opencv\build\platform-windows\arch-AMD64\msvc-19.1\python-3.9\opencv\modules\core\opencv_core_AVX512_SKX.vcxproj]
```

##### Steps to reproduce

N/A

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [N/A] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by hmaarrfk** [comment]
If a build log helps, here is one

[windows_eigen_log.txt](https://github.com/opencv/opencv/files/8800296/windows_eigen_log.txt)

**Comment by cantonios** [comment]
There are a lot of compile warnings in the log.  Some opencv source files seem to have
```
using namespace cv;
```
which is always a bad idea, and is causing symbol shadowing (specifically between `cv::Scalar`, and all the `Scalar` types throughout Eigen).  This is the cause of the majority of warnings in the build log.

The build error is an eigen bug (combined with a VS bug) - older versions of VS don't properly support AVX512 simd math functions, so we disable them.  There's one spot in AVX512/BesselFunctions.h though that we forget to disable.  Will be fixed on the master branch soon.  If you need to compile on VS without the fix, you'll need to use a newer version (e.g. 2019 16.3 or newer).

**Comment by hmaarrfk** [comment]
Thank you very much for taking a look at it. I'm going to try to build with vs2019 and see if that fixes things. High hopes!

**Comment by db4** [comment]
@cantonios 
>  Will be fixed on the master branch soon.

Has it been fixed? I'd like to add the fix to opencv conan package that is broken due to eigen upgrade.

**Comment by hmaarrfk** [comment]
i think the "fix" might be to use VS2019.  I don't recall any recent issues with eigen + windows on conda-forge
https://github.com/conda-forge/opencv-feedstock/blob/main/recipe/meta.yaml

**Comment by db4** [comment]
> i think the "fix" might be to use VS2019

Unfortunately for me, it's not acceptable. I wouldn't ask but @cantonios announced a fix for VS2017 as already done (at least I understood him that way)

**Comment by cantonios** [comment]
> Has it been fixed? I'd like to add the fix to opencv conan package that is broken due to eigen upgrade.

> I wouldn't ask but @cantonios announced a fix for VS2017 as already done (at least I understood him that way)

The fix (disabling AVX512 bessel functions) went in to master a year ago with [Eigen !1001].(https://gitlab.com/libeigen/eigen/-/merge_requests/1001).  This was not (yet) cherry-picked to the 3.4 branch, and we haven't released a 3.4.1.  So whether you consider it "fixed" or not depends on what version of Eigen you can link to.

**Comment by db4** [comment]
@cantonios 
That's exactly what I was asking for. Thanks a lot!

**Comment by db4** [comment]
@cantonios 

Unfortunately [Eigen !1001](https://gitlab.com/libeigen/eigen/-/merge_requests/1001) is not enough. OpenCV 4.5.3 build still fails with
```
d:\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\eigen\src/Core/MathFunctions.h(327): error C2665: 'sqrt': none of the 3 overloads could convert all the argument types [D:\.conan\c7c6b4\1\build\modules\imgproc\opencv_imgproc_AVX512_SKX.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\cmath(600): note: could be 'long double sqrt(long double) noexcept'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\cmath(293): note: or       'float sqrt(float) noexcept'
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_math.h(483): note: or       'double sqrt(double)'
  d:\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\eigen\src/Core/MathFunctions.h(327): note: while trying to match the argument list '(const Scalar)'
          with
          [
              Scalar=__m512
          ]
  d:\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\eigen\src/Core/MathFunctions.h(325): note: while compiling class template member function 'Scalar Eigen::internal::sqrt_impl<Scalar>::run(const Scalar &)'
          with
          [
              Scalar=__m512
          ]
  d:\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\eigen\src/Core/MathFunctions.h(1467): note: see reference to function template instantiation 'Scalar Eigen::internal::sqrt_impl<Scalar>::run(const Scalar &)' being compiled
          with
          [
              Scalar=__m512
          ]
  d:\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\eigen\src/Core/MathFunctions.h(1467): note: see reference to class template instantiation 'Eigen::internal::sqrt_impl<__m512>' being compiled
  d:\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\eigen\src/Core/GenericPacketMath.h(815): note: see reference to function template instantiation '__m512 Eigen::numext::sqrt<Packet>(const Scalar &)' being compiled
          with
          [
              Packet=Eigen::internal::Packet16f,
              Scalar=Eigen::internal::Packet16f
          ]
  d:\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\eigen\src/Core/arch/Default/GenericPacketMathFunctions.h(813): note: see reference to function template instantiation 'Packet Eigen::internal::psqrt<Eigen::internal::Packet16f>(const Packet &)' being compiled
          with
          [
              Packet=Eigen::internal::Packet16f
          ]
  d:\.conan\data\eigen\3.4.0\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\eigen3\eigen\src/Core/arch/AVX512/Complex.h(416): note: see reference to function template instantiation 'Packet Eigen::internal::psqrt_complex<Eigen::internal::Packet8cf>(const Packet &)' being compiled
          with
          [
              Packet=Eigen::internal::Packet8cf
          ]
```
Looks like another eigen 3.4.0 problem w.r.t. VS2017

**Comment by cantonios** [comment]
@db4 are you separately cherry-picking that MR onto the 3.4 branch?  Maybe you need [!832](https://gitlab.com/libeigen/eigen/-/merge_requests/832) as well?

I just tried now, and the master branch currently seems to build with VS2017 and AVX512.

**Comment by db4** [comment]
@cantonios yes, I need to fix eigen/3.4.0 Conan package that is a dependency of many other packages, so I have to create a minimal patch set for that specific version. I cannot just move to the master branch.

Unfortunately,  [!832](https://gitlab.com/libeigen/eigen/-/merge_requests/832) doesn't apply cleanly to 3.4.0, so additional efforts are still needed...
