### ISSUE TITLE
Build fails with lapack 3.9.1

### ISSUE THREAD

**Issue by antonio-rojas** [opencv/opencv#19846]
##### System information (version)
- OpenCV => 4.5.2
- Operating System / Platform => Linux
- Compiler => GCC 10.2.0

##### Detailed description
opencv fails to build with lapack 3.9.1 with the following error:
```
/build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp: In function ‘int lapack_QR(fptype*, size_t, int, int, int, fptype*, size_t, fptype*, int*)’:
/build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:293:111: error: too few arguments to function ‘void dgels_(const char*, const int*, const int*, const int*, double*, const int*, double*, const int*, double*, const int*, int*, size_t)’
  293 |                 dgels_(mode, &m, &n, &k, (double*)tmpA, &ldtmpA, (double*)b, &m, (double*)&work1, &lwork, info);
      |                                                                                                               ^
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from /build/opencv/src/build/opencv_lapack.h:12,
                 from /build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:1525:6: note: declared here
 1525 | void LAPACK_dgels_base(
      |      ^~~~~~~~~~~~~~~~~
/build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:302:111: error: too few arguments to function ‘void dgels_(const char*, const int*, const int*, const int*, double*, const int*, double*, const int*, double*, const int*, int*, size_t)’
  302 |                 dgels_(mode, &m, &n, &k, (double*)tmpA, &ldtmpA, (double*)b, &m, (double*)buffer, &lwork, info);
      |                                                                                                               ^
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from /build/opencv/src/build/opencv_lapack.h:12,
                 from /build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:1525:6: note: declared here
 1525 | void LAPACK_dgels_base(
      |      ^~~~~~~~~~~~~~~~~
/build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:314:114: error: too few arguments to function ‘void dgels_(const char*, const int*, const int*, const int*, double*, const int*, double*, const int*, double*, const int*, int*, size_t)’
  314 |                 dgels_(mode, &m, &n, &k, (double*)tmpA, &ldtmpA, (double*)tmpB, &m, (double*)&work1, &lwork, info);
      |                                                                                                                  ^
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from /build/opencv/src/build/opencv_lapack.h:12,
                 from /build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:1525:6: note: declared here
 1525 | void LAPACK_dgels_base(
      |      ^~~~~~~~~~~~~~~~~
/build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:323:114: error: too few arguments to function ‘void dgels_(const char*, const int*, const int*, const int*, double*, const int*, double*, const int*, double*, const int*, int*, size_t)’
  323 |                 dgels_(mode, &m, &n, &k, (double*)tmpA, &ldtmpA, (double*)tmpB, &m, (double*)buffer, &lwork, info);
      |                                                                                                                  ^
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from /build/opencv/src/build/opencv_lapack.h:12,
                 from /build/opencv/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:1525:6: note: declared here
 1525 | void LAPACK_dgels_base(
      |      ^~~~~~~~~~~~~~~~~
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/split.dispatch.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/stat.dispatch.cpp.o
[  9%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/stat_c.cpp.o
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:509: modules/core/CMakeFiles/opencv_core.dir/src/hal_internal.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

##### Steps to reproduce
Build opencv with lapack 3.9.1

Possibly related: https://github.com/Reference-LAPACK/lapack/commit/2d9fbdeecca906d7abb89e9cc16b02ed5286298e

**Comment by alalek** [comment]
Workaround: `cmake -DWITH_LAPACK=OFF ...`

**Comment by antonio-rojas** [comment]
Another workaround: `s/dgels_/LAPACK_dgels/`

**Comment by alexdewar** [comment]
+1 for the fix by @antonio-rojas

**Comment by steczol** [comment]
@antonio-rojas 
> Another workaround: `s/dgels_/LAPACK_dgels/`

Could you please explain what do you mean by this line?
Where should it be added/modified?

**Comment by antonio-rojas** [comment]
> Could you please explain what do you mean by this line?
> Where should it be added/modified?

See https://github.com/archlinux/svntogit-packages/blob/packages/opencv/trunk/opencv-lapack-3.9.1.patch

**Comment by alexdewar** [comment]
I'm getting even more errors of a similar kind with LAPACK 3.10.0:
```
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp: In function ‘int lapack_Cholesky(fptype*, size_t, int, fptype*, size_t, int, bool*)’:
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:166:23: error: too few arguments to function ‘void sposv_(const char*, const int*, const int*, float*, const int*, float*, const int*, int*, size_t)’
  166 |                 sposv_(L, &m, &n, (float*)a, &lda, (float*)b, &m, &lapackStatus);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from ./opencv_lapack.h:12,
                 from /build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:13003:6: note: declared here
13003 | void LAPACK_sposv_base(
      |      ^~~~~~~~~~~~~~~~~
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:168:23: error: too few arguments to function ‘void dposv_(const char*, const int*, const int*, double*, const int*, double*, const int*, int*, size_t)’
  168 |                 dposv_(L, &m, &n, (double*)a, &lda, (double*)b, &m, &lapackStatus);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from ./opencv_lapack.h:12,
                 from /build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:12986:6: note: declared here
12986 | void LAPACK_dposv_base(
      |      ^~~~~~~~~~~~~~~~~
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:177:23: error: too few arguments to function ‘void sposv_(const char*, const int*, const int*, float*, const int*, float*, const int*, int*, size_t)’
  177 |                 sposv_(L, &m, &n, (float*)a, &lda, (float*)tmpB, &m, &lapackStatus);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from ./opencv_lapack.h:12,
                 from /build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:13003:6: note: declared here
13003 | void LAPACK_sposv_base(
      |      ^~~~~~~~~~~~~~~~~
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:179:23: error: too few arguments to function ‘void dposv_(const char*, const int*, const int*, double*, const int*, double*, const int*, int*, size_t)’
  179 |                 dposv_(L, &m, &n, (double*)a, &lda, (double*)tmpB, &m, &lapackStatus);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from ./opencv_lapack.h:12,
                 from /build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:12986:6: note: declared here
12986 | void LAPACK_dposv_base(
      |      ^~~~~~~~~~~~~~~~~
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:188:20: error: too few arguments to function ‘void spotrf_(const char*, const int*, float*, const int*, int*, size_t)’
  188 |             spotrf_(L, &m, (float*)a, &lda, &lapackStatus);
      |             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from ./opencv_lapack.h:12,
                 from /build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:13394:6: note: declared here
13394 | void LAPACK_spotrf_base(
      |      ^~~~~~~~~~~~~~~~~~
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:190:20: error: too few arguments to function ‘void dpotrf_(const char*, const int*, double*, const int*, int*, size_t)’
  190 |             dpotrf_(L, &m, (double*)a, &lda, &lapackStatus);
      |             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from ./opencv_lapack.h:12,
                 from /build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:13378:6: note: declared here
13378 | void LAPACK_dpotrf_base(
      |      ^~~~~~~~~~~~~~~~~~
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp: In function ‘int lapack_SVD(fptype*, size_t, fptype*, fptype*, size_t, fptype*, size_t, int, int, int, int*)’:
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:230:16: error: too few arguments to function ‘void sgesdd_(const char*, const int*, const int*, float*, const int*, float*, float*, const int*, float*, const int*, float*, const int*, int*, int*, size_t)’
  230 |         sgesdd_(mode, &m, &n, (float*)a, &lda, (float*)w, (float*)u, &ldu, (float*)vt, &ldv, (float*)&work1, &lwork, iworkBuf, info);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from ./opencv_lapack.h:12,
                 from /build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:3264:6: note: declared here
 3264 | void LAPACK_sgesdd_base(
      |      ^~~~~~~~~~~~~~~~~~
/build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:238:16: error: too few arguments to function ‘void sgesdd_(const char*, const int*, const int*, float*, const int*, float*, float*, const int*, float*, const int*, float*, const int*, int*, int*, size_t)’
  238 |         sgesdd_(mode, &m, &n, (float*)a, &lda, (float*)w, (float*)u, &ldu, (float*)vt, &ldv, (float*)buffer, &lwork, iworkBuf, info);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/lapack.h:11,
                 from /usr/include/lapacke.h:36,
                 from ./opencv_lapack.h:12,
                 from /build/opencv-cuda/src/opencv-4.5.2/modules/core/src/hal_internal.cpp:51:
/usr/include/lapack.h:3264:6: note: declared here
 3264 | void LAPACK_sgesdd_base(
```

**Comment by cappelletto** [comment]
> @antonio-rojas
> 
> > Another workaround: `s/dgels_/LAPACK_dgels/`
> 
> Could you please explain what do you mean by this line? Where should it be added/modified?

For future references this might come handy:
I faced a similar problem when compiling OpenCV 4.0.1 against OpenBLAS 0.3-21 on an ARM device. Using @antonio-rojas suggestions to replace all references to "`spotrf_ dpotrf_ dgesdd_ sgesdd_ sgels_ dgels_ sposv_ dposv_`" in `opencv-4.0.1/modules/core/src/hal_internal.cpp` 

A quick visit to bash can do the trick:
```
LIST="spotrf dpotrf dgesdd sgesdd sgels dgels sposv dposv"
for KK in $LIST; do echo $KK; sed -i "s/${KK}_/LAPACK_${KK}/g" /home/root/sources/opencv-4.0.1/modules/core/src/hal_internal.cpp; done;
```
then resume your compilation as usual.
