### ISSUE TITLE
cv2.cvtColor does not work with single pixel in OpenCV 4.5.4-dev

### ISSUE THREAD

**Issue by froanas** [opencv/opencv#20968]
##### System information (version)

- OpenCV => 4.5.4-dev
- Operating System / Platform => Windows 64 Bit
- Compiler => precompiled from opencv-contrib-python-headless 4.5.4.58

##### Detailed description

Issue encountered in python: https://github.com/opencv/opencv-python/issues/575
cvtColor should be able to convert a single pixel's color as it does in version 4.5.3

##### Steps to reproduce

```
import cv2
import numpy as np

pixel = np.uint8([[[40, 50, 200]]])
new_pixel = cv2.cvtColor(pixel, cv2.COLOR_RGB2BGR)
print(new_pixel)
```

with OpenCV 4.5.3, this runs successfully. With OpenCV 4.5.4-dev, I get the following error:
`OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix.cpp:466: error: (-215:Assertion failed) _step >= minstep in function 'cv::Mat::Mat'`

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by froanas** [comment]
Thanks!

FYI just found that `8UC4` works fine. Modified the code in my previous comment to use an alpha channel:
```
import cv2
import numpy as np

pixel = np.uint8([[[40, 50, 200, 255]]])
print(f"original pixel: {pixel}")
print(f"original pixel dumped: {cv2.utils.dumpInputArray(pixel)}")
new_pixel = cv2.cvtColor(pixel, cv2.COLOR_RGB2BGR)
print(f"new pixel: {cv2.utils.dumpInputArray(new_pixel)}")
print(f"new pixel dumped: {new_pixel}")
```

4.5.3 results:
```
original pixel: [[[ 40  50 200 255]]]
original pixel dumped: InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=1 dims(-1)=2 size(-1)=1x1 type(-1)=CV_8UC4
new pixel: InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=1 dims(-1)=2 size(-1)=1x1 type(-1)=CV_8UC3
new pixel dumped: [[[200  50  40]]]
```

4.5.4-dev results:
```
original pixel: [[[ 40  50 200 255]]]
original pixel dumped: InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=1 dims(-1)=2 size(-1)=1x1 type(-1)=CV_8UC4
new pixel: InputArray: empty()=false kind=0x00010000 flags=0x01010000 total(-1)=1 dims(-1)=2 size(-1)=1x1 type(-1)=CV_8UC3
new pixel dumped: [[[200  50  40]]]
```
