### ISSUE TITLE
3.2.0 fails to compile on archlinux x64 (gcc 6.3.1)

### ISSUE THREAD

**Issue by fommil** [opencv/opencv#8738]
Looks like gcc 6.0 => 6.3 got a little stricter. I've trimmed the output to the error. // @ItachiSan

```
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/immintrin.h:81:0,
                 from /usr/include/tbb/machine/gcc_itsx.h:61,
                 from /usr/include/tbb/machine/gcc_ia32_common.h:110,
                 from /usr/include/tbb/machine/linux_intel64.h:28,
                 from /usr/include/tbb/tbb_machine.h:239,
                 from /usr/include/tbb/aligned_space.h:25,
                 from /usr/include/tbb/tbb.h:35,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/private.hpp:63,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp:55:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/f16cintrin.h: In function ‘cv::v_float32x4 cv::v_cvt_f32(const cv::v_float16x4&)’:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/f16cintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128 _mm_cvtph_ps(__m128i)’: target specific option mismatch
 _mm_cvtph_ps (__m128i __A)
 ^~~~~~~~~~~~
In file included from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/hal/intrin.hpp:293:0,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp:84:
/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/hal/intrin_sse.hpp:1721:12: note: called from here
     return v_float32x4(_mm_cvtph_ps(a.val));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/immintrin.h:81:0,
                 from /usr/include/tbb/machine/gcc_itsx.h:61,
                 from /usr/include/tbb/machine/gcc_ia32_common.h:110,
                 from /usr/include/tbb/machine/linux_intel64.h:28,
                 from /usr/include/tbb/tbb_machine.h:239,
                 from /usr/include/tbb/aligned_space.h:25,
                 from /usr/include/tbb/tbb.h:35,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/private.hpp:63,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp:55:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/f16cintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128 _mm_cvtph_ps(__m128i)’: target specific option mismatch
 _mm_cvtph_ps (__m128i __A)
 ^~~~~~~~~~~~
In file included from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/hal/intrin.hpp:293:0,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp:84:
/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/hal/intrin_sse.hpp:1721:12: note: called from here
     return v_float32x4(_mm_cvtph_ps(a.val));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:235: modules/core/CMakeFiles/opencv_core.dir/src/convert.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1027: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build opencv-java.
```

**Comment by alalek** [comment]
Please add compiler command-line/options (via `make VERBOSE=1` or something like this)

**Comment by fommil** [comment]
```
cd /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core && /usr/bin/c++  -DCVAPI_EXPORTS -D__OPENCV_BUILD=1 -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/3rdparty/ippicv/ippicv_lnx/include -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build -isystem /usr/include/eigen3 -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/src -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/3rdparty/include/opencl/1.2  -march=native -O3 -pipe -fstack-protector-strong   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG -fPIC   -include "/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp"  -Winvalid-pch  -o CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o -c /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/src/cuda_gpu_mat.cpp
make[2]: Leaving directory '/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build'
[ 10%] Built target pch_Generate_opencv_stitching
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/immintrin.h:81:0,
                 from /usr/include/tbb/machine/gcc_itsx.h:61,
                 from /usr/include/tbb/machine/gcc_ia32_common.h:110,
                 from /usr/include/tbb/machine/linux_intel64.h:28,
                 from /usr/include/tbb/tbb_machine.h:239,
                 from /usr/include/tbb/aligned_space.h:25,
                 from /usr/include/tbb/tbb.h:35,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/private.hpp:63,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp:55:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/f16cintrin.h: In function ‘cv::v_float32x4 cv::v_cvt_f32(const cv::v_float16x4&)’:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/f16cintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128 _mm_cvtph_ps(__m128i)’: target specific option mismatch
 _mm_cvtph_ps (__m128i __A)
 ^~~~~~~~~~~~
In file included from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/hal/intrin.hpp:293:0,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp:84:
/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/hal/intrin_sse.hpp:1721:12: note: called from here
     return v_float32x4(_mm_cvtph_ps(a.val));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/immintrin.h:81:0,
                 from /usr/include/tbb/machine/gcc_itsx.h:61,
                 from /usr/include/tbb/machine/gcc_ia32_common.h:110,
                 from /usr/include/tbb/machine/linux_intel64.h:28,
                 from /usr/include/tbb/tbb_machine.h:239,
                 from /usr/include/tbb/aligned_space.h:25,
                 from /usr/include/tbb/tbb.h:35,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/private.hpp:63,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp:55:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/include/f16cintrin.h:46:1: error: inlining failed in call to always_inline ‘__m128 _mm_cvtph_ps(__m128i)’: target specific option mismatch
 _mm_cvtph_ps (__m128i __A)
 ^~~~~~~~~~~~
In file included from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/hal/intrin.hpp:293:0,
                 from /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp:84:
/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include/opencv2/core/hal/intrin_sse.hpp:1721:12: note: called from here
     return v_float32x4(_mm_cvtph_ps(a.val));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 10%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/cuda_host_mem.cpp.o
cd /tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core && /usr/bin/c++  -DCVAPI_EXPORTS -D__OPENCV_BUILD=1 -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/3rdparty/ippicv/ippicv_lnx/include -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build -isystem /usr/include/eigen3 -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/include -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/src -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core -I/tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/3rdparty/include/opencl/1.2  -march=native -O3 -pipe -fstack-protector-strong   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG -fPIC   -include "/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build/modules/core/precomp.hpp"  -Winvalid-pch  -o CMakeFiles/opencv_core.dir/src/cuda_host_mem.cpp.o -c /tmp/yaourt-tmp-fommil/aur-opencv-java/src/opencv-3.2.0/modules/core/src/cuda_host_mem.cpp
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:235: modules/core/CMakeFiles/opencv_core.dir/src/convert.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build'
make[1]: *** [CMakeFiles/Makefile2:1027: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: Leaving directory '/tmp/yaourt-tmp-fommil/aur-opencv-java/src/build'
make: *** [Makefile:163: all] Error 2

```

**Comment by fommil** [comment]
Yes I have `-march=native -O3 -pipe -fstack-protector-strong` in my archlinux pkg defaults.

Thank you, this worked! Shall we leave this open or do you consider this a package manager concern?

**Comment by ItachiSan** [comment]
@fommil I am building the package witht the default `makepkg` flags and I have no issue.
I've contacted you by e-mail, we can further discuss there. 😄
This can be used as reference for better FP16 detection.

**Comment by alalek** [comment]
`-march=native` is not supported well in 3.2.
Better support is added into the latest code of master branch (no releases yet).
