### ISSUE TITLE
BGRx format in the VideoCapture's gstreamer integration

### ISSUE THREAD

**Issue by wjzhou** [opencv/opencv#11059]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Linux Arm64
- Compiler => gcc 5

##### Detailed description
The gstreamer will return a vague error message `OpenCV(3.4.1) Error: Unspecified error (GStreamer: unable to start pipeline` when used the BGRx format. From the source code it is clear why this happens:

https://github.com/opencv/opencv/blob/6ffc48769ac60d53c4bd1913eac15117c9b1c9f7/modules/videoio/src/cap_gstreamer.cpp#L321-L323 

But these code comments are not accessible anywhere out of source code. And for the fourcc code, BGRx is more nature than BGR(at least for me)

Could we either
1. add these comments to public document
2. support BGRx in addition to BGR format?

Also, could we add an early error message if the format is not supported. For now, it didn't do anything if a unsupported format is present and it cause random error in later stage.

##### Steps to reproduce
``` python
import cv2
pipeline='v4l2src device=/dev/video1 ! video/x-raw,width=640,height=480,format=I420,framerate=30/1  !  videoconvert ! video/x-raw,width=640,height=480,format=BGRx ! appsink'
cap=cv2.VideoCapture(pipeline, cv2.CAP_GSTREAMER)
```
Error:
```
OpenCV(3.4.1) Error: Unspecified error (GStreamer: unable to start pipeline
) in cvCaptureFromCAM_GStreamer, file /home/nvidia/tmp/opencv/modules/videoio/src/cap_gstreamer.cpp, line 890
VIDEOIO(cvCreateCapture_GStreamer (CV_CAP_GSTREAMER_FILE, filename)): raised OpenCV exception:

OpenCV(3.4.1) /home/nvidia/tmp/opencv/modules/videoio/src/cap_gstreamer.cpp:890: error: (-2) GStreamer: unable to start pipeline
 in function cvCaptureFromCAM_GStreamer
```

**Comment by alalek** [comment]
0. `GST_DEBUG` may improve debugging experience.
1. You working with custom gstreamer pipeline. So it is your responsibility to follow current restrictions, like expected output format.
2. VideoCapture API itself doesn't support `BGRx` (32-bit per pixel) - this is clearly stated in documentation. Additional conversion is not a good solution. It is better to apply this conversion in gstreamer (but your pipeline forces `format=BGRx`). If you want gstreamer features, so perhaps you should use gstreamer directly. OpenCV Video I/O API is mostly designed for small universal demos.
3. I believe implementation details like these should not bloat documentation. There are no huge problems because OpenCV is Open Source library - all code is available.

**Comment by whizzzkid** [comment]
For some reason, I am getting the same error but I am pretty sure my problem is not the same.

```
$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cap=cv2.VideoCapture(0)
OpenCV(3.4.1-dev) Error: Unspecified error (GStreamer: unable to start pipeline
) in cvCaptureFromCAM_GStreamer, file /home/nishantarora/git-clients/ocv/opencv/modules/videoio/src/cap_gstreamer.cpp, line 890
VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:

OpenCV(3.4.1-dev) /home/nishantarora/git-clients/ocv/opencv/modules/videoio/src/cap_gstreamer.cpp:890: error: (-2) Unspecified error: GStreamer: unable to start pipeline
 in function cvCaptureFromCAM_GStreamer

>>>
```

I am not even sure, what's wrong. It's working fine on build 3.4.0 on my laptop, but fails on my workstations with multiple usb cameras.

Any thoughts?

**Comment by alalek** [comment]
`print(cap.isOpened())`?

To debug GStreamer you can use `GST_DEBUG` environment variable (refer to GStreamer documentation).

**Comment by wjzhou** [comment]
Not supporting BGRx and not adding implementation details to public document are understandable.


Could we add an early error message? 

https://github.com/opencv/opencv/blob/6ffc48769ac60d53c4bd1913eac15117c9b1c9f7/modules/videoio/src/cap_gstreamer.cpp#L321-L323

add CV_ERROR(CV_StsError, "Opencv: unknow GStreamer format, the supported format are BGR, GRAY ...\n");

Please feel free to close this issue.

**Comment by wjzhou** [comment]
@whizzzkid Your problem is probably permission of /dev/video0

You may set `GST_DEBUG=2` (Warning Level) to see the exact reason.

**Comment by yjcn** [comment]
@wjzhou I meet the same problem in jetson TX2. Have you solved it?

**Comment by wjzhou** [comment]
My problem was BGRx is not supported.
```
import cv2
pipeline='v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480,format=I420,framerate=30/1  !  videoconvert ! video/x-raw,width=640,height=480,format=BGR ! appsink'
cap=cv2.VideoCapture(pipeline, cv2.CAP_GSTREAMER)
```
This pipeline should work.

You may use 
```export GST_DEBUG=2``` to see more detailed error messages.

By the way, the opencv that came with the tx2 doesn't support gstreamer. You may need to recompile the opencv

With the opencv that came with the tx2:
```python
import cv2
print(cv2.getBuildInformation())
```
return 
```
...
Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 56.60.100)
      avformat:                  YES (ver 56.40.101)
      avutil:                    YES (ver 54.31.100)
      swscale:                   YES (ver 3.1.101)
      avresample:                NO
    GStreamer:                   NO
    libv4l/libv4l2:              NO
    v4l/v4l2:                    linux/videodev2.h
    gPhoto2:                     NO

  Parallel framework:            pthreads
...
```

**Comment by andrewssobral** [comment]
The same for me on Jetson TX2 (with JetPack 3.2):
By the way, in my case, I've built OpenCV 3.4.1 from source and here is the build info:
```
...
Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 56.60.100)
      avformat:                  YES (ver 56.40.101)
      avutil:                    YES (ver 54.31.100)
      swscale:                   YES (ver 3.1.101)
      avresample:                NO
    GStreamer:                   
      base:                      YES (ver 1.8.3)
      video:                     YES (ver 1.8.3)
      app:                       YES (ver 1.8.3)
      riff:                      YES (ver 1.8.3)
      pbutils:                   YES (ver 1.8.3)
    libv4l/libv4l2:              1.10.0 / 1.10.0
    v4l/v4l2:                    linux/videodev2.h
    gPhoto2:                     NO
...
```

**Comment by andrewssobral** [comment]
Apparently the solution is to modify the examples from OpenCV by doing:

For C/C++:
```
std::string get_tegra_pipeline(int width, int height, int fps) {
    return "nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)" + std::to_string(width) + ", height=(int)" +
           std::to_string(height) + ", format=(string)I420, framerate=(fraction)" + std::to_string(fps) +
           "/1 ! nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink";
}
...
int main() {
   // Options
    int WIDTH = 1920;
    int HEIGHT = 1080;
    int FPS = 30;

    // Define the gstream pipeline
    std::string pipeline = get_tegra_pipeline(WIDTH, HEIGHT, FPS);
    std::cout << "Using pipeline: \n\t" << pipeline << "\n";

    // Create OpenCV capture object, ensure it works.
    cv::VideoCapture cap(pipeline, cv::CAP_GSTREAMER);
    ...
```

For Python:
```
# On versions of L4T previous to L4T 28.1, flip-method=2
# Use the Jetson onboard camera
def open_onboard_camera():
    return cv2.VideoCapture("nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)640, height=(int)480, format=(string)I420, framerate=(fraction)30/1 ! nvvidconv ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink")
...
if __name__ == '__main__':
    arguments = parse_cli_args()
    print("Called with args:")
    print(arguments)
    print("OpenCV version: {}".format(cv2.__version__))
    print("Device Number:",arguments.video_device)
    if arguments.video_device==0:
      video_capture=open_onboard_camera()
    ...
```
As described here:
https://github.com/jetsonhacks/buildOpenCVTX2/tree/master/Examples

Now, everything is working for me...

**Comment by Georg-W** [comment]
I had the same issue

`
/src/opencv-3.4.0/modules/videoio/src/cap_gstreamer.cpp:890: error: (-2) GStreamer: unable to start pipeline
`
when running

`cap = cv2.VideoCapture(0)`

in python.

In the end I specified the FFMPEG Backend for VideoCapture  and everything worked again!

`cap = cv2.VideoCapture(0, cv2.CAP_FFMPEG)`

As described in the Open CV Forum

http://answers.opencv.org/question/123883/videoio-error-v4l/

**Comment by Sindreedelange** [comment]
@Georg-W I get:
` TypeError: VideoCapture() takes at most 1 argument (2 given) `, when trying to specify the FFMPEG backend:
`cap = cv2.VideoCapture(0, cv2.CAP_FFMPEG)`
Any tips?

**Comment by alalek** [comment]
@Sindreedelange What is OpenCV version used?

**Comment by Sindreedelange** [comment]
@alalek `python3 -c 'import cv2; print(cv2.__version__)' ` : 3.4.0

**Comment by alalek** [comment]
OpenCV 3.4.x statement is `cv.VideoCapture(0 + cv.CAP_FFMPEG)`.
Two parameters are available since OpenCV 4+ (master branch).

But it make no sense, because FFmpeg backend doesn't support cameras indices (it will not open anything).
Interface is `cv.VideoCapture(filename_string, cv.CAP_FFMPEG)`.

**Comment by gzz1529657064** [comment]
> Apparently the solution is to modify the examples from OpenCV by doing:
> 
> For C/C++:
> 
> ```
> std::string get_tegra_pipeline(int width, int height, int fps) {
>     return "nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)" + std::to_string(width) + ", height=(int)" +
>            std::to_string(height) + ", format=(string)I420, framerate=(fraction)" + std::to_string(fps) +
>            "/1 ! nvvidconv flip-method=0 ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink";
> }
> ...
> int main() {
>    // Options
>     int WIDTH = 1920;
>     int HEIGHT = 1080;
>     int FPS = 30;
> 
>     // Define the gstream pipeline
>     std::string pipeline = get_tegra_pipeline(WIDTH, HEIGHT, FPS);
>     std::cout << "Using pipeline: \n\t" << pipeline << "\n";
> 
>     // Create OpenCV capture object, ensure it works.
>     cv::VideoCapture cap(pipeline, cv::CAP_GSTREAMER);
>     ...
> ```
> 
> For Python:
> 
> ```
> # On versions of L4T previous to L4T 28.1, flip-method=2
> # Use the Jetson onboard camera
> def open_onboard_camera():
>     return cv2.VideoCapture("nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)640, height=(int)480, format=(string)I420, framerate=(fraction)30/1 ! nvvidconv ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink")
> ...
> if __name__ == '__main__':
>     arguments = parse_cli_args()
>     print("Called with args:")
>     print(arguments)
>     print("OpenCV version: {}".format(cv2.__version__))
>     print("Device Number:",arguments.video_device)
>     if arguments.video_device==0:
>       video_capture=open_onboard_camera()
>     ...
> ```
> 
> As described here:
> https://github.com/jetsonhacks/buildOpenCVTX2/tree/master/Examples
> 
> Now, everything is working for me...

In your code for python, your method doesn't use gstream, it just uses opencv.

**Comment by HEBOS** [comment]
The videoconverter plugin is a really poor solution. It produces only 9fps on Jetson.
Another plugin, nvvidconv, and nvvideoconvert are really fast, but they can't convert to BGR.
As it is clearly stated that OpenCV won't support BGRx (which are used by nvvidconv, and nvvideoconvert), the only way to get around that on Jetson nano is to use pipes as described [here](https://medium.com/@fanzongshaoxing/use-nvidia-deepstream-to-accelerate-h-264-video-stream-decoding-8f0fec764778).

**Comment by mdegans** [comment]
> The videoconverter plugin is a really poor solution. It produces only 9fps on Jetson. Another plugin, nvvidconv, and nvvideoconvert are really fast, but they can't convert to BGR. As it is clearly stated that OpenCV won't support BGRx (which are used by nvvidconv, and nvvideoconvert), the only way to get around that on Jetson nano is to use pipes as described [here](https://medium.com/@fanzongshaoxing/use-nvidia-deepstream-to-accelerate-h-264-video-stream-decoding-8f0fec764778).

It looks like it's supported in master now (`...modules/videoio/src/cap_gstreamer.cpp`)
```C++
    // we support these types of data:
    //     video/x-raw, format=BGR   -> 8bit, 3 channels
...
    //     video/x-raw, format={BGRA, RGBA, BGRx, RGBx} -> 8bit, 4 channels
    // bayer data is never decoded, the user is responsible for that
...
        else if (format == "BGRA" || format == "RGBA" || format == "BGRX" || format == "RGBX")
        {
            CV_CheckEQ((int)n_planes, 1, "");
            size_t step = GST_VIDEO_INFO_PLANE_STRIDE(&info, 0);
            CV_CheckGE(step, (size_t)frame_width, "");
            Mat src(sz, CV_8UC4, map_info.data + GST_VIDEO_INFO_PLANE_OFFSET(&info, 0), step);
            src.copyTo(dst);
            return true;
        }
```
