### PR TITLE
Fix bug with int64 support for FileStorage

### LINKED ISSUE #26829: Bug in cv::FileStorage when the XML contains integer values larger INT_MAX
### System Information

OpenCV version: 4.11.0
Operating System / Platform: Windows
Compiler: msvc 19.42.34436.0 (Visual Studio 2022)

### Detailed description

There seems to be a problem in the cv::FileStorage when it contains integers larger than INT_MAX.

When reading the Name node from an XML file like this one below, we get an error in modules\core\src\persistence.cpp:2233.
The XML reads fine for OpenCV up to version 4.10.0, or with integer values smaller than INT_MAX.

```xml
<?xml version="1.0"?>
    <opencv_storage>
      <A>
        <Value>2147483648</Value>
        <Name>"image"</Name>
      </A>
    </opencv_storage>
```

Output built with OpenCV 4.11.0
```
a is ok
b is ok
OpenCV(4.11.0) modules\core\src\persistence.cpp:2233: error: (-215:Assertion failed) key2 < fs->str_hash_data.size() in function 'cv::FileNode::operator []'
```

Output build with OpenCV 4.10.0
```
a is ok
b is ok
c is ok
```

### Steps to reproduce

```cpp
#include <iostream>
#include <opencv2/core/persistence.hpp>

int main() {
    auto example_a = R"(<?xml version="1.0"?>
    <opencv_storage>
      <A>
        <Value>2147483648</Value>
      </A>
    </opencv_storage>)";

    auto example_b = R"(<?xml version="1.0"?>
    <opencv_storage>
      <A>
        <Value>2147483647</Value>
        <Name>"image"</Name>
      </A>
    </opencv_storage>)";

    auto example_c = R"(<?xml version="1.0"?>
    <opencv_storage>
      <A>
        <Value>2147483648</Value>
        <Name>"image"</Name>
      </A>
    </opencv_storage>)";

    std::string name;
    cv::FileStorage fs;

    try {
        fs = cv::FileStorage(example_a, cv::FileStorage::READ | cv::FileStorage::MEMORY | cv::FileStorage::FORMAT_XML);
        fs["A"]["Name"] >> name;
        std::cout << "a is ok" << std::endl;
    } catch (std::exception &e) {
        std::cout << e.what() << std::endl;
    }

    try {
        fs = cv::FileStorage(example_b, cv::FileStorage::READ | cv::FileStorage::MEMORY | cv::FileStorage::FORMAT_XML);
        fs["A"]["Name"] >> name;
        std::cout << "b is ok" << std::endl;
    } catch (std::exception &e) {
        std::cout << e.what() << std::endl;
    }

    try {
        fs = cv::FileStorage(example_c, cv::FileStorage::READ | cv::FileStorage::MEMORY | cv::FileStorage::FORMAT_XML);
        fs["A"]["Name"] >> name;
        std::cout << "c is ok" << std::endl;
    } catch (std::exception &e) {
        std::cout << e.what() << std::endl;
    }

    return 0;
}

```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by MaximSmolskiy**
### Pull Request Readiness Checklist

Fix #26829, https://github.com/opencv/opencv-python/issues/1078

In current implementation of `int64` support raw size of recorded integer is variable (`4` or `8` bytes depending on value). But then we iterate over nodes we need to know it exact value
https://github.com/opencv/opencv/blob/dfad11aae7ef3b3a0643379266bc363b1a9c3d40/modules/core/src/persistence.cpp#L2596-L2609

Bug is that `rawSize` method still return `4` for any integer. I haven't figured out a way how to get variable raw size for integer in this method. I made raw size for integer is constant and equal to `8`.

Yes, after this patch memory consumption for integers will increase, but I don't know a better way to do it yet. At least this fixes bug and implementation becomes more correct

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by dkurt** [comment]
> Yes, after this patch memory consumption for integers will increase, but I don't know a better way to do it yet. At least this fixes bug and implementation becomes more correct

Probably, this fix may break compatibility on reading raw data serialized before with 4 bytes per int, doesn't it?

**Comment by dkurt** [comment]
@MaximSmolskiy, May I also ask you to open a PR with similar patch to 5.x branch? In such way we will test CV_64S Mat read/write too: https://github.com/opencv/opencv/pull/26399/files#diff-cf43289d2308f02754d618a5d975c44123ebb553fe074ccff700c7328a49badfR2078

**Comment by MaximSmolskiy** [comment]
> > Yes, after this patch memory consumption for integers will increase, but I don't know a better way to do it yet. At least this fixes bug and implementation becomes more correct
> 
> Probably, this fix may break compatibility on reading raw data serialized before with 4 bytes per int, doesn't it?

Yes, it is

File: modules/core/test/test_io.cpp [hunk 1]
```diff
@@ -2003,6 +2003,70 @@ TEST(Core_InputOutput, FileStorage_invalid_attribute_value_regression_25946)
...
+        {
+            int64_t value;
+
+            fs["Int64Min"] >> value;
+            EXPECT_EQ(value, INT64_MIN);
+
+            fs["Int64Max"] >> value;
+            EXPECT_EQ(value, INT64_MAX);
+        }
+    }
```
[the remark this answers is not in the document]
Comment (MaximSmolskiy) [reply modules/core/test/test_io.cpp:2061]: Done

**Comment by dkurt** [comment]
> > > Yes, after this patch memory consumption for integers will increase, but I don't know a better way to do it yet. At least this fixes bug and implementation becomes more correct
> >
> > Probably, this fix may break compatibility on reading raw data serialized before with 4 bytes per int, doesn't it?
>
> Yes, it is. But I can't think of any example code to do that. Can you please provide one?

Never mind, I just checked that both 5.x and PR produces the same base64 raw data outputs for int32:
```python
@staticmethod
    def get_normal_2d_mat():
        rows = 10
        cols = 20
        cn = 3

        image = np.zeros((rows, cols, cn), np.int32)
        image[:] = (1, 2, 127)

        for i in range(rows):
            for j in range(cols):
                image[i, j, 1] = (i + j) % 256

        return image

def write_base64_json(self, fname):
        fname = "/home/d.kurtaev/test_file.json"
        fs = cv.FileStorage(fname, cv.FileStorage_WRITE_BASE64)

        mats = {'normal_2d_mat': self.get_normal_2d_mat()}

        for name, mat in mats.items():
            fs.write(name, mat)

        fs.release()
```
```
0c16e58d13286e0d1b489e71be614f7b2a0fa57313ee36dd9b6329b7c6383976  /home/d.kurtaev/test_file_pr.json
0c16e58d13286e0d1b489e71be614f7b2a0fa57313ee36dd9b6329b7c6383976  /home/d.kurtaev/test_file_5.x.json
```
However seems like we should fix int64 base64 write mode later (in a separate PR for sure):
```patch
diff --git a/modules/python/test/test_filestorage_io.py b/modules/python/test/test_filestorage_io.py
index 01e0a72300..5ef0fd26ee 100644
--- a/modules/python/test/test_filestorage_io.py
+++ b/modules/python/test/test_filestorage_io.py
@@ -124,7 +124,7 @@ class filestorage_io_test(NewOpenCVTests):
         cols = 20
         cn = 3
 
-        image = np.zeros((rows, cols, cn), np.uint8)
+        image = np.zeros((rows, cols, cn), np.int64)
         image[:] = (1, 2, 127)
 
         for i in range(rows):
```
```
Testing OpenCV 5.0.0-pre
Local repo path: None
F...
======================================================================
FAIL: test_base64 (__main__.filestorage_io_test.test_base64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/d.kurtaev/opencv/modules/python/test/test_filestorage_io.py", line 118, in test_base64
    self.write_base64_json(fname)
  File "/home/d.kurtaev/opencv/modules/python/test/test_filestorage_io.py", line 202, in write_base64_json
    self.assertEqual(buffer, self.decode(data[name]['data']))
AssertionError: b'\x0[26 chars]x00\x00\x00\x00\x00\x00\x00\x00\x00\x7f\x00\x0[19061 chars]\x00' != b'\x0[26 chars]x00\x7f\x00\x00\x00\x01\x00\x00\x00\x01\x00\x0[9461 chars]\x00'

----------------------------------------------------------------------
Ran 4 tests in 0.009s

FAILED (failures=1)
```

**Review by dkurt — APPROVED** [review]
