### PR TITLE
Solve issue 7676

### LINKED ISSUE #7676: detect_blob.cpp  detect_mser.cpp using sintax not supported by clang C++11 compiler
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => FreeBSD 11
- Compiler => Clang 3.8.0

##### Detailed description

When compiling samples/cpp/detect_blob.cpp and samples/cpp/detect_mser.cpp clang C++ compiler raises so many errors like bellow. This is related with lines like this: 

String inf = static_cast<ostringstream*>(&(ostringstream() << pAct.minArea))->str(); 

[ 95%] Built target example_image_sequence
--- samples/cpp/CMakeFiles/example_select3dobj.dir/all ---
/usr/bin/make -f samples/cpp/CMakeFiles/example_select3dobj.dir/build.make samples/cpp/CMakeFiles/example_select3dobj.dir/depend
--- samples/cpp/CMakeFiles/example_select3dobj.dir/depend ---
cd /usr/ports/graphics/opencv3/work/opencv-3.1.0 && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /usr/ports/graphics/opencv3/work/opencv-3.1.0 /usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp /usr/ports/graphics/opencv3/work/opencv-3.1.0 /usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp /usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/CMakeFiles/example_select3dobj.dir/DependInfo.cmake --color=
--- samples/cpp/CMakeFiles/example_detect_mser.dir/all ---
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:76:46: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    String inf = static_cast<ostringstream*>(&(ostringstream() << pAct.minArea))->str();
                                             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:77:46: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    String sup = static_cast<ostringstream*>(&(ostringstream() << pAct.maxArea))->str();
                                             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:80:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << pAct.delta))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:82:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << pAct.maxVariation))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:84:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.minDiversity))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:86:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.pass2Only))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:88:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.maxEvolution))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:90:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.areaThreshold))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:92:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.minMargin))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/graphics/opencv3/work/opencv-3.1.0/samples/cpp/detect_mser.cpp:94:39: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    inf = static_cast<ostringstream*>(&(ostringstream() << (int)pAct.edgeBlurSize))->str();
                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

##### Steps to reproduce

 Compile using clang 3.8.0 with C++11 enabled.

Attached are the patches to solve this problem. 

[patch-samples_cpp_detect__blob.txt](https://github.com/opencv/opencv/files/591940/patch-samples_cpp_detect__blob.txt)
[patch-samples_cpp_detect__mser.txt](https://github.com/opencv/opencv/files/591939/patch-samples_cpp_detect__mser.txt)

### PR DESCRIPTION
**Pull request by LaurentBerger**
Resolves #7676

### CODE REVIEW

**Comment by alalek** [comment]
Thanks! :+1:
