### PR TITLE
Support very old V4L

### LINKED ISSUE #14439: Fail to build opencv3.4.6
##### System information (version)

- OpenCV => 3.4.6
- Operating System / Platform => centos6.3
- Compiler => 4.8.2

##### Detailed description

I try to build opencv3.4.6 but the below errors occurs:

[ 57%] Built target opencv_imgcodecs
[ 57%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_v4l.cpp.o
BullseyeCoverage Compile C++ 8.13.21 Linux-x64 License 3179 
Copyright (c) Bullseye Testing Technology 1990-2017
BullseyeCoverage Compile C++ 8.13.21 Linux-x64 License 3179 
Copyright (c) Bullseye Testing Technology 1990-2017
/home/work/meicheng/opencv/opencv-3.4.6/modules/videoio/src/cap_v4l.cpp: In function 'int cv::capPropertyToV4L2(int)':
/home/work/meicheng/opencv/opencv-3.4.6/modules/videoio/src/cap_v4l.cpp:1614:9: error: 'V4L2_CID_ROTATE' was not declared in this scope
         return V4L2_CID_ROTATE;
         ^
/home/work/meicheng/opencv/opencv-3.4.6/modules/videoio/src/cap_v4l.cpp:1616:9: error: 'V4L2_CID_IRIS_ABSOLUTE' was not declared in this scope
         return V4L2_CID_IRIS_ABSOLUTE;
         ^
BullseyeCoverage error: status 1 from /opt/compiler/gcc-4.8.2/bin/c++
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:154: modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_v4l.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2515: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

My cmake command is:
cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_contrib=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_photo=OFF  ..

I execlude some modules because some compile errors happens.
But I can not exclude opencv_imgcodecs, so what's the solution?
Thanks in advance.

### PR DESCRIPTION
**Pull request by mshabunin**
Related #13969
Resolves #14439

### This pullrequest changes

Build with enabled V4L2 failed on CentOS 6.10 (docker image `condaforge/linux-anvil-comp7`):
```
../modules/videoio/src/cap_v4l.cpp: In function 'int cv::capPropertyToV4L2(int)':
../modules/videoio/src/cap_v4l.cpp:1614:16: error: 'V4L2_CID_ROTATE' was not declared in this scope
         return V4L2_CID_ROTATE;
                ^~~~~~~~~~~~~~~
../modules/videoio/src/cap_v4l.cpp:1614:16: note: suggested alternative: 'V4L2_CID_BASE'
         return V4L2_CID_ROTATE;
                ^~~~~~~~~~~~~~~
                V4L2_CID_BASE
../modules/videoio/src/cap_v4l.cpp:1616:16: error: 'V4L2_CID_IRIS_ABSOLUTE' was not declared in this scope
         return V4L2_CID_IRIS_ABSOLUTE;
                ^~~~~~~~~~~~~~~~~~~~~~
../modules/videoio/src/cap_v4l.cpp:1616:16: note: suggested alternative: 'V4L2_CID_FOCUS_ABSOLUTE'
         return V4L2_CID_IRIS_ABSOLUTE;
                ^~~~~~~~~~~~~~~~~~~~~~
                V4L2_CID_FOCUS_ABSOLUTE
```

### CODE REVIEW

**Comment by alalek** [comment]
=> 3.4
