### ISSUE TITLE
MSER openCV not working

### ISSUE THREAD

**Issue by Maia07** [opencv/opencv#10554]
Hello,

I have an issue. I'm trying to test the module MSER but i keep getting this error: "File "C:\Users\Rita\Desktop\ISCTE\2_ano\Tese\MSER.py", line 26, in <listcomp>
    hulls = [cv2.convexHull(p.reshape(-1, 1, 2)) for p in regions]
AttributeError: 'list' object has no attribute 'reshape'"

Where does variable 'p' comes from?

Thanks in advance.

Rita Maia

**Comment by berak** [comment]
not a bug, but a user error.
it should be:

        regions, boxes = mser.detectRegions(gray)

if you omit the `boxes` retval (that probably happened to you!), like this:

        regions = mser.detectRegions(gray)

you have a list of [regions,boxes] in there, that's one list too many.
(regions contains a list of pointlists, per region; and boxes a list of resp. bounding boxes)
and please, questions like this should not go here, but on http://answers.opencv.org

**Comment by alalek** [comment]
OpenCV's [MSER.py](https://github.com/opencv/opencv/blob/3.4.0/samples/python/mser.py) works well in 3.4.0 release.
