### PR TITLE
core: several improves and fixes on ppc64le infrastructure

### LINKED ISSUE #13210: ppc64le: build fails on GCC 4.9.2
##### System information (version)

- OpenCV => 3.4.*, 4.0.*, master
- Operating System / Platform => ppc64le GNU/Linux
- Compiler => GCC 4.9.2

##### Detailed description

````
In file included from /worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin.hpp:158:0,
                 from /worker/buildbot/Power8_Linux_gcc-4_9__opencv/build/modules/core/precomp.hpp:85:
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp: In function 'void cv::hal::cpu_baseline::cmp_loop(const T1*, size_t, const T1*, size_t, uchar*, size_t, int, int) [with OP = cv::hal::cpu_baseline::op_cmplt; T1 = double; Tvec = cv::hal_baseline::v_float64x2; size_t = long unsigned int; uchar = unsigned char]':
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:405:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ab = vec_pack(a.val, b.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:406:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 cd = vec_pack(c.val, d.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:407:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ef = vec_pack(e.val, f.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:408:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 gh = vec_pack(g.val, h.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp: In function 'void cv::hal::cpu_baseline::cmp_loop(const T1*, size_t, const T1*, size_t, uchar*, size_t, int, int) [with OP = cv::hal::cpu_baseline::op_cmple; T1 = double; Tvec = cv::hal_baseline::v_float64x2; size_t = long unsigned int; uchar = unsigned char]':
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:405:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ab = vec_pack(a.val, b.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:406:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 cd = vec_pack(c.val, d.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:407:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ef = vec_pack(e.val, f.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:408:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 gh = vec_pack(g.val, h.val);
                                         ^
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp: In function 'void cv::hal::cpu_baseline::cmp_loop(const T1*, size_t, const T1*, size_t, uchar*, size_t, int, int) [with OP = cv::hal::cpu_baseline::op_cmpeq; T1 = double; Tvec = cv::hal_baseline::v_float64x2; size_t = long unsigned int; uchar = unsigned char]':
/worker/buildbot/Power8_Linux_gcc-4_9__opencv/opencv/modules/core/include/opencv2/core/hal/intrin_vsx.hpp:405:41: error: Builtin function __builtin_altivec_vpkudum requires the -mpower8-vector option
     vec_uint4 ab = vec_pack(a.val, b.val);
````
CI url:
https://ocv-power.imavr.com/#/builders/5/builds/1

##### Steps to reproduce

build on GCC 4.9.2

### LINKED ISSUE #13222: ppc64le: build fails on CLANG 4 due missing VSX flag
##### System information (version)

- OpenCV => 3.4, master
- Operating System / Platform => ppc64le GNU/Linux
- Compiler => CLANG 4.0.1

##### Detailed description
````
#error "AltiVec support not enabled"
 ^
/usr/include/clang/4.0.1/include/altivec.h:62:19: error: unknown type name 'vector'
static __inline__ vector signed char __ATTRS_o_ai vec_perm(
                  ^
/usr/include/clang/4.0.1/include/altivec.h:62:26: error: expected unqualified-id
static __inline__ vector signed char __ATTRS_o_ai vec_perm(
                         ^
/usr/include/clang/4.0.1/include/altivec.h:65:19: error: unknown type name 'vector'
static __inline__ vector unsigned char __ATTRS_o_ai
                  ^
/usr/include/clang/4.0.1/include/altivec.h:65:26: error: expected unqualified-id
static __inline__ vector unsigned char __ATTRS_o_ai
                         ^
/usr/include/clang/4.0.1/include/altivec.h:69:19: error: unknown type name 'vector'
static __inline__ vector bool char __ATTRS_o_ai
                  ^
/usr/include/clang/4.0.1/include/altivec.h:69:26: error: expected unqualified-id
static __inline__ vector bool char __ATTRS_o_ai
                         ^
/usr/include/clang/4.0.1/include/altivec.h:72:19: error: unknown type name 'vector'
static __inline__ vector short __ATTRS_o_ai vec_perm(vector signed short __a,
                  ^
/usr/include/clang/4.0.1/include/altivec.h:72:26: error: expected unqualified-id
static __inline__ vector short __ATTRS_o_ai vec_perm(vector signed short __a,
                         ^
/usr/include/clang/4.0.1/include/altivec.h:76:19: error: unknown type name 'vector'
static __inline__ vector unsigned short __ATTRS_o_ai
                  ^
/usr/include/clang/4.0.1/include/altivec.h:76:26: error: expected unqualified-id
static __inline__ vector unsigned short __ATTRS_o_ai
                         ^
/usr/include/clang/4.0.1/include/altivec.h:80:19: error: unknown type name 'vector'
static __inline__ vector bool short __ATTRS_o_ai vec_perm(
                  ^
/usr/include/clang/4.0.1/include/altivec.h:80:26: error: expected unqualified-id
static __inline__ vector bool short __ATTRS_o_ai vec_perm(
                         ^
/usr/include/clang/4.0.1/include/altivec.h:83:19: error: unknown type name 'vector'
static __inline__ vector pixel __ATTRS_o_ai vec_perm(vector pixel __a,
                  ^
/usr/include/clang/4.0.1/include/altivec.h:83:32: error: '__overloadable__' attribute only applies to functions
static __inline__ vector pixel __ATTRS_o_ai vec_perm(vector pixel __a,
                               ^
/usr/include/clang/4.0.1/include/altivec.h:56:37: note: expanded from macro '__ATTRS_o_ai'
#define __ATTRS_o_ai __attribute__((__overloadable__, __always_inline__))
                                    ^
/usr/include/clang/4.0.1/include/altivec.h:83:44: error: expected ';' after top level declarator
static __inline__ vector pixel __ATTRS_o_ai vec_perm(vector pixel __a,
                                           ^
/usr/include/clang/4.0.1/include/altivec.h:87:19: error: unknown type name 'vector'
static __inline__ vector int __ATTRS_o_ai vec_perm(vector signed int __a,
                  ^
/usr/include/clang/4.0.1/include/altivec.h:87:26: error: expected unqualified-id
static __inline__ vector int __ATTRS_o_ai vec_perm(vector signed int __a,
                         ^
/usr/include/clang/4.0.1/include/altivec.h:91:19: error: unknown type name 'vector'
static __inline__ vector unsigned int __ATTRS_o_ai vec_perm(
````
CI: https://ocv-power.imavr.com/#/builders/3/builds/1/

##### Steps to reproduce

build opencv on CLANG 4

### PR DESCRIPTION
**Pull request by seiko2plus**
resolves #13210
resolves #13222

### This pullrequest changes

  - add infrastructure support for Power9/VSX3
  - fix missing VSX flags on GCC4.9 and CLANG4(#13210, #13222)
  - fix disable VSX optimzation on GCC by using flag ENABLE_VSX
  - flag ENABLE_VSX is deprecated now, use CPU_BASELINE, CPU_DISPATCH instead
  - add VSX3 to arithmetic dispatchable flags

````
force_builders=Custom
docker_image:Custom=powerpc64le
pw_compilers=gcc-4.9, gcc-5, gcc-6, gcc-7, clang-4, clang-5, clang-6, power9_gcc-4.9, power9_gcc-5, power9_gcc-6, power9_gcc-7, power9_clang-4, power9_clang-6
# new version of Eigen(3.3.5) has bug on clang .. gonna investigate on it later  
pw_cmake_definitions=WITH_EIGEN:OFF 
````

### CODE REVIEW

File: cmake/OpenCVCompilerOptimizations.cmake [hunk 1]
```diff
@@ -30,6 +34,7 @@
 set(CPU_ALL_OPTIMIZATIONS "SSE;SSE2;SSE3;SSSE3;SSE4_1;SSE4_2;POPCNT;AVX;FP16;AVX2;FMA3;AVX_512F;AVX512_SKX")
 list(APPEND CPU_ALL_OPTIMIZATIONS NEON VFPV3 FP16)
 list(APPEND CPU_ALL_OPTIMIZATIONS VSX)
+list(APPEND CPU_ALL_OPTIMIZATIONS VSX3)
```
Comment (alalek) [inline cmake/OpenCVCompilerOptimizations.cmake]: Please merge these two lines:
```
list(APPEND CPU_ALL_OPTIMIZATIONS VSX VSX3)
```

File: cmake/OpenCVCompilerOptimizations.cmake [hunk 2]
```diff
@@ -289,14 +294,30 @@ elseif(ARM OR AARCH64)
...
     ocv_update(CPU_VSX_FLAGS_ON "-mvsx -maltivec")
+    ocv_update(CPU_VSX3_FLAGS_ON "-mpower9-vector")
   else()
     ocv_update(CPU_VSX_FLAGS_ON "-mcpu=power8")
+    ocv_update(CPU_VSX3_FLAGS_ON "-mcpu=power9 -mtune=power9")
   endif()
+
+  if(NOT DEFINED CPU_DISPATCH)
+    set(CPU_DISPATCH "VSX3" CACHE STRING "${HELP_CPU_DISPATCH}")
+  endif()
```
Comment (alalek) [inline cmake/OpenCVCompilerOptimizations.cmake]: Pre-check here is not necessary - CMake doesn't update already existed cache variables (if there is no FORCE or INTERNAL).
```
set(CPU_DISPATCH "VSX3" CACHE STRING "${HELP_CPU_DISPATCH}")
set(CPU_BASELINE "VSX" CACHE STRING "${HELP_CPU_BASELINE}")
```

BTW, For non-cache variables there is `ocv_update()` macro with this check.

Comment (seiko2plus) [reply cmake/OpenCVCompilerOptimizations.cmake]: @alalek , got it, thank you!
