### PR TITLE
fix build #6993

### LINKED ISSUE #6993: OpenCV 3.1 build with QT and Cuda 8.0 errors
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc/g++ 5.4

##### Detailed description

I try to build opencv 3.1 from master branch, but I have errors: 

/home/ubuntu/opencv/modules/highgui/src/window_QT.cpp: In member function ‘virtual void OpenGlViewPort::wheelEvent(QWheelEvent*)’:
/home/ubuntu/opencv/modules/highgui/src/window_QT.cpp:3204:32: error: ‘scaleView’ was not declared in this scope
     scaleView(delta / 240.0, pt);

/home/ubuntu/opencv/modules/highgui/src/window_QT.cpp:3205:14: error: ‘viewport’ was not declared in this scope
     viewport()->update();

Also I had error:

In file included from /home/ubuntu/opencv/build/modules/cudalegacy/opencv_test_cudalegacy_pch_dephelp.cxx:1:0:
/home/ubuntu/opencv/modules/cudalegacy/test/test_precomp.hpp:54:69: error: operator '&&' has no right operand

I fixed it by removing "\n" in test_precomp.hpp on line 54.

If I try to build without QT, I get errors:

/usr/local/cuda-8.0/include/thrust/detail/reference.inl(127): error: no default constructor exists for class "thrust::detail::execute_with_allocator<cv::cuda::device::ThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>"

/usr/local/cuda-8.0/include/thrust/detail/reference.inl(98): error: no default constructor exists for class "thrust::detail::execute_with_allocator<cv::cuda::device::ThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>"

##### Steps to reproduce

Clone from https://github.com/opencv/opencv

Run cmake with -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON or without WITH_QT=ON

Run make

### PR DESCRIPTION
**Pull request by StevenPuttemans**
resolves #6993 partially

### This pullrequest changes

Removes some `\n` that were destroying the condition statements. Now master builds fine again without Qt (those issues still open)

### CODE REVIEW

**Comment by alalek** [comment]
:+1:
