### ISSUE TITLE
Link error with OpenCV 2.4.13.2 and FFmpeg 3.2.4

### ISSUE THREAD

**Issue by Beanocean** [opencv/opencv#8464]
##### System information (version)

- OpenCV => 2.4.13.2
- Operating System / Platform => Linux 2.6.32 x86_64
- Compiler => g++ 4.8.3

##### Detailed description

When compiling OpenCV 2.4.13.2 with FFmpeg 3.2.4, I met with a problem in linking stage. The error are:
```text
[ 46%] Building CXX object modules/objdetect/CMakeFiles/opencv_objdetect.dir/src/featurepyramid.cpp.o
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_new_stream'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_close_input'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_write_trailer'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_open_input'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_malloc'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_find_encoder'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_write_frame'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avformat_find_stream_info'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_frame_get_buffer'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `avcodec_find_decoder'
../../lib/libopencv_highgui.so.2.4.13: undefined reference to `av_sub_q'
```
In cmake stage, the FFmpeg libraries were found, and the cmake log showed that: 

```
--     FFMPEG:                      YES
--       avcodec:                   YES (ver 57.64.101)
--       avformat:                  YES (ver 57.56.101)
--       avutil:                    YES (ver 55.34.101)
--       swscale:                   YES (ver 4.2.100)
--       avresample:                YES (ver 3.1.0)
```

##### Other information

Here attached are CMakeCache.txt, CMakeVars.txt, CMake.output.txt and Make.ouput.txt
[CMakeCache.txt](https://github.com/opencv/opencv/files/871615/CMakeCache.txt)
[CMakeVars.txt](https://github.com/opencv/opencv/files/871614/CMakeVars.txt)
[CMake.output.txt](https://github.com/opencv/opencv/files/871621/CMake.output.txt)
[Make.output.txt](https://github.com/opencv/opencv/files/871622/Make.output.txt)

**Comment by alalek** [comment]
> -- WARNING: Can't build ffmpeg test code

Check build log in this file: CMakeFiles/CMakeError.log

Use latest code from 2.4 branch, it will correctly disable FFMPEG support.
Also I can confirm that OpenCV 2.4 is able to successfully build with FFMPEG 3.2.4.

BTW, always clean CMake cache or build directory while playing with parameters/options. This is not specific for OpenCV only - this is required for almost all CMake-based projects.

**Comment by iegrsy** [comment]
https://drive.google.com/open?id=1j5qC1izhLVbHFpw-KkVRXNca8ASV1km5 
download this file.
Copy the contents into /usr/lib/x86_64-linux-gnu/
That is all.
