### ISSUE TITLE
opencv2/gpu/gpu.hpp: No such file or directory

### ISSUE THREAD

**Issue by wangzhankun** [opencv/opencv#15748]
##### System information (version)

- OpenCV => 3.4.7
- Operating System / Platform => ubuntu18.04 nvidia tx2
- Compiler => g++ (Ubuntu/Linaro 7.4.0-1ubuntu1\~18.04.1) 7.4.0
                      gcc (Ubuntu/Linaro 7.4.0-1ubuntu1\~18.04.1) 7.4.0
                      Cuda compilation tools, release 10.0, V10.0.326

```Bash
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_CUDA=ON -D CUDA_ARCH_BIN="6.2" -D CUDA_ARCH_PTX="" -D WITH_CUBLAS=ON -D ENABLE_FAST_MATH=ON -D CUDA_FAST_MATH=ON -D ENABLE_NEON=ON -D WITH_GSTREAMER=ON -D WITH_LIBV4L=ON -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=ON -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_EXAMPLES=OFF  ..
make -j4
sudo make install
sudo ldconfig
```
![image](https://user-images.githubusercontent.com/35724924/67146758-be307480-f2c0-11e9-96df-38c9b69208d7.png)

In the /usr/local/include there are `opencv` `opencv2` directory. 
In the `opencv2` directory
![image](https://user-images.githubusercontent.com/35724924/67146691-27fc4e80-f2c0-11e9-8fe7-aee781093ef0.png)
In the `opencv` directory
![image](https://user-images.githubusercontent.com/35724924/67146723-6abe2680-f2c0-11e9-9473-2f8f36fbc209.png)

##### Detailed description

I have tried to compile opencv with cuda10 many times. But when I try to include "opencv2/gpu/gpu.hpp", there is no such file.
```Bash
error: Share/include/header.h:51:10: fatal error: opencv2/gpu/gpu.hpp: No such file or directory
 #include <opencv2/gpu/gpu.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by alalek** [comment]
> Share/include/header.h

Your code expecting OpenCV 2.4 built with CUDA. You trying to use OpenCV 3.4.x

OpenCV 2.4 development/maintenance is abandoned several years ago, so CUDA 10 is not get supported.

**Comment by wangzhankun** [comment]
Could you please give me some instructions on how to use gpu with opencv3.4.7? It is hard to find the tutorial.

**Comment by vijay180396** [comment]
@wangzhankun , you are build with opencv 2.4 development not for opencv 3.4

**Comment by Necktwi** [comment]
@vijay180396 a ooru bhayya needhi?
